export const uiTerms = {
  today: { ko: "오늘", vi: "Hôm nay" },
  curriculum: { ko: "과정", vi: "Lộ trình học" },
  review: { ko: "복습", vi: "Ôn tập", description: "Xem lại nội dung đã đến hạn." },
  notebook: { ko: "노트", vi: "Sổ từ vựng" },
  errors: { ko: "오답", vi: "Sổ lỗi" },
  settings: { ko: "설정", vi: "Cài đặt" },
  dailyGoal: { ko: "오늘의 목표", vi: "Mục tiêu hôm nay" },
  continueLearning: { ko: "학습 계속하기", vi: "Tiếp tục học" },
  startLearning: { ko: "학습 시작", vi: "Bắt đầu học" },
  todayReview: { ko: "오늘 복습", vi: "Ôn tập hôm nay", description: "Những nội dung đã đến hạn ôn trong hôm nay." },
  weeklyStudy: { ko: "이번 주 학습", vi: "Học tập tuần này" },
  currentCourse: { ko: "현재 과정", vi: "Khóa học hiện tại" },
  skillGrowth: { ko: "영역별 성장", vi: "Tiến bộ theo kỹ năng" },
  recentMistakes: { ko: "최근 실수", vi: "Lỗi gần đây" },
  courseMap: { ko: "학습 과정", vi: "Lộ trình học" },
  available: { ko: "학습 가능", vi: "Có thể học" },
  prerequisite: { ko: "선행 학습 필요", vi: "Cần học bài trước" },
  lessonGoals: { ko: "학습 목표", vi: "Mục tiêu bài học" },
  dialogue: { ko: "대화", vi: "Hội thoại" },
  vocabulary: { ko: "어휘", vi: "Từ vựng" },
  grammar: { ko: "문법", vi: "Ngữ pháp" },
  examples: { ko: "예문", vi: "Câu ví dụ" },
  practice: { ko: "연습", vi: "Luyện tập" },
  production: { ko: "활용", vi: "Thực hành chủ động" },
  masteryCheck: { ko: "마지막 확인", vi: "Kiểm tra cuối bài" },
  easierKorean: { ko: "더 쉽게 설명해 주세요", vi: "Giải thích bằng tiếng Hàn dễ hơn" },
  vietnameseExplanation: { ko: "베트남어 설명", vi: "Giải thích bằng tiếng Việt" },
  reviewCenter: { ko: "복습 센터", vi: "Trung tâm ôn tập" },
  all: { ko: "전체", vi: "Tất cả" },
  sentences: { ko: "문장", vi: "Câu" },
  myMistakes: { ko: "나의 실수", vi: "Lỗi của tôi" },
  again: { ko: "다시", vi: "Lại từ đầu" },
  hard: { ko: "어려움", vi: "Khó" },
  good: { ko: "좋음", vi: "Tốt" },
  easy: { ko: "쉬움", vi: "Dễ" },
  vocabularyNotebook: { ko: "어휘 노트", vi: "Sổ từ vựng" },
  savedSentences: { ko: "저장한 문장", vi: "Câu đã lưu" },
  search: { ko: "검색", vi: "Tìm kiếm" },
  level: { ko: "레벨", vi: "Cấp độ" },
  topic: { ko: "주제", vi: "Chủ đề" },
  mastery: { ko: "숙련도", vi: "Mức độ thành thạo" },
  errorNotebook: { ko: "나의 오답 노트", vi: "Sổ lỗi cá nhân" },
  newStatus: { ko: "새 항목", vi: "Mới" },
  practicing: { ko: "연습 중", vi: "Đang luyện tập" },
  improving: { ko: "향상 중", vi: "Đang tiến bộ" },
  resolved: { ko: "해결됨", vi: "Đã khắc phục" },
  recurring: { ko: "반복됨", vi: "Lặp lại" },
  studySettings: { ko: "학습 설정", vi: "Cài đặt học tập" },
  englishLevel: { ko: "영어 과정 수준", vi: "Trình độ tiếng Anh" },
  koreanLevel: { ko: "한국어 설명 수준", vi: "Mức giải thích tiếng Hàn" },
  dailyDuration: { ko: "하루 학습 시간", vi: "Thời gian học mỗi ngày" },
  pronunciation: { ko: "기본 발음", vi: "Giọng phát âm mặc định" },
  assistMode: { ko: "베트남어 인터페이스 도움", vi: "Hỗ trợ giao diện tiếng Việt" },
  assistOff: { ko: "사용 안 함", vi: "Tắt" },
  assistOnDemand: { ko: "필요할 때 보기", vi: "Khi cần" },
  assistAlways: { ko: "항상 함께 보기", vi: "Luôn hiển thị" },
  saveSettings: { ko: "설정 저장", vi: "Lưu cài đặt" },
  saved: { ko: "저장했어요", vi: "Đã lưu" },
  exportData: { ko: "학습 데이터 내보내기", vi: "Xuất dữ liệu học tập" },
  importData: { ko: "가져오기", vi: "Nhập dữ liệu" },
  answer: { ko: "답변", vi: "Câu trả lời" },
  checkAnswer: { ko: "정답 확인", vi: "Kiểm tra đáp án" },
  modelAnswer: { ko: "모범 답안 보기", vi: "Xem câu trả lời mẫu" },
  tryAgain: { ko: "다시 해보기", vi: "Thử lại" },
  helpNeeded: { ko: "도움 필요", vi: "Cần trợ giúp" },
  didWell: { ko: "잘했어요", vi: "Làm tốt" },
  next: { ko: "다음", vi: "Tiếp theo" },
  complete: { ko: "완료", vi: "Hoàn thành" },
  listening: { ko: "듣기", vi: "Nghe" },
  writing: { ko: "쓰기", vi: "Viết" },
  speaking: { ko: "말하기", vi: "Nói" },
  reading: { ko: "읽기", vi: "Đọc" },
  playAudio: { ko: "음성 듣기", vi: "Nghe âm thanh" },
  playbackSpeed: { ko: "재생 속도", vi: "Tốc độ phát" },
  repeatCount: { ko: "반복 횟수", vi: "Số lần lặp" },
  showTranscript: { ko: "대본 보기", vi: "Hiện bản chép lời" },
  hideTranscript: { ko: "대본 숨기기", vi: "Ẩn bản chép lời" },
  record: { ko: "녹음하기", vi: "Ghi âm" },
  stopRecording: { ko: "녹음 멈추기", vi: "Dừng ghi âm" },
  shadowing: { ko: "따라 말하기", vi: "Luyện nói theo" },
  speechPractice: { ko: "말하기 연습", vi: "Luyện nói" },
  loading: { ko: "불러오는 중", vi: "Đang tải" },
  empty: { ko: "아직 항목이 없어요", vi: "Chưa có mục nào" },
  success: { ko: "완료했어요", vi: "Đã hoàn thành" },
  validationError: { ko: "입력 내용을 확인해 주세요", vi: "Vui lòng kiểm tra nội dung" },
  errorState: { ko: "문제가 생겼어요", vi: "Đã xảy ra lỗi" },
  frequentTerms: { ko: "자주 확인한 인터페이스 단어", vi: "Các từ giao diện thường phải tra" },
} as const;

export type UiTermKey = keyof typeof uiTerms;
export type AssistMode = "off" | "on-demand" | "always";
export function getUiTerm(key: UiTermKey | string): {ko:string;vi:string;description?:string}|undefined { return uiTerms[key as UiTermKey]; }
