import { bilingualUnitSchema } from "@/lib/curriculum/bilingual-schema";
import { buildLesson, exercise, type LessonSeed } from "./a2-lesson-factory";

const unitId = "a2-6-work-study";

/* ------------------------------------------------------------------ *
 * Bài 1 — Mô tả nhiệm vụ và lịch làm việc, học tập
 * ------------------------------------------------------------------ */
const jobTasks: LessonSeed = {
  id: "a2-job-tasks",
  unitId,
  number: 1,
  prerequisites: ["a2-unit-5-review"],
  titleVi: "Mô tả nhiệm vụ và lịch làm việc, học tập",
  titleKo: "업무와 일정 설명하기",
  situationVi: "Sora giới thiệu công việc mới cho Linh: nhiệm vụ hằng ngày, ca làm, hạn chót và việc cô phải làm.",
  situationKo: "소라는 린에게 새 직장을 소개해요. 매일 하는 일, 근무 시간, 마감, 꼭 해야 하는 일을 설명해요.",
  objectives: [
    { id: "a2-job-tasks-communicate", en: "Describe tasks, schedules and responsibilities.", vi: "Mô tả nhiệm vụ, lịch làm việc và trách nhiệm.", ko: "업무, 일정, 책임을 설명할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-job-tasks-form", en: "Use have to, need to and don’t need to.", vi: "Dùng have to, need to và don’t need to.", ko: "have to, need to, don’t need to를 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-job-tasks-comprehension", en: "Understand the order of someone’s working day.", vi: "Nghe hiểu trình tự một ngày làm việc của ai đó.", ko: "누군가의 하루 업무 순서를 들을 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["responsibility", "responsibility", "trách nhiệm", "책임", "/rɪˌspɒnsəˈbɪləti/", "responsiBILity", "formal", ["a main responsibility", "share responsibilities"]],
    ["task", "daily task", "nhiệm vụ hằng ngày", "일일 업무", "/tɑːsk/", "TASK", "neutral", ["a daily task", "finish a task"]],
    ["deadline", "meet a deadline", "kịp hạn chót", "마감을 지키다", "/ˈdedlaɪn/", "DEADline", "neutral", ["meet a deadline", "a tight deadline"]],
    ["shift", "morning shift", "ca sáng", "오전 근무", "/ʃɪft/", "SHIFT", "neutral", ["work a morning shift", "swap shifts"]],
    ["schedule", "weekly schedule", "lịch làm việc hằng tuần", "주간 일정", "/ˈʃedjuːl/", "SCHEDule", "neutral", ["a weekly schedule", "check the schedule"]],
    ["colleague", "colleague", "đồng nghiệp", "동료", "/ˈkɒliːɡ/", "COLleague", "neutral", ["a new colleague", "ask a colleague"]],
    ["attend", "attend a meeting", "tham dự cuộc họp", "회의에 참석하다", "/əˈtend/", "atTEND", "formal", ["attend a meeting", "attend a training course"]],
    ["in-charge", "be in charge of", "phụ trách", "담당하다", "/ɪn ˈtʃɑːdʒ əv/", "in CHARGE of", "formal", ["be in charge of orders", "be in charge of a team"]],
    ["part-time", "a part-time job", "việc làm bán thời gian", "아르바이트", "/ˌpɑːt ˈtaɪm/", "part-TIME", "neutral", ["a part-time job", "work part-time"]],
    ["report", "write a report", "viết báo cáo", "보고서를 쓰다", "/rɪˈpɔːt/", "rePORT", "formal", ["write a weekly report", "send the report"]],
  ],
  dialogue: [
    ["Linh", "How’s the new job going?", "Công việc mới thế nào rồi?", "새 직장은 어때요?", "casual"],
    ["Sora", "Busy but interesting. I’m in charge of online orders.", "Bận nhưng thú vị. Tôi phụ trách đơn hàng trực tuyến.", "바쁘지만 재미있어요. 온라인 주문을 담당해요.", "casual"],
    ["Linh", "What time do you usually start?", "Bạn thường bắt đầu lúc mấy giờ?", "보통 몇 시에 시작해요?", "neutral"],
    ["Sora", "I usually start at eight, but on Fridays I work the afternoon shift.", "Tôi thường bắt đầu lúc tám giờ, nhưng thứ Sáu tôi làm ca chiều.", "보통 8시에 시작하는데, 금요일에는 오후 근무를 해요.", "neutral"],
    ["Linh", "Do you have to work at the weekend?", "Bạn có phải làm cuối tuần không?", "주말에도 일해야 해요?", "neutral"],
    ["Sora", "Sometimes. I have to check the orders on Saturday morning, but I don’t need to stay all day.", "Thỉnh thoảng. Tôi phải kiểm tra đơn hàng sáng thứ Bảy, nhưng không cần ở cả ngày.", "가끔요. 토요일 아침에 주문을 확인해야 하지만 하루 종일 있을 필요는 없어요.", "neutral"],
    ["Linh", "And meetings?", "Còn họp thì sao?", "회의는요?", "neutral"],
    ["Sora", "We have a team meeting every Monday, and I need to attend the training course this month.", "Chúng tôi họp nhóm mỗi thứ Hai, và tháng này tôi cần tham dự khóa đào tạo.", "월요일마다 팀 회의가 있고, 이번 달에는 교육 과정을 들어야 해요.", "neutral"],
    ["Linh", "What’s the hardest part?", "Phần khó nhất là gì?", "가장 어려운 부분은 뭐예요?", "casual"],
    ["Sora", "The deadlines. I have to send a report every Friday at five.", "Hạn chót. Tôi phải gửi báo cáo vào năm giờ chiều thứ Sáu hằng tuần.", "마감이요. 매주 금요일 5시까지 보고서를 보내야 해요.", "neutral"],
    ["Linh", "Do you need help with anything?", "Bạn có cần giúp gì không?", "도와줄 일이 있어요?", "casual"],
    ["Sora", "Not now, thanks. I need to finish two tasks today.", "Chưa cần, cảm ơn. Hôm nay tôi cần xong hai nhiệm vụ.", "지금은 괜찮아요, 고마워요. 오늘 두 가지 일을 끝내야 해요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "have to, need to và don’t need to",
      titleKo: "have to, need to, don’t need to",
      explanationVi: "have to dùng khi có quy định hoặc người khác yêu cầu: “I have to send a report every Friday.” need to dùng khi bản thân thấy cần: “I need to finish two tasks today.” don’t need to nghĩa là không cần thiết.",
      explanationKo: "have to는 규칙이나 지시에 따른 의무, need to는 스스로 필요한 일을 말해요. don’t need to는 하지 않아도 된다는 뜻이에요.",
      easierKorean: "정해진 의무는 have to, 스스로 필요하면 need to를 써요.",
    },
    {
      titleVi: "Hiện tại đơn cho lịch làm việc lặp lại",
      titleKo: "반복되는 일정의 현재형",
      explanationVi: "Lịch lặp lại dùng hiện tại đơn với trạng từ tần suất: “I usually start at eight.” “We have a team meeting every Monday.” on Fridays và at the weekend là cụm thời gian cố định.",
      explanationKo: "반복되는 일정은 현재형과 빈도 부사로 말해요. every Monday, on Fridays처럼 시간 표현을 함께 써요.",
      easierKorean: "매주 반복되는 일은 현재형으로 말해요.",
    },
  ],
  examples: [
    ["I’m in charge of online orders.", "Tôi phụ trách đơn hàng trực tuyến.", "저는 온라인 주문을 담당해요.", "Sora giới thiệu phần việc chính của mình."],
    ["I usually start work at eight.", "Tôi thường bắt đầu làm lúc tám giờ.", "보통 8시에 일을 시작해요.", "Câu trả lời khi Linh hỏi giờ làm."],
    ["On Fridays I work the afternoon shift.", "Thứ Sáu tôi làm ca chiều.", "금요일에는 오후 근무를 해요.", "Sora giải thích lịch tuần của mình."],
    ["I have to check the orders on Saturday morning.", "Tôi phải kiểm tra đơn hàng sáng thứ Bảy.", "토요일 아침에는 주문을 확인해야 해요.", "Nhiệm vụ bắt buộc vào cuối tuần."],
    ["I don’t need to stay all day.", "Tôi không cần ở lại cả ngày.", "하루 종일 있을 필요는 없어요.", "Sora làm rõ mức độ của nhiệm vụ thứ Bảy."],
    ["We have a team meeting every Monday.", "Chúng tôi họp nhóm mỗi thứ Hai.", "월요일마다 팀 회의가 있어요.", "Lịch cố định của nhóm Sora."],
    ["I need to attend a training course this month.", "Tháng này tôi cần tham dự một khóa đào tạo.", "이번 달에는 교육 과정을 들어야 해요.", "Yêu cầu từ công ty trong tháng đầu."],
    ["Does your colleague share the night shift?", "Đồng nghiệp của bạn có chia ca đêm không?", "동료가 야간 근무를 나눠서 하나요?", "Câu hỏi Linh hỏi về cách chia việc."],
    ["I have to send a report every Friday at five.", "Tôi phải gửi báo cáo năm giờ chiều thứ Sáu hằng tuần.", "매주 금요일 5시까지 보고서를 보내야 해요.", "Hạn chót cố định trong tuần."],
    ["You don’t need to answer emails after work.", "Bạn không cần trả lời email sau giờ làm.", "퇴근 후에는 이메일에 답하지 않아도 돼요.", "Quy định mới giúp Sora nghỉ ngơi tốt hơn."],
    ["My schedule changes every week.", "Lịch của tôi thay đổi mỗi tuần.", "제 일정은 매주 바뀌어요.", "Sora giải thích vì sao khó hẹn gặp bạn bè."],
    ["What time does your shift finish?", "Ca của bạn kết thúc lúc mấy giờ?", "근무는 몇 시에 끝나요?", "Câu hỏi trước khi hai người hẹn ăn tối."],
    ["I need to prepare the numbers before the meeting.", "Tôi cần chuẩn bị số liệu trước cuộc họp.", "회의 전에 숫자를 준비해야 해요.", "Việc Sora làm vào sáng thứ Hai."],
    ["Our team has three part-time staff.", "Nhóm chúng tôi có ba nhân viên bán thời gian.", "우리 팀에는 아르바이트 직원이 세 명 있어요.", "Thông tin Sora kể khi nói về đồng nghiệp."],
    ["How many tasks do you have today?", "Hôm nay bạn có bao nhiêu nhiệm vụ?", "오늘 할 일이 몇 개예요?", "Câu hỏi Linh hỏi trong giờ nghỉ trưa."],
    ["I’ve already finished one task.", "Tôi đã xong một nhiệm vụ rồi.", "이미 한 가지 일은 끝냈어요.", "Câu trả lời ngắn trong tin nhắn buổi chiều."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-job-tasks-listen-mc",
      "Nghe câu “I usually start at eight, but on Fridays I work the afternoon shift.” và chọn thông tin đúng.",
      ["Thứ Sáu Sora làm ca chiều.", "Sora làm ca chiều mỗi ngày.", "Sora bắt đầu lúc tám giờ tối."],
      "Thứ Sáu Sora làm ca chiều.",
      "listening",
      "a2-job-tasks-comprehension",
      "Chú ý “but on Fridays”.",
    ),
    exercise.dictation(
      "a2-job-tasks-listen-dictation",
      "Nghe và chép lại nhiệm vụ bắt buộc vào thứ Bảy.",
      "I have to check the orders on Saturday morning.",
      "a2-job-tasks-form",
    ),
  ],
  shadowing: {
    line: "I have to send a report every Friday at five.",
    notesVi: ["Nhấn mạnh “Friday” và “five” vì đó là thông tin về hạn chót.", "Đọc “have to” nhanh và nhẹ, gần như “hafta”."],
    notesKo: ["“Friday”와 “five”를 또렷하게 말하면 마감이 분명해져요.", "“have to”는 빠르고 가볍게 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-job-tasks-guided-mc",
      "Chọn câu đúng nghĩa “Tôi không cần làm việc cuối tuần.”",
      ["I don’t need to work at the weekend.", "I mustn’t work at the weekend.", "I need to work at the weekend."],
      "I don’t need to work at the weekend.",
      "grammar",
      "a2-job-tasks-form",
    ),
    exercise.fillBlank(
      "a2-job-tasks-guided-blank",
      "Điền “have to” hoặc “don’t need to”: “Our manager says we ______ send a report every Friday.”",
      "have to",
      "grammar",
      "a2-job-tasks-form",
      "Đây là yêu cầu từ quản lý.",
    ),
    exercise.arrange(
      "a2-job-tasks-guided-arrange",
      "Sắp xếp thành câu mô tả lịch lặp lại.",
      ["We", "have", "a", "team", "meeting", "every", "Monday", "."],
      "We have a team meeting every Monday .",
      "a2-job-tasks-form",
    ),
    exercise.translation(
      "a2-job-tasks-guided-translate",
      "Dịch sang tiếng Anh: “Tôi phụ trách đơn hàng trực tuyến.”",
      "I’m in charge of online orders.",
      "a2-job-tasks-communicate",
    ),
  ],
  production: [
    exercise.written(
      "a2-job-tasks-production-write",
      "Viết một đoạn 6–7 câu mô tả công việc hoặc việc học của bạn: hai nhiệm vụ, lịch lặp lại, một việc bắt buộc, một việc không cần làm và một hạn chót.",
      "a2-job-tasks-communicate",
      "I study English and I also work part-time in a bookshop. I’m in charge of the online orders, and I usually start at nine. We have a short meeting every Wednesday. I have to check the stock on Saturday, but I don’t need to work on Sunday. I need to finish my report before five on Friday.",
      ["Có hai nhiệm vụ và lịch cụ thể", "Có have to, need to hoặc don’t need to", "Có một hạn chót"],
    ),
    exercise.speaking(
      "a2-job-tasks-production-speak",
      "Nói 60–75 giây giới thiệu công việc hoặc việc học của bạn: nhiệm vụ chính, lịch tuần, việc bắt buộc và điều bạn cần làm hôm nay.",
      "a2-job-tasks-communicate",
      "I work in a small office and I’m in charge of the schedule. I usually start at eight thirty, and on Fridays I work the afternoon shift. I have to attend a team meeting every Monday, and I need to send a weekly report. Today I need to finish two tasks before five.",
      ["Có bốn thông tin theo yêu cầu", "Dùng have to hoặc need to ít nhất hai lần", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-job-tasks-mastery-mc",
      "Chọn câu đúng ngữ pháp.",
      ["I don’t need to attend the training course.", "I don’t need attend the training course.", "I don’t need to attending the training course."],
      "I don’t need to attend the training course.",
      "grammar",
      "a2-job-tasks-form",
    ),
    exercise.fillBlank(
      "a2-job-tasks-mastery-blank",
      "Điền dạng đúng: “She ______ (have to) work on Saturday morning.”",
      "has to",
      "grammar",
      "a2-job-tasks-form",
    ),
    exercise.dictation(
      "a2-job-tasks-mastery-dictation",
      "Nghe và chép lại câu về ca làm việc.",
      "On Fridays I work the afternoon shift.",
      "a2-job-tasks-comprehension",
    ),
    exercise.translation(
      "a2-job-tasks-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi cần chuẩn bị số liệu trước cuộc họp.”",
      "I need to prepare the numbers before the meeting.",
      "a2-job-tasks-communicate",
    ),
    exercise.speaking(
      "a2-job-tasks-mastery-speak",
      "Nói 75 giây về trách nhiệm của bạn trong một tuần: nhiệm vụ, lịch, hai việc bắt buộc và một việc không cần làm.",
      "a2-job-tasks-communicate",
      "I’m in charge of online orders. I usually start at eight, and I work the afternoon shift on Fridays. I have to check the orders on Saturday morning, but I don’t need to stay all day. I need to send my report every Friday at five.",
      ["Có bốn thông tin theo yêu cầu", "Dùng đúng have to và don’t need to", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể mô tả nhiệm vụ, lịch làm việc và trách nhiệm của mình."],
  spiralReview: ["A1: giờ giấc và ngày trong tuần", "A2 Unit 5 bài 3: trạng từ tần suất"],
  errorCategories: ["grammar-form", "missing-word", "word-choice", "preposition"],
};

/* ------------------------------------------------------------------ *
 * Bài 2 — Nói về kỹ năng và khả năng
 * ------------------------------------------------------------------ */
const skillsAbilities: LessonSeed = {
  id: "a2-skills-abilities",
  unitId,
  number: 2,
  prerequisites: ["a2-job-tasks"],
  titleVi: "Nói về kỹ năng và khả năng",
  titleKo: "기술과 능력 말하기",
  situationVi: "Linh chuẩn bị phỏng vấn cho vị trí mới và cùng Sora nói về kỹ năng, điểm mạnh và điều cần cải thiện.",
  situationKo: "린은 새 직장 면접을 준비해요. 소라와 함께 기술, 장점, 개선할 점을 이야기해요.",
  objectives: [
    { id: "a2-skills-abilities-communicate", en: "Talk about skills, strengths and things to improve.", vi: "Nói về kỹ năng, điểm mạnh và điều cần cải thiện.", ko: "기술, 강점, 개선할 점을 말할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-skills-abilities-form", en: "Use can, could and be able to.", vi: "Dùng can, could và be able to.", ko: "can, could, be able to를 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-skills-abilities-gerund", en: "Use gerunds and infinitives after common verbs.", vi: "Dùng động danh từ và động từ nguyên mẫu sau một số động từ thông dụng.", ko: "자주 쓰는 동사 뒤에 동명사와 부정사를 쓸 수 있어요.", skills: ["grammar", "speaking"] },
  ],
  vocab: [
    ["skill", "practical skill", "kỹ năng thực tế", "실무 기술", "/skɪl/", "SKILL", "neutral", ["a practical skill", "improve your skills"]],
    ["good-at", "be good at", "giỏi về", "…을 잘하다", "/biː ɡʊd æt/", "be GOOD at", "neutral", ["be good at numbers", "be good at explaining"]],
    ["improve", "improve your English", "cải thiện tiếng Anh", "영어를 늘리다", "/ɪmˈpruːv/", "imPROVE", "neutral", ["improve quickly", "improve your writing"]],
    ["experience", "work experience", "kinh nghiệm làm việc", "업무 경험", "/ɪkˈspɪəriəns/", "exPERience", "formal", ["work experience", "gain experience"]],
    ["confident", "feel confident", "cảm thấy tự tin", "자신감이 있다", "/ˈkɒnfɪdənt/", "CONfident", "neutral", ["feel confident about", "a confident speaker"]],
    ["manage", "manage a small team", "quản lý một nhóm nhỏ", "작은 팀을 관리하다", "/ˈmænɪdʒ/", "MANage", "formal", ["manage a team", "manage your time"]],
    ["solve", "solve a problem", "giải quyết vấn đề", "문제를 해결하다", "/sɒlv/", "SOLVE", "neutral", ["solve a problem", "solve it quickly"]],
    ["training", "training course", "khóa đào tạo", "교육 과정", "/ˈtreɪnɪŋ kɔːs/", "TRAINing course", "formal", ["attend a training course", "start training"]],
    ["practise", "practise every day", "luyện tập mỗi ngày", "매일 연습하다", "/ˈpræktɪs/", "PRACtise", "neutral", ["practise speaking", "practise every day"]],
    ["improve-on", "improve on last year", "tiến bộ hơn năm ngoái", "작년보다 나아지다", "/ɪmˈpruːv ɒn/", "imPROVE on", "neutral", ["improve on your result", "improve on the first try"]],
  ],
  dialogue: [
    ["Linh", "I have an interview on Thursday and I’m nervous.", "Thứ Năm tôi phỏng vấn và tôi hồi hộp.", "목요일에 면접이 있는데 긴장돼요.", "casual"],
    ["Sora", "You can speak English well, so you’ll be fine.", "Bạn nói tiếng Anh tốt mà, sẽ ổn thôi.", "영어를 잘하니까 괜찮을 거예요.", "casual"],
    ["Linh", "Thanks. I could write reports last year, but I couldn’t present them.", "Cảm ơn. Năm ngoái tôi viết được báo cáo, nhưng không trình bày được.", "고마워요. 작년에는 보고서를 쓸 수 있었지만 발표는 못 했어요.", "neutral"],
    ["Sora", "And now?", "Còn bây giờ?", "지금은요?", "casual"],
    ["Linh", "Now I’m able to present in front of ten people.", "Bây giờ tôi có thể trình bày trước mười người.", "이제는 열 명 앞에서 발표할 수 있어요.", "neutral"],
    ["Sora", "That’s a big change. What are you good at?", "Đó là thay đổi lớn. Bạn giỏi việc gì?", "정말 큰 변화네요. 무엇을 잘해요?", "neutral"],
    ["Linh", "I’m good at organising tasks, and I enjoy working with numbers.", "Tôi giỏi sắp xếp nhiệm vụ và thích làm việc với số liệu.", "일을 정리하는 걸 잘하고 숫자 다루는 걸 좋아해요.", "neutral"],
    ["Sora", "You should say that in the interview. What do you want to improve?", "Bạn nên nói điều đó trong buổi phỏng vấn. Bạn muốn cải thiện gì?", "면접에서 그렇게 말해 보세요. 무엇을 개선하고 싶어요?", "neutral"],
    ["Linh", "I want to improve my speaking speed.", "Tôi muốn cải thiện tốc độ nói.", "말하는 속도를 높이고 싶어요.", "neutral"],
    ["Sora", "You could practise with me twice a week.", "Bạn có thể luyện với tôi hai lần một tuần.", "저와 일주일에 두 번 연습할 수 있어요.", "neutral"],
    ["Linh", "That would help. Can you listen to my answers tonight?", "Như vậy sẽ hữu ích. Tối nay bạn nghe thử câu trả lời của tôi được không?", "그러면 도움이 될 거예요. 오늘 밤 제 답변을 들어 줄 수 있어요?", "casual"],
    ["Sora", "Of course. Bring your notes and we’ll start at seven.", "Tất nhiên. Mang ghi chú của bạn đến, chúng ta bắt đầu lúc bảy giờ.", "물론이죠. 메모를 가져오세요. 7시에 시작해요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "can, could và be able to",
      titleKo: "can, could, be able to",
      explanationVi: "can dùng cho khả năng ở hiện tại: “I can speak English well.” could dùng cho khả năng trong quá khứ: “I couldn’t present them last year.” be able to linh hoạt hơn, dùng được sau will hoặc have to: “I’ll be able to help you tomorrow.”",
      explanationKo: "can은 현재 능력, could는 과거 능력을 말해요. be able to는 will이나 have to 뒤에도 쓸 수 있어서 더 유연해요.",
      easierKorean: "지금 할 수 있으면 can, 예전에 할 수 있었으면 could예요.",
    },
    {
      titleVi: "Động danh từ và động từ nguyên mẫu",
      titleKo: "동명사와 부정사",
      explanationVi: "Sau enjoy, be good at, practise và giới từ, dùng động từ + -ing: “I enjoy working with numbers.” Sau want, need, would like và decide, dùng to + động từ nguyên mẫu: “I want to improve my speaking speed.”",
      explanationKo: "enjoy, be good at, practise 뒤에는 동명사를, want, need, would like 뒤에는 to부정사를 써요.",
      easierKorean: "enjoy 뒤에는 -ing, want 뒤에는 to + 동사원형을 써요.",
    },
  ],
  examples: [
    ["I can speak English well.", "Tôi có thể nói tiếng Anh tốt.", "저는 영어를 잘할 수 있어요.", "Sora động viên Linh trước buổi phỏng vấn."],
    ["I couldn’t present in front of a group last year.", "Năm ngoái tôi không thể trình bày trước một nhóm.", "작년에는 여러 사람 앞에서 발표하지 못했어요.", "Linh nói về khả năng cũ của mình."],
    ["Now I’m able to present to ten people.", "Bây giờ tôi có thể trình bày trước mười người.", "이제는 열 명 앞에서 발표할 수 있어요.", "Tiến bộ Linh đạt được sau khóa học."],
    ["I’ll be able to help you tomorrow.", "Mai tôi sẽ có thể giúp bạn.", "내일은 도와줄 수 있어요.", "Sora trả lời khi Linh hỏi về buổi luyện tập."],
    ["Can you listen to my answers tonight?", "Tối nay bạn nghe câu trả lời của tôi được không?", "오늘 밤 제 답변을 들어 줄 수 있어요?", "Lời nhờ giúp đỡ trước buổi phỏng vấn."],
    ["I’m good at organising tasks.", "Tôi giỏi sắp xếp nhiệm vụ.", "저는 일을 정리하는 걸 잘해요.", "Điểm mạnh Linh chọn để trình bày trong phỏng vấn."],
    ["She’s good at explaining things simply.", "Cô ấy giỏi giải thích mọi thứ một cách đơn giản.", "그녀는 쉽게 설명하는 걸 잘해요.", "Nhận xét của đồng nghiệp về một thành viên mới."],
    ["I enjoy working with numbers.", "Tôi thích làm việc với số liệu.", "저는 숫자 다루는 일을 좋아해요.", "Lý do Linh chọn vị trí kế toán."],
    ["He wants to improve his writing.", "Anh ấy muốn cải thiện kỹ năng viết.", "그는 쓰기를 늘리고 싶어해요.", "Mục tiêu của một đồng nghiệp trong nhóm."],
    ["I need to practise speaking every day.", "Tôi cần luyện nói mỗi ngày.", "매일 말하기를 연습해야 해요.", "Kế hoạch Linh tự đặt ra."],
    ["It’s important to gain work experience.", "Việc có kinh nghiệm làm việc là quan trọng.", "업무 경험을 쌓는 것이 중요해요.", "Lời khuyên của người hướng dẫn trong lớp học."],
    ["I didn’t feel confident two months ago.", "Hai tháng trước tôi không thấy tự tin.", "두 달 전에는 자신감이 없었어요.", "Linh kể về cảm giác trước khóa đào tạo."],
    ["Now I feel confident about phone calls in English.", "Bây giờ tôi tự tin khi gọi điện bằng tiếng Anh.", "이제는 영어로 전화하는 게 자신 있어요.", "Kết quả Sora ghi nhận được."],
    ["Can you manage a small team?", "Bạn có thể quản lý một nhóm nhỏ không?", "작은 팀을 관리할 수 있어요?", "Câu hỏi thường gặp trong phỏng vấn."],
    ["I can solve problems quickly, but I need to work on my speed.", "Tôi có thể giải quyết vấn đề nhanh, nhưng cần cải thiện tốc độ.", "문제를 빨리 해결할 수 있지만 속도는 더 연습해야 해요.", "Câu trả lời cân bằng giữa điểm mạnh và điểm cần cải thiện."],
    ["I’d like to start the training course in March.", "Tôi muốn bắt đầu khóa đào tạo vào tháng Ba.", "3월에 교육 과정을 시작하고 싶어요.", "Kế hoạch Linh trình bày với quản lý."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-skills-abilities-listen-mc",
      "Nghe câu “I couldn’t present in front of a group last year.” và chọn thông tin đúng.",
      ["Năm ngoái Linh không thể trình bày trước một nhóm.", "Năm ngoái Linh trình bày rất tốt.", "Bây giờ Linh vẫn không trình bày được."],
      "Năm ngoái Linh không thể trình bày trước một nhóm.",
      "listening",
      "a2-skills-abilities-form",
      "Chú ý “couldn’t” và “last year”.",
    ),
    exercise.dictation(
      "a2-skills-abilities-listen-dictation",
      "Nghe và chép lại câu về điểm mạnh.",
      "I’m good at organising tasks.",
      "a2-skills-abilities-communicate",
    ),
  ],
  shadowing: {
    line: "I enjoy working with numbers, and I’m good at organising tasks.",
    notesVi: ["Nhấn vào “enjoy” để thể hiện sở thích.", "Đọc “organising tasks” nhanh và liền, không tách từng từ."],
    notesKo: ["“enjoy”를 살짝 세게 말하면 관심사가 잘 드러나요.", "“organising tasks”는 빠르게 붙여 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-skills-abilities-guided-mc",
      "Chọn câu đúng.",
      ["I want to improve my writing.", "I want improving my writing.", "I want improve my writing."],
      "I want to improve my writing.",
      "grammar",
      "a2-skills-abilities-gerund",
    ),
    exercise.fillBlank(
      "a2-skills-abilities-guided-blank",
      "Điền dạng đúng: “She’s good at ______ (explain) things simply.”",
      "explaining",
      "grammar",
      "a2-skills-abilities-gerund",
    ),
    exercise.arrange(
      "a2-skills-abilities-guided-arrange",
      "Sắp xếp thành câu về khả năng trong quá khứ.",
      ["I", "couldn’t", "present", "in", "front", "of", "a", "group", "last", "year", "."],
      "I couldn’t present in front of a group last year .",
      "a2-skills-abilities-form",
    ),
    exercise.translation(
      "a2-skills-abilities-guided-translate",
      "Dịch sang tiếng Anh: “Bây giờ tôi có thể trình bày trước mười người.”",
      "Now I’m able to present to ten people.",
      "a2-skills-abilities-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-skills-abilities-production-write",
      "Viết 6–7 câu giới thiệu kỹ năng của bạn: hai điểm mạnh với be good at hoặc enjoy, một khả năng trong quá khứ với could, một khả năng hiện tại với can hoặc be able to và một điều bạn muốn cải thiện.",
      "a2-skills-abilities-communicate",
      "I’m good at organising tasks, and I enjoy working with numbers. Two years ago I couldn’t speak English at work, but now I can answer emails and phone calls. I’m able to explain simple problems to customers. I want to improve my speaking speed, so I need to practise every day.",
      ["Có hai điểm mạnh", "Có could, can hoặc be able to", "Có một mục tiêu cải thiện"],
    ),
    exercise.speaking(
      "a2-skills-abilities-production-speak",
      "Đóng vai trả lời phỏng vấn trong 60–75 giây: nêu hai kỹ năng, một ví dụ cụ thể và một điều bạn đang cải thiện.",
      "a2-skills-abilities-communicate",
      "I’m good at organising tasks and I enjoy working with numbers. Last year I couldn’t present in front of a group, but now I’m able to present to ten people. I can solve problems quickly, and I want to improve my speaking speed, so I practise twice a week.",
      ["Có hai kỹ năng và ví dụ", "Có can, could hoặc be able to", "Giọng rõ, tốc độ vừa phải"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-skills-abilities-mastery-mc",
      "Chọn câu đúng.",
      ["I’m able to work in a team.", "I’m able work in a team.", "I’m able to working in a team."],
      "I’m able to work in a team.",
      "grammar",
      "a2-skills-abilities-form",
    ),
    exercise.fillBlank(
      "a2-skills-abilities-mastery-blank",
      "Điền dạng đúng: “He enjoys ______ (solve) difficult problems.”",
      "solving",
      "grammar",
      "a2-skills-abilities-gerund",
    ),
    exercise.dictation(
      "a2-skills-abilities-mastery-dictation",
      "Nghe và chép lại câu về tự tin khi gọi điện.",
      "Now I feel confident about phone calls in English.",
      "a2-skills-abilities-comprehension",
    ),
    exercise.translation(
      "a2-skills-abilities-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi cần luyện nói mỗi ngày.”",
      "I need to practise speaking every day.",
      "a2-skills-abilities-communicate",
    ),
    exercise.speaking(
      "a2-skills-abilities-mastery-speak",
      "Nói 75 giây về kỹ năng của bạn: hai điểm mạnh, một khả năng trước đây, một khả năng hiện tại và kế hoạch cải thiện.",
      "a2-skills-abilities-communicate",
      "I’m good at planning my time, and I enjoy learning languages. Last year I couldn’t speak English on the phone, but now I’m able to answer simple questions. I can write short reports, and I want to improve my listening, so I practise with podcasts every day.",
      ["Đủ bốn phần", "Dùng đúng can, could, be able to", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể nói về kỹ năng, khả năng và điều mình muốn cải thiện."],
  spiralReview: ["A1: sở thích với like và enjoy", "A2 Unit 5 bài 3: động danh từ sau động từ thông dụng"],
  errorCategories: ["grammar-form", "word-choice", "missing-word", "word-order"],
};

/* ------------------------------------------------------------------ *
 * Bài 3 — Xin phép, đề nghị hỗ trợ và thương lượng thời hạn
 * ------------------------------------------------------------------ */
const permissionNegotiation: LessonSeed = {
  id: "a2-permission-deadlines",
  unitId,
  number: 3,
  prerequisites: ["a2-skills-abilities"],
  titleVi: "Xin phép, đề nghị hỗ trợ và thương lượng thời hạn",
  titleKo: "허락을 구하고 도움을 요청하고 기한을 조정하기",
  situationVi: "Linh xin nghỉ một buổi, đề nghị đồng nghiệp hỗ trợ và thương lượng lùi hạn chót với quản lý.",
  situationKo: "린은 오전 휴가를 요청하고, 동료에게 도움을 부탁하고, 관리자와 마감을 조정해요.",
  objectives: [
    { id: "a2-permission-deadlines-communicate", en: "Ask for permission and help at work.", vi: "Xin phép và nhờ hỗ trợ trong công việc.", ko: "직장에서 허락과 도움을 요청할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-permission-deadlines-form", en: "Negotiate a deadline politely.", vi: "Thương lượng thời hạn một cách lịch sự.", ko: "정중하게 마감을 조정할 수 있어요.", skills: ["speaking", "writing"] },
    { id: "a2-permission-deadlines-advice", en: "Use should for advice about priorities.", vi: "Dùng should để khuyên về thứ tự ưu tiên.", ko: "should로 우선순위에 대해 조언할 수 있어요.", skills: ["grammar", "listening"] },
  ],
  vocab: [
    ["permission", "ask for permission", "xin phép", "허락을 구하다", "/pəˈmɪʃn/", "perMISsion", "formal", ["ask for permission", "get permission"]],
    ["day-off", "take a day off", "nghỉ một ngày", "하루 휴가를 내다", "/deɪ ɒf/", "day OFF", "neutral", ["take a day off", "book a day off"]],
    ["negotiate", "negotiate a deadline", "thương lượng thời hạn", "마감을 조정하다", "/nɪˈɡəʊʃieɪt/", "neGOtiate", "formal", ["negotiate a deadline", "negotiate with your manager"]],
    ["extend", "extend the deadline", "lùi hạn chót", "마감을 연장하다", "/ɪkˈstend/", "exTEND", "formal", ["extend the deadline", "extend by two days"]],
    ["flexible", "a flexible schedule", "lịch làm việc linh hoạt", "유연한 일정", "/ˈfleksəbl/", "FLEXible", "neutral", ["a flexible schedule", "be flexible about"]],
    ["swap", "swap shifts", "đổi ca", "근무를 바꾸다", "/swɒp/", "SWAP", "casual", ["swap shifts", "swap with a colleague"]],
    ["request", "make a request", "đưa ra yêu cầu", "요청을 하다", "/rɪˈkwest/", "reQUEST", "formal", ["make a request", "a formal request"]],
    ["advance", "in advance", "trước (thời hạn)", "미리", "/ɪn ədˈvɑːns/", "in adVANCE", "formal", ["ask in advance", "two days in advance"]],
    ["priority", "first priority", "ưu tiên hàng đầu", "최우선 순위", "/praɪˈɒrəti/", "priORity", "formal", ["the first priority", "set priorities"]],
    ["deadline", "tight deadline", "hạn chót gấp", "촉박한 마감", "/ˈdedlaɪn/", "DEADline", "neutral", ["a tight deadline", "change the deadline"]],
  ],
  dialogue: [
    ["Linh", "Could I take Friday morning off? I have a medical appointment.", "Tôi có thể nghỉ sáng thứ Sáu không? Tôi có lịch khám.", "금요일 오전에 휴가를 낼 수 있을까요? 병원 예약이 있어요.", "formal"],
    ["Manager", "That should be fine. Have you asked anyone to cover your tasks?", "Chắc là được. Bạn đã nhờ ai làm thay phần việc của mình chưa?", "괜찮을 거예요. 업무를 대신할 사람에게 부탁했나요?", "formal"],
    ["Linh", "Not yet. Would you mind if I asked Tom to check the orders?", "Chưa. Tôi nhờ Tom kiểm tra đơn hàng có được không?", "아직요. 톰에게 주문 확인을 부탁해도 될까요?", "formal"],
    ["Manager", "That’s fine. What about the Friday report?", "Được đấy. Còn báo cáo thứ Sáu thì sao?", "괜찮아요. 금요일 보고서는요?", "formal"],
    ["Linh", "Could we extend the deadline to Monday? I need two more days to check the numbers.", "Chúng ta có thể lùi hạn đến thứ Hai không? Tôi cần thêm hai ngày để kiểm tra số liệu.", "마감을 월요일로 연장할 수 있을까요? 숫자를 확인하려면 이틀 더 필요해요.", "formal"],
    ["Manager", "Monday is possible, but the client needs the summary on Friday.", "Thứ Hai thì được, nhưng khách cần bản tóm tắt vào thứ Sáu.", "월요일은 가능하지만 고객은 금요일에 요약본이 필요해요.", "formal"],
    ["Linh", "So should I send a short summary on Friday and the full report on Monday?", "Vậy tôi nên gửi tóm tắt ngắn thứ Sáu và báo cáo đầy đủ thứ Hai không?", "그럼 금요일에 짧은 요약을 보내고 월요일에 전체 보고서를 보내면 될까요?", "formal"],
    ["Manager", "Exactly. You should ask Tom for the numbers today.", "Chính xác. Bạn nên hỏi Tom số liệu ngay hôm nay.", "맞아요. 오늘 톰에게 숫자를 요청하세요.", "formal"],
    ["Linh", "I’ll do that. Could you confirm the new deadline by email?", "Tôi sẽ làm vậy. Bạn xác nhận hạn mới qua email được không?", "그렇게 할게요. 새 마감을 이메일로 확인해 주시겠어요?", "formal"],
    ["Manager", "Of course. I’ll send it this afternoon.", "Tất nhiên. Tôi sẽ gửi chiều nay.", "물론이죠. 오늘 오후에 보낼게요.", "formal"],
    ["Linh", "Thank you. One more thing — can I swap my Thursday shift with Anna?", "Cảm ơn. Còn một việc nữa — tôi đổi ca thứ Năm với Anna được không?", "감사합니다. 하나 더요, 목요일 근무를 안나와 바꿀 수 있을까요?", "formal"],
    ["Manager", "Ask her first, then let me know in advance.", "Hỏi cô ấy trước, rồi báo tôi trước nhé.", "먼저 그녀에게 물어보고, 미리 알려 주세요.", "formal"],
  ],
  grammar: [
    {
      titleVi: "Xin phép và nhờ hỗ trợ lịch sự",
      titleKo: "정중하게 허락과 도움을 구하기",
      explanationVi: "Could I…? và Would you mind if I…? dùng để xin phép: “Could I take Friday morning off?” Để nhờ hỗ trợ, dùng Could you…? hoặc Would you mind -ing: “Would you mind checking the orders?”",
      explanationKo: "허락을 구할 때는 Could I…?나 Would you mind if I…?를 써요. 도움을 부탁할 때는 Could you…?나 Would you mind -ing를 써요.",
      easierKorean: "허락은 Could I, 부탁은 Could you로 시작해요.",
    },
    {
      titleVi: "should cho lời khuyên về ưu tiên",
      titleKo: "우선순위 조언의 should",
      explanationVi: "should dùng để đề nghị điều nên làm: “You should ask Tom for the numbers today.” Câu hỏi “Should I…?” dùng để xin ý kiến về lựa chọn: “Should I send a short summary on Friday?”",
      explanationKo: "should는 해야 할 일을 조언할 때 써요. “Should I…?”는 선택에 대한 의견을 물을 때 써요.",
      easierKorean: "조언은 You should, 의견을 물을 때는 Should I를 써요.",
    },
  ],
  examples: [
    ["Could I take Friday morning off?", "Tôi có thể nghỉ sáng thứ Sáu không?", "금요일 오전에 휴가를 낼 수 있을까요?", "Câu xin phép Linh nói với quản lý."],
    ["Would you mind if I asked Tom to help?", "Tôi nhờ Tom giúp có được không?", "톰에게 도움을 부탁해도 될까요?", "Cách xin phép lịch sự trong công việc."],
    ["Could you help me with the numbers?", "Bạn giúp tôi phần số liệu được không?", "숫자 부분을 도와줄 수 있어요?", "Lời nhờ đồng nghiệp trong cùng nhóm."],
    ["Would you mind checking the orders?", "Bạn kiểm tra đơn hàng giúp được không?", "주문 확인을 부탁드려도 될까요?", "Lời nhờ hỗ trợ khi Linh đi khám."],
    ["Could we extend the deadline to Monday?", "Chúng ta có thể lùi hạn đến thứ Hai không?", "마감을 월요일로 연장할 수 있을까요?", "Câu thương lượng chính trong cuộc họp."],
    ["I need two more days to check the numbers.", "Tôi cần thêm hai ngày để kiểm tra số liệu.", "숫자를 확인하려면 이틀 더 필요해요.", "Lý do Linh đưa ra khi đề nghị lùi hạn."],
    ["I can send a summary on Friday if that helps.", "Tôi có thể gửi tóm tắt thứ Sáu nếu điều đó hữu ích.", "도움이 된다면 금요일에 요약본을 보낼 수 있어요.", "Phương án Linh đề nghị để khách vẫn có thông tin."],
    ["You should ask Tom for the numbers today.", "Bạn nên hỏi Tom số liệu ngay hôm nay.", "오늘 톰에게 숫자를 요청하는 게 좋아요.", "Lời khuyên của quản lý về thứ tự công việc."],
    ["Should I send the full report on Monday?", "Tôi nên gửi báo cáo đầy đủ vào thứ Hai không?", "월요일에 전체 보고서를 보내면 될까요?", "Câu hỏi xin xác nhận về kế hoạch."],
    ["Please let me know two days in advance.", "Hãy cho tôi biết trước hai ngày.", "이틀 전에 알려 주세요.", "Yêu cầu của quản lý về việc đổi ca."],
    ["Can I swap my Thursday shift with Anna?", "Tôi đổi ca thứ Năm với Anna được không?", "목요일 근무를 안나와 바꿀 수 있을까요?", "Câu hỏi khi Linh cần đổi lịch cá nhân."],
    ["My schedule is flexible this week.", "Tuần này lịch của tôi linh hoạt.", "이번 주는 제 일정이 유연해요.", "Sora nói khi được nhờ hỗ trợ."],
    ["The client’s request is the first priority.", "Yêu cầu của khách là ưu tiên hàng đầu.", "고객 요청이 최우선 순위예요.", "Quản lý giải thích lý do không thể lùi quá lâu."],
    ["We have a tight deadline, so let’s start early.", "Chúng ta có hạn gấp, nên hãy bắt đầu sớm.", "마감이 촉박하니까 일찍 시작해요.", "Câu trao đổi trong cuộc họp nhóm."],
    ["I’ll confirm everything by email.", "Tôi sẽ xác nhận mọi thứ qua email.", "모든 내용을 이메일로 확인할게요.", "Câu kết thúc để tránh hiểu nhầm."],
    ["Thanks for being flexible about the deadline.", "Cảm ơn vì đã linh hoạt về thời hạn.", "마감을 유연하게 조정해 주셔서 감사합니다.", "Câu cảm ơn cuối cuộc thương lượng."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-permission-deadlines-listen-mc",
      "Nghe câu “Could we extend the deadline to Monday?” và chọn đề nghị đúng.",
      ["Lùi hạn chót sang thứ Hai.", "Nộp báo cáo sớm hơn.", "Hủy báo cáo tuần này."],
      "Lùi hạn chót sang thứ Hai.",
      "listening",
      "a2-permission-deadlines-form",
      "Chú ý giới từ “to” đứng trước thứ Hai.",
    ),
    exercise.dictation(
      "a2-permission-deadlines-listen-dictation",
      "Nghe và chép lại lời khuyên của quản lý.",
      "You should ask Tom for the numbers today.",
      "a2-permission-deadlines-advice",
    ),
  ],
  shadowing: {
    line: "Would you mind checking the orders for me?",
    notesVi: ["Lên giọng nhẹ ở “mind” để tạo giọng lịch sự.", "Đọc “checking the orders” liền mạch, nhấn nhẹ ở “orders”."],
    notesKo: ["“mind”를 살짝 올리면 정중한 부탁으로 들려요.", "“checking the orders”는 이어 말하고 “orders”를 살짝 세게 해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-permission-deadlines-guided-mc",
      "Chọn cách xin phép lịch sự nhất.",
      ["Could I take Friday morning off?", "I take Friday off.", "Give me Friday off."],
      "Could I take Friday morning off?",
      "grammar",
      "a2-permission-deadlines-communicate",
    ),
    exercise.fillBlank(
      "a2-permission-deadlines-guided-blank",
      "Điền “Should” hoặc “Shouldn’t”: “______ I send the summary on Friday?”",
      "Should",
      "grammar",
      "a2-permission-deadlines-advice",
    ),
    exercise.arrange(
      "a2-permission-deadlines-guided-arrange",
      "Sắp xếp thành câu thương lượng thời hạn.",
      ["Could", "we", "extend", "the", "deadline", "to", "Monday", "?"],
      "Could we extend the deadline to Monday ?",
      "a2-permission-deadlines-form",
    ),
    exercise.translation(
      "a2-permission-deadlines-guided-translate",
      "Dịch sang tiếng Anh: “Bạn kiểm tra đơn hàng giúp tôi được không?”",
      "Would you mind checking the orders for me?",
      "a2-permission-deadlines-communicate",
    ),
  ],
  production: [
    exercise.written(
      "a2-permission-deadlines-production-write",
      "Viết email ngắn (6–7 câu) cho quản lý: xin nghỉ một buổi, đề nghị người hỗ trợ, giải thích lý do cần thêm thời gian, đề xuất hạn mới và xin xác nhận.",
      "a2-permission-deadlines-communicate",
      "Dear Mr Lee, could I take Friday morning off? I have a medical appointment. Would you mind if I asked Tom to check the orders? I need two more days for the numbers, so could we extend the deadline to Monday? I can send a short summary on Friday if that helps. Could you confirm the new deadline by email? Thank you for being flexible.",
      ["Có lời xin phép và đề nghị hỗ trợ", "Có đề xuất hạn mới và lý do", "Có câu xin xác nhận"],
    ),
    exercise.speaking(
      "a2-permission-deadlines-production-speak",
      "Nói 75 giây: xin nghỉ, nhờ hỗ trợ, thương lượng hạn chót và chốt lại thỏa thuận.",
      "a2-permission-deadlines-communicate",
      "Could I take Friday morning off? I have an appointment. Would you mind if Tom checked the orders? I need two more days for the report, so could we extend the deadline to Monday? If you prefer, I can send a summary on Friday. Should I ask Tom for the numbers today?",
      ["Có bốn bước của cuộc thương lượng", "Dùng Could I, Would you mind, Should I", "Giọng lịch sự, bình tĩnh"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-permission-deadlines-mastery-mc",
      "Chọn câu nhờ hỗ trợ đúng ngữ pháp.",
      ["Would you mind helping me with the report?", "Would you mind to help me with the report?", "Would you mind help me with the report?"],
      "Would you mind helping me with the report?",
      "grammar",
      "a2-permission-deadlines-communicate",
    ),
    exercise.fillBlank(
      "a2-permission-deadlines-mastery-blank",
      "Điền “should” hoặc “shouldn’t”: “You ______ tell your manager two days in advance.”",
      "should",
      "grammar",
      "a2-permission-deadlines-advice",
    ),
    exercise.dictation(
      "a2-permission-deadlines-mastery-dictation",
      "Nghe và chép lại yêu cầu về thời gian báo trước.",
      "Please let me know two days in advance.",
      "a2-permission-deadlines-communicate",
    ),
    exercise.translation(
      "a2-permission-deadlines-mastery-translate",
      "Dịch sang tiếng Anh: “Tuần này lịch của tôi linh hoạt.”",
      "My schedule is flexible this week.",
      "a2-permission-deadlines-form",
    ),
    exercise.speaking(
      "a2-permission-deadlines-mastery-speak",
      "Nói 75 giây: xin phép một buổi nghỉ, nhờ một đồng nghiệp hỗ trợ, thương lượng hạn chót và xác nhận lại bằng email.",
      "a2-permission-deadlines-communicate",
      "Could I take Thursday afternoon off? Would you mind if Anna covered my shift? I need one more day for the report, so could we extend the deadline to Friday? Should I send a short summary first? Could you confirm the new deadline by email?",
      ["Đủ bốn bước", "Ngôn ngữ lịch sự, phù hợp công việc", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể xin phép, nhờ hỗ trợ và thương lượng thời hạn một cách lịch sự."],
  spiralReview: ["A2 Unit 2: nhờ giúp đỡ và đổi lịch hẹn", "A2 Unit 4: câu hỏi gián tiếp và xác nhận bằng văn bản"],
  errorCategories: ["register", "grammar-form", "missing-word", "word-order"],
};

/* ------------------------------------------------------------------ *
 * Bài 4 — Báo cáo tiến độ và giải thích vấn đề
 * ------------------------------------------------------------------ */
const progressReporting: LessonSeed = {
  id: "a2-progress-reporting",
  unitId,
  number: 4,
  prerequisites: ["a2-permission-deadlines"],
  titleVi: "Báo cáo tiến độ và giải thích vấn đề",
  titleKo: "진행 상황을 보고하고 문제를 설명하기",
  situationVi: "Linh báo cáo tiến độ dự án trong cuộc họp nhóm: việc đã xong, việc đang làm, vấn đề phát sinh và kế hoạch tiếp theo.",
  situationKo: "린은 팀 회의에서 프로젝트 진행 상황을 보고해요. 끝난 일, 진행 중인 일, 문제, 다음 계획을 말해요.",
  objectives: [
    { id: "a2-progress-reporting-communicate", en: "Report progress and explain a problem at work.", vi: "Báo cáo tiến độ và giải thích một vấn đề trong công việc.", ko: "업무 진행 상황과 문제를 설명할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-progress-reporting-form", en: "Use the present perfect with for, since, just, already and yet.", vi: "Dùng hiện tại hoàn thành với for, since, just, already và yet.", ko: "for, since, just, already, yet과 함께 현재완료를 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-progress-reporting-comprehension", en: "Follow a status update and identify what is late.", vi: "Nghe hiểu báo cáo tiến độ và nhận ra phần nào bị chậm.", ko: "진행 보고를 듣고 늦어진 부분을 찾아낼 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["progress", "make progress", "đạt tiến độ", "진전을 보이다", "/ˈprəʊɡres/", "PROgress", "neutral", ["make progress", "good progress"]],
    ["update", "send an update", "gửi cập nhật", "업데이트를 보내다", "/ˈʌpdeɪt/", "UPdate", "neutral", ["a quick update", "send an update"]],
    ["on-track", "be on track", "đúng tiến độ", "순조롭게 진행되다", "/ɒn træk/", "on TRACK", "neutral", ["be on track", "stay on track"]],
    ["complete", "complete the report", "hoàn thành báo cáo", "보고서를 완성하다", "/kəmˈpliːt/", "comPLETE", "formal", ["complete the task", "complete the report"]],
    ["delay", "cause a delay", "gây ra sự chậm trễ", "지연을 일으키다", "/dɪˈleɪ/", "deLAY", "neutral", ["a short delay", "cause a delay"]],
    ["explain", "explain the problem", "giải thích vấn đề", "문제를 설명하다", "/ɪkˈspleɪn/", "exPLAIN", "neutral", ["explain the problem", "explain clearly"]],
    ["expect", "take longer than expected", "lâu hơn dự kiến", "예상보다 오래 걸리다", "/ɪkˈspekt/", "exPECT", "neutral", ["longer than expected", "as expected"]],
    ["catch-up", "catch up on the work", "làm bù phần việc còn lại", "밀린 일을 따라잡다", "/kætʃ ʌp ɒn/", "catch UP on", "casual", ["catch up on emails", "catch up on the work"]],
    ["fix", "fix a problem", "sửa một vấn đề", "문제를 해결하다", "/fɪks/", "FIX", "casual", ["fix a problem", "fix it quickly"]],
    ["meeting", "status meeting", "cuộc họp tiến độ", "진행 회의", "/ˈmiːtɪŋ/", "MEEting", "neutral", ["a status meeting", "join the meeting"]],
  ],
  dialogue: [
    ["Manager", "Let’s start with the update. How’s the report going?", "Bắt đầu với cập nhật nhé. Báo cáo thế nào rồi?", "업데이트부터 시작해요. 보고서는 어떻게 되고 있어요?", "formal"],
    ["Linh", "I’ve already finished the first two sections.", "Tôi đã hoàn thành hai phần đầu rồi.", "처음 두 부분은 이미 끝냈어요.", "formal"],
    ["Manager", "Good. Have you checked the numbers yet?", "Tốt. Bạn đã kiểm tra số liệu chưa?", "좋아요. 숫자는 확인했어요?", "formal"],
    ["Linh", "Not yet. I’ve just received the sales figures this morning.", "Chưa. Tôi vừa nhận được số liệu bán hàng sáng nay.", "아직요. 오늘 아침에 매출 숫자를 막 받았어요.", "formal"],
    ["Manager", "Is everything on track for Friday?", "Mọi thứ có đúng tiến độ cho thứ Sáu không?", "금요일까지 순조롭게 진행되고 있어요?", "formal"],
    ["Linh", "Mostly. One part is taking longer than expected.", "Phần lớn là vậy. Một phần đang lâu hơn dự kiến.", "대부분은요. 한 부분이 예상보다 오래 걸려요.", "formal"],
    ["Manager", "Which part?", "Phần nào?", "어느 부분이요?", "formal"],
    ["Linh", "The comparison table. I’ve been checking it for two days, and I still need the March data.", "Bảng so sánh. Tôi đã kiểm tra nó hai ngày rồi, và vẫn cần số liệu tháng Ba.", "비교 표예요. 이틀 동안 확인했는데 3월 데이터가 아직 필요해요.", "formal"],
    ["Manager", "I see. Can we fix that today?", "Tôi hiểu rồi. Hôm nay xử lý được không?", "알겠어요. 오늘 해결할 수 있어요?", "formal"],
    ["Linh", "Yes. Tom has worked on similar tables since January, so he can help me.", "Được. Tom đã làm những bảng tương tự từ tháng Một, nên anh ấy có thể giúp tôi.", "네. 톰이 1월부터 비슷한 표를 만들어 왔으니까 도와줄 수 있어요.", "formal"],
    ["Manager", "Great. Please send me an update this afternoon.", "Tốt đấy. Chiều nay gửi tôi bản cập nhật nhé.", "좋아요. 오늘 오후에 업데이트를 보내 주세요.", "formal"],
    ["Linh", "I’ll send it before four. I haven’t finished the last section yet, but it’ll be ready tomorrow morning.", "Tôi sẽ gửi trước bốn giờ. Tôi chưa xong phần cuối, nhưng sáng mai sẽ xong.", "4시 전에 보낼게요. 마지막 부분은 아직 못 끝냈지만 내일 아침까지 될 거예요.", "formal"],
  ],
  grammar: [
    {
      titleVi: "Hiện tại hoàn thành với for, since, just, already, yet",
      titleKo: "for, since, just, already, yet과 현재완료",
      explanationVi: "Dùng hiện tại hoàn thành để nói việc đã xong và còn liên quan tới hiện tại: “I’ve already finished two sections.” already đứng trước động từ chính, yet đứng cuối câu phủ định và câu hỏi: “I haven’t finished the last section yet.” for + khoảng thời gian, since + mốc thời gian.",
      explanationKo: "현재완료는 끝난 일이 지금과 이어질 때 써요. already는 동사 앞, yet은 부정문과 의문문 끝에 와요. for는 기간, since는 시작 시점과 함께 써요.",
      easierKorean: "already는 끝난 일, yet은 아직 안 끝난 일에 써요.",
    },
    {
      titleVi: "Động từ nguyên mẫu và động danh từ trong công việc",
      titleKo: "업무 상황의 부정사와 동명사",
      explanationVi: "Sau need, want, decide, plan dùng to + động từ nguyên mẫu: “I need to check the numbers.” Sau finish, keep, avoid, suggest dùng động từ + -ing: “I haven’t finished checking the table.”",
      explanationKo: "need, want, decide 뒤에는 to부정사, finish, keep, avoid, suggest 뒤에는 동명사를 써요.",
      easierKorean: "need 뒤에는 to + 동사, finish 뒤에는 -ing를 써요.",
    },
  ],
  examples: [
    ["I’ve already finished the first two sections.", "Tôi đã hoàn thành hai phần đầu rồi.", "처음 두 부분은 이미 끝냈어요.", "Linh báo cáo tiến độ ở đầu cuộc họp."],
    ["I’ve just received the sales figures.", "Tôi vừa nhận được số liệu bán hàng.", "매출 숫자를 방금 받았어요.", "Lý do phần số liệu chưa xong."],
    ["I haven’t checked the March data yet.", "Tôi chưa kiểm tra số liệu tháng Ba.", "3월 데이터는 아직 확인하지 못했어요.", "Câu trả lời trung thực về phần còn thiếu."],
    ["Have you sent the update yet?", "Bạn đã gửi bản cập nhật chưa?", "업데이트는 보냈어요?", "Câu hỏi quản lý hỏi trong cuộc họp."],
    ["She has worked on similar tables since January.", "Cô ấy đã làm những bảng tương tự từ tháng Một.", "그녀는 1월부터 비슷한 표를 만들어 왔어요.", "Kinh nghiệm khiến Tom phù hợp để hỗ trợ."],
    ["I’ve been checking the table for two days.", "Tôi đã kiểm tra bảng này hai ngày rồi.", "이틀 동안 표를 확인하고 있어요.", "Phần việc kéo dài hơn kế hoạch."],
    ["The task is taking longer than expected.", "Nhiệm vụ đang lâu hơn dự kiến.", "업무가 예상보다 오래 걸리고 있어요.", "Câu giải thích nguyên nhân chậm tiến độ."],
    ["We’re still on track for Friday.", "Chúng tôi vẫn đúng tiến độ cho thứ Sáu.", "금요일 계획대로 진행되고 있어요.", "Câu trả lời tích cực trong báo cáo."],
    ["There’s a short delay because of the missing data.", "Có chút chậm trễ vì thiếu dữ liệu.", "데이터가 없어서 조금 지연됐어요.", "Cách giải thích vấn đề không đổ lỗi cho ai."],
    ["I need to finish the comparison table today.", "Tôi cần hoàn thành bảng so sánh hôm nay.", "오늘 비교 표를 끝내야 해요.", "Kế hoạch Linh nêu sau khi nhận hỗ trợ."],
    ["Tom has already prepared the March figures.", "Tom đã chuẩn bị số liệu tháng Ba rồi.", "톰이 3월 숫자를 이미 준비했어요.", "Thông tin giúp Linh xử lý nhanh hơn."],
    ["Have you explained the delay to the client?", "Bạn đã giải thích sự chậm trễ với khách chưa?", "고객에게 지연을 설명했어요?", "Câu hỏi quản lý ở cuối cuộc họp."],
    ["Yes, I sent an email this morning.", "Rồi, tôi gửi email sáng nay.", "네, 오늘 아침에 이메일을 보냈어요.", "Câu trả lời ngắn gọn kèm thời điểm."],
    ["I haven’t fixed the last problem yet.", "Tôi chưa sửa vấn đề cuối cùng.", "마지막 문제는 아직 해결하지 못했어요.", "Phần việc còn lại Linh nêu trong báo cáo."],
    ["I’ll catch up on the work tomorrow morning.", "Sáng mai tôi sẽ làm bù phần việc còn lại.", "내일 아침에 밀린 일을 따라잡을게요.", "Cam kết cụ thể về thời gian."],
    ["The report will be ready by ten tomorrow.", "Báo cáo sẽ sẵn sàng trước mười giờ mai.", "보고서는 내일 10시까지 준비될 거예요.", "Câu chốt kế hoạch với quản lý."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-progress-reporting-listen-mc",
      "Nghe câu “I’ve already finished the first two sections.” và chọn tiến độ đúng.",
      ["Hai phần đầu đã xong.", "Hai phần đầu chưa bắt đầu.", "Tất cả các phần đã xong."],
      "Hai phần đầu đã xong.",
      "listening",
      "a2-progress-reporting-comprehension",
      "Chú ý “already finished”.",
    ),
    exercise.dictation(
      "a2-progress-reporting-listen-dictation",
      "Nghe và chép lại câu giải thích vấn đề.",
      "The task is taking longer than expected.",
      "a2-progress-reporting-form",
    ),
  ],
  shadowing: {
    line: "I haven’t finished the last section yet.",
    notesVi: ["Nhấn vào “yet” ở cuối câu.", "Đọc “haven’t finished” nhanh và dính nhẹ vào nhau."],
    notesKo: ["문장 끝 “yet”을 살짝 세게 말해요.", "“haven’t finished”는 빠르게 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-progress-reporting-guided-mc",
      "Chọn câu đúng.",
      ["I haven’t checked the numbers yet.", "I don’t checked the numbers yet.", "I haven’t check the numbers yet."],
      "I haven’t checked the numbers yet.",
      "grammar",
      "a2-progress-reporting-form",
    ),
    exercise.fillBlank(
      "a2-progress-reporting-guided-blank",
      "Điền “for” hoặc “since”: “She has worked on this project ______ January.”",
      "since",
      "grammar",
      "a2-progress-reporting-form",
      "January là mốc thời gian.",
    ),
    exercise.arrange(
      "a2-progress-reporting-guided-arrange",
      "Sắp xếp thành câu báo cáo tiến độ.",
      ["We", "are", "still", "on", "track", "for", "Friday", "."],
      "We are still on track for Friday .",
      "a2-progress-reporting-communicate",
    ),
    exercise.translation(
      "a2-progress-reporting-guided-translate",
      "Dịch sang tiếng Anh: “Tôi đã hoàn thành hai phần đầu rồi.”",
      "I’ve already finished the first two sections.",
      "a2-progress-reporting-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-progress-reporting-production-write",
      "Viết báo cáo tiến độ 6–7 câu cho một dự án học tập hoặc công việc: việc đã xong, việc vừa làm, việc chưa xong, vấn đề, cách giải quyết và kế hoạch tiếp theo.",
      "a2-progress-reporting-communicate",
      "I’ve already finished the first two parts of my project. I’ve just received the data from my partner, but I haven’t checked all the numbers yet. One table is taking longer than expected because one file is missing. Tom has helped with similar work since January, so he can check it today. I need to finish the table tonight, and I’ll send an update tomorrow morning.",
      ["Có việc đã xong, chưa xong và vấn đề", "Dùng already, just, yet hoặc for/since", "Có kế hoạch tiếp theo"],
    ),
    exercise.speaking(
      "a2-progress-reporting-production-speak",
      "Báo cáo tiến độ trong 75 giây trước nhóm: ba mốc tiến độ, một vấn đề, cách xử lý và thời hạn tiếp theo.",
      "a2-progress-reporting-communicate",
      "I’ve already finished the introduction and the first section. I’ve just received the sales figures, but I haven’t checked the March data yet. The comparison table is taking longer than expected. Tom has worked on similar tables since January, so he can help me today. I need to finish it tonight and send an update before four tomorrow.",
      ["Có ba mốc tiến độ và một vấn đề", "Dùng hiện tại hoàn thành chính xác", "Giọng rõ, có số liệu hoặc thời gian cụ thể"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-progress-reporting-mastery-mc",
      "Chọn câu đúng vị trí của “already”.",
      ["I’ve already sent the update.", "I’ve sent already the update.", "Already I’ve sent the update."],
      "I’ve already sent the update.",
      "grammar",
      "a2-progress-reporting-form",
    ),
    exercise.fillBlank(
      "a2-progress-reporting-mastery-blank",
      "Điền “for” hoặc “since”: “I’ve been checking the table ______ two days.”",
      "for",
      "grammar",
      "a2-progress-reporting-form",
    ),
    exercise.dictation(
      "a2-progress-reporting-mastery-dictation",
      "Nghe và chép lại câu về tiến độ đúng kế hoạch.",
      "We’re still on track for Friday.",
      "a2-progress-reporting-comprehension",
    ),
    exercise.translation(
      "a2-progress-reporting-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi chưa kiểm tra số liệu tháng Ba.”",
      "I haven’t checked the March data yet.",
      "a2-progress-reporting-form",
    ),
    exercise.speaking(
      "a2-progress-reporting-mastery-speak",
      "Báo cáo tiến độ 90 giây: việc đã xong, việc đang làm, vấn đề, cách giải quyết và thời hạn mới.",
      "a2-progress-reporting-communicate",
      "I’ve already completed the first two sections of the report. I’ve just received the figures, and I haven’t checked the March data yet. The comparison table is taking longer than expected, so I need to fix it today. I’ll send an update before four, and the full report will be ready tomorrow morning.",
      ["Đủ năm phần của báo cáo", "Dùng already, just, yet", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể báo cáo tiến độ và giải thích vấn đề công việc rõ ràng."],
  spiralReview: ["A2 Unit 6 bài 1: nhiệm vụ và lịch làm việc", "A2 Unit 4: giải thích vấn đề và xác nhận giải pháp"],
  errorCategories: ["verb-tense", "word-order", "grammar-form", "word-choice"],
};

/* ------------------------------------------------------------------ *
 * Bài 5 — Ôn tập Unit 6 và nhiệm vụ thực tế
 * ------------------------------------------------------------------ */
const unitReview: LessonSeed = {
  id: "a2-unit-6-review",
  unitId,
  number: 5,
  prerequisites: ["a2-progress-reporting"],
  titleVi: "Ôn tập Unit 6 và nhiệm vụ thực tế",
  titleKo: "Unit 6 복습과 실전 미션",
  situationVi: "Linh chọn giữa hai phương án công việc: so sánh ưu điểm, xin lời khuyên, thương lượng và báo cáo quyết định cuối cùng.",
  situationKo: "린은 두 가지 일자리 중 하나를 골라요. 장단점을 비교하고 조언을 구하고 협상한 뒤 결정을 보고해요.",
  objectives: [
    { id: "a2-unit-6-review-communicate", en: "Handle a complete work or study task from planning to report.", vi: "Xử lý trọn vẹn một việc công việc hoặc học tập từ lập kế hoạch đến báo cáo.", ko: "계획부터 보고까지 업무나 학습 과제를 처리할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-unit-6-review-form", en: "Compare options and choose with comparatives and superlatives.", vi: "So sánh lựa chọn bằng so sánh hơn và so sánh nhất.", ko: "비교급과 최상급으로 선택지를 비교할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-unit-6-review-comprehension", en: "Understand a work conversation with deadlines and conditions.", vi: "Nghe hiểu một cuộc trao đổi công việc có thời hạn và điều kiện.", ko: "마감과 조건이 있는 업무 대화를 이해할 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["option", "the best option", "phương án tốt nhất", "가장 좋은 선택", "/ˈɒpʃn/", "OPtion", "neutral", ["the best option", "compare the options"]],
    ["advantage", "a big advantage", "lợi thế lớn", "큰 장점", "/ədˈvɑːntɪdʒ/", "adVANtage", "formal", ["a big advantage", "the main advantage"]],
    ["disadvantage", "the main disadvantage", "nhược điểm chính", "주요 단점", "/ˌdɪsədˈvɑːntɪdʒ/", "disadVANtage", "formal", ["the main disadvantage", "one disadvantage"]],
    ["useful", "a useful course", "khóa học hữu ích", "유용한 과정", "/ˈjuːsfl/", "USEful", "neutral", ["a useful skill", "useful experience"]],
    ["convenient", "a convenient schedule", "lịch thuận tiện", "편리한 일정", "/kənˈviːniənt/", "conVEnient", "neutral", ["a convenient time", "convenient for everyone"]],
    ["salary", "a higher salary", "mức lương cao hơn", "더 높은 급여", "/ˈsæləri/", "SALary", "formal", ["a higher salary", "the starting salary"]],
    ["responsibility", "more responsibility", "nhiều trách nhiệm hơn", "더 많은 책임", "/rɪˌspɒnsəˈbɪləti/", "responsiBILity", "formal", ["more responsibility", "a new responsibility"]],
    ["decision", "make a decision", "đưa ra quyết định", "결정을 하다", "/dɪˈsɪʒn/", "deCIsion", "neutral", ["make a decision", "the final decision"]],
  ],
  dialogue: [
    ["Linh", "I have two options: a full-time job or a part-time job with a training course.", "Tôi có hai phương án: một việc toàn thời gian hoặc một việc bán thời gian kèm khóa đào tạo.", "선택지가 두 개 있어요. 정규직 아니면 교육 과정이 있는 아르바이트예요.", "neutral"],
    ["Sora", "Which one is more convenient for your studies?", "Cái nào thuận tiện hơn cho việc học của bạn?", "어느 쪽이 공부에 더 편해요?", "neutral"],
    ["Linh", "The part-time job is easier to manage, but the full-time job pays better.", "Việc bán thời gian dễ sắp xếp hơn, nhưng việc toàn thời gian trả lương tốt hơn.", "아르바이트가 관리하기는 더 쉽지만 정규직이 급여가 더 좋아요.", "neutral"],
    ["Sora", "What’s the biggest advantage of the part-time job?", "Lợi thế lớn nhất của việc bán thời gian là gì?", "아르바이트의 가장 큰 장점은 뭐예요?", "neutral"],
    ["Linh", "I can attend the course on Tuesdays, and the schedule is more flexible.", "Tôi có thể tham dự khóa học vào thứ Ba, và lịch linh hoạt hơn.", "화요일에 교육을 들을 수 있고 일정이 더 유연해요.", "neutral"],
    ["Sora", "And the full-time job?", "Còn việc toàn thời gian?", "정규직은요?", "neutral"],
    ["Linh", "The salary is the best part, but I’d have less free time than now.", "Lương là phần tốt nhất, nhưng tôi sẽ có ít thời gian rảnh hơn hiện tại.", "급여가 가장 좋지만 지금보다 자유 시간이 줄어들 거예요.", "neutral"],
    ["Sora", "You should think about the next two years, not only this month.", "Bạn nên nghĩ đến hai năm tới, không chỉ tháng này.", "이번 달만이 아니라 앞으로 2년을 생각해 보세요.", "neutral"],
    ["Linh", "That’s good advice. Which option would you choose?", "Lời khuyên hay đấy. Bạn sẽ chọn phương án nào?", "좋은 조언이에요. 당신이라면 어느 쪽을 고르겠어요?", "neutral"],
    ["Sora", "I’d choose the part-time job because the course is more useful for your career.", "Tôi sẽ chọn việc bán thời gian vì khóa học hữu ích hơn cho sự nghiệp của bạn.", "저는 아르바이트를 고르겠어요. 그 과정이 커리어에 더 도움이 되니까요.", "neutral"],
    ["Linh", "I agree. I’ll ask for two months to decide and I’ll report back next week.", "Tôi đồng ý. Tôi sẽ xin hai tháng để quyết định và báo lại tuần sau.", "동의해요. 결정할 시간을 두 달 달라고 하고 다음 주에 알려 줄게요.", "neutral"],
    ["Sora", "Good plan. Send me an update when you’ve decided.", "Kế hoạch tốt đấy. Cập nhật cho tôi khi bạn quyết định nhé.", "좋은 계획이에요. 결정하면 알려 주세요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "So sánh hơn và so sánh nhất khi chọn phương án",
      titleKo: "선택지를 비교하는 비교급과 최상급",
      explanationVi: "So sánh hơn dùng -er hoặc more: “The part-time job is easier to manage.” “The full-time job pays better.” So sánh nhất dùng the + -est hoặc the most: “The salary is the best part.” Khi so sánh hai việc, dùng than: “less free time than now”.",
      explanationKo: "두 가지를 비교할 때는 비교급 + than, 여러 가지 중 하나를 고를 때는 최상급을 써요. 짧은 형용사는 -er/-est, 긴 형용사는 more/most를 써요.",
      easierKorean: "두 개를 비교하면 better, 가장 좋으면 the best를 써요.",
    },
    {
      titleVi: "Tổng hợp Unit 6: nhiệm vụ, khả năng, thương lượng và tiến độ",
      titleKo: "Unit 6 종합: 업무, 능력, 협상, 진행",
      explanationVi: "Nhiệm vụ và lịch: hiện tại đơn với have to, need to. Khả năng: can, could, be able to. Xin phép: Could I…? Thương lượng: Could we extend…? Tiến độ: hiện tại hoàn thành với already, yet, just, for, since. Lời khuyên: should.",
      explanationKo: "업무와 일정은 현재형과 have to, need to, 능력은 can, could, be able to, 허락은 Could I…?, 협상은 Could we extend…?, 진행은 현재완료, 조언은 should를 써요.",
      easierKorean: "상황에 맞게 업무, 능력, 허락, 협상, 진행, 조언 표현을 골라 써요.",
    },
  ],
  examples: [
    ["The part-time job is easier to manage than the full-time job.", "Việc bán thời gian dễ sắp xếp hơn việc toàn thời gian.", "아르바이트가 정규직보다 관리하기 쉬워요.", "Câu so sánh Linh dùng khi cân nhắc hai phương án."],
    ["The full-time job pays better, but it’s busier.", "Việc toàn thời gian trả lương tốt hơn nhưng bận hơn.", "정규직이 급여는 더 좋지만 더 바빠요.", "Nhược điểm Linh nhận ra sau khi đọc tin tuyển dụng."],
    ["The schedule is the most flexible option.", "Lịch này là phương án linh hoạt nhất.", "이 일정이 가장 유연한 선택이에요.", "Lý do Linh nghiêng về việc bán thời gian."],
    ["The training course is the most useful part for me.", "Khóa đào tạo là phần hữu ích nhất với tôi.", "교육 과정이 저에게 가장 유용한 부분이에요.", "Điều Linh cân nhắc kỹ nhất khi chọn."],
    ["I have less free time than before.", "Tôi có ít thời gian rảnh hơn trước.", "예전보다 자유 시간이 적어요.", "Thay đổi Linh lo lắng nếu nhận việc toàn thời gian."],
    ["I’m in charge of two projects.", "Tôi phụ trách hai dự án.", "저는 두 개의 프로젝트를 담당해요.", "Thông tin Linh nêu trong buổi phỏng vấn."],
    ["I can start next month, but I need to finish my course first.", "Tôi có thể bắt đầu tháng sau, nhưng cần xong khóa học trước.", "다음 달에 시작할 수 있지만 교육을 먼저 끝내야 해요.", "Điều kiện Linh đưa ra khi thương lượng."],
    ["Could I start part-time and change later?", "Tôi có thể bắt đầu bán thời gian rồi đổi sau không?", "아르바이트로 시작하고 나중에 바꿀 수 있을까요?", "Câu thương lượng Linh chuẩn bị trước."],
    ["Could we agree on a two-month trial period?", "Chúng ta có thể thống nhất thời gian thử việc hai tháng không?", "두 달 수습 기간으로 합의할 수 있을까요?", "Phương án cân bằng giữa hai lựa chọn."],
    ["I’ve already sent my application.", "Tôi đã gửi đơn ứng tuyển rồi.", "지원서는 이미 보냈어요.", "Cập nhật Linh báo cho Sora."],
    ["I haven’t decided yet, but I’ve spoken to both managers.", "Tôi chưa quyết định, nhưng đã nói chuyện với cả hai quản lý.", "아직 결정하지 않았지만 두 관리자와 이야기했어요.", "Tiến độ trước khi Linh chốt phương án."],
    ["I’ve worked in customer service for three years.", "Tôi đã làm dịch vụ khách hàng ba năm.", "고객 서비스에서 3년 동안 일했어요.", "Kinh nghiệm Linh nêu trong đơn ứng tuyển."],
    ["You should ask about the training budget before you decide.", "Bạn nên hỏi về ngân sách đào tạo trước khi quyết định.", "결정하기 전에 교육 예산을 물어보는 게 좋아요.", "Lời khuyên Sora dành cho Linh."],
    ["The second offer has more responsibility.", "Lời đề nghị thứ hai có nhiều trách nhiệm hơn.", "두 번째 제안이 책임이 더 많아요.", "Sora giúp Linh so sánh hai đề nghị."],
    ["In the end, I chose the option with the better schedule.", "Cuối cùng tôi chọn phương án có lịch tốt hơn.", "결국 저는 일정이 더 좋은 쪽을 선택했어요.", "Kết luận sau khi cân nhắc cả hai."],
    ["I’ll report the decision to my manager on Monday.", "Tôi sẽ báo quyết định cho quản lý vào thứ Hai.", "월요일에 관리자에게 결정을 보고할 거예요.", "Bước cuối cùng trong nhiệm vụ thực tế."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-unit-6-review-listen-mc",
      "Nghe câu “The part-time job is easier to manage than the full-time job.” và chọn ý đúng.",
      ["Việc bán thời gian dễ sắp xếp hơn.", "Việc toàn thời gian dễ sắp xếp hơn.", "Hai công việc giống hệt nhau."],
      "Việc bán thời gian dễ sắp xếp hơn.",
      "listening",
      "a2-unit-6-review-comprehension",
      "Chú ý từ so sánh “easier … than”.",
    ),
    exercise.dictation(
      "a2-unit-6-review-listen-dictation",
      "Nghe và chép lại lời khuyên về thời điểm quyết định.",
      "You should ask about the training budget before you decide.",
      "a2-unit-6-review-form",
    ),
  ],
  shadowing: {
    line: "I’d choose the part-time job because the course is more useful for my career.",
    notesVi: ["Nhấn vào “more useful” vì đó là lý do chính.", "Ngắt nhẹ sau “job” trước khi nêu lý do."],
    notesKo: ["“more useful”을 살짝 세게 말하면 이유가 분명해져요.", "“job” 뒤에서 잠깐 쉬고 이유를 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-unit-6-review-guided-mc",
      "Chọn câu so sánh đúng.",
      ["The salary is better than before.", "The salary is more better than before.", "The salary is gooder than before."],
      "The salary is better than before.",
      "grammar",
      "a2-unit-6-review-form",
    ),
    exercise.fillBlank(
      "a2-unit-6-review-guided-blank",
      "Điền dạng so sánh nhất: “The training course is the ______ (useful) part for me.”",
      "most useful",
      "grammar",
      "a2-unit-6-review-form",
    ),
    exercise.arrange(
      "a2-unit-6-review-guided-arrange",
      "Sắp xếp thành câu thương lượng.",
      ["Could", "we", "agree", "on", "a", "two-month", "trial", "period", "?"],
      "Could we agree on a two-month trial period ?",
      "a2-unit-6-review-communicate",
    ),
    exercise.translation(
      "a2-unit-6-review-guided-translate",
      "Dịch sang tiếng Anh: “Tôi đã gửi đơn ứng tuyển rồi.”",
      "I’ve already sent my application.",
      "a2-unit-6-review-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-unit-6-review-production-write",
      "Viết 8 câu so sánh hai lựa chọn học tập hoặc công việc: hai lợi thế, hai nhược điểm, một câu so sánh nhất, một điều kiện và quyết định cuối cùng.",
      "a2-unit-6-review-communicate",
      "I have two options for next year. The full-time job pays better, and it offers more responsibility. The part-time job is easier to manage, and the training course is the most useful part for my career. The main disadvantage of the part-time job is the lower salary. I can start in March if the course finishes in February. In the end, I’ll choose the option with the better schedule.",
      ["Có hai lợi thế và hai nhược điểm", "Có so sánh hơn và so sánh nhất", "Có quyết định cuối cùng"],
    ),
    exercise.speaking(
      "a2-unit-6-review-production-speak",
      "Nhiệm vụ thực tế: nói 90 giây để so sánh hai lựa chọn, xin lời khuyên, thương lượng một điều kiện và báo cáo quyết định.",
      "a2-unit-6-review-communicate",
      "I’m comparing two options. The full-time job pays better, but it’s busier. The part-time job is more flexible, and the training course is the most useful part for me. I can start in March if the course finishes in February. Could we agree on a two-month trial period? I’ve already sent my application, and I’ll report my decision on Monday.",
      ["Đủ bốn bước", "Dùng so sánh hơn, so sánh nhất và một câu điều kiện", "Tự đánh giá và ghi một điểm cần sửa"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-unit-6-review-mastery-mc",
      "Chọn câu đúng nhất.",
      ["This course is the most useful option for me.", "This course is the usefulest option for me.", "This course is more usefulest option for me."],
      "This course is the most useful option for me.",
      "grammar",
      "a2-unit-6-review-form",
    ),
    exercise.fillBlank(
      "a2-unit-6-review-mastery-blank",
      "Điền dạng so sánh hơn: “The part-time job is ______ (easy) to manage than the full-time job.”",
      "easier",
      "grammar",
      "a2-unit-6-review-form",
    ),
    exercise.dictation(
      "a2-unit-6-review-mastery-dictation",
      "Nghe và chép lại câu về thời điểm báo quyết định.",
      "I’ll report the decision to my manager on Monday.",
      "a2-unit-6-review-comprehension",
    ),
    exercise.translation(
      "a2-unit-6-review-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi chưa quyết định, nhưng đã nói chuyện với cả hai quản lý.”",
      "I haven’t decided yet, but I’ve spoken to both managers.",
      "a2-unit-6-review-communicate",
    ),
    exercise.speaking(
      "a2-unit-6-review-mastery-speak",
      "Nói 90 giây: so sánh hai lựa chọn, xin ý kiến, thương lượng thời hạn và báo cáo kết quả cuối cùng.",
      "a2-unit-6-review-communicate",
      "I have two options for next year. The full-time job pays better, but the part-time job is more flexible and the course is the most useful for my career. Could we agree on a two-month trial period? I’ve already sent my application, and I’ll report my decision on Monday.",
      ["Đủ bốn bước", "Dùng ít nhất ba cấu trúc của Unit 6", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể xử lý một việc công việc hoặc học tập từ lập kế hoạch, thương lượng đến báo cáo kết quả."],
  spiralReview: ["A2 Unit 6 bài 1 đến bài 4: nhiệm vụ, kỹ năng, thương lượng và tiến độ", "A2 Unit 1: sắp xếp kế hoạch và xác nhận"],
  errorCategories: ["grammar-form", "word-choice", "word-order", "verb-tense"],
};

export const a2Unit6 = bilingualUnitSchema.parse({
  id: unitId,
  level: "A2",
  titleVi: "Công việc, học tập và trách nhiệm",
  titleKo: "일, 학습, 책임",
  lessons: [jobTasks, skillsAbilities, permissionNegotiation, progressReporting, unitReview].map(buildLesson),
});
