import { bilingualUnitSchema } from "@/lib/curriculum/bilingual-schema";
import { buildLesson, exercise, type LessonSeed } from "./a2-lesson-factory";

/**
 * A2 Unit 3 — Câu chuyện và sự việc trong quá khứ.
 *
 * ID bài, ID mục tiêu, ID từ vựng (thứ tự v1–v8) và ID bài tập được giữ nguyên
 * như bản trước để tiến độ, thẻ FSRS và dữ liệu cũ vẫn liên kết đúng.
 */
const unitId = "a2-3-stories-past-events";

/* ------------------------------------------------------------------ *
 * Bài 1 — Kể một sự việc đã xảy ra
 * ------------------------------------------------------------------ */
const tellingPastEvent: LessonSeed = {
  id: "a2-telling-past-event",
  unitId,
  number: 1,
  prerequisites: ["a2-unit-2-mission"],
  titleVi: "Kể một sự việc đã xảy ra",
  titleKo: "지난 일 이야기하기",
  situationVi: "Linh kể lại buổi sáng cô bị lỡ chuyến xe buýt và phải đi taxi đến văn phòng.",
  situationKo: "린은 아침에 버스를 놓쳐서 택시를 타고 사무실에 간 일을 이야기해요.",
  objectives: [
    { id: "a2-telling-past-event-communication", en: "Tell a short story about something that happened.", vi: "Kể một câu chuyện ngắn về việc đã xảy ra.", ko: "일어난 일을 짧게 이야기할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-telling-past-event-form", en: "Use the past simple with sequence words.", vi: "Dùng quá khứ đơn kèm từ nối trình tự.", ko: "과거형과 순서 표현을 함께 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-telling-past-event-comprehension", en: "Follow the order of events in someone’s story.", vi: "Nghe theo dõi trình tự sự việc trong câu chuyện.", ko: "이야기에서 사건 순서를 따라갈 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "miss the bus", "lỡ xe buýt", "버스를 놓치다", "/mɪs ðə bʌs/", "miss the BUS", "neutral", ["miss the bus", "miss the last train"]],
    ["v2", "happen", "xảy ra", "일어나다", "/ˈhæpən/", "HAPpen", "neutral", ["what happened", "it happened on Monday"]],
    ["v3", "first", "đầu tiên", "먼저", "/fɜːst/", "FIRST", "neutral", ["first, I left home", "first we waited"]],
    ["v4", "then", "sau đó", "그다음", "/ðen/", "THEN", "neutral", ["then I called", "then we left"]],
    ["v5", "after that", "sau đó", "그 후에", "/ˈɑːftə ðæt/", "AFter that", "neutral", ["after that, I took a taxi", "after that we walked"]],
    ["v6", "finally", "cuối cùng", "마침내", "/ˈfaɪnəli/", "FI-nally", "neutral", ["finally, I arrived", "finally it worked"]],
    ["v7", "arrive", "đến nơi", "도착하다", "/əˈraɪv/", "arRIVE", "neutral", ["arrive at the office", "arrive twenty minutes late"]],
    ["v8", "on time", "đúng giờ", "제시간에", "/ɒn taɪm/", "on TIME", "neutral", ["arrive on time", "not on time"]],
  ],
  dialogue: [
    ["Joon", "You look tired. What happened this morning?", "Trông bạn mệt. Sáng nay có chuyện gì vậy?", "피곤해 보여요. 오늘 아침에 무슨 일이 있었어요?", "casual"],
    ["Linh", "I missed the bus and I had to take a taxi.", "Tôi lỡ xe buýt và phải đi taxi.", "버스를 놓쳐서 택시를 탔어요.", "neutral"],
    ["Joon", "How did that happen?", "Sao lại như vậy?", "어떻게 그렇게 됐어요?", "casual"],
    ["Linh", "First, I left home later than usual.", "Đầu tiên, tôi rời nhà muộn hơn thường lệ.", "먼저 평소보다 늦게 집을 나섰어요.", "neutral"],
    ["Joon", "What did you do then?", "Sau đó bạn làm gì?", "그다음에는 어떻게 했어요?", "casual"],
    ["Linh", "Then I ran to the bus stop, but the bus left just before I arrived.", "Sau đó tôi chạy ra trạm xe buýt, nhưng xe vừa đi trước khi tôi đến.", "그다음 정류장으로 뛰었는데, 제가 도착하기 직전에 버스가 떠났어요.", "neutral"],
    ["Joon", "And after that?", "Rồi sau đó?", "그 후에는요?", "casual"],
    ["Linh", "After that, I called my manager and ordered a taxi.", "Sau đó, tôi gọi cho quản lý và đặt taxi.", "그 후에 관리자에게 전화하고 택시를 불렀어요.", "neutral"],
    ["Joon", "Was the traffic bad?", "Đường có đông không?", "차가 많이 막혔어요?", "casual"],
    ["Linh", "Very bad. Finally, I arrived twenty minutes late.", "Rất đông. Cuối cùng tôi đến muộn hai mươi phút.", "아주 막혔어요. 결국 20분 늦게 도착했어요.", "neutral"],
    ["Joon", "Did your manager mind?", "Quản lý có khó chịu không?", "관리자가 불편해했어요?", "casual"],
    ["Linh", "No, she understood the problem. Luckily, the meeting started late too.", "Không, cô ấy hiểu vấn đề. May là cuộc họp cũng bắt đầu muộn.", "아니요, 상황을 이해해 줬어요. 다행히 회의도 늦게 시작했어요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "Quá khứ đơn cho sự việc đã xảy ra",
      titleKo: "일어난 일의 과거형",
      explanationVi: "Dùng quá khứ đơn cho những việc xảy ra và đã kết thúc: “I missed the bus.” “I called my manager.” Động từ bất quy tắc cần học dạng riêng: left, ran, took, understood.",
      explanationKo: "끝난 일은 과거형으로 말해요. left, ran, took, understood처럼 불규칙 동사는 형태를 따로 외워야 해요.",
      easierKorean: "지난 일은 동사의 과거형으로 말해요.",
    },
    {
      titleVi: "Từ nối trình tự trong câu chuyện",
      titleKo: "이야기 순서 연결어",
      explanationVi: "first, then, after that, finally giúp người nghe theo dõi thứ tự: “First, I left home late. Then I ran to the bus stop. After that, I ordered a taxi. Finally, I arrived late.”",
      explanationKo: "first, then, after that, finally를 쓰면 사건 순서가 분명해져요.",
      easierKorean: "먼저 First, 그다음 Then, 그 후 After that, 마지막 Finally를 써요.",
    },
  ],
  examples: [
    ["I missed the bus yesterday morning.", "Sáng qua tôi lỡ xe buýt.", "어제 아침에 버스를 놓쳤어요.", "Câu mở đầu Linh kể với Joon."],
    ["First, I left home later than usual.", "Đầu tiên, tôi rời nhà muộn hơn thường lệ.", "먼저 평소보다 늦게 집을 나섰어요.", "Nguyên nhân đầu tiên của sự việc."],
    ["Then I ran to the bus stop.", "Sau đó tôi chạy ra trạm xe buýt.", "그다음 정류장으로 뛰었어요.", "Bước tiếp theo Linh cố xử lý."],
    ["The bus left just before I arrived.", "Xe buýt vừa đi trước khi tôi đến.", "제가 도착하기 직전에 버스가 떠났어요.", "Chi tiết quyết định khiến Linh trễ."],
    ["After that, I called my manager.", "Sau đó, tôi gọi cho quản lý.", "그 후에 관리자에게 전화했어요.", "Cách Linh báo tình hình."],
    ["I took a taxi to the office.", "Tôi đi taxi đến văn phòng.", "사무실까지 택시를 탔어요.", "Phương án Linh chọn thay xe buýt."],
    ["The traffic was very heavy.", "Đường rất đông.", "차가 아주 막혔어요.", "Lý do Linh vẫn đến muộn."],
    ["I arrived twenty minutes late.", "Tôi đến muộn hai mươi phút.", "20분 늦게 도착했어요.", "Kết quả cuối cùng của buổi sáng."],
    ["My manager understood the problem.", "Quản lý của tôi hiểu vấn đề.", "관리자가 상황을 이해했어요.", "Phản ứng tích cực của quản lý."],
    ["What happened after you missed the bus?", "Chuyện gì xảy ra sau khi bạn lỡ xe buýt?", "버스를 놓친 뒤에 무슨 일이 있었어요?", "Câu hỏi nối tiếp của Joon."],
    ["Did you get to work on time?", "Bạn đến chỗ làm đúng giờ không?", "제시간에 출근했어요?", "Câu hỏi kiểm tra kết quả."],
    ["I forgot to set my alarm.", "Tôi quên đặt báo thức.", "알람을 맞추는 걸 잊었어요.", "Chi tiết Linh kể thêm ở cuối."],
    ["Luckily, the meeting started late too.", "May là cuộc họp cũng bắt đầu muộn.", "다행히 회의도 늦게 시작했어요.", "Chi tiết khiến câu chuyện nhẹ nhõm hơn."],
    ["Finally, everything worked out.", "Cuối cùng, mọi việc đều ổn.", "결국 모든 게 잘 풀렸어요.", "Câu kết của câu chuyện."],
    ["It was a stressful start to the day.", "Đó là một khởi đầu ngày căng thẳng.", "스트레스가 많은 하루의 시작이었어요.", "Cảm nhận Linh nói khi kết thúc."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-telling-past-event-listen",
      "Nghe câu “The bus left just before I arrived.” và chọn thông tin đúng.",
      ["Xe buýt đi trước khi Linh đến.", "Xe buýt đến sau khi Linh đợi.", "Xe buýt không chạy hôm đó."],
      "Xe buýt đi trước khi Linh đến.",
      "listening",
      "a2-telling-past-event-comprehension",
      "Chú ý “just before”.",
    ),
    exercise.dictation(
      "a2-telling-past-event-dictation",
      "Nghe và chép lại câu kết của câu chuyện.",
      "Finally, I arrived twenty minutes late.",
      "a2-telling-past-event-form",
    ),
  ],
  shadowing: {
    line: "First, I left home later than usual, so I missed the bus.",
    notesVi: ["Ngắt nhẹ sau “usual” để tách nguyên nhân và kết quả.", "Nhấn vào “missed” ở cuối câu."],
    notesKo: ["“usual” 뒤에서 잠깐 쉬면 원인과 결과가 구분돼요.", "문장 끝 “missed”를 살짝 세게 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-telling-past-event-g1",
      "Chọn câu đúng.",
      ["I forgot to set my alarm yesterday.", "I forget to set my alarm yesterday.", "I forgotten to set my alarm yesterday."],
      "I forgot to set my alarm yesterday.",
      "grammar",
      "a2-telling-past-event-form",
    ),
    exercise.translation(
      "a2-telling-past-event-g2",
      "Dịch sang tiếng Anh: “Sau đó, tôi gọi cho quản lý.”",
      "After that, I called my manager.",
      "a2-telling-past-event-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-telling-past-event-write",
      "Viết 5–6 câu kể một việc đã xảy ra với bạn: mở đầu, hai bước xử lý, kết quả và một cảm nhận.",
      "a2-telling-past-event-communication",
      "Last Friday I missed my train to work. First, I left home late because my alarm didn’t ring. Then I ran to the station, but the train left just before I arrived. After that, I called my manager and took a bus. Finally, I arrived thirty minutes late, but my manager understood.",
      ["Có trình tự với first, then, after that, finally", "Dùng quá khứ đơn chính xác", "Có câu kết"],
    ),
    exercise.speaking(
      "a2-telling-past-event-speak",
      "Kể một việc đã xảy ra trong 60 giây với bốn bước trình tự và kết quả cuối cùng.",
      "a2-telling-past-event-communication",
      "Last week I missed my bus home. First, I stayed at work later than usual. Then I walked to the bus stop, but the last bus left before I arrived. After that, I called a friend. Finally, she picked me up and I got home at ten.",
      ["Có bốn bước trình tự", "Có kết quả rõ ràng", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-telling-past-event-m1",
      "Chọn câu đúng.",
      ["I took a taxi after I missed the bus.", "I take a taxi after I missed the bus.", "I taken a taxi after I miss the bus."],
      "I took a taxi after I missed the bus.",
      "grammar",
      "a2-telling-past-event-form",
    ),
    exercise.dictation(
      "a2-telling-past-event-m2",
      "Nghe và chép lại câu về việc quên báo thức.",
      "I forgot to set my alarm last night.",
      "a2-telling-past-event-comprehension",
    ),
    exercise.translation(
      "a2-telling-past-event-m3",
      "Dịch sang tiếng Anh: “Cuối cùng, mọi việc đều ổn.”",
      "Finally, everything worked out.",
      "a2-telling-past-event-form",
    ),
    exercise.speaking(
      "a2-telling-past-event-m4",
      "Kể một việc đã xảy ra trong 45 giây với ba bước.",
      "a2-telling-past-event-communication",
      "Yesterday I missed my appointment. First, I left the office late. Then I got on the wrong bus. After that, I called the clinic and they gave me a new time.",
      ["Có ba bước và kết quả", "Dùng quá khứ đơn", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-telling-past-event-m5",
      "Điền dạng quá khứ: “The bus ______ (leave) before I arrived.”",
      "left",
      "grammar",
      "a2-telling-past-event-comprehension",
    ),
  ],
  canDo: ["Có thể kể một sự việc đã xảy ra theo đúng thứ tự."],
  spiralReview: ["A1: quá khứ đơn của động từ thông dụng", "A2 Unit 1 bài 1: phân biệt quá khứ đơn và hiện tại hoàn thành"],
  errorCategories: ["verb-tense", "word-order", "missing-word", "word-choice"],
};

/* ------------------------------------------------------------------ *
 * Bài 2 — Mô tả bối cảnh và hành động đang diễn ra
 * ------------------------------------------------------------------ */
const backgroundActions: LessonSeed = {
  id: "a2-background-actions",
  unitId,
  number: 2,
  prerequisites: ["a2-telling-past-event"],
  titleVi: "Mô tả bối cảnh và hành động đang diễn ra",
  titleKo: "배경과 진행 중인 행동 묘사하기",
  situationVi: "Buổi chiều ở văn phòng mất điện; Linh kể lại mọi người đang làm gì khi đèn tắt.",
  situationKo: "사무실 오후에 정전이 일어났어요. 린은 불이 꺼질 때 사람들이 무엇을 하고 있었는지 이야기해요.",
  objectives: [
    { id: "a2-background-actions-communication", en: "Describe what was happening at a moment in the past.", vi: "Mô tả điều đang diễn ra tại một thời điểm trong quá khứ.", ko: "과거의 한 시점에 하고 있던 일을 설명할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-background-actions-form", en: "Use the past continuous with while and when.", vi: "Dùng quá khứ tiếp diễn với while và when.", ko: "while과 when으로 과거진행형을 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-background-actions-comprehension", en: "Identify which action was in progress.", vi: "Nhận ra hành động nào đang diễn ra.", ko: "어떤 행동이 진행 중이었는지 찾아낼 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "while", "trong khi", "…하는 동안", "/waɪl/", "WHILE", "neutral", ["while I was working", "while we were waiting"]],
    ["v2", "when", "khi", "…했을 때", "/wen/", "WHEN", "neutral", ["when the lights went out", "when my phone rang"]],
    ["v3", "was working", "đang làm việc", "일하고 있었다", "/wəz ˈwɜːkɪŋ/", "was WORKing", "neutral", ["I was working on the report", "she was working late"]],
    ["v4", "suddenly", "đột nhiên", "갑자기", "/ˈsʌdənli/", "SUD-denly", "neutral", ["suddenly the lights went out", "suddenly it started raining"]],
    ["v5", "at that moment", "lúc đó", "그 순간", "/ət ðæt ˈməʊmənt/", "at that MOment", "neutral", ["at that moment, nobody moved", "at that moment the phone rang"]],
    ["v6", "ring", "reo", "울리다", "/rɪŋ/", "RING", "neutral", ["the phone rang", "my alarm rang at six"]],
    ["v7", "carry", "mang", "나르다", "/ˈkæri/", "CARry", "neutral", ["carry some boxes", "carry a laptop bag"]],
    ["v8", "notice", "nhận thấy", "알아차리다", "/ˈnəʊtɪs/", "NOtice", "neutral", ["notice the problem", "didn’t notice the sign"]],
  ],
  dialogue: [
    ["Joon", "I heard the power went out at your office.", "Tôi nghe nói văn phòng bạn mất điện.", "사무실에 정전이 있었다고 들었어요.", "casual"],
    ["Linh", "Yes, it happened yesterday afternoon.", "Vâng, chuyện xảy ra chiều qua.", "네, 어제 오후에 있었어요.", "neutral"],
    ["Joon", "What were you doing when it happened?", "Bạn đang làm gì khi đó?", "그때 뭐 하고 있었어요?", "casual"],
    ["Linh", "I was working on a report when the lights went out.", "Tôi đang làm báo cáo thì đèn tắt.", "보고서를 쓰고 있는데 불이 꺼졌어요.", "neutral"],
    ["Joon", "Was anyone else in the office?", "Còn ai khác ở văn phòng không?", "다른 사람도 사무실에 있었어요?", "casual"],
    ["Linh", "Yes. Tom was carrying some boxes, and two colleagues were talking to a client.", "Có. Tom đang mang mấy cái hộp, và hai đồng nghiệp đang nói chuyện với khách.", "네. 톰은 상자를 옮기고 있었고, 두 동료는 고객과 이야기하고 있었어요.", "neutral"],
    ["Joon", "Did anyone notice the problem first?", "Có ai phát hiện vấn đề trước không?", "누가 먼저 문제를 알아차렸어요?", "neutral"],
    ["Linh", "Tom noticed it. He was standing near the fuse box at that moment.", "Tom phát hiện. Lúc đó anh ấy đang đứng gần hộp cầu dao.", "톰이 알아차렸어요. 그 순간 그는 두꺼비집 근처에 서 있었어요.", "neutral"],
    ["Joon", "And what happened next?", "Rồi sau đó thế nào?", "그다음엔 어떻게 됐어요?", "casual"],
    ["Linh", "While we were looking for a flashlight, my phone rang — it was the building manager.", "Trong khi chúng tôi đang tìm đèn pin thì điện thoại tôi reo — đó là quản lý tòa nhà.", "손전등을 찾고 있는데 제 전화가 울렸어요. 건물 관리인이었어요.", "neutral"],
    ["Joon", "So you solved it quickly.", "Vậy là bạn xử lý nhanh.", "그럼 빨리 해결했네요.", "casual"],
    ["Linh", "Yes. The lights came back after ten minutes, and nobody was hurt.", "Vâng. Đèn trở lại sau mười phút, và không ai bị thương.", "네. 10분 뒤에 불이 들어왔고 아무도 다치지 않았어요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "Quá khứ tiếp diễn cho hành động đang diễn ra",
      titleKo: "진행 중이던 행동의 과거진행형",
      explanationVi: "Dùng was/were + -ing để mô tả việc đang diễn ra tại một thời điểm trong quá khứ: “I was working on a report.” “Two colleagues were talking to a client.”",
      explanationKo: "과거의 한 시점에 하고 있던 일은 was/were + -ing로 말해요.",
      easierKorean: "그때 하고 있던 일은 was/were + -ing로 말해요.",
    },
    {
      titleVi: "while và when",
      titleKo: "while과 when",
      explanationVi: "while đứng trước hành động kéo dài: “While we were looking for a flashlight, my phone rang.” when thường đứng trước hành động ngắn cắt ngang: “I was working when the lights went out.”",
      explanationKo: "while 뒤에는 계속되던 행동, when 뒤에는 갑자기 일어난 행동을 써요.",
      easierKorean: "길게 이어진 일은 while, 갑자기 생긴 일은 when으로 이어요.",
    },
  ],
  examples: [
    ["I was working when the lights went out.", "Tôi đang làm việc thì đèn tắt.", "일하고 있는데 불이 꺼졌어요.", "Câu chính Linh kể về sự việc hôm qua."],
    ["Everyone was talking at that moment.", "Lúc đó mọi người đang nói chuyện.", "그 순간 모두가 이야기하고 있었어요.", "Bối cảnh trong văn phòng khi mất điện."],
    ["While I was carrying some boxes, my phone rang.", "Trong khi tôi đang mang mấy cái hộp thì điện thoại reo.", "상자를 옮기고 있는데 전화가 울렸어요.", "Sự việc xảy ra với Tom cùng lúc."],
    ["It was raining outside.", "Bên ngoài trời đang mưa.", "밖에 비가 오고 있었어요.", "Chi tiết thời tiết Linh thêm vào câu chuyện."],
    ["My colleague was speaking to a customer.", "Đồng nghiệp của tôi đang nói chuyện với khách hàng.", "동료는 고객과 이야기하고 있었어요.", "Mô tả một người khác trong văn phòng."],
    ["Suddenly, the computer turned off.", "Đột nhiên, máy tính tắt.", "갑자기 컴퓨터가 꺼졌어요.", "Diễn biến ngay khi mất điện."],
    ["We were preparing a presentation.", "Chúng tôi đang chuẩn bị một bài trình bày.", "우리는 발표를 준비하고 있었어요.", "Công việc bị gián đoạn giữa chừng."],
    ["What were you doing when it happened?", "Bạn đang làm gì khi việc đó xảy ra?", "그 일이 일어났을 때 뭐 하고 있었어요?", "Câu hỏi thường gặp khi nghe kể chuyện."],
    ["I was waiting for the file to download.", "Tôi đang chờ tệp tải xuống.", "파일이 다운로드되기를 기다리고 있었어요.", "Chi tiết Linh nhớ lại trong cuộc trò chuyện."],
    ["While we were looking for a flashlight, the lights came back.", "Trong khi chúng tôi đang tìm đèn pin thì đèn trở lại.", "손전등을 찾고 있는데 불이 들어왔어요.", "Cách sự việc kết thúc nhanh chóng."],
    ["The manager was checking the fuse box.", "Quản lý đang kiểm tra hộp cầu dao.", "관리자는 두꺼비집을 확인하고 있었어요.", "Hành động đang diễn ra của một người khác."],
    ["Some people were using their phone lights.", "Một số người đang dùng đèn điện thoại.", "몇 사람은 휴대폰 손전등을 쓰고 있었어요.", "Cách mọi người xử lý trong bóng tối."],
    ["Nobody was hurt.", "Không ai bị thương.", "아무도 다치지 않았어요.", "Thông tin quan trọng sau sự việc."],
    ["We laughed after the surprise.", "Chúng tôi bật cười sau cú bất ngờ.", "놀란 뒤에 다들 웃었어요.", "Phản ứng của nhóm sau khi có điện lại."],
    ["The office returned to normal a few minutes later.", "Văn phòng trở lại bình thường vài phút sau đó.", "몇 분 뒤 사무실은 평소로 돌아왔어요.", "Câu kết của câu chuyện mất điện."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-background-actions-listen",
      "Nghe câu “I was working on a report when the lights went out.” và chọn hành động đang diễn ra.",
      ["Linh đang làm báo cáo.", "Linh đang nói chuyện với khách.", "Linh đang sửa hộp cầu dao."],
      "Linh đang làm báo cáo.",
      "listening",
      "a2-background-actions-communication",
      "Hành động đang diễn ra đứng sau “was”.",
    ),
    exercise.dictation(
      "a2-background-actions-dictation",
      "Nghe và chép lại câu về hành động của Tom.",
      "While I was carrying some boxes, my phone rang.",
      "a2-background-actions-form",
    ),
  ],
  shadowing: {
    line: "I was working on a report when the lights went out.",
    notesVi: ["Ngắt nhẹ sau “report” để tách hai hành động.", "Nhấn vào “out” ở cuối câu."],
    notesKo: ["“report” 뒤에서 잠깐 쉬면 두 행동이 구분돼요.", "문장 끝 “out”을 살짝 세게 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-background-actions-g1",
      "Chọn câu đúng.",
      ["I was waiting when the phone rang.", "I waited when the phone was ringing.", "I was wait when the phone rang."],
      "I was waiting when the phone rang.",
      "grammar",
      "a2-background-actions-form",
    ),
    exercise.translation(
      "a2-background-actions-g2",
      "Dịch sang tiếng Anh: “Chúng tôi đang chuẩn bị một bài trình bày.”",
      "We were preparing a presentation.",
      "a2-background-actions-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-background-actions-write",
      "Viết 5–6 câu mô tả một lúc có sự việc bất ngờ: hai hành động đang diễn ra, một hành động cắt ngang, phản ứng và kết quả.",
      "a2-background-actions-communication",
      "Yesterday it was raining and I was waiting for the bus. Two people were talking next to me, and a student was reading. Suddenly, a car stopped in front of the stop. While everyone was looking at the car, the driver asked for directions. In the end, the bus arrived and we all got on.",
      ["Có hai hành động đang diễn ra", "Có một hành động cắt ngang với when hoặc suddenly", "Có kết quả"],
    ),
    exercise.speaking(
      "a2-background-actions-speak",
      "Nói 60–75 giây mô tả một lúc bất ngờ bạn từng trải qua, dùng while và when.",
      "a2-background-actions-communication",
      "Last month I was cooking when the power went out. While I was looking for a candle, my phone rang. My sister was waiting for me at the station, so I told her about the power cut. Everything was fine after fifteen minutes.",
      ["Có while và when", "Có phản ứng và kết quả", "Tự nghe lại và nhận xét"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-background-actions-m1",
      "Chọn câu đúng.",
      ["While we were waiting, the gate changed.", "While we waited, the gate was changing.", "While we was waiting, the gate changed."],
      "While we were waiting, the gate changed.",
      "grammar",
      "a2-background-actions-form",
    ),
    exercise.dictation(
      "a2-background-actions-m2",
      "Nghe và chép lại câu về sự việc xảy ra đột ngột.",
      "Suddenly, the computer turned off.",
      "a2-background-actions-comprehension",
    ),
    exercise.translation(
      "a2-background-actions-m3",
      "Dịch sang tiếng Anh: “Không ai bị thương.”",
      "Nobody was hurt.",
      "a2-background-actions-form",
    ),
    exercise.speaking(
      "a2-background-actions-m4",
      "Mô tả một lúc bất ngờ trong 45 giây.",
      "a2-background-actions-communication",
      "I was walking home when it started to rain. While I was looking for my umbrella, a friend called me. She was driving nearby, so she gave me a lift.",
      ["Có hai hành động đang diễn ra", "Có when hoặc while", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-background-actions-m5",
      "Điền dạng đúng: “They ______ (talk) when the lights went out.”",
      "were talking",
      "grammar",
      "a2-background-actions-comprehension",
    ),
  ],
  canDo: ["Có thể mô tả bối cảnh và việc đang diễn ra khi một sự việc xảy ra."],
  spiralReview: ["A1: thời tiết và hoạt động hằng ngày", "A2 Unit 3 bài 1: quá khứ đơn và trình tự sự việc"],
  errorCategories: ["verb-tense", "word-order", "grammar-form", "missing-word"],
};

/* ------------------------------------------------------------------ *
 * Bài 3 — Kể vấn đề bất ngờ và cách giải quyết
 * ------------------------------------------------------------------ */
const problemResolution: LessonSeed = {
  id: "a2-problem-resolution",
  unitId,
  number: 3,
  prerequisites: ["a2-background-actions"],
  titleVi: "Kể vấn đề bất ngờ và cách giải quyết",
  titleKo: "뜻밖의 문제와 해결 이야기하기",
  situationVi: "Linh làm mất ví trên tàu, báo cho nhân viên nhà ga và may mắn tìm lại được.",
  situationKo: "린은 기차에서 지갑을 잃어버려서 역 직원에게 신고하고, 다행히 다시 찾아요.",
  objectives: [
    { id: "a2-problem-resolution-communication", en: "Explain a problem and how it was solved.", vi: "Trình bày một vấn đề và cách giải quyết.", ko: "문제와 해결 방법을 설명할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-problem-resolution-form", en: "Combine the past simple and the past continuous.", vi: "Kết hợp quá khứ đơn và quá khứ tiếp diễn.", ko: "과거형과 과거진행형을 함께 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-problem-resolution-comprehension", en: "Understand a problem story and its outcome.", vi: "Nghe hiểu câu chuyện về vấn đề và kết quả.", ko: "문제 이야기와 결과를 이해할 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "lose", "làm mất", "잃어버리다", "/luːz/", "LOSE", "neutral", ["lose my wallet", "lost on the train"]],
    ["v2", "realize", "nhận ra", "깨닫다", "/ˈriːəlaɪz/", "REalize", "neutral", ["realize the problem", "I realized it was missing"]],
    ["v3", "look for", "tìm kiếm", "찾다", "/lʊk fɔː/", "LOOK for", "neutral", ["look for my bag", "look for help"]],
    ["v4", "report", "báo lại", "신고하다", "/rɪˈpɔːt/", "rePORT", "formal", ["report the loss", "report it at the station"]],
    ["v5", "lost and found", "quầy đồ thất lạc", "분실물 센터", "/lɒst ənd faʊnd/", "LOST and FOUND", "neutral", ["go to lost and found", "the lost and found office"]],
    ["v6", "fortunately", "may mắn là", "다행히", "/ˈfɔːtʃənətli/", "FORtunately", "neutral", ["fortunately, they found it", "fortunately, nobody minded"]],
    ["v7", "solve", "giải quyết", "해결하다", "/sɒlv/", "SOLVE", "neutral", ["solve the problem", "solve it quickly"]],
    ["v8", "in the end", "cuối cùng", "결국", "/ɪn ði end/", "in the END", "neutral", ["in the end, everything was fine", "in the end I found it"]],
  ],
  dialogue: [
    ["Joon", "You look relieved. What happened?", "Trông bạn nhẹ nhõm. Có chuyện gì vậy?", "안심한 표정이네요. 무슨 일이 있었어요?", "casual"],
    ["Linh", "I realized my wallet was missing when I got off the train.", "Tôi nhận ra ví mất khi xuống tàu.", "기차에서 내렸을 때 지갑이 없는 걸 알았어요.", "neutral"],
    ["Joon", "Oh no. What did you do?", "Trời ơi. Bạn đã làm gì?", "이런. 어떻게 했어요?", "casual"],
    ["Linh", "First, I checked all my pockets on the platform.", "Đầu tiên, tôi kiểm tra hết túi khi đang ở sân ga.", "먼저 승강장에서 주머니를 다 확인했어요.", "neutral"],
    ["Joon", "And then?", "Rồi sau đó?", "그다음엔요?", "casual"],
    ["Linh", "Then I went to the lost and found office and reported it.", "Sau đó tôi đến quầy đồ thất lạc và báo lại.", "그다음 분실물 센터에 가서 신고했어요.", "neutral"],
    ["Joon", "Did they need any information?", "Họ có cần thông tin gì không?", "정보가 필요했어요?", "casual"],
    ["Linh", "A station worker asked me to describe it, and I told her it was small and brown.", "Một nhân viên nhà ga yêu cầu tôi mô tả, và tôi nói nó nhỏ và màu nâu.", "역 직원이 설명을 요청해서 작은 갈색 지갑이라고 말했어요.", "neutral"],
    ["Joon", "Were you waiting long?", "Bạn có chờ lâu không?", "오래 기다렸어요?", "casual"],
    ["Linh", "While she was checking the system, another passenger called the station.", "Trong khi cô ấy đang kiểm tra hệ thống thì một hành khách khác gọi đến nhà ga.", "직원이 시스템을 확인하는 동안 다른 승객이 역에 전화했어요.", "neutral"],
    ["Joon", "So someone found it.", "Vậy là có người tìm thấy.", "누가 찾았네요.", "casual"],
    ["Linh", "Fortunately, yes. He had left it at the next station, and I took the next train to collect it.", "May mắn là vậy. Anh ấy để nó ở ga tiếp theo, và tôi đi chuyến tàu sau để lấy.", "다행히요. 그 사람이 다음 역에 맡겼고, 저는 다음 기차를 타고 찾으러 갔어요.", "neutral"],
    ["Joon", "That’s a relief.", "Thật nhẹ nhõm.", "정말 다행이에요.", "casual"],
    ["Linh", "It was. In the end, I was only thirty minutes late.", "Đúng vậy. Cuối cùng tôi chỉ muộn ba mươi phút.", "그랬어요. 결국 30분만 늦었어요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "Kết hợp quá khứ đơn và quá khứ tiếp diễn",
      titleKo: "과거형과 과거진행형 함께 쓰기",
      explanationVi: "Câu chuyện tự nhiên thường có cả hai thì: hành động đang diễn ra ở quá khứ tiếp diễn, hành động cắt ngang ở quá khứ đơn. “I realized my wallet was missing when I got off the train.” “While she was checking the system, a passenger called.”",
      explanationKo: "이야기에서는 두 시제를 함께 써요. 하고 있던 일은 과거진행형, 갑자기 일어난 일은 과거형으로 말해요.",
      easierKorean: "하고 있던 일은 was/were -ing, 갑자기 생긴 일은 과거형으로 말해요.",
    },
    {
      titleVi: "Giải quyết vấn đề với fortunately và in the end",
      titleKo: "fortunately, in the end로 해결 말하기",
      explanationVi: "fortunately mở đầu kết quả tốt: “Fortunately, another passenger found it.” in the end tóm tắt kết quả cuối: “In the end, I was only thirty minutes late.” Cấu trúc ask someone to + động từ nguyên mẫu dùng khi mô tả yêu cầu.",
      explanationKo: "fortunately는 좋은 결과를 소개할 때, in the end는 최종 결과를 정리할 때 써요. ask someone to + 동사원형은 요청을 설명할 때 써요.",
      easierKorean: "좋은 결과는 fortunately, 마지막 결과는 in the end로 말해요.",
    },
  ],
  examples: [
    ["I realized my wallet was missing.", "Tôi nhận ra ví của mình đã mất.", "지갑이 없는 걸 알아차렸어요.", "Câu mở đầu câu chuyện Linh kể."],
    ["I was getting off the train when I dropped it.", "Tôi đang xuống tàu thì đánh rơi nó.", "기차에서 내리다가 떨어뜨렸어요.", "Thời điểm Linh phỏng đoán ví bị rơi."],
    ["First, I checked all my pockets.", "Đầu tiên, tôi kiểm tra tất cả túi.", "먼저 주머니를 모두 확인했어요.", "Bước đầu tiên Linh tự xử lý."],
    ["Then I went to the lost and found office.", "Sau đó tôi đến quầy đồ thất lạc.", "그다음 분실물 센터에 갔어요.", "Bước thứ hai khi không tìm thấy."],
    ["A station worker asked for a description.", "Một nhân viên nhà ga yêu cầu mô tả.", "역 직원이 설명을 요청했어요.", "Quy trình khi báo mất đồ."],
    ["I told her it was small and brown.", "Tôi nói với cô ấy nó nhỏ và màu nâu.", "작고 갈색이라고 말했어요.", "Chi tiết giúp nhân viên tìm đúng đồ."],
    ["While she was checking the system, someone called.", "Trong khi cô ấy đang kiểm tra hệ thống thì có người gọi đến.", "직원이 시스템을 확인하는 동안 누군가 전화했어요.", "Diễn biến quan trọng của câu chuyện."],
    ["Fortunately, another passenger had found it.", "May mắn là một hành khách khác đã tìm thấy.", "다행히 다른 승객이 찾았어요.", "Bước ngoặt của câu chuyện."],
    ["They left it at the next station.", "Họ để nó ở ga tiếp theo.", "다음 역에 맡겼어요.", "Thông tin Linh nhận được từ nhân viên."],
    ["I took the next train to collect it.", "Tôi đi chuyến tàu tiếp theo để lấy lại.", "다음 기차를 타고 찾으러 갔어요.", "Hành động cuối để lấy lại ví."],
    ["Everything was still inside.", "Mọi thứ vẫn còn nguyên trong đó.", "안에 있는 것은 다 그대로였어요.", "Chi tiết Linh kiểm tra sau khi nhận lại."],
    ["I thanked the passenger by phone.", "Tôi cảm ơn hành khách đó qua điện thoại.", "전화로 그 승객에게 감사했어요.", "Cách Linh kết thúc câu chuyện tử tế."],
    ["The staff solved the problem quickly.", "Nhân viên giải quyết vấn đề nhanh chóng.", "직원들이 문제를 빠르게 해결했어요.", "Nhận xét Linh dành cho nhà ga."],
    ["In the end, I was only thirty minutes late.", "Cuối cùng tôi chỉ muộn ba mươi phút.", "결국 30분만 늦었어요.", "Kết quả ảnh hưởng đến kế hoạch của Linh."],
    ["Now I keep my wallet in a zipped pocket.", "Bây giờ tôi để ví trong túi có khóa kéo.", "이제는 지퍼 있는 주머니에 지갑을 넣어요.", "Bài học Linh rút ra sau sự việc."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-problem-resolution-listen",
      "Nghe câu “While she was checking the system, another passenger called the station.” và chọn ai gọi đến.",
      ["Một hành khách khác.", "Quản lý nhà ga.", "Bạn của Linh."],
      "Một hành khách khác.",
      "listening",
      "a2-problem-resolution-comprehension",
      "Chú ý “another passenger”.",
    ),
    exercise.dictation(
      "a2-problem-resolution-dictation",
      "Nghe và chép lại câu kết quả tốt.",
      "Fortunately, another passenger had found it.",
      "a2-problem-resolution-form",
    ),
  ],
  shadowing: {
    line: "I was getting off the train when I realized my wallet was missing.",
    notesVi: ["Ngắt nhẹ sau “train” để tách hai hành động.", "Nhấn vào “missing” ở cuối câu."],
    notesKo: ["“train” 뒤에서 잠깐 쉬면 두 행동이 구분돼요.", "문장 끝 “missing”을 살짝 세게 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-problem-resolution-g1",
      "Chọn câu đúng.",
      ["I was walking home when I dropped my phone.", "I walked home when I was dropping my phone.", "I was walk home when I dropped my phone."],
      "I was walking home when I dropped my phone.",
      "grammar",
      "a2-problem-resolution-form",
    ),
    exercise.translation(
      "a2-problem-resolution-g2",
      "Dịch sang tiếng Anh: “Cuối cùng tôi chỉ muộn ba mươi phút.”",
      "In the end, I was only thirty minutes late.",
      "a2-problem-resolution-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-problem-resolution-write",
      "Viết 6 câu kể một vấn đề bất ngờ và cách giải quyết: bối cảnh, vấn đề, hai bước xử lý, kết quả và bài học.",
      "a2-problem-resolution-communication",
      "Last month I lost my keys while I was walking home. I was carrying two bags when I noticed they were missing. First, I checked my pockets and my bag. Then I went back to the shop and asked for help. Fortunately, a staff member had found them near the door. In the end, I only waited ten minutes, and now I keep my keys in a small pocket.",
      ["Có bối cảnh và vấn đề rõ ràng", "Có hai bước xử lý và kết quả", "Có câu kết hoặc bài học"],
    ),
    exercise.speaking(
      "a2-problem-resolution-speak",
      "Kể một vấn đề bất ngờ và cách giải quyết trong 75 giây, dùng quá khứ đơn và quá khứ tiếp diễn.",
      "a2-problem-resolution-communication",
      "I was travelling to work when I realized my bag was open. My phone wasn’t inside. First, I checked the seat and the floor. Then I reported it to the staff at the next station. Fortunately, another passenger had found it and left it at the lost and found office. In the end, I got it back the same day.",
      ["Có vấn đề, hai bước xử lý và kết quả", "Dùng cả hai thì quá khứ", "Tự nghe lại và nhận xét"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-problem-resolution-m1",
      "Chọn câu đúng.",
      ["They were checking the system when I called.", "They checked the system when I was calling.", "They was checking the system when I called."],
      "They were checking the system when I called.",
      "grammar",
      "a2-problem-resolution-form",
    ),
    exercise.dictation(
      "a2-problem-resolution-m2",
      "Nghe và chép lại câu về kết quả cuối cùng.",
      "In the end, I was only thirty minutes late.",
      "a2-problem-resolution-comprehension",
    ),
    exercise.translation(
      "a2-problem-resolution-m3",
      "Dịch sang tiếng Anh: “Tôi nhận ra ví của mình đã mất.”",
      "I realized my wallet was missing.",
      "a2-problem-resolution-form",
    ),
    exercise.speaking(
      "a2-problem-resolution-m4",
      "Kể một vấn đề nhỏ và cách giải quyết trong 45 giây.",
      "a2-problem-resolution-communication",
      "I was leaving the office when I realized I had the wrong keys. First, I called my sister. Then I waited in a café near the office. Fortunately, she arrived in twenty minutes.",
      ["Có vấn đề, hai bước và kết quả", "Dùng quá khứ đơn và quá khứ tiếp diễn", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-problem-resolution-m5",
      "Điền dạng đúng: “While I ______ (look) for my bag, a staff member called my name.”",
      "was looking",
      "grammar",
      "a2-problem-resolution-comprehension",
    ),
  ],
  canDo: ["Có thể kể một vấn đề bất ngờ, cách xử lý và kết quả cuối cùng."],
  spiralReview: ["A2 Unit 3 bài 1 và 2: quá khứ đơn và quá khứ tiếp diễn", "A2 Unit 2 bài 3: mô tả vấn đề với sản phẩm"],
  errorCategories: ["verb-tense", "word-order", "grammar-form", "missing-word"],
};

/* ------------------------------------------------------------------ *
 * Bài 4 — Phản ứng và hỏi tiếp câu chuyện
 * ------------------------------------------------------------------ */
const storyReactions: LessonSeed = {
  id: "a2-story-reactions",
  unitId,
  number: 4,
  prerequisites: ["a2-problem-resolution"],
  titleVi: "Phản ứng và hỏi tiếp câu chuyện",
  titleKo: "이야기에 반응하고 이어서 묻기",
  situationVi: "Linh gặp lại thầy giáo cũ và kể cho Joon nghe; Joon phản ứng và hỏi tiếp từng chi tiết.",
  situationKo: "린은 옛 선생님을 만난 이야기를 준에게 해요. 준은 반응하고 세부 내용을 이어서 물어요.",
  objectives: [
    { id: "a2-story-reactions-communication", en: "React to a story and keep it going with follow-up questions.", vi: "Phản ứng trước một câu chuyện và hỏi tiếp để câu chuyện tiếp diễn.", ko: "이야기에 반응하고 이어서 질문할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-story-reactions-form", en: "Ask follow-up questions in the past simple.", vi: "Hỏi tiếp bằng quá khứ đơn.", ko: "과거형으로 후속 질문을 할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-story-reactions-comprehension", en: "Understand reactions and feelings in a story.", vi: "Nghe hiểu phản ứng và cảm xúc trong một câu chuyện.", ko: "이야기 속 반응과 감정을 이해할 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "Really?", "Thật sao?", "정말요?", "/ˈrɪəli/", "REally", "casual", ["Really? Where?", "Really? That’s unusual"]],
    ["v2", "That sounds…", "Nghe có vẻ…", "…하게 들려요", "/ðæt saʊndz/", "That SOUNDS", "neutral", ["that sounds lovely", "that sounds difficult"]],
    ["v3", "What happened next?", "Sau đó chuyện gì xảy ra?", "그다음에 어떻게 됐어요?", "/wɒt ˈhæpənd nekst/", "What HAPpened NEXT", "casual", ["what happened next", "what happened after that"]],
    ["v4", "How did you feel?", "Bạn cảm thấy thế nào?", "기분이 어땠어요?", "/haʊ dɪd juː fiːl/", "How did you FEEL", "neutral", ["how did you feel then", "how did everyone feel"]],
    ["v5", "That’s a relief", "Thật nhẹ nhõm", "다행이에요", "/ðæts ə rɪˈliːf/", "That’s a reLIEF", "neutral", ["that’s a relief", "what a relief"]],
    ["v6", "What a surprise", "Thật bất ngờ", "정말 놀랍네요", "/wɒt ə səˈpraɪz/", "What a surPRISE", "casual", ["what a surprise", "that was a surprise"]],
    ["v7", "Were you okay?", "Bạn có ổn không?", "괜찮았어요?", "/wɜː juː əʊˈkeɪ/", "Were you oKAY", "neutral", ["were you okay", "was he okay"]],
    ["v8", "Tell me more", "Kể thêm đi", "더 이야기해 주세요", "/tel miː mɔː/", "TELL me MORE", "casual", ["tell me more about it", "tell me more later"]],
  ],
  dialogue: [
    ["Linh", "I met our old teacher last weekend.", "Cuối tuần trước tôi gặp lại thầy giáo cũ của chúng ta.", "지난 주말에 옛 선생님을 만났어요.", "casual"],
    ["Joon", "Really? Where did you see her?", "Thật sao? Bạn gặp cô ấy ở đâu?", "정말요? 어디서 만났어요?", "casual"],
    ["Linh", "We were waiting at the same café near the school.", "Chúng tôi đang đợi ở cùng một quán cà phê gần trường.", "학교 근처 같은 카페에서 기다리고 있었어요.", "neutral"],
    ["Joon", "What a surprise! Did she remember you?", "Bất ngờ thật! Cô ấy có nhớ bạn không?", "정말 놀랍네요! 선생님이 기억했어요?", "casual"],
    ["Linh", "She remembered my name right away.", "Cô nhớ tên tôi ngay lập tức.", "제 이름을 바로 기억했어요.", "neutral"],
    ["Joon", "How did you feel?", "Bạn cảm thấy thế nào?", "기분이 어땠어요?", "casual"],
    ["Linh", "I was surprised and really happy.", "Tôi bất ngờ và rất vui.", "놀랐고 정말 기뻤어요.", "neutral"],
    ["Joon", "What happened next?", "Sau đó chuyện gì xảy ra?", "그다음에는 어떻게 됐어요?", "casual"],
    ["Linh", "We talked for nearly an hour about the old class.", "Chúng tôi nói chuyện gần một giờ về lớp học cũ.", "옛 반 이야기를 거의 한 시간 동안 했어요.", "neutral"],
    ["Joon", "That sounds lovely. Did she tell you about the school?", "Nghe dễ thương đấy. Cô ấy có kể về trường không?", "좋았겠네요. 학교 이야기도 했어요?", "casual"],
    ["Linh", "Yes, and she showed me some old photos on her phone.", "Có, và cô cho tôi xem mấy tấm ảnh cũ trên điện thoại.", "네, 휴대폰으로 옛 사진도 보여 줬어요.", "neutral"],
    ["Joon", "Were you late for your next appointment?", "Bạn có trễ cuộc hẹn sau đó không?", "다음 약속에 늦었어요?", "casual"],
    ["Linh", "No, I had plenty of time. It was such a nice surprise.", "Không, tôi có nhiều thời gian. Đó là một bất ngờ dễ chịu.", "아니요, 시간이 넉넉했어요. 정말 좋은 우연이었어요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "Câu hỏi nối tiếp trong quá khứ",
      titleKo: "과거형 후속 질문",
      explanationVi: "Để giữ câu chuyện tiếp diễn, hỏi lại bằng quá khứ đơn: What did you do? Where did you see her? How did you feel? Were you okay? Did she remember you?",
      explanationKo: "이야기를 이어 가려면 과거형으로 되물어요. What did you do? How did you feel? Did she remember you?처럼 물어요.",
      easierKorean: "이야기를 이어 갈 때는 Did you…? How did you…?로 물어요.",
    },
    {
      titleVi: "Phản ứng tự nhiên khi nghe kể",
    titleKo: "이야기를 들을 때의 자연스러운 반응",
      explanationVi: "Phản ứng ngắn giúp người kể biết bạn đang nghe: Really? What a surprise! That sounds lovely. That’s a relief. Sau đó thêm một câu hỏi nối tiếp để câu chuyện đi tiếp.",
      explanationKo: "Really? What a surprise! That sounds lovely. That’s a relief.처럼 짧게 반응하고, 이어서 질문을 하나 더 해요.",
      easierKorean: "짧게 반응하고 바로 이어서 질문해요.",
    },
  ],
  examples: [
    ["I met our old teacher last weekend.", "Cuối tuần trước tôi gặp lại thầy giáo cũ.", "지난 주말에 옛 선생님을 만났어요.", "Câu mở đầu Linh kể cho Joon."],
    ["Really? Where did you see her?", "Thật sao? Bạn gặp cô ấy ở đâu?", "정말요? 어디서 만났어요?", "Phản ứng kèm câu hỏi nối tiếp."],
    ["We were waiting at the same café.", "Chúng tôi đang đợi ở cùng một quán cà phê.", "같은 카페에서 기다리고 있었어요.", "Chi tiết bối cảnh của cuộc gặp."],
    ["What a surprise!", "Bất ngờ thật!", "정말 놀랍네요!", "Phản ứng tự nhiên trước tình huống hiếm gặp."],
    ["She remembered my name right away.", "Cô nhớ tên tôi ngay lập tức.", "선생님이 제 이름을 바로 기억했어요.", "Chi tiết khiến câu chuyện thú vị hơn."],
    ["How did you feel?", "Bạn cảm thấy thế nào?", "기분이 어땠어요?", "Câu hỏi về cảm xúc trong quá khứ."],
    ["I was surprised and really happy.", "Tôi bất ngờ và rất vui.", "놀랐고 정말 기뻤어요.", "Câu trả lời về cảm xúc."],
    ["What happened next?", "Sau đó chuyện gì xảy ra?", "그다음에는 어떻게 됐어요?", "Câu hỏi giữ câu chuyện tiếp diễn."],
    ["We talked for nearly an hour.", "Chúng tôi nói chuyện gần một giờ.", "거의 한 시간 동안 이야기했어요.", "Chi tiết thời lượng của cuộc trò chuyện."],
    ["That sounds lovely.", "Nghe dễ thương đấy.", "좋았겠네요.", "Phản hồi tích cực khi nghe kể."],
    ["Did she tell you about the old school?", "Cô ấy có kể cho bạn về ngôi trường cũ không?", "옛 학교 이야기를 했어요?", "Câu hỏi nối tiếp tiếp theo."],
    ["She showed me some photos on her phone.", "Cô ấy cho tôi xem mấy tấm ảnh trên điện thoại.", "휴대폰으로 사진을 보여 줬어요.", "Chi tiết cụ thể trong câu trả lời."],
    ["Were you late for your next appointment?", "Bạn có trễ cuộc hẹn sau đó không?", "다음 약속에 늦었어요?", "Câu hỏi quan tâm đến hậu quả."],
    ["That’s a relief.", "Thật nhẹ nhõm.", "다행이에요.", "Phản ứng khi nghe tin tốt."],
    ["It was such a nice surprise.", "Đó là một bất ngờ dễ chịu.", "정말 반가운 우연이었어요.", "Câu kết của người kể chuyện."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-story-reactions-listen",
      "Nghe câu “I was surprised and really happy.” và chọn cảm xúc.",
      ["Bất ngờ và vui.", "Lo lắng và mệt.", "Tức giận và thất vọng."],
      "Bất ngờ và vui.",
      "listening",
      "a2-story-reactions-communication",
      "Chú ý hai tính từ cảm xúc.",
    ),
    exercise.dictation(
      "a2-story-reactions-dictation",
      "Nghe và chép lại câu hỏi nối tiếp về cảm xúc.",
      "How did you feel?",
      "a2-story-reactions-form",
    ),
  ],
  shadowing: {
    line: "What a surprise! Did she remember you?",
    notesVi: ["Lên giọng mạnh ở “surprise” để thể hiện bất ngờ.", "Ngắt rõ giữa hai câu để tách phản ứng và câu hỏi."],
    notesKo: ["“surprise”를 올려 말하면 놀라움이 잘 드러나요.", "두 문장 사이에서 또렷하게 쉬어요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-story-reactions-g1",
      "Chọn câu hỏi nối tiếp đúng ngữ pháp.",
      ["Where did you see her?", "Where you saw her?", "Where did you saw her?"],
      "Where did you see her?",
      "grammar",
      "a2-story-reactions-form",
    ),
    exercise.translation(
      "a2-story-reactions-g2",
      "Dịch sang tiếng Anh: “Sau đó chuyện gì xảy ra?”",
      "What happened next?",
      "a2-story-reactions-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-story-reactions-write",
      "Viết 6 câu: một câu mở đầu câu chuyện, ba phản ứng tự nhiên và hai câu hỏi nối tiếp.",
      "a2-story-reactions-communication",
      "I met an old friend at the airport last month. Really? What was he doing there? What a surprise! How did you feel? We talked for twenty minutes, and he showed me photos of his new flat. That sounds lovely.",
      ["Có ba phản ứng khác nhau", "Có hai câu hỏi nối tiếp", "Câu hỏi dùng quá khứ đơn"],
    ),
    exercise.speaking(
      "a2-story-reactions-speak",
      "Đóng vai người nghe trong 60 giây: phản ứng ba lần và đặt bốn câu hỏi nối tiếp cho một câu chuyện.",
      "a2-story-reactions-communication",
      "Really? Where did that happen? What a surprise! What happened next? That sounds lovely. Were you okay after that? How did everyone feel? Tell me more about it.",
      ["Có ba phản ứng và bốn câu hỏi", "Câu hỏi dùng quá khứ đơn", "Tự nghe lại và nhận xét"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-story-reactions-m1",
      "Chọn câu hỏi đúng.",
      ["What happened after you got home?", "What happened after you get home?", "What did happened after you got home?"],
      "What happened after you got home?",
      "grammar",
      "a2-story-reactions-form",
    ),
    exercise.dictation(
      "a2-story-reactions-m2",
      "Nghe và chép lại phản ứng khi nghe tin tốt.",
      "That’s a relief.",
      "a2-story-reactions-comprehension",
    ),
    exercise.translation(
      "a2-story-reactions-m3",
      "Dịch sang tiếng Anh: “Cô ấy nhớ tên tôi ngay lập tức.”",
      "She remembered my name right away.",
      "a2-story-reactions-form",
    ),
    exercise.speaking(
      "a2-story-reactions-m4",
      "Kể một câu chuyện ngắn trong 45 giây và tự phản ứng lại một chi tiết.",
      "a2-story-reactions-communication",
      "I met my old teacher at a café last weekend. Really? She remembered my name right away. What a surprise! We talked for an hour and she showed me some photos.",
      ["Có câu chuyện và phản ứng", "Có ít nhất hai câu hỏi hoặc phản ứng", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-story-reactions-m5",
      "Điền trợ động từ: “Where ______ you see her?”",
      "did",
      "grammar",
      "a2-story-reactions-comprehension",
    ),
  ],
  canDo: ["Có thể phản ứng và hỏi tiếp để một câu chuyện tiếp diễn tự nhiên."],
  spiralReview: ["A1: câu hỏi Wh- ở hiện tại", "A2 Unit 3 bài 1 đến bài 3: kể chuyện ở quá khứ"],
  errorCategories: ["verb-tense", "word-order", "grammar-form", "register"],
};

/* ------------------------------------------------------------------ *
 * Bài 5 — Ôn tập và kể một câu chuyện hoàn chỉnh
 * ------------------------------------------------------------------ */
const completeStory: LessonSeed = {
  id: "a2-complete-story",
  unitId,
  number: 5,
  prerequisites: ["a2-story-reactions"],
  titleVi: "Ôn tập và kể một câu chuyện hoàn chỉnh",
  titleKo: "Unit 3 복습과 완성된 이야기",
  situationVi: "Linh kể lại chuyến đi biển có sự cố xe hỏng, từ lúc khởi hành đến khi về nhà.",
  situationKo: "린은 차가 고장 난 바다 여행을 처음부터 끝까지 이야기해요.",
  objectives: [
    { id: "a2-complete-story-communication", en: "Tell a complete story from start to finish.", vi: "Kể một câu chuyện hoàn chỉnh từ đầu đến cuối.", ko: "이야기를 처음부터 끝까지 완성해서 말할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-complete-story-form", en: "Use narrative tenses and sequence connectors together.", vi: "Dùng thì kể chuyện và từ nối trình tự cùng lúc.", ko: "이야기 시제와 순서 연결어를 함께 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-complete-story-comprehension", en: "Follow a longer story and catch the turning point.", vi: "Nghe hiểu câu chuyện dài và nhận ra điểm ngoặt.", ko: "긴 이야기를 듣고 전환점을 찾아낼 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "at first", "lúc đầu", "처음에는", "/ət fɜːst/", "at FIRST", "neutral", ["at first, everything was fine", "at first we planned"]],
    ["v2", "while", "trong khi", "…하는 동안", "/waɪl/", "WHILE", "neutral", ["while we were driving", "while they were waiting"]],
    ["v3", "suddenly", "đột nhiên", "갑자기", "/ˈsʌdənli/", "SUD-denly", "neutral", ["suddenly, we had to stop", "suddenly it got dark"]],
    ["v4", "because", "bởi vì", "왜냐하면", "/bɪˈkɒz/", "beCAUSE", "neutral", ["because there was no garage", "because it was raining"]],
    ["v5", "so", "vì vậy", "그래서", "/səʊ/", "SO", "neutral", ["so we called for help", "so we waited"]],
    ["v6", "after that", "sau đó", "그 후에", "/ˈɑːftə ðæt/", "AFter that", "neutral", ["after that, a mechanic arrived", "after that we continued"]],
    ["v7", "luckily", "may mắn là", "다행히", "/ˈlʌkɪli/", "LUCKily", "neutral", ["luckily, the car was fine", "luckily, we had water"]],
    ["v8", "in the end", "cuối cùng", "결국", "/ɪn ði end/", "in the END", "neutral", ["in the end, we continued", "in the end it was fine"]],
  ],
  dialogue: [
    ["Joon", "How was your trip to the coast?", "Chuyến đi biển của bạn thế nào?", "바다 여행은 어땠어요?", "casual"],
    ["Linh", "It was memorable, but not in the way we planned.", "Đáng nhớ, nhưng không theo cách chúng tôi dự định.", "기억에 남지만 계획한 대로는 아니었어요.", "casual"],
    ["Joon", "What do you mean?", "Ý bạn là sao?", "무슨 뜻이에요?", "casual"],
    ["Linh", "At first, everything was going well. We were driving to the coast when the car made a strange noise.", "Lúc đầu mọi thứ ổn. Chúng tôi đang lái xe ra biển thì xe kêu lạ.", "처음에는 다 잘 되고 있었어요. 차를 몰고 가는데 이상한 소리가 났어요.", "neutral"],
    ["Joon", "Oh no. What did you do?", "Trời ơi. Bạn đã làm gì?", "이런. 어떻게 했어요?", "casual"],
    ["Linh", "Suddenly, we had to stop. Because there was no garage nearby, we called for help.", "Đột nhiên chúng tôi phải dừng lại. Vì gần đó không có gara, chúng tôi gọi cứu hộ.", "갑자기 멈춰야 했어요. 근처에 정비소가 없어서 도움을 요청했어요.", "neutral"],
    ["Joon", "Were you waiting long?", "Bạn chờ lâu không?", "오래 기다렸어요?", "casual"],
    ["Linh", "While we were waiting, a local family stopped and gave us water.", "Trong khi chúng tôi đang chờ, một gia đình địa phương dừng lại và cho chúng tôi nước.", "기다리는 동안 현지 가족이 차를 세우고 물을 줬어요.", "neutral"],
    ["Joon", "That’s kind. And then?", "Tử tế thật. Rồi sau đó?", "친절하네요. 그다음엔요?", "casual"],
    ["Linh", "After that, a mechanic arrived and fixed a loose cable in ten minutes.", "Sau đó, một thợ máy đến và sửa một sợi dây lỏng trong mười phút.", "그 후 정비사가 와서 느슨한 케이블을 10분 만에 고쳤어요.", "neutral"],
    ["Joon", "Luckily, it wasn’t serious.", "May là không nghiêm trọng.", "다행히 심각하지 않았네요.", "casual"],
    ["Linh", "Luckily, no. In the end, we continued our journey before sunset and found a small hotel near the beach.", "May thật. Cuối cùng chúng tôi tiếp tục hành trình trước khi trời tối và tìm được một khách sạn nhỏ gần biển.", "다행히요. 결국 해 지기 전에 여행을 이어 갔고 해변 근처 작은 호텔을 찾았어요.", "neutral"],
    ["Joon", "So the problem became a good story.", "Vậy là sự cố đã thành một câu chuyện hay.", "그럼 그 문제가 좋은 이야기가 됐네요.", "casual"],
    ["Linh", "Exactly. The unexpected stop made the trip more memorable.", "Chính xác. Việc dừng lại bất ngờ khiến chuyến đi đáng nhớ hơn.", "맞아요. 예상치 못한 정차 덕분에 여행이 더 기억에 남았어요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "Thì kể chuyện: quá khứ đơn và quá khứ tiếp diễn",
      titleKo: "이야기 시제: 과거형과 과거진행형",
      explanationVi: "Bối cảnh đang diễn ra dùng quá khứ tiếp diễn: “We were driving to the coast.” Sự việc cắt ngang dùng quá khứ đơn: “the car made a strange noise.” Đan xen hai thì giúp câu chuyện tự nhiên.",
      explanationKo: "배경이 되는 상황은 과거진행형, 갑자기 생긴 일은 과거형으로 말해요. 두 시제를 섞으면 이야기가 자연스러워져요.",
      easierKorean: "배경은 was/were -ing, 사건은 과거형으로 말해요.",
    },
    {
      titleVi: "Từ nối trình tự và lý do",
      titleKo: "순서와 이유 연결어",
      explanationVi: "at first mở đầu, while nối hai việc cùng lúc, suddenly đánh dấu điểm ngoặt, because nêu lý do, so nêu kết quả, after that tiếp diễn, in the end tóm tắt kết quả.",
      explanationKo: "at first로 시작하고, while로 동시에 일어난 일을 잇고, suddenly로 전환점을 표시해요. because는 이유, so는 결과, in the end는 최종 결과를 말해요.",
      easierKorean: "at first → while → suddenly → because → so → after that → in the end 순서로 이어 말해요.",
    },
  ],
  examples: [
    ["At first, our trip was going exactly as planned.", "Lúc đầu, chuyến đi diễn ra đúng như kế hoạch.", "처음에는 여행이 계획대로 진행되고 있었어요.", "Câu mở đầu câu chuyện Linh kể."],
    ["We were driving to the coast when the car made a strange noise.", "Chúng tôi đang lái xe ra biển thì xe kêu lạ.", "차를 몰고 가는데 이상한 소리가 났어요.", "Điểm ngoặt đầu tiên của câu chuyện."],
    ["Suddenly, we had to stop.", "Đột nhiên, chúng tôi phải dừng lại.", "갑자기 멈춰야 했어요.", "Sự việc bất ngờ tiếp theo."],
    ["Because there was no garage nearby, we called for help.", "Vì gần đó không có gara, chúng tôi gọi cứu hộ.", "근처에 정비소가 없어서 도움을 요청했어요.", "Lý do và cách xử lý."],
    ["While we were waiting, a local family stopped.", "Trong khi chúng tôi đang chờ, một gia đình địa phương dừng lại.", "기다리는 동안 현지 가족이 차를 세웠어요.", "Chi tiết ấm áp giữa sự cố."],
    ["They gave us water and showed us a nearby café.", "Họ cho chúng tôi nước và chỉ một quán cà phê gần đó.", "물을 주고 근처 카페를 알려 줬어요.", "Hành động cụ thể của gia đình địa phương."],
    ["After that, a mechanic arrived.", "Sau đó, một thợ máy đến.", "그 후 정비사가 왔어요.", "Bước giải quyết tiếp theo."],
    ["He fixed a loose cable in ten minutes.", "Anh ấy sửa một sợi dây lỏng trong mười phút.", "느슨한 케이블을 10분 만에 고쳤어요.", "Chi tiết kỹ thuật nhưng dễ hiểu."],
    ["Luckily, the car was not seriously damaged.", "May là xe không hỏng nặng.", "다행히 차가 심하게 고장 나지 않았어요.", "Tin tốt sau khi kiểm tra."],
    ["We continued our journey before sunset.", "Chúng tôi tiếp tục hành trình trước khi trời tối.", "해 지기 전에 여행을 이어 갔어요.", "Cách câu chuyện quay lại kế hoạch ban đầu."],
    ["What happened when you reached the coast?", "Chuyện gì xảy ra khi bạn đến biển?", "바다에 도착했을 때 무슨 일이 있었어요?", "Câu hỏi nối tiếp của Joon."],
    ["We found a small hotel near the beach.", "Chúng tôi tìm được một khách sạn nhỏ gần biển.", "해변 근처 작은 호텔을 찾았어요.", "Kết quả sau khi tiếp tục hành trình."],
    ["The next morning was bright and calm.", "Sáng hôm sau trời sáng và yên.", "다음 날 아침은 맑고 조용했어요.", "Chi tiết khép lại câu chuyện."],
    ["In the end, the problem became our favorite travel story.", "Cuối cùng, sự cố trở thành câu chuyện du lịch yêu thích của chúng tôi.", "결국 그 문제는 우리가 가장 좋아하는 여행 이야기가 됐어요.", "Câu kết của câu chuyện."],
    ["The unexpected stop made the trip more memorable.", "Việc dừng lại bất ngờ khiến chuyến đi đáng nhớ hơn.", "예상치 못한 정차 덕분에 여행이 더 기억에 남았어요.", "Bài học Linh rút ra từ chuyến đi."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-complete-story-listen",
      "Nghe câu “We were driving to the coast when the car made a strange noise.” và chọn hành động đang diễn ra.",
      ["Hai người đang lái xe ra biển.", "Hai người đang sửa xe.", "Hai người đang chờ ở khách sạn."],
      "Hai người đang lái xe ra biển.",
      "listening",
      "a2-complete-story-comprehension",
      "Hành động đang diễn ra đứng sau “were driving”.",
    ),
    exercise.dictation(
      "a2-complete-story-dictation",
      "Nghe và chép lại bước xử lý khi xe hỏng.",
      "Because there was no garage nearby, we called for help.",
      "a2-complete-story-form",
    ),
  ],
  shadowing: {
    line: "We were driving to the coast when the car made a strange noise.",
    notesVi: ["Ngắt nhẹ sau “coast” để tách bối cảnh và sự việc.", "Nhấn vào “strange” trước danh từ."],
    notesKo: ["“coast” 뒤에서 잠깐 쉬면 배경과 사건이 구분돼요.", "“strange”를 살짝 세게 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-complete-story-g1",
      "Chọn câu đúng.",
      ["We were waiting when the mechanic arrived.", "We waited when the mechanic was arriving.", "We was waiting when the mechanic arrived."],
      "We were waiting when the mechanic arrived.",
      "grammar",
      "a2-complete-story-form",
    ),
    exercise.translation(
      "a2-complete-story-g2",
      "Dịch sang tiếng Anh: “Sau đó, một thợ máy đến.”",
      "After that, a mechanic arrived.",
      "a2-complete-story-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-complete-story-write",
      "Viết 8 câu kể một chuyến đi có sự cố: bối cảnh, sự việc bất ngờ, lý do, hai bước xử lý, kết quả và cảm nhận cuối.",
      "a2-complete-story-communication",
      "At first, our trip to the mountains was going well. We were driving when the car started to make a strange noise. Because there was no garage nearby, we called for help. While we were waiting, a farmer brought us tea. After that, a mechanic arrived and fixed the problem. Luckily, the car was fine. In the end, we reached the hotel before dark, and the unexpected stop became our favourite story.",
      ["Có đủ bảy phần của câu chuyện", "Dùng ít nhất bốn từ nối", "Dùng đúng hai thì quá khứ"],
    ),
    exercise.speaking(
      "a2-complete-story-speak",
      "Kể một câu chuyện hoàn chỉnh trong 90 giây: mở đầu, sự việc bất ngờ, cách xử lý, kết quả và cảm nhận.",
      "a2-complete-story-communication",
      "At first, everything was fine on our trip. We were driving when the car stopped. Because we were far from the city, we called for help. While we were waiting, a local family brought us water. After that, a mechanic arrived. Luckily, it was a small problem. In the end, we continued our trip and it became a memorable story.",
      ["Đủ năm phần của câu chuyện", "Dùng while, because, so, in the end", "Tự đánh giá và ghi một điểm cần sửa"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-complete-story-m1",
      "Chọn câu đúng.",
      ["At first, we were driving when the car stopped.", "At first, we drove when the car was stopping.", "At first, we was driving when the car stopped."],
      "At first, we were driving when the car stopped.",
      "grammar",
      "a2-complete-story-form",
    ),
    exercise.dictation(
      "a2-complete-story-m2",
      "Nghe và chép lại câu kết của câu chuyện.",
      "In the end, the problem became our favourite travel story.",
      "a2-complete-story-comprehension",
    ),
    exercise.translation(
      "a2-complete-story-m3",
      "Dịch sang tiếng Anh: “May là xe không hỏng nặng.”",
      "Luckily, the car was not seriously damaged.",
      "a2-complete-story-form",
    ),
    exercise.speaking(
      "a2-complete-story-m4",
      "Kể một câu chuyện hoàn chỉnh trong 90 giây với ít nhất bốn từ nối.",
      "a2-complete-story-communication",
      "At first, our weekend was quiet. We were walking in the park when it started to rain. Because we had no umbrella, we went into a small café. While we were waiting, we met an old friend. After that, the sun came out, and in the end we walked home together.",
      ["Có bốn từ nối trở lên", "Dùng hai thì quá khứ", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-complete-story-m5",
      "Điền từ nối: “______ there was no garage nearby, we called for help.”",
      "Because",
      "grammar",
      "a2-complete-story-comprehension",
    ),
  ],
  canDo: ["Có thể kể một câu chuyện hoàn chỉnh với bối cảnh, sự việc và kết quả."],
  spiralReview: ["A1: kể hoạt động trong kỳ nghỉ", "A2 Unit 1 đến Unit 3: thay đổi, trải nghiệm và sự việc trong quá khứ"],
  errorCategories: ["verb-tense", "word-order", "word-choice", "missing-word"],
};

export const a2Unit3 = bilingualUnitSchema.parse({
  id: unitId,
  level: "A2",
  titleVi: "Câu chuyện và sự việc trong quá khứ",
  titleKo: "이야기와 과거 사건",
  lessons: [tellingPastEvent, backgroundActions, problemResolution, storyReactions, completeStory].map(buildLesson),
});
