import { bilingualUnitSchema } from "@/lib/curriculum/bilingual-schema";
import { buildLesson, exercise, type LessonSeed } from "./a2-lesson-factory";

/**
 * A2 Unit 2 — Hoàn thành việc cần làm.
 *
 * ID bài, ID mục tiêu, ID từ vựng (thứ tự v1–v8) và ID bài tập được giữ nguyên
 * như bản trước để tiến độ, thẻ FSRS và dữ liệu cũ vẫn liên kết đúng.
 */
const unitId = "a2-2-getting-things-done";

/* ------------------------------------------------------------------ *
 * Bài 1 — Nhờ giúp đỡ một cách lịch sự
 * ------------------------------------------------------------------ */
const politeRequests: LessonSeed = {
  id: "a2-polite-requests",
  unitId,
  number: 1,
  prerequisites: ["a2-unit-1-review"],
  titleVi: "Nhờ giúp đỡ một cách lịch sự",
  titleKo: "정중하게 도움 요청하기",
  situationVi: "Ngày đầu ở văn phòng mới, Linh nhờ đồng nghiệp chỉ cách điền biểu mẫu và gửi tài liệu.",
  situationKo: "새 사무실 첫날, 린은 동료에게 서류 작성 방법과 자료 전송을 부탁해요.",
  objectives: [
    { id: "a2-polite-requests-communication", en: "Ask for help politely and respond to requests.", vi: "Nhờ giúp đỡ lịch sự và phản hồi lời nhờ.", ko: "정중하게 도움을 요청하고 부탁에 답할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-polite-requests-form", en: "Use could, would and can for requests.", vi: "Dùng could, would và can để nhờ.", ko: "could, would, can으로 부탁할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-polite-requests-comprehension", en: "Understand what someone is being asked to do.", vi: "Nghe hiểu người khác đang được nhờ làm gì.", ko: "누구에게 무엇을 부탁하는지 들을 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "Could you help me?", "Bạn có thể giúp tôi không?", "도와주실 수 있어요?", "/kʊd juː help miː/", "Could you HELP me", "neutral", ["Could you help me with this form", "Could you help me for a minute"]],
    ["v2", "Would you mind…?", "Bạn có phiền… không?", "…해 주시겠어요?", "/wʊd juː maɪnd/", "Would you MIND", "formal", ["Would you mind checking this", "Would you mind waiting"]],
    ["v3", "give me a hand", "giúp một tay", "한 손 거들어 주다", "/ɡɪv miː ə hænd/", "give me a HAND", "casual", ["give me a hand with the boxes", "give me a hand for five minutes"]],
    ["v4", "when you have a moment", "khi bạn rảnh một chút", "잠깐 시간 될 때", "/wen juː hæv ə ˈməʊmənt/", "when you have a MOment", "formal", ["when you have a moment", "when you have a moment today"]],
    ["v5", "No problem", "Không vấn đề gì", "문제없어요", "/nəʊ ˈprɒbləm/", "No PROBlem", "casual", ["No problem at all", "that’s no problem"]],
    ["v6", "I’m afraid I can’t", "E là tôi không thể", "아쉽지만 못 해요", "/aɪm əˈfreɪd aɪ kɑːnt/", "I’m aFRAID I CAN’T", "formal", ["I’m afraid I can’t stay late", "I’m afraid I can’t today"]],
    ["v7", "Could you clarify that?", "Bạn có thể làm rõ không?", "다시 설명해 주시겠어요?", "/kʊd juː ˈklærəfaɪ ðæt/", "Could you CLARify that", "formal", ["Could you clarify the last step", "Could you clarify what you mean"]],
    ["v8", "Thanks, I appreciate it", "Cảm ơn, tôi rất trân trọng", "고마워요, 정말 감사해요", "/θæŋks aɪ əˈpriːʃieɪt ɪt/", "THANKS, I apPREciate it", "formal", ["thanks, I appreciate it", "thanks, I really appreciate it"]],
  ],
  dialogue: [
    ["Linh", "Excuse me, could you help me with this form?", "Xin lỗi, bạn giúp tôi tờ biểu mẫu này được không?", "실례합니다, 이 서류 작성을 도와주실 수 있어요?", "neutral"],
    ["Tom", "Sure. Which part is difficult?", "Được. Phần nào khó?", "그럼요. 어느 부분이 어려워요?", "casual"],
    ["Linh", "The second page. I don’t understand the address field.", "Trang thứ hai. Tôi không hiểu phần địa chỉ.", "두 번째 장이요. 주소 칸을 모르겠어요.", "neutral"],
    ["Tom", "No problem. You write the street first, then the city.", "Không vấn đề gì. Bạn ghi đường trước, rồi đến thành phố.", "문제없어요. 도로명을 먼저 쓰고, 그다음 도시를 써요.", "casual"],
    ["Linh", "Could you clarify the last step?", "Bạn làm rõ bước cuối được không?", "마지막 단계를 설명해 주시겠어요?", "formal"],
    ["Tom", "Of course. Sign here and send it to the office email address.", "Tất nhiên. Ký ở đây và gửi đến email văn phòng.", "물론이죠. 여기에 서명하고 사무실 이메일로 보내세요.", "formal"],
    ["Linh", "Thank you. And would you mind checking the file I sent you?", "Cảm ơn. Bạn kiểm tra tệp tôi gửi được không?", "감사합니다. 그리고 제가 보낸 파일도 확인해 주시겠어요?", "formal"],
    ["Tom", "I can do it after lunch. Could you send the link again when you have a moment?", "Tôi làm được sau bữa trưa. Khi nào rảnh bạn gửi lại đường dẫn nhé?", "점심 후에 확인할 수 있어요. 시간 될 때 링크를 다시 보내 주시겠어요?", "neutral"],
    ["Linh", "I’ll send it now. Sorry, one more thing — can I borrow your stapler?", "Tôi gửi ngay. Xin lỗi, còn một việc nữa — tôi mượn dập ghim của bạn được không?", "지금 보낼게요. 죄송한데 하나만 더요, 스테이플러를 빌릴 수 있을까요?", "casual"],
    ["Tom", "Sure, it’s on my desk. Could you give me a hand with these boxes later?", "Được, nó ở trên bàn tôi. Lát nữa bạn giúp tôi mấy cái hộp này được không?", "그럼요, 제 책상에 있어요. 나중에 이 상자들 옮기는 것 좀 도와줄 수 있어요?", "casual"],
    ["Linh", "Of course. I’m afraid I can’t stay late today, but I’m free after three.", "Tất nhiên. Tiếc là hôm nay tôi không ở lại muộn được, nhưng tôi rảnh sau ba giờ.", "물론이죠. 오늘은 늦게까지 못 있지만 3시 이후에는 괜찮아요.", "neutral"],
    ["Tom", "Three is perfect. Thanks, I appreciate it.", "Ba giờ là tuyệt. Cảm ơn, tôi rất trân trọng.", "3시가 딱 좋아요. 고마워요.", "formal"],
  ],
  grammar: [
    {
      titleVi: "could, would và can trong lời nhờ",
      titleKo: "부탁의 could, would, can",
      explanationVi: "Could you…? là cách nhờ lịch sự nhất với đồng nghiệp: “Could you help me with this form?” Could I…? dùng khi xin phép: “Can I borrow your stapler?” Can you…? thân mật hơn, phù hợp với người quen.",
      explanationKo: "Could you…?는 동료에게 가장 정중한 부탁이에요. Can I…?는 허락을 구할 때, Can you…?는 더 편한 사이에서 써요.",
      easierKorean: "정중한 부탁은 Could you, 편한 부탁은 Can you를 써요.",
    },
    {
      titleVi: "Would you mind + -ing?",
      titleKo: "Would you mind + -ing",
      explanationVi: "Would you mind -ing? nghĩa là “Bạn có phiền… không?”, nhưng câu trả lời đồng ý là No, not at all. Dùng khi muốn nhờ người khác làm việc gì đó một cách rất lịch sự.",
      explanationKo: "Would you mind -ing?는 아주 정중한 부탁이에요. 승낙할 때는 No, not at all이라고 대답해요.",
      easierKorean: "Would you mind 뒤에는 -ing를 써요.",
    },
  ],
  examples: [
    ["Could you help me with this form?", "Bạn giúp tôi tờ biểu mẫu này được không?", "이 서류 작성을 도와주실 수 있어요?", "Linh nhờ đồng nghiệp trong ngày đầu đi làm."],
    ["Would you mind checking the address?", "Bạn kiểm tra giúp tôi phần địa chỉ được không?", "주소를 확인해 주시겠어요?", "Lời nhờ lịch sự trước khi gửi hồ sơ."],
    ["Could you send me the file when you have a moment?", "Khi nào rảnh bạn gửi tôi tệp đó nhé?", "시간 될 때 파일을 보내 주시겠어요?", "Tin nhắn trao đổi trong nhóm dự án."],
    ["Can you give me a hand with these boxes?", "Bạn giúp tôi mấy cái hộp này được không?", "이 상자들 옮기는 것 좀 도와줄 수 있어요?", "Nhờ đồng thân thiết trong kho."],
    ["I’m afraid I can’t stay late today.", "Tiếc là hôm nay tôi không ở lại muộn được.", "오늘은 늦게까지 못 있어요.", "Câu từ chối lịch sự khi được nhờ."],
    ["That’s okay. Tomorrow morning works too.", "Không sao. Sáng mai cũng được.", "괜찮아요. 내일 아침도 돼요.", "Câu trả lời khi người kia từ chối."],
    ["Could you clarify the last step?", "Bạn làm rõ bước cuối được không?", "마지막 단계를 설명해 주시겠어요?", "Linh hỏi khi đọc hướng dẫn điền biểu mẫu."],
    ["Would you open the window, please?", "Bạn mở cửa sổ giúp được không?", "창문 좀 열어 주시겠어요?", "Lời nhờ ngắn trong phòng họp."],
    ["Can I borrow your charger?", "Tôi mượn sạc của bạn được không?", "충전기를 빌릴 수 있을까요?", "Câu nhờ ở bàn làm việc."],
    ["Could you speak a little more slowly?", "Bạn nói chậm hơn một chút được không?", "조금 더 천천히 말해 줄 수 있어요?", "Linh hỏi trong cuộc gọi với khách hàng."],
    ["Thanks for helping me finish this.", "Cảm ơn đã giúp tôi hoàn thành việc này.", "이 일을 끝내도록 도와줘서 고마워요.", "Câu cảm ơn sau khi nhận hỗ trợ."],
    ["Would it be possible to move the meeting?", "Có thể dời cuộc họp được không?", "회의를 옮길 수 있을까요?", "Lời đề nghị trang trọng trong email."],
    ["I’d appreciate your help today.", "Tôi rất trân trọng sự giúp đỡ của bạn hôm nay.", "오늘 도와주시면 정말 감사하겠어요.", "Câu viết trong email gửi đồng nghiệp cấp trên."],
    ["No problem, I can do it now.", "Không vấn đề gì, tôi làm ngay được.", "문제없어요, 지금 할 수 있어요.", "Câu trả lời đồng ý giúp đỡ."],
    ["Sorry, I didn’t catch that. Could you repeat it?", "Xin lỗi, tôi chưa nghe rõ. Bạn nhắc lại được không?", "죄송해요, 못 들었어요. 다시 말해 줄 수 있어요?", "Câu nhờ khi nghe không rõ trong cuộc họp."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-polite-requests-listen",
      "Nghe câu “Could you send me the file when you have a moment?” và chọn việc được nhờ.",
      ["Gửi tệp khi rảnh.", "In tệp ngay bây giờ.", "Xóa tệp cũ."],
      "Gửi tệp khi rảnh.",
      "listening",
      "a2-polite-requests-communication",
      "Chú ý “send me the file”.",
    ),
    exercise.dictation(
      "a2-polite-requests-dictation",
      "Nghe và chép lại lời nhờ lịch sự.",
      "Would you mind checking the address?",
      "a2-polite-requests-form",
    ),
  ],
  shadowing: {
    line: "Could you send me the file when you have a moment?",
    notesVi: ["Lên giọng nhẹ ở “moment” vì đây là câu hỏi.", "Nối “send_me_the_file” thành một cụm nhanh."],
    notesKo: ["질문이니까 “moment”를 살짝 올려 말해요.", "“send me the file”은 빠르게 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-polite-requests-g1",
      "Chọn cách nhờ lịch sự nhất với đồng nghiệp mới.",
      ["Could you help me with this form?", "Help me now.", "You help me."],
      "Could you help me with this form?",
      "grammar",
      "a2-polite-requests-form",
    ),
    exercise.translation(
      "a2-polite-requests-g2",
      "Dịch sang tiếng Anh: “Bạn kiểm tra giúp tôi phần địa chỉ được không?”",
      "Would you mind checking the address?",
      "a2-polite-requests-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-polite-requests-write",
      "Viết 5 câu: hai lời nhờ lịch sự với Could you và Would you mind, một lời xin phép, một lời từ chối lịch sự và một câu cảm ơn.",
      "a2-polite-requests-communication",
      "Could you help me with the second page? Would you mind checking the address? Can I borrow your stapler for five minutes? I’m afraid I can’t stay late today because I have a class. Thanks, I appreciate your help.",
      ["Có hai lời nhờ lịch sự", "Có một lời từ chối kèm lý do", "Có câu cảm ơn"],
    ),
    exercise.speaking(
      "a2-polite-requests-speak",
      "Nói 60 giây: nhờ đồng nghiệp ba việc khác nhau, phản hồi một lời từ chối và thống nhất thời gian hỗ trợ.",
      "a2-polite-requests-communication",
      "Could you check this form for me? Would you mind sending the file again when you have a moment? Can you give me a hand with the boxes after three? If you can’t today, tomorrow morning works too.",
      ["Có ba lời nhờ khác mức độ lịch sự", "Có phản hồi khi bị từ chối", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-polite-requests-m1",
      "Chọn câu đúng.",
      ["Would you mind checking this?", "Would you mind to check this?", "Would you mind check this?"],
      "Would you mind checking this?",
      "grammar",
      "a2-polite-requests-form",
    ),
    exercise.dictation(
      "a2-polite-requests-m2",
      "Nghe và chép lại lời nhờ giúp một tay.",
      "Can you give me a hand with these boxes?",
      "a2-polite-requests-comprehension",
    ),
    exercise.translation(
      "a2-polite-requests-m3",
      "Dịch sang tiếng Anh: “Tiếc là hôm nay tôi không ở lại muộn được.”",
      "I’m afraid I can’t stay late today.",
      "a2-polite-requests-form",
    ),
    exercise.speaking(
      "a2-polite-requests-m4",
      "Nhờ giúp đỡ trong 45 giây: hai lời nhờ, một lời từ chối và một phương án khác.",
      "a2-polite-requests-communication",
      "Could you help me with this report? Would you mind checking the numbers? I’m afraid I can’t finish it today, but I can do it tomorrow before ten.",
      ["Có hai lời nhờ", "Có một lời từ chối và phương án khác", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-polite-requests-m5",
      "Điền dạng đúng: “Would you mind ______ (wait) for five minutes?”",
      "waiting",
      "grammar",
      "a2-polite-requests-comprehension",
    ),
  ],
  canDo: ["Có thể nhờ giúp đỡ và phản hồi lời nhờ một cách lịch sự."],
  spiralReview: ["A1: Can I…? và Can you…? ở mức cơ bản", "A2 Unit 1 bài 4: lời mời và cách từ chối lịch sự"],
  errorCategories: ["register", "grammar-form", "missing-word", "word-choice"],
};

/* ------------------------------------------------------------------ *
 * Bài 2 — Hỏi đường và đi phương tiện công cộng
 * ------------------------------------------------------------------ */
const directionsTransit: LessonSeed = {
  id: "a2-directions-transit",
  unitId,
  number: 2,
  prerequisites: ["a2-polite-requests"],
  titleVi: "Hỏi đường và đi phương tiện công cộng",
  titleKo: "길과 대중교통 묻기",
  situationVi: "Linh tìm đường đến bảo tàng bằng tàu điện, hỏi nhân viên nhà ga và một người đi đường.",
  situationKo: "린은 지하철로 박물관에 가는 길을 찾아요. 역 직원과 지나가는 사람에게 길을 물어요.",
  objectives: [
    { id: "a2-directions-transit-communication", en: "Ask for and follow directions on public transport.", vi: "Hỏi và làm theo chỉ dẫn khi đi phương tiện công cộng.", ko: "대중교통에서 길을 묻고 따라갈 수 있어요.", skills: ["speaking", "listening"] },
    { id: "a2-directions-transit-form", en: "Use imperatives, prepositions of movement and sequence words.", vi: "Dùng câu mệnh lệnh, giới từ chuyển động và từ nối trình tự.", ko: "명령문, 이동 전치사, 순서 표현을 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-directions-transit-comprehension", en: "Understand a route with two or three steps.", vi: "Nghe hiểu một lộ trình có hai đến ba bước.", ko: "두세 단계로 된 이동 경로를 들을 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "go straight", "đi thẳng", "곧장 가다", "/ɡəʊ streɪt/", "go STRAIGHT", "neutral", ["go straight for two blocks", "go straight and turn left"]],
    ["v2", "turn left", "rẽ trái", "왼쪽으로 돌다", "/tɜːn left/", "turn LEFT", "neutral", ["turn left at the bank", "turn left after the bridge"]],
    ["v3", "across from", "đối diện", "맞은편에", "/əˈkrɒs frɒm/", "aCROSS from", "neutral", ["across from the station", "right across from the park"]],
    ["v4", "next to", "bên cạnh", "옆에", "/nekst tuː/", "NEXT to", "neutral", ["next to the bookstore", "next to exit four"]],
    ["v5", "get off", "xuống xe", "내리다", "/ɡet ɒf/", "get OFF", "neutral", ["get off at Central", "get off the bus"]],
    ["v6", "transfer to", "chuyển sang tuyến", "갈아타다", "/trænsˈfɜː tuː/", "transFER to", "neutral", ["transfer to line two", "transfer at City Hall"]],
    ["v7", "platform", "sân ga", "승강장", "/ˈplætfɔːm/", "PLATform", "neutral", ["platform six", "which platform"]],
    ["v8", "How long does it take?", "Mất bao lâu?", "얼마나 걸려요?", "/haʊ lɒŋ dʌz ɪt teɪk/", "How LONG does it TAKE", "neutral", ["How long does it take by bus", "How long does the journey take"]],
  ],
  dialogue: [
    ["Linh", "Excuse me, how do I get to the city museum?", "Xin lỗi, tôi đến bảo tàng thành phố bằng cách nào?", "실례합니다, 시립 박물관에 어떻게 가요?", "neutral"],
    ["Staff", "Take line two and get off at Central.", "Bạn đi tuyến số hai và xuống ở ga Central.", "2호선을 타고 센트럴에서 내리세요.", "neutral"],
    ["Linh", "Which platform does the train leave from?", "Tàu khởi hành từ sân ga nào?", "기차는 어느 승강장에서 출발해요?", "neutral"],
    ["Staff", "Platform four. Then follow the signs to exit two.", "Sân ga số bốn. Sau đó đi theo biển chỉ dẫn đến lối ra số hai.", "4번 승강장이에요. 그다음 2번 출구 표지를 따라가세요.", "neutral"],
    ["Linh", "Do I need to transfer?", "Tôi có phải chuyển tuyến không?", "갈아타야 하나요?", "neutral"],
    ["Staff", "No, it’s a direct line. It takes about twenty minutes.", "Không, tuyến này đi thẳng. Mất khoảng hai mươi phút.", "아니요, 직통이에요. 20분 정도 걸려요.", "neutral"],
    ["Linh", "Thank you. One more question — is the museum across from the station?", "Cảm ơn. Một câu nữa — bảo tàng có đối diện nhà ga không?", "감사합니다. 하나만 더요, 박물관이 역 맞은편에 있어요?", "neutral"],
    ["Staff", "Not exactly. Go straight for two blocks and turn left at the bank.", "Không hẳn. Bạn đi thẳng hai dãy nhà rồi rẽ trái ở ngân hàng.", "꼭 그렇지는 않아요. 두 블록 곧장 가서 은행에서 왼쪽으로 도세요.", "neutral"],
    ["Linh", "And after that?", "Sau đó thì sao?", "그다음에는요?", "neutral"],
    ["Staff", "The museum is next to the bookstore, on your right.", "Bảo tàng ở bên cạnh hiệu sách, phía tay phải của bạn.", "박물관은 서점 옆, 오른쪽에 있어요.", "neutral"],
    ["Linh", "That’s clear. Thank you so much.", "Rõ rồi. Cảm ơn bạn rất nhiều.", "잘 알겠어요. 정말 감사합니다.", "neutral"],
    ["Staff", "You’re welcome. Have a good visit.", "Không có gì. Chúc bạn tham quan vui vẻ.", "천만에요. 즐거운 관람 되세요.", "formal"],
  ],
  grammar: [
    {
      titleVi: "Câu mệnh lệnh và giới từ chuyển động",
      titleKo: "명령문과 이동 전치사",
      explanationVi: "Chỉ đường thường dùng động từ nguyên mẫu ở đầu câu: “Go straight for two blocks.” “Turn left at the bank.” Giới từ chuyển động: across from (đối diện), next to (bên cạnh), past (đi ngang qua), through (xuyên qua).",
      explanationKo: "길을 알려 줄 때는 동사원형으로 문장을 시작해요. across from은 맞은편, next to는 옆, past는 지나서, through는 통과해서라는 뜻이에요.",
      easierKorean: "길 안내는 Go straight, Turn left처럼 동사원형으로 시작해요.",
    },
    {
      titleVi: "Hỏi lộ trình với How long và Which",
      titleKo: "How long, Which로 경로 묻기",
      explanationVi: "How long does it take? hỏi thời gian di chuyển. Which platform…? hỏi chọn trong nhiều lựa chọn. Do I need to transfer? dùng để hỏi về việc đổi tuyến.",
      explanationKo: "How long does it take?는 걸리는 시간을 물어요. Which platform…?은 여러 승강장 중 어느 것인지 물어요.",
      easierKorean: "시간은 How long, 승강장은 Which platform으로 물어요.",
    },
  ],
  examples: [
    ["Go straight for two blocks and turn left at the bank.", "Đi thẳng hai dãy nhà rồi rẽ trái ở ngân hàng.", "두 블록 곧장 가서 은행에서 왼쪽으로 도세요.", "Nhân viên nhà ga chỉ đường đến bảo tàng."],
    ["The pharmacy is across from the station.", "Hiệu thuốc ở đối diện nhà ga.", "약국은 역 맞은편에 있어요.", "Chỉ dẫn Linh hỏi khi đi mua thuốc."],
    ["The entrance is next to the bookstore.", "Lối vào ở bên cạnh hiệu sách.", "입구는 서점 옆에 있어요.", "Thông tin trên biển chỉ dẫn ngoài phố."],
    ["Get off at Central and follow the signs.", "Xuống ở Central rồi đi theo biển chỉ dẫn.", "센트럴에서 내리고 표지를 따라가세요.", "Hướng dẫn của nhân viên cho khách."],
    ["You need to transfer to the green line.", "Bạn cần chuyển sang tuyến màu xanh.", "초록색 노선으로 갈아타야 해요.", "Lời khuyên khi lộ trình phải đổi tuyến."],
    ["Which platform does the train leave from?", "Tàu khởi hành từ sân ga nào?", "기차는 어느 승강장에서 출발해요?", "Câu hỏi Linh hỏi ở nhà ga."],
    ["How long does the journey take?", "Chuyến đi mất bao lâu?", "이동 시간이 얼마나 걸려요?", "Câu hỏi trước khi mua vé."],
    ["It takes about twenty minutes.", "Mất khoảng hai mươi phút.", "20분 정도 걸려요.", "Câu trả lời của nhân viên nhà ga."],
    ["Walk past the café and cross the street.", "Đi ngang qua quán cà phê rồi băng qua đường.", "카페를 지나서 길을 건너세요.", "Chỉ dẫn chi tiết cho người đi bộ."],
    ["Does this bus stop near the museum?", "Xe buýt này có dừng gần bảo tàng không?", "이 버스가 박물관 근처에 서나요?", "Linh hỏi tài xế xe buýt."],
    ["Am I going in the right direction?", "Tôi đi đúng hướng chưa?", "제가 맞는 방향으로 가고 있나요?", "Câu hỏi khi Linh thấy không chắc đường."],
    ["First take the bus, then walk for five minutes.", "Đầu tiên đi xe buýt, sau đó đi bộ năm phút.", "먼저 버스를 타고, 그다음 5분 걸어요.", "Lộ trình hai bước Linh ghi vào ghi chú."],
    ["Take exit four and turn right at the corner.", "Ra ở lối số bốn rồi rẽ phải ở góc phố.", "4번 출구로 나가서 모퉁이에서 오른쪽으로 도세요.", "Chỉ dẫn ở ga tàu điện ngầm."],
    ["The bus stop is on the other side of the road.", "Trạm xe buýt ở phía bên kia đường.", "버스 정류장은 길 반대편에 있어요.", "Thông tin Linh hỏi một người đi đường."],
    ["You can’t miss it — it’s a big white building.", "Bạn không thể nhầm được — đó là tòa nhà trắng lớn.", "놓칠 수 없어요. 큰 흰색 건물이에요.", "Câu kết khi chỉ đường cho khách du lịch."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-directions-transit-listen",
      "Nghe câu “Take line two and get off at Central.” và chọn bến cần xuống.",
      ["Central.", "City Hall.", "Green Park."],
      "Central.",
      "listening",
      "a2-directions-transit-comprehension",
      "Tên bến nằm sau “get off at”.",
    ),
    exercise.dictation(
      "a2-directions-transit-dictation",
      "Nghe và chép lại chỉ dẫn rẽ trái.",
      "Go straight for two blocks and turn left at the bank.",
      "a2-directions-transit-form",
    ),
  ],
  shadowing: {
    line: "The museum is next to the bookstore, on your right.",
    notesVi: ["Ngắt nhẹ sau “bookstore” để tách vị trí và hướng.", "Nhấn nhẹ vào “right”."],
    notesKo: ["“bookstore” 뒤에서 잠깐 쉬면 위치와 방향이 구분돼요.", "“right”를 살짝 세게 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-directions-transit-g1",
      "Chọn câu chỉ đường đúng ngữ pháp.",
      ["Go straight and turn left at the bank.", "Go straight and turning left at the bank.", "Going straight and turn left at the bank."],
      "Go straight and turn left at the bank.",
      "grammar",
      "a2-directions-transit-form",
    ),
    exercise.translation(
      "a2-directions-transit-g2",
      "Dịch sang tiếng Anh: “Chuyến đi mất bao lâu?”",
      "How long does the journey take?",
      "a2-directions-transit-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-directions-transit-write",
      "Viết 4–5 câu chỉ đường từ nhà bạn đến một nơi quen thuộc: hai bước bằng mệnh lệnh, một giới từ vị trí và thời gian di chuyển.",
      "a2-directions-transit-communication",
      "From my flat, go straight for two blocks and turn right at the pharmacy. Then walk past the school and cross the street. The market is next to the bank. It takes about fifteen minutes on foot.",
      ["Có hai bước chỉ đường", "Có giới từ vị trí", "Có thời gian di chuyển"],
    ),
    exercise.speaking(
      "a2-directions-transit-speak",
      "Nói 60 giây: hỏi đường ở nhà ga, nhắc lại lộ trình và xác nhận lại bến cần xuống.",
      "a2-directions-transit-communication",
      "How do I get to the city museum? Which platform does the train leave from? Do I need to transfer? So I take line two, get off at Central, and then walk past the bank? It takes about twenty minutes, right?",
      ["Có ba câu hỏi và một câu nhắc lại", "Dùng mệnh lệnh hoặc giới từ chuyển động", "Tự nghe lại và nhận xét"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-directions-transit-m1",
      "Chọn câu hỏi đúng để hỏi sân ga.",
      ["Which platform does the train leave from?", "Which platform the train leaves from?", "From which platform the train leave?"],
      "Which platform does the train leave from?",
      "grammar",
      "a2-directions-transit-form",
    ),
    exercise.dictation(
      "a2-directions-transit-m2",
      "Nghe và chép lại câu về vị trí hiệu thuốc.",
      "The pharmacy is across from the station.",
      "a2-directions-transit-comprehension",
    ),
    exercise.translation(
      "a2-directions-transit-m3",
      "Dịch sang tiếng Anh: “Bạn cần chuyển sang tuyến màu xanh.”",
      "You need to transfer to the green line.",
      "a2-directions-transit-form",
    ),
    exercise.speaking(
      "a2-directions-transit-m4",
      "Chỉ đường trong 45 giây từ nhà bạn đến ga tàu gần nhất.",
      "a2-directions-transit-communication",
      "Go straight for one block and turn left at the corner. Walk past the park and cross the street. The station is next to the supermarket. It takes about ten minutes.",
      ["Có lộ trình rõ ràng", "Dùng mệnh lệnh và giới từ vị trí", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-directions-transit-m5",
      "Điền giới từ: “The museum is ______ from the station.”",
      "across",
      "grammar",
      "a2-directions-transit-comprehension",
    ),
  ],
  canDo: ["Có thể hỏi đường, hiểu lộ trình và hỏi lại khi chưa chắc."],
  spiralReview: ["A1: hỏi vị trí với Where is…?", "A2 Unit 4 bài 2: hỏi thông tin ở nhà ga bằng câu hỏi gián tiếp"],
  errorCategories: ["preposition", "word-order", "grammar-form", "missing-word"],
};

/* ------------------------------------------------------------------ *
 * Bài 3 — Mua hàng, đổi và trả sản phẩm
 * ------------------------------------------------------------------ */
const shoppingReturns: LessonSeed = {
  id: "a2-shopping-returns",
  unitId,
  number: 3,
  prerequisites: ["a2-directions-transit"],
  titleVi: "Mua hàng, đổi và trả sản phẩm",
  titleKo: "쇼핑, 교환과 환불",
  situationVi: "Linh mua áo nhưng size quá nhỏ, quay lại cửa hàng đổi và phát hiện khóa kéo bị hỏng.",
  situationKo: "린은 산 옷이 너무 작아서 가게에 다시 가서 교환하고, 지퍼가 고장 난 것을 발견해요.",
  objectives: [
    { id: "a2-shopping-returns-communication", en: "Exchange or return an item and explain the problem.", vi: "Đổi hoặc trả sản phẩm và giải thích vấn đề.", ko: "상품을 교환하거나 환불하고 문제를 설명할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-shopping-returns-form", en: "Use too, enough and adjectives to describe problems.", vi: "Dùng too, enough và tính từ để mô tả vấn đề.", ko: "too, enough와 형용사로 문제를 설명할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-shopping-returns-comprehension", en: "Understand shop rules about exchange and refunds.", vi: "Nghe hiểu quy định của cửa hàng về đổi và trả hàng.", ko: "가게의 교환과 환불 규정을 이해할 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "receipt", "hóa đơn", "영수증", "/rɪˈsiːt/", "reCEIPT", "neutral", ["keep the receipt", "do you have the receipt"]],
    ["v2", "exchange", "đổi hàng", "교환하다", "/ɪksˈtʃeɪndʒ/", "exCHANGE", "neutral", ["exchange a shirt", "exchange it for a larger size"]],
    ["v3", "refund", "hoàn tiền", "환불", "/ˈriːfʌnd/", "REfund", "neutral", ["ask for a refund", "a full refund"]],
    ["v4", "too small", "quá nhỏ", "너무 작다", "/tuː smɔːl/", "TOO SMALL", "neutral", ["too small for me", "a size too small"]],
    ["v5", "large enough", "đủ lớn", "충분히 크다", "/lɑːdʒ ɪˈnʌf/", "LARGE eNOUGH", "neutral", ["large enough for the table", "not large enough"]],
    ["v6", "damaged", "bị hỏng", "손상된", "/ˈdæmɪdʒd/", "DAMaged", "neutral", ["a damaged zipper", "arrived damaged"]],
    ["v7", "try it on", "thử đồ", "입어 보다", "/traɪ ɪt ɒn/", "try it ON", "casual", ["try it on in the shop", "can I try it on"]],
    ["v8", "in stock", "còn hàng", "재고가 있는", "/ɪn stɒk/", "in STOCK", "neutral", ["in stock in blue", "not in stock"]],
  ],
  dialogue: [
    ["Linh", "Hi, I’d like to exchange this shirt.", "Chào, tôi muốn đổi chiếc áo này.", "안녕하세요, 이 셔츠를 교환하고 싶어요.", "neutral"],
    ["Assistant", "Of course. What’s the problem?", "Tất nhiên. Vấn đề là gì ạ?", "물론이죠. 어떤 문제인가요?", "formal"],
    ["Linh", "It’s too small for me. The sleeves are also too short.", "Nó quá nhỏ với tôi. Tay áo cũng quá ngắn.", "저에게 너무 작아요. 소매도 너무 짧아요.", "neutral"],
    ["Assistant", "Do you have the receipt?", "Bạn có hóa đơn không?", "영수증 있으세요?", "formal"],
    ["Linh", "Yes, here it is. Do you have a larger size in stock?", "Có, đây ạ. Cửa hàng còn size lớn hơn không?", "네, 여기 있어요. 더 큰 사이즈 재고가 있나요?", "neutral"],
    ["Assistant", "We have a medium. You can try it on in the fitting room.", "Chúng tôi có size M. Bạn có thể thử ở phòng thử đồ.", "M 사이즈가 있어요. 탈의실에서 입어 보세요.", "formal"],
    ["Linh", "Thanks. One problem — the zipper on the new one is damaged.", "Cảm ơn. Có một vấn đề — khóa kéo của chiếc mới bị hỏng.", "감사합니다. 그런데 새 옷 지퍼가 고장 났어요.", "neutral"],
    ["Assistant", "I’m sorry about that. Let me look for another one.", "Tôi xin lỗi. Để tôi tìm chiếc khác.", "죄송합니다. 다른 것을 찾아 볼게요.", "formal"],
    ["Linh", "Could I get a refund instead if there isn’t one?", "Nếu không còn chiếc nào thì tôi có thể được hoàn tiền không?", "다른 게 없으면 환불받을 수 있을까요?", "neutral"],
    ["Assistant", "Yes, you can. Refunds take three to five days.", "Vâng, được. Hoàn tiền mất ba đến năm ngày.", "네, 가능해요. 환불은 3일에서 5일 정도 걸려요.", "formal"],
    ["Linh", "That’s fine. I’ll try the medium first.", "Không sao. Tôi sẽ thử size M trước.", "괜찮아요. 먼저 M 사이즈를 입어 볼게요.", "neutral"],
    ["Assistant", "Let me know if it’s large enough. I’ll wait here.", "Cho tôi biết nếu nó đủ rộng nhé. Tôi đợi ở đây.", "충분히 크면 알려 주세요. 여기서 기다릴게요.", "formal"],
  ],
  grammar: [
    {
      titleVi: "too và enough khi mô tả vấn đề",
      titleKo: "문제를 설명하는 too와 enough",
      explanationVi: "too + tính từ nghĩa là quá mức: “It’s too small.” enough đứng sau tính từ: “The sleeves aren’t long enough.” Muốn nói đủ thì dùng tính từ + enough, không dùng enough + tính từ.",
      explanationKo: "too + 형용사는 너무 심한 상태를 말해요. enough는 형용사 뒤에 와요. “long enough”가 맞고 “enough long”은 틀려요.",
      easierKorean: "너무 크면 too big, 충분히 크면 big enough예요.",
    },
    {
      titleVi: "Đổi và trả hàng: câu hỏi và điều kiện",
      titleKo: "교환과 환불의 질문과 조건",
      explanationVi: "Cấu trúc cần thiết: I’d like to exchange this…, Do you have a larger size in stock?, You can try it on…, Could I get a refund instead? Các câu này đều dùng động từ nguyên mẫu hoặc -ing đúng vị trí.",
      explanationKo: "교환할 때는 I’d like to exchange this…, 환불할 때는 Could I get a refund instead?를 써요. Can I try it on?처럼 부탁할 수 있어요.",
      easierKorean: "교환은 exchange, 환불은 refund, thử đồ là try it on이에요.",
    },
  ],
  examples: [
    ["I’d like to exchange this shirt.", "Tôi muốn đổi chiếc áo này.", "이 셔츠를 교환하고 싶어요.", "Câu mở đầu Linh nói ở quầy đổi trả."],
    ["It’s too small for me.", "Nó quá nhỏ với tôi.", "저에게 너무 작아요.", "Lý do chính Linh muốn đổi size."],
    ["Do you have a larger size in stock?", "Cửa hàng còn size lớn hơn không?", "더 큰 사이즈 재고가 있나요?", "Câu hỏi thiết thực trong cửa hàng."],
    ["You can try it on in the fitting room.", "Bạn có thể thử ở phòng thử đồ.", "탈의실에서 입어 볼 수 있어요.", "Nhân viên hướng dẫn Linh thử áo."],
    ["The sleeves aren’t long enough.", "Tay áo không đủ dài.", "소매가 충분히 길지 않아요.", "Vấn đề Linh nhận ra khi thử áo."],
    ["The zipper is damaged.", "Khóa kéo bị hỏng.", "지퍼가 고장 났어요.", "Lỗi của sản phẩm mới lấy từ kho."],
    ["Do you still have the receipt?", "Bạn còn giữ hóa đơn không?", "영수증을 아직 가지고 있나요?", "Câu hỏi điều kiện để đổi hàng."],
    ["Could I get a refund instead?", "Tôi có thể được hoàn tiền thay vào đó không?", "대신 환불받을 수 있을까요?", "Phương án Linh đề nghị nếu hết hàng."],
    ["I bought it here yesterday.", "Tôi mua nó ở đây hôm qua.", "어제 여기서 샀어요.", "Thông tin xác nhận thời điểm mua."],
    ["The color is different from the photo.", "Màu khác so với ảnh.", "사진과 색이 달라요.", "Lý do khách khác trong hàng đổi trả."],
    ["This pair fits much better.", "Đôi này vừa vặn hơn nhiều.", "이게 훨씬 잘 맞아요.", "Nhận xét của Linh sau khi thử size mới."],
    ["There is a small mark on the sleeve.", "Có một vết nhỏ ở tay áo.", "소매에 작은 얼룩이 있어요.", "Lỗi nhỏ Linh phát hiện trước khi mua."],
    ["We can exchange it at no extra cost.", "Chúng tôi có thể đổi mà không tính thêm phí.", "추가 비용 없이 교환해 드릴 수 있어요.", "Câu nhân viên nói để trấn an khách."],
    ["I’m sorry, that size is sold out.", "Xin lỗi, size đó đã hết hàng.", "죄송해요, 그 사이즈는 품절이에요.", "Thông tin buộc Linh phải chọn phương án khác."],
    ["Could you tell me when it will be back in stock?", "Bạn cho tôi biết khi nào có hàng lại được không?", "언제 다시 들어오는지 알려 주시겠어요?", "Câu hỏi trước khi quyết định chờ hàng."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-shopping-returns-listen",
      "Nghe câu “It’s too small for me. The sleeves are also too short.” và chọn vấn đề.",
      ["Áo quá nhỏ và tay áo quá ngắn.", "Áo quá rộng và tay áo quá dài.", "Áo bị hỏng khóa kéo."],
      "Áo quá nhỏ và tay áo quá ngắn.",
      "listening",
      "a2-shopping-returns-communication",
      "Chú ý hai lần dùng “too”.",
    ),
    exercise.dictation(
      "a2-shopping-returns-dictation",
      "Nghe và chép lại câu hỏi về hóa đơn.",
      "Do you still have the receipt?",
      "a2-shopping-returns-form",
    ),
  ],
  shadowing: {
    line: "It’s too small for me and the sleeves aren’t long enough.",
    notesVi: ["Nhấn mạnh “too small” và “long enough” vì đó là vấn đề.", "Ngắt nhẹ sau “me” giữa hai ý."],
    notesKo: ["“too small”과 “long enough”를 세게 말하면 문제가 분명해져요.", "“me” 뒤에서 잠깐 쉬어 두 문제를 나눠요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-shopping-returns-g1",
      "Chọn câu đúng.",
      ["The jacket isn’t warm enough.", "The jacket isn’t enough warm.", "The jacket isn’t too warm enough."],
      "The jacket isn’t warm enough.",
      "grammar",
      "a2-shopping-returns-form",
    ),
    exercise.translation(
      "a2-shopping-returns-g2",
      "Dịch sang tiếng Anh: “Cửa hàng còn size lớn hơn không?”",
      "Do you have a larger size in stock?",
      "a2-shopping-returns-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-shopping-returns-write",
      "Viết 5 câu mô tả một lần đổi hàng: vấn đề với too hoặc enough, một lỗi khác của sản phẩm, câu hỏi về size, câu hỏi về hoàn tiền và kết quả.",
      "a2-shopping-returns-communication",
      "I bought a shirt last week, but it’s too small for me. The sleeves aren’t long enough, and the zipper is damaged. Do you have a larger size in stock? Could I get a refund instead? In the end, I exchanged it for a medium and it fits well.",
      ["Có hai vấn đề được mô tả", "Có câu hỏi về size và hoàn tiền", "Có kết quả cuối cùng"],
    ),
    exercise.speaking(
      "a2-shopping-returns-speak",
      "Đóng vai ở quầy đổi trả trong 60 giây: nêu vấn đề, hỏi size khác, đề nghị hoàn tiền và xác nhận kết quả.",
      "a2-shopping-returns-communication",
      "I’d like to exchange this jacket. It’s too small and the sleeves aren’t long enough. Do you have a larger size in stock? Could I get a refund instead if it’s sold out? Yes, I have the receipt. Thank you for your help.",
      ["Có vấn đề, câu hỏi và kết quả", "Dùng too hoặc enough", "Giọng lịch sự, bình tĩnh"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-shopping-returns-m1",
      "Chọn câu đúng nghĩa “áo không đủ ấm”.",
      ["The jacket isn’t warm enough.", "The jacket isn’t too warm.", "The jacket is enough warm."],
      "The jacket isn’t warm enough.",
      "grammar",
      "a2-shopping-returns-form",
    ),
    exercise.dictation(
      "a2-shopping-returns-m2",
      "Nghe và chép lại lời đề nghị đổi hàng.",
      "I’d like to exchange this shirt.",
      "a2-shopping-returns-comprehension",
    ),
    exercise.translation(
      "a2-shopping-returns-m3",
      "Dịch sang tiếng Anh: “Tôi có thể được hoàn tiền thay vào đó không?”",
      "Could I get a refund instead?",
      "a2-shopping-returns-form",
    ),
    exercise.speaking(
      "a2-shopping-returns-m4",
      "Nói 45 giây về một sản phẩm bạn muốn đổi và lý do.",
      "a2-shopping-returns-communication",
      "I’d like to exchange these shoes. They’re too small for me, and the color is different from the photo. Do you have a larger size in stock? If not, could I get a refund?",
      ["Có hai lý do", "Có câu hỏi về đổi hoặc trả", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-shopping-returns-m5",
      "Điền “too” hoặc “enough”: “These trousers are ______ long for me.”",
      "too",
      "grammar",
      "a2-shopping-returns-comprehension",
    ),
  ],
  canDo: ["Có thể đổi hoặc trả hàng và giải thích vấn đề rõ ràng."],
  spiralReview: ["A1: mua sắm cơ bản và hỏi giá", "A2 Unit 2 bài 1: nhờ giúp đỡ lịch sự ở cửa hàng"],
  errorCategories: ["word-choice", "grammar-form", "missing-word", "preposition"],
};

/* ------------------------------------------------------------------ *
 * Bài 4 — Đặt và thay đổi cuộc hẹn
 * ------------------------------------------------------------------ */
const appointments: LessonSeed = {
  id: "a2-appointments",
  unitId,
  number: 4,
  prerequisites: ["a2-shopping-returns"],
  titleVi: "Đặt và thay đổi cuộc hẹn",
  titleKo: "약속 예약하고 변경하기",
  situationVi: "Linh đặt lịch cắt tóc, rồi phải đổi giờ vì họp kéo dài và đến muộn mười phút.",
  situationKo: "린은 미용실 예약을 했다가 회의가 길어져 시간을 바꾸고, 10분 늦게 도착해요.",
  objectives: [
    { id: "a2-appointments-communication", en: "Make, change and cancel an appointment.", vi: "Đặt, thay đổi và hủy một cuộc hẹn.", ko: "약속을 잡고, 바꾸고, 취소할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-appointments-form", en: "Suggest alternatives and confirm times.", vi: "Đề xuất phương án khác và xác nhận thời gian.", ko: "대안을 제안하고 시간을 확인할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-appointments-comprehension", en: "Catch dates, times and changes in an appointment call.", vi: "Nghe ra ngày, giờ và thay đổi trong một cuộc gọi đặt hẹn.", ko: "예약 통화에서 날짜, 시간, 변경 사항을 들을 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "make an appointment", "đặt lịch hẹn", "예약하다", "/meɪk ən əˈpɔɪntmənt/", "make an apPOINTment", "formal", ["make an appointment for a haircut", "make an appointment online"]],
    ["v2", "reschedule", "đổi lịch", "일정을 변경하다", "/ˌriːˈʃedjuːl/", "reSCHEDule", "formal", ["reschedule the appointment", "reschedule for Friday"]],
    ["v3", "available", "còn lịch, rảnh", "시간이 되는", "/əˈveɪləbl/", "aVAILable", "neutral", ["available on Thursday", "not available until four"]],
    ["v4", "Does Friday work?", "Thứ Sáu có được không?", "금요일 괜찮아요?", "/dʌz ˈfraɪdeɪ wɜːk/", "Does FRIday WORK", "neutral", ["Does Friday work for you", "Does two o’clock work"]],
    ["v5", "running late", "đến muộn", "늦고 있는", "/ˈrʌnɪŋ leɪt/", "RUNning LATE", "casual", ["I’m running late", "sorry, I’m running about ten minutes late"]],
    ["v6", "cancel", "hủy", "취소하다", "/ˈkænsl/", "CANcel", "neutral", ["cancel the appointment", "cancel without a fee"]],
    ["v7", "confirm", "xác nhận", "확인하다", "/kənˈfɜːm/", "conFIRM", "formal", ["confirm the date", "confirm by text"]],
    ["v8", "instead", "thay vào đó", "대신에", "/ɪnˈsted/", "inSTEAD", "neutral", ["morning instead", "Thursday instead"]],
  ],
  dialogue: [
    ["Receptionist", "Good morning. How can I help you?", "Chào buổi sáng. Tôi có thể giúp gì?", "안녕하세요. 무엇을 도와드릴까요?", "formal"],
    ["Linh", "I’d like to make an appointment for a haircut on Thursday.", "Tôi muốn đặt lịch cắt tóc vào thứ Năm.", "목요일에 머리 자르는 예약을 하고 싶어요.", "formal"],
    ["Receptionist", "We have three o’clock or five thirty. Which is better for you?", "Chúng tôi có ba giờ hoặc năm giờ ba mươi. Giờ nào tốt hơn cho bạn?", "3시와 5시 30분이 가능해요. 어느 쪽이 좋으세요?", "formal"],
    ["Linh", "Five thirty, please. Could you confirm the date by text?", "Năm giờ ba mươi ạ. Bạn xác nhận ngày qua tin nhắn được không?", "5시 30분으로 해 주세요. 문자로 날짜를 확인해 주시겠어요?", "neutral"],
    ["Receptionist", "Of course. So that’s Thursday the ninth at five thirty.", "Tất nhiên. Vậy là thứ Năm ngày mùng chín lúc năm giờ ba mươi.", "네. 그럼 9일 목요일 5시 30분이에요.", "formal"],
    ["Linh", "Actually, I’m afraid I need to reschedule.", "Thực ra, tiếc là tôi cần đổi lịch.", "사실 아쉽지만 일정을 바꿔야 해요.", "formal"],
    ["Receptionist", "That’s fine. When would you like to come instead?", "Không sao. Bạn muốn đến lúc nào thay vào đó?", "괜찮아요. 대신 언제 오고 싶으세요?", "formal"],
    ["Linh", "Would Friday morning work instead?", "Sáng thứ Sáu thay vào đó có được không?", "대신 금요일 오전은 어때요?", "neutral"],
    ["Receptionist", "We have ten fifteen on Friday. Does that work?", "Chúng tôi có mười giờ mười lăm thứ Sáu. Giờ đó được không?", "금요일 10시 15분이 가능해요. 괜찮으세요?", "formal"],
    ["Linh", "Yes, ten fifteen is perfect. I’m running about ten minutes late today, so thank you for changing it.", "Vâng, mười giờ mười lăm là tuyệt. Hôm nay tôi đến muộn khoảng mười phút, cảm ơn bạn đã đổi giúp.", "네, 10시 15분이 좋아요. 오늘은 10분 정도 늦을 것 같아서 바꿔 주셔서 고마워요.", "neutral"],
    ["Receptionist", "No problem. I’ve moved your appointment and sent a new confirmation.", "Không vấn đề gì. Tôi đã đổi lịch và gửi xác nhận mới.", "문제없어요. 예약을 옮기고 새 확인 메시지를 보냈어요.", "formal"],
    ["Linh", "Thank you. See you on Friday.", "Cảm ơn. Hẹn gặp thứ Sáu.", "감사합니다. 금요일에 뵐게요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "Đề xuất và xác nhận thời gian",
      titleKo: "시간을 제안하고 확인하기",
      explanationVi: "Does Friday work? / Does that work for you? là cách hỏi lịch rất thông dụng. Khi xác nhận, nhắc lại đầy đủ ngày và giờ: “So that’s Thursday the ninth at five thirty.”",
      explanationKo: "Does Friday work?는 시간이 괜찮은지 묻는 자연스러운 표현이에요. 확인할 때는 날짜와 시간을 다시 말해요.",
      easierKorean: "시간이 되는지 물을 때는 Does … work?를 써요.",
    },
    {
      titleVi: "instead và thay đổi lịch",
      titleKo: "instead와 일정 변경",
      explanationVi: "Khi đổi lịch, dùng I’d like to…, I’m afraid I need to reschedule và …instead: “Would Friday morning work instead?” instead đứng cuối cụm từ hoặc cuối câu.",
      explanationKo: "일정을 바꿀 때는 I’m afraid I need to reschedule.라고 하고 새 시간을 instead와 함께 말해요. instead는 보통 문장 끝에 와요.",
      easierKorean: "다른 시간을 제안할 때는 …instead를 문장 끝에 붙여요.",
    },
  ],
  examples: [
    ["I’d like to make an appointment for a haircut.", "Tôi muốn đặt lịch cắt tóc.", "머리 자르는 예약을 하고 싶어요.", "Câu mở đầu Linh nói khi gọi điện."],
    ["Are you available on Thursday afternoon?", "Chiều thứ Năm bạn có lịch trống không?", "목요일 오후에 시간이 되나요?", "Câu hỏi khi sắp xếp giờ hẹn."],
    ["I’m afraid I need to reschedule.", "Tiếc là tôi cần đổi lịch.", "아쉽지만 일정을 바꿔야 해요.", "Câu Linh nói khi họp kéo dài."],
    ["Would Friday morning work instead?", "Sáng thứ Sáu thay vào đó có được không?", "대신 금요일 오전은 어때요?", "Lời đề xuất thời gian mới."],
    ["I’m running about ten minutes late.", "Tôi đến muộn khoảng mười phút.", "10분 정도 늦을 것 같아요.", "Câu báo trước khi đến muộn."],
    ["Could we move it to three thirty?", "Chúng ta chuyển sang ba giờ ba mươi được không?", "3시 30분으로 옮길 수 있을까요?", "Lời đề nghị đổi giờ trong ngày."],
    ["Let me check the calendar.", "Để tôi kiểm tra lịch.", "일정을 확인해 볼게요.", "Câu nói trước khi trả lời chính xác."],
    ["There’s an opening at four.", "Có một chỗ trống lúc bốn giờ.", "4시에 빈 시간이 있어요.", "Thông tin lễ tân báo cho Linh."],
    ["That time works well for me.", "Giờ đó phù hợp với tôi.", "그 시간이 괜찮아요.", "Câu xác nhận sau khi nghe lựa chọn."],
    ["Could you confirm the date by text?", "Bạn xác nhận ngày qua tin nhắn được không?", "문자로 날짜를 확인해 주시겠어요?", "Yêu cầu tránh nhầm lẫn về ngày."],
    ["I need to cancel tomorrow’s appointment.", "Tôi cần hủy cuộc hẹn ngày mai.", "내일 예약을 취소해야 해요.", "Câu nói khi có việc đột xuất."],
    ["Is there anything available next week?", "Tuần sau còn lịch trống nào không?", "다음 주에 가능한 시간이 있나요?", "Câu hỏi khi cần dời xa hơn."],
    ["Tuesday at eleven is perfect.", "Thứ Ba lúc mười một giờ là tuyệt.", "화요일 11시가 딱 좋아요.", "Câu chốt thời gian cuối cùng."],
    ["Sorry, I misunderstood the time.", "Xin lỗi, tôi hiểu nhầm giờ.", "죄송해요, 시간을 잘못 이해했어요.", "Câu nói khi đến sai giờ."],
    ["So that’s Friday, May tenth, at nine.", "Vậy là thứ Sáu, ngày mười tháng Năm, lúc chín giờ.", "그럼 5월 10일 금요일 9시네요.", "Câu nhắc lại để xác nhận thông tin."],
    ["Thank you for changing it at short notice.", "Cảm ơn đã đổi giúp trong thời gian gấp.", "급하게 바꿔 주셔서 감사합니다.", "Câu cảm ơn khi phải đổi lịch muộn."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-appointments-listen",
      "Nghe câu “Would Friday morning work instead?” và chọn thời gian mới.",
      ["Sáng thứ Sáu.", "Sáng thứ Năm.", "Chiều thứ Sáu."],
      "Sáng thứ Sáu.",
      "listening",
      "a2-appointments-comprehension",
      "Chú ý “Friday morning”.",
    ),
    exercise.dictation(
      "a2-appointments-dictation",
      "Nghe và chép lại câu báo đến muộn.",
      "I’m running about ten minutes late.",
      "a2-appointments-form",
    ),
  ],
  shadowing: {
    line: "I’d like to make an appointment for Thursday afternoon.",
    notesVi: ["Nhấn nhẹ vào “Thursday afternoon” vì đó là thông tin chính.", "Đọc “make_an_appointment” thành một cụm liền."],
    notesKo: ["“Thursday afternoon”을 살짝 세게 말해요.", "“make an appointment”는 붙여서 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-appointments-g1",
      "Chọn câu hỏi tự nhiên nhất để hỏi lịch.",
      ["Does Friday work for you?", "Friday you work?", "Does Friday working?"],
      "Does Friday work for you?",
      "grammar",
      "a2-appointments-form",
    ),
    exercise.translation(
      "a2-appointments-g2",
      "Dịch sang tiếng Anh: “Tiếc là tôi cần đổi lịch.”",
      "I’m afraid I need to reschedule.",
      "a2-appointments-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-appointments-write",
      "Viết một tin nhắn 5 câu để đổi lịch hẹn: nêu lịch cũ, lý do, đề xuất hai thời gian mới, xác nhận và cảm ơn.",
      "a2-appointments-communication",
      "I have an appointment on Thursday at five thirty, but I’m afraid I need to reschedule. I have a meeting that afternoon. Would Friday morning work instead, or Monday at ten? Could you confirm the new time by text? Thank you for changing it.",
      ["Có lịch cũ và lý do", "Có hai thời gian đề xuất", "Có câu xác nhận và cảm ơn"],
    ),
    exercise.speaking(
      "a2-appointments-speak",
      "Gọi điện đổi lịch hẹn trong 60 giây: nêu lịch cũ, xin đổi, đề xuất giờ khác và xác nhận lại.",
      "a2-appointments-communication",
      "Hello, I have an appointment for a haircut on Thursday at five thirty. I’m afraid I need to reschedule because of a meeting. Would Friday morning work instead? Ten fifteen is perfect. Could you confirm the date by text?",
      ["Có lịch cũ và lý do", "Có đề xuất và xác nhận", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-appointments-m1",
      "Chọn câu đúng.",
      ["I’d like to make an appointment for Friday.", "I’d like make an appointment for Friday.", "I’d like making an appointment for Friday."],
      "I’d like to make an appointment for Friday.",
      "grammar",
      "a2-appointments-form",
    ),
    exercise.dictation(
      "a2-appointments-m2",
      "Nghe và chép lại câu chốt thời gian.",
      "So that’s Friday, May tenth, at nine.",
      "a2-appointments-comprehension",
    ),
    exercise.translation(
      "a2-appointments-m3",
      "Dịch sang tiếng Anh: “Tuần sau còn lịch trống nào không?”",
      "Is there anything available next week?",
      "a2-appointments-form",
    ),
    exercise.speaking(
      "a2-appointments-m4",
      "Đặt một cuộc hẹn trong 45 giây và xác nhận lại ngày giờ.",
      "a2-appointments-communication",
      "I’d like to make an appointment for next Tuesday. Does eleven o’clock work? Yes, that’s fine. So that’s Tuesday at eleven, and I’ll get a confirmation by text.",
      ["Có câu đặt lịch và xác nhận", "Có ngày và giờ cụ thể", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-appointments-m5",
      "Điền từ còn thiếu: “Could you confirm the date ______ text?”",
      "by",
      "grammar",
      "a2-appointments-comprehension",
    ),
  ],
  canDo: ["Có thể đặt, đổi và hủy một cuộc hẹn bằng tiếng Anh."],
  spiralReview: ["A2 Unit 1 bài 3: sắp xếp thời gian và xác nhận kế hoạch", "A2 Unit 2 bài 1: nhờ giúp đỡ lịch sự qua điện thoại"],
  errorCategories: ["grammar-form", "preposition", "word-choice", "missing-word"],
};

/* ------------------------------------------------------------------ *
 * Bài 5 — Ôn tập Unit 2 và nhiệm vụ một buổi chiều
 * ------------------------------------------------------------------ */
const unitMission: LessonSeed = {
  id: "a2-unit-2-mission",
  unitId,
  number: 5,
  prerequisites: ["a2-appointments"],
  titleVi: "Ôn tập và nhiệm vụ Unit 2",
  titleKo: "Unit 2 복습과 실전 과제",
  situationVi: "Trong một buổi chiều, Linh nhờ đồng nghiệp, hỏi đường, đổi hàng ở cửa hàng và đổi lịch hẹn.",
  situationKo: "한 오후 동안 린은 동료에게 도움을 부탁하고, 길을 묻고, 상품을 교환하고, 예약 시간을 바꿔요.",
  objectives: [
    { id: "a2-unit-2-mission-communication", en: "Complete several everyday tasks in one afternoon.", vi: "Hoàn thành nhiều việc thường ngày trong một buổi chiều.", ko: "한 오후에 여러 가지 일상 일을 처리할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-unit-2-mission-form", en: "Choose the right request, direction and time structures.", vi: "Chọn đúng cấu trúc để nhờ, chỉ đường và nói thời gian.", ko: "부탁, 길 안내, 시간 표현에서 알맞은 문법을 고를 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-unit-2-mission-comprehension", en: "Follow three short conversations with different purposes.", vi: "Nghe hiểu ba đoạn hội thoại ngắn với mục đích khác nhau.", ko: "목적이 다른 세 대화를 이해할 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["v1", "Could you…?", "Bạn có thể…?", "…해 주시겠어요?", "/kʊd juː/", "COULD you", "neutral", ["Could you help me", "Could you check this"]],
    ["v2", "first, then", "đầu tiên, sau đó", "먼저, 그다음", "/fɜːst ðen/", "FIRST, THEN", "neutral", ["first, then walk", "first, then transfer"]],
    ["v3", "across from", "đối diện", "맞은편", "/əˈkrɒs frɒm/", "aCROSS from", "neutral", ["across from the bank", "across from the exit"]],
    ["v4", "too late", "quá muộn", "너무 늦은", "/tuː leɪt/", "TOO LATE", "neutral", ["too late to change", "it’s too late now"]],
    ["v5", "enough time", "đủ thời gian", "충분한 시간", "/ɪˈnʌf taɪm/", "eNOUGH TIME", "neutral", ["enough time to finish", "not enough time"]],
    ["v6", "exchange", "đổi hàng", "교환", "/ɪksˈtʃeɪndʒ/", "exCHANGE", "neutral", ["make an exchange", "exchange a shirt"]],
    ["v7", "reschedule", "đổi lịch", "일정 변경", "/ˌriːˈʃedjuːl/", "reSCHEDule", "formal", ["reschedule the meeting", "reschedule for Friday"]],
    ["v8", "confirm", "xác nhận", "확인", "/kənˈfɜːm/", "conFIRM", "formal", ["confirm the time", "confirm by message"]],
  ],
  dialogue: [
    ["Linh", "Could you help me plan this afternoon?", "Bạn giúp tôi sắp xếp buổi chiều nay được không?", "오늘 오후 계획을 도와줄 수 있어요?", "neutral"],
    ["Tom", "Sure. What do you need to do?", "Được. Bạn cần làm gì?", "그럼요. 뭘 해야 해요?", "casual"],
    ["Linh", "First, I need to return this jacket to the shop.", "Đầu tiên, tôi cần trả chiếc áo khoác này ở cửa hàng.", "먼저 이 재킷을 가게에 반품해야 해요.", "neutral"],
    ["Tom", "The shop is across from the station. Take the number seven bus.", "Cửa hàng ở đối diện nhà ga. Bạn đi xe buýt số bảy.", "가게는 역 맞은편에 있어요. 7번 버스를 타세요.", "neutral"],
    ["Linh", "Then I need to go to the clinic, and I’m running late already.", "Sau đó tôi cần đến phòng khám, mà giờ tôi đã muộn rồi.", "그다음 병원에 가야 하는데 벌써 늦고 있어요.", "neutral"],
    ["Tom", "Do you have enough time for both?", "Bạn có đủ thời gian cho cả hai việc không?", "둘 다 할 시간이 충분해요?", "neutral"],
    ["Linh", "Maybe not. It’s too late to change the shop visit, but I can reschedule the clinic.", "Có lẽ không. Đổi lịch cửa hàng thì quá muộn, nhưng tôi có thể đổi lịch phòng khám.", "아마 부족해요. 가게 방문은 너무 늦었지만 병원은 바꿀 수 있어요.", "neutral"],
    ["Tom", "Then call the clinic first. Would ten o’clock tomorrow work?", "Vậy hãy gọi phòng khám trước. Mười giờ mai có được không?", "그럼 병원에 먼저 전화하세요. 내일 10시는 어때요?", "neutral"],
    ["Linh", "I’ll ask. Could you send me the bus number again?", "Tôi sẽ hỏi. Bạn nhắn lại số xe buýt giúp tôi được không?", "물어볼게요. 버스 번호를 다시 보내 줄 수 있어요?", "neutral"],
    ["Tom", "Number seven, and get off at Central.", "Số bảy, và xuống ở Central.", "7번이고, 센트럴에서 내려요.", "neutral"],
    ["Linh", "Thanks. Let’s confirm after I call the clinic.", "Cảm ơn. Sau khi gọi phòng khám chúng ta xác nhận nhé.", "고마워요. 병원에 전화한 뒤 확인해요.", "neutral"],
    ["Tom", "Good plan. Good luck!", "Kế hoạch tốt đấy. Chúc may mắn!", "좋은 계획이에요. 잘 다녀오세요!", "casual"],
  ],
  grammar: [
    {
      titleVi: "Chọn cấu trúc theo từng việc",
      titleKo: "일마다 맞는 문법 고르기",
      explanationVi: "Nhờ giúp: Could you…? / Would you mind -ing? Chỉ đường: mệnh lệnh + giới từ. Mô tả vấn đề: too, enough. Thời gian: Does… work? và instead. Đổi lịch: reschedule, confirm.",
      explanationKo: "도움 부탁은 Could you…?, 길 안내는 명령문, 문제 설명은 too와 enough, 시간은 Does… work?, 일정 변경은 reschedule과 confirm을 써요.",
      easierKorean: "부탁, 길 안내, 문제, 시간, 일정 변경 표현을 상황에 맞게 골라 써요.",
    },
  ],
  examples: [
    ["Could you help me plan this afternoon?", "Bạn giúp tôi sắp xếp buổi chiều nay được không?", "오늘 오후 계획을 도와줄 수 있어요?", "Câu mở đầu Linh nói với đồng nghiệp."],
    ["First, take the bus to the shopping center.", "Đầu tiên, đi xe buýt đến trung tâm mua sắm.", "먼저 버스를 타고 쇼핑센터에 가요.", "Bước đầu trong kế hoạch buổi chiều."],
    ["The return desk is across from the entrance.", "Quầy trả hàng ở đối diện lối vào.", "반품 데스크는 입구 맞은편에 있어요.", "Thông tin Tom đưa khi hướng dẫn."],
    ["I need to exchange a damaged item.", "Tôi cần đổi một món bị hỏng.", "고장 난 물건을 교환해야 해요.", "Việc đầu tiên Linh làm ở cửa hàng."],
    ["This size is too small.", "Size này quá nhỏ.", "이 사이즈는 너무 작아요.", "Vấn đề Linh nói với nhân viên bán hàng."],
    ["Then call the clinic to reschedule.", "Sau đó gọi phòng khám để đổi lịch.", "그다음 병원에 전화해서 일정을 바꿔요.", "Bước thứ hai trong kế hoạch."],
    ["Would five o’clock work instead?", "Năm giờ thay vào đó có được không?", "대신 5시는 어때요?", "Lời đề xuất giờ mới cho cuộc hẹn."],
    ["That gives me enough time.", "Như vậy tôi có đủ thời gian.", "그러면 시간이 충분해요.", "Lý do Linh chọn giờ mới."],
    ["Could you confirm the new appointment?", "Bạn xác nhận cuộc hẹn mới được không?", "새 예약을 확인해 주시겠어요?", "Câu hỏi cuối trong cuộc gọi."],
    ["Which stop should I get off at?", "Tôi nên xuống ở bến nào?", "어느 정류장에서 내려야 해요?", "Câu hỏi khi đi xe buýt lần đầu."],
    ["Go past the library and turn right.", "Đi qua thư viện rồi rẽ phải.", "도서관을 지나서 오른쪽으로 도세요.", "Chỉ dẫn chi tiết trên đường."],
    ["Do I need the receipt for a refund?", "Tôi có cần hóa đơn để hoàn tiền không?", "환불받으려면 영수증이 필요한가요?", "Câu hỏi ở quầy trả hàng."],
    ["I’m running late, but I’ll be there soon.", "Tôi đến muộn, nhưng sẽ có mặt sớm.", "늦고 있지만 곧 도착할게요.", "Tin nhắn Linh gửi cho lễ tân."],
    ["Thanks for helping me sort everything out.", "Cảm ơn đã giúp tôi sắp xếp mọi việc.", "모든 일을 정리하도록 도와줘서 고마워요.", "Câu cảm ơn khi kết thúc buổi chiều bận rộn."],
    ["In the end, I finished all four tasks.", "Cuối cùng, tôi hoàn thành cả bốn việc.", "결국 네 가지 일을 다 끝냈어요.", "Câu kết Linh nói khi kể lại buổi chiều."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-unit-2-mission-listen",
      "Nghe câu “Number seven, and get off at Central.” và chọn tuyến xe buýt.",
      ["Xe buýt số bảy.", "Xe buýt số mười một.", "Xe buýt số mười bảy."],
      "Xe buýt số bảy.",
      "listening",
      "a2-unit-2-mission-communication",
      "Số tuyến nằm ở đầu câu.",
    ),
    exercise.dictation(
      "a2-unit-2-mission-dictation",
      "Nghe và chép lại câu hỏi về bến xuống.",
      "Which stop should I get off at?",
      "a2-unit-2-mission-form",
    ),
  ],
  shadowing: {
    line: "It’s too late to change the shop visit, but I can reschedule the clinic.",
    notesVi: ["Ngắt rõ sau “visit” để tách hai vế đối lập.", "Đọc “reschedule the clinic” liền mạch."],
    notesKo: ["“visit” 뒤에서 쉬면 두 내용이 분명해져요.", "“reschedule the clinic”은 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-unit-2-mission-g1",
      "Chọn câu phù hợp khi bạn cần đổi lịch hẹn.",
      ["I’m afraid I need to reschedule.", "I’m afraid I need reschedule.", "I need to rescheduling."],
      "I’m afraid I need to reschedule.",
      "grammar",
      "a2-unit-2-mission-form",
    ),
    exercise.translation(
      "a2-unit-2-mission-g2",
      "Dịch sang tiếng Anh: “Như vậy tôi có đủ thời gian.”",
      "That gives me enough time.",
      "a2-unit-2-mission-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-unit-2-mission-write",
      "Viết kế hoạch 6–7 câu cho một buổi chiều có bốn việc: một việc nhờ người khác, một việc cần đi lại, một việc đổi trả và một cuộc hẹn cần xác nhận.",
      "a2-unit-2-mission-communication",
      "This afternoon I have four things to do. First, I’ll ask my colleague to check the report. Then I need to go to the shop to exchange a jacket that is too small. The shop is across from the station. After that, I’ll call the clinic to reschedule my appointment for Friday. Could you confirm the new time by text? In the end, everything should be finished by six.",
      ["Có bốn việc với thứ tự rõ ràng", "Dùng ít nhất ba cấu trúc của Unit 2", "Có câu xác nhận"],
    ),
    exercise.speaking(
      "a2-unit-2-mission-speak",
      "Nói 90 giây về một buổi chiều có bốn việc: nhờ giúp, đi lại, đổi trả và đổi lịch hẹn.",
      "a2-unit-2-mission-communication",
      "This afternoon I need to do four things. Could you help me check the report? Then I’ll take the number seven bus to the shopping center because the shop is across from the station. I need to exchange a jacket that is too small. After that, I’ll reschedule my clinic appointment and confirm the new time by text.",
      ["Đủ bốn việc theo thứ tự", "Dùng lời nhờ, chỉ đường và đổi lịch", "Tự đánh giá và ghi một điểm cần sửa"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-unit-2-mission-m1",
      "Chọn câu đúng nghĩa “Cửa hàng ở đối diện nhà ga.”",
      ["The shop is across from the station.", "The shop is next the station.", "The shop is across the station from."],
      "The shop is across from the station.",
      "grammar",
      "a2-unit-2-mission-form",
    ),
    exercise.dictation(
      "a2-unit-2-mission-m2",
      "Nghe và chép lại lời đề xuất giờ mới.",
      "Would five o’clock work instead?",
      "a2-unit-2-mission-comprehension",
    ),
    exercise.translation(
      "a2-unit-2-mission-m3",
      "Dịch sang tiếng Anh: “Tôi cần đổi một món bị hỏng.”",
      "I need to exchange a damaged item.",
      "a2-unit-2-mission-form",
    ),
    exercise.speaking(
      "a2-unit-2-mission-m4",
      "Trình bày kế hoạch buổi chiều trong 90 giây với bốn việc khác nhau.",
      "a2-unit-2-mission-communication",
      "I have four things to do this afternoon. First, I’ll ask my colleague for help with the report. Then I’ll go to the shop to exchange a jacket, and the shop is across from the station. After that, I’ll reschedule my appointment. Finally, I’ll confirm everything by message.",
      ["Có bốn việc và thứ tự", "Dùng ba cấu trúc trọng tâm", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-unit-2-mission-m5",
      "Điền “late” hoặc “enough”: “It’s too ______ to change the booking now.”",
      "late",
      "grammar",
      "a2-unit-2-mission-comprehension",
    ),
  ],
  canDo: ["Có thể xử lý nhiều việc thường ngày trong cùng một buổi bằng tiếng Anh."],
  spiralReview: ["A1: số đếm, giờ và phương tiện", "A2 Unit 1: sắp xếp kế hoạch và phản hồi lời mời"],
  errorCategories: ["grammar-form", "preposition", "word-choice", "register"],
};

export const a2Unit2 = bilingualUnitSchema.parse({
  id: unitId,
  level: "A2",
  titleVi: "Hoàn thành việc cần làm",
  titleKo: "일 처리하기",
  lessons: [politeRequests, directionsTransit, shoppingReturns, appointments, unitMission].map(buildLesson),
});
