import { bilingualUnitSchema } from "@/lib/curriculum/bilingual-schema";
import { buildLesson, exercise, type LessonSeed } from "./a2-lesson-factory";

const unitId = "a2-4-travel-problems";

/* ------------------------------------------------------------------ *
 * Bài 1 — Lên kế hoạch cho chuyến đi
 * ------------------------------------------------------------------ */
const tripPlans: LessonSeed = {
  id: "a2-trip-plans",
  unitId,
  number: 1,
  prerequisites: ["a2-complete-story"],
  titleVi: "Lên kế hoạch cho chuyến đi",
  titleKo: "여행 계획 세우기",
  situationVi: "Linh và Sora chốt lịch trình bốn ngày ở Đà Nẵng: ngày đi, chỗ ở, ngân sách và một buổi tham quan.",
  situationKo: "린과 소라는 다낭 4일 일정을 정해요. 출발 날짜, 숙소, 예산, 관광 일정까지 함께 확인해요.",
  objectives: [
    { id: "a2-trip-plans-communicate", en: "Agree on a trip plan with another person.", vi: "Cùng người khác thống nhất kế hoạch cho một chuyến đi.", ko: "다른 사람과 함께 여행 계획을 정할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-trip-plans-form", en: "Use be going to and the present continuous for plans.", vi: "Dùng be going to và thì hiện tại tiếp diễn để nói về kế hoạch.", ko: "be going to와 현재진행형으로 계획을 말할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-trip-plans-comprehension", en: "Catch dates, times and prices in a booking conversation.", vi: "Nghe được ngày, giờ và giá trong một cuộc trao đổi đặt chỗ.", ko: "예약 대화에서 날짜, 시간, 가격을 들을 수 있어요.", skills: ["listening", "writing"] },
  ],
  vocab: [
    ["itinerary", "itinerary", "lịch trình chuyến đi", "여행 일정", "/aɪˈtɪnərəri/", "iTINerary", "neutral", ["a detailed itinerary", "plan the itinerary"]],
    ["book", "book a flight", "đặt vé máy bay", "항공권을 예약하다", "/bʊk/", "BOOK", "neutral", ["book a flight", "book online"]],
    ["accommodation", "accommodation", "chỗ ở", "숙소", "/əˌkɒməˈdeɪʃn/", "aCCOMmodation", "formal", ["find accommodation", "book accommodation"]],
    ["departure", "departure time", "giờ khởi hành", "출발 시간", "/dɪˈpɑːtʃə(r)/", "dePARTure", "neutral", ["departure time", "a late departure"]],
    ["return", "return ticket", "vé khứ hồi", "왕복표", "/rɪˈtɜːn ˈtɪkɪt/", "reTURN TICKet", "neutral", ["a return ticket", "a return flight"]],
    ["check-in", "check in online", "làm thủ tục trực tuyến", "온라인으로 체크인하다", "/tʃek ɪn/", "check IN", "neutral", ["check in online", "check in at the desk"]],
    ["pack", "pack a suitcase", "xếp hành lý vào vali", "가방을 싸다", "/pæk/", "PACK", "casual", ["pack a suitcase", "pack light"]],
    ["budget", "budget trip", "chuyến đi tiết kiệm", "저예산 여행", "/ˈbʌdʒɪt/", "BUDGet", "neutral", ["on a budget", "a travel budget"]],
    ["sightseeing", "go sightseeing", "đi tham quan", "관광하다", "/ˈsaɪtsiːɪŋ/", "SIGHTseeing", "neutral", ["go sightseeing", "a sightseeing tour"]],
    ["confirm", "confirm the booking", "xác nhận việc đặt chỗ", "예약을 확정하다", "/kənˈfɜːm/", "conFIRM", "formal", ["confirm the booking", "confirm by email"]],
  ],
  dialogue: [
    ["Linh", "Have you decided when we’re going to Da Nang?", "Bạn đã quyết định khi nào chúng ta đi Đà Nẵng chưa?", "다낭에 언제 갈지 정했어요?", "casual"],
    ["Sora", "Yes, we’re flying on the evening of the twelfth.", "Rồi, chúng ta bay tối ngày mười hai.", "네, 12일 저녁 비행기로 가요.", "casual"],
    ["Linh", "Perfect. I’m going to look for a hotel near My Khe beach tonight.", "Tuyệt. Tối nay tôi sẽ tìm khách sạn gần biển Mỹ Khê.", "좋아요. 오늘 밤에 미케 해변 근처 호텔을 찾을 거예요.", "casual"],
    ["Sora", "How much can we spend on accommodation?", "Chúng ta có thể chi bao nhiêu cho chỗ ở?", "숙소에 얼마까지 쓸 수 있어요?", "neutral"],
    ["Linh", "About two million dong a night. We’re meeting the agent at ten tomorrow, so I’ll ask her then.", "Khoảng hai triệu đồng một đêm. Mai chúng ta gặp nhân viên lúc mười giờ, nên tôi sẽ hỏi cô ấy.", "1박에 200만 동 정도요. 내일 10시에 직원을 만나니까 그때 물어볼게요.", "neutral"],
    ["Sora", "Good idea. Shall we book a sightseeing tour as well?", "Ý hay đấy. Chúng ta có đặt luôn tour tham quan không?", "좋은 생각이에요. 관광 투어도 예약할까요?", "neutral"],
    ["Linh", "Let’s decide after we check the weather. If it rains, we’re staying in the city.", "Hãy quyết định sau khi xem thời tiết. Nếu mưa, chúng ta ở lại thành phố.", "날씨를 보고 정해요. 비가 오면 시내에 있을 거예요.", "casual"],
    ["Sora", "Fine with me. I’ll confirm the flights and send you the itinerary.", "Tôi đồng ý. Tôi sẽ xác nhận chuyến bay và gửi bạn lịch trình.", "좋아요. 항공편을 확정하고 일정표를 보내 줄게요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "be going to cho kế hoạch đã định",
      titleKo: "이미 정한 계획의 be going to",
      explanationVi: "Khi bạn đã quyết định làm gì đó trước lúc nói, dùng be going to + động từ nguyên mẫu: “I’m going to look for a hotel.” Trạng từ thời gian như tonight, next week, on Friday cho biết kế hoạch đó chưa xảy ra.",
      explanationKo: "말하기 전에 이미 마음먹은 일은 be going to + 동사원형으로 말해요. tonight, next week처럼 앞으로의 시간 표현과 함께 씁니다.",
      easierKorean: "미리 정한 일은 am/is/are going to를 써요.",
    },
    {
      titleVi: "Hiện tại tiếp diễn cho lịch hẹn đã chốt",
      titleKo: "확정된 약속의 현재진행형",
      explanationVi: "Với lịch đã ghi trong lịch và có người khác cùng tham gia, tiếng Anh hay dùng hiện tại tiếp diễn: “We’re flying on the evening of the twelfth.” Câu này không phải hành động đang diễn ra mà là một lịch đã chốt.",
      explanationKo: "날짜와 시간이 정해져 있고 다른 사람과 함께하는 일정은 현재진행형으로 말해요. 지금 하고 있다는 뜻이 아니라 확정된 약속이라는 뜻이에요.",
      easierKorean: "정해진 약속은 am/is/are + -ing로 말해요.",
    },
  ],
  examples: [
    ["I’m going to book the flight tonight.", "Tối nay tôi sẽ đặt vé máy bay.", "오늘 밤에 항공권을 예약할 거예요.", "Linh nói với Sora sau khi xem giá vé trên mạng."],
    ["We’re flying on the evening of the twelfth.", "Chúng ta bay vào tối ngày mười hai.", "우리는 12일 저녁에 비행기를 타요.", "Hai người chốt ngày bay trong tin nhắn."],
    ["She’s meeting the travel agent at ten tomorrow.", "Mai cô ấy gặp nhân viên du lịch lúc mười giờ.", "그녀는 내일 10시에 여행사 직원을 만나요.", "Lịch hẹn đã có trong điện thoại của Linh."],
    ["Are you going to take a suitcase or a backpack?", "Bạn định mang vali hay ba lô?", "가방은 캐리어로 갈까요, 배낭으로 갈까요?", "Sora hỏi khi cả hai xếp hành lý."],
    ["I’m going to pack light because we’re moving hotels.", "Tôi sẽ xếp ít đồ thôi vì chúng ta đổi khách sạn.", "호텔을 옮기니까 짐을 가볍게 쌀 거예요.", "Linh giải thích lý do chỉ mang một túi nhỏ."],
    ["How much are we going to spend on accommodation?", "Chúng ta định chi bao nhiêu cho chỗ ở?", "숙소에 얼마를 쓸 생각이에요?", "Hai người bàn ngân sách cho bốn đêm."],
    ["We’re staying near My Khe beach for two nights.", "Chúng ta ở gần biển Mỹ Khê hai đêm.", "미케 해변 근처에서 이틀 묵어요.", "Thông tin này đã có trong lịch trình gửi qua email."],
    ["They’re visiting Hoi An on Saturday.", "Họ sẽ đi Hội An vào thứ Bảy.", "그들은 토요일에 호이안을 방문해요.", "Kế hoạch tham quan trong ngày thứ ba của chuyến đi."],
    ["Is the price of the tour included?", "Giá tour đã bao gồm chưa?", "투어 가격이 포함되어 있나요?", "Câu hỏi khi đọc bảng giá tour tham quan."],
    ["The booking is confirmed for four nights.", "Việc đặt phòng đã được xác nhận cho bốn đêm.", "예약은 4박으로 확정되었어요.", "Linh đọc lại email xác nhận của khách sạn."],
    ["I’ll check the weather app before we decide.", "Tôi sẽ xem ứng dụng thời tiết trước khi chúng ta quyết định.", "결정하기 전에 날씨 앱을 확인할게요.", "Sora đưa ra cách quyết định tour tham quan."],
    ["We don’t have to book the tour today.", "Chúng ta không cần đặt tour hôm nay.", "오늘 투어를 예약하지 않아도 돼요.", "Linh trấn an Sora vì tour vẫn còn chỗ."],
    ["What time are you leaving on the last day?", "Ngày cuối bạn đi lúc mấy giờ?", "마지막 날에 몇 시에 출발해요?", "Câu hỏi của Sora khi sắp xếp xe ra sân bay."],
    ["Our flight leaves at six forty in the morning.", "Chuyến bay của chúng ta khởi hành lúc sáu giờ bốn mươi sáng.", "우리 비행기는 아침 6시 40분에 출발해요.", "Thông tin trên vé điện tử hiện trong ứng dụng."],
    ["Let’s write the itinerary in one note.", "Hãy viết lịch trình vào một ghi chú thôi.", "일정은 메모 하나에 정리해요.", "Hai người thống nhất cách chia sẻ thông tin trước khi đi."],
    ["I’ve already put the hotel address in the note.", "Tôi đã để địa chỉ khách sạn vào ghi chú rồi.", "메모에 호텔 주소를 이미 넣어 두었어요.", "Linh cập nhật ghi chú chung sau khi đặt phòng."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-trip-plans-listen-mc",
      "Nghe câu “We’re flying on the evening of the twelfth.” và chọn thông tin đúng.",
      ["Chuyến bay đi vào tối ngày mười hai.", "Chuyến bay đi vào sáng ngày hai mươi.", "Hai người chưa chọn ngày bay."],
      "Chuyến bay đi vào tối ngày mười hai.",
      "listening",
      "a2-trip-plans-comprehension",
      "Chú ý cụm “on the evening of”.",
    ),
    exercise.dictation(
      "a2-trip-plans-listen-dictation",
      "Nghe và chép lại câu về lịch hẹn với nhân viên du lịch.",
      "She’s meeting the travel agent at ten tomorrow.",
      "a2-trip-plans-comprehension",
    ),
  ],
  shadowing: {
    line: "We’re staying near My Khe beach for two nights.",
    notesVi: ["Nhấn nhẹ vào “two nights” vì đó là thông tin quan trọng.", "Nối “staying_near” thành một cụm, không ngắt giữa hai từ."],
    notesKo: ["“two nights”를 조금 길게 말하면 정보가 분명해져요.", "“staying near”는 끊지 말고 이어서 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-trip-plans-guided-mc",
      "Chọn câu nói đúng về một kế hoạch đã quyết định từ trước.",
      ["I’m going to book the hotel tonight.", "I book the hotel tonight.", "I’m book the hotel tonight."],
      "I’m going to book the hotel tonight.",
      "grammar",
      "a2-trip-plans-form",
    ),
    exercise.arrange(
      "a2-trip-plans-guided-arrange",
      "Sắp xếp các từ thành câu hỏi về thời gian bay.",
      ["What", "time", "are", "you", "leaving", "?"],
      "What time are you leaving ?",
      "a2-trip-plans-form",
    ),
    exercise.fillBlank(
      "a2-trip-plans-guided-blank",
      "Điền dạng đúng: “We ______ (stay) in a small hotel for three nights.”",
      "are staying",
      "grammar",
      "a2-trip-plans-form",
      "Đây là lịch đã chốt với khách sạn.",
    ),
    exercise.translation(
      "a2-trip-plans-guided-translate",
      "Dịch sang tiếng Anh: “Chúng tôi sẽ ở gần biển hai đêm.”",
      "We’re staying near the beach for two nights.",
      "a2-trip-plans-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-trip-plans-production-write",
      "Viết lịch trình bốn ngày cho chuyến đi của bạn: ngày đi, phương tiện, chỗ ở, ngân sách và một hoạt động tham quan. Dùng ít nhất hai câu với be going to và một câu với hiện tại tiếp diễn.",
      "a2-trip-plans-communicate",
      "We’re flying to Da Nang on Friday evening. I’m going to book a hotel near the beach for two nights, and we’re meeting a friend on Saturday morning. The budget is about two million dong a night.",
      ["Có ngày và phương tiện cụ thể", "Có chỗ ở và ngân sách", "Dùng đúng be going to và hiện tại tiếp diễn"],
    ),
    exercise.speaking(
      "a2-trip-plans-production-speak",
      "Nói 45–60 giây để thống nhất kế hoạch với một người bạn: đề xuất ngày đi, hỏi ý kiến và chốt lại lịch trình.",
      "a2-trip-plans-communicate",
      "Are you free on the twelfth? We could fly in the evening. I’m going to look for a hotel near the beach, and we’re meeting the agent at ten tomorrow. Does that work for you?",
      ["Có lời đề xuất, câu hỏi và câu chốt", "Dùng ngôn ngữ A2, câu ngắn rõ ý", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-trip-plans-mastery-mc",
      "Chọn câu phù hợp nhất khi bạn đã quyết định đặt khách sạn tối nay.",
      ["I’m going to book a hotel tonight.", "I booked a hotel tonight tomorrow.", "I am book a hotel tonight."],
      "I’m going to book a hotel tonight.",
      "grammar",
      "a2-trip-plans-form",
    ),
    exercise.fillBlank(
      "a2-trip-plans-mastery-blank",
      "Điền trợ động từ còn thiếu: “______ you going to take a suitcase?”",
      "Are",
      "grammar",
      "a2-trip-plans-form",
    ),
    exercise.dictation(
      "a2-trip-plans-mastery-dictation",
      "Nghe và chép lại câu xác nhận việc đặt phòng.",
      "The booking is confirmed for four nights.",
      "a2-trip-plans-comprehension",
    ),
    exercise.translation(
      "a2-trip-plans-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi sẽ xếp hành lý tối nay.”",
      "I’m going to pack my suitcase tonight.",
      "a2-trip-plans-form",
    ),
    exercise.speaking(
      "a2-trip-plans-mastery-speak",
      "Trình bày kế hoạch chuyến đi trong 60 giây: ngày đi, chỗ ở, ngân sách và một hoạt động.",
      "a2-trip-plans-communicate",
      "We’re flying on Friday evening and staying near the beach for two nights. I’m going to book the hotel tonight because the price is good. On Saturday we’re going sightseeing in Hoi An.",
      ["Đủ bốn thông tin", "Câu nói rõ, không đọc lại giấy", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể cùng người khác thống nhất một kế hoạch chuyến đi bằng tiếng Anh."],
  spiralReview: ["A1: ngày tháng, giờ và con số", "A2 Unit 1: sắp xếp lịch hẹn và xác nhận kế hoạch"],
  errorCategories: ["word-choice", "grammar-form", "missing-word", "word-order"],
};

/* ------------------------------------------------------------------ *
 * Bài 2 — Làm thủ tục ở sân bay và nhà ga
 * ------------------------------------------------------------------ */
const airportStation: LessonSeed = {
  id: "a2-airport-station",
  unitId,
  number: 2,
  prerequisites: ["a2-trip-plans"],
  titleVi: "Làm thủ tục ở sân bay và nhà ga",
  titleKo: "공항과 기차역에서 수속하기",
  situationVi: "Sora làm thủ tục và hỏi thông tin ở sân bay, sau đó tìm sân ga đúng cho chuyến tàu tiếp theo.",
  situationKo: "소라는 공항에서 수속하고 정보를 물어본 뒤, 다음 기차를 타러 맞는 승강장을 찾아요.",
  objectives: [
    { id: "a2-airport-station-communicate", en: "Check in and ask for information at an airport or station.", vi: "Làm thủ tục và hỏi thông tin ở sân bay hoặc nhà ga.", ko: "공항이나 역에서 수속하고 정보를 물어볼 수 있어요.", skills: ["speaking", "listening"] },
    { id: "a2-airport-station-form", en: "Use have to, must and don’t have to for rules.", vi: "Dùng have to, must và don’t have to để nói về quy định.", ko: "have to, must, don’t have to로 규칙을 말할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-airport-station-ask", en: "Ask indirect questions politely.", vi: "Đặt câu hỏi gián tiếp một cách lịch sự.", ko: "간접의문문으로 정중하게 물어볼 수 있어요.", skills: ["speaking", "grammar"] },
  ],
  vocab: [
    ["boarding-pass", "boarding pass", "thẻ lên máy bay", "탑승권", "/ˈbɔːdɪŋ pɑːs/", "BOARDing pass", "neutral", ["show your boarding pass", "print the boarding pass"]],
    ["check-in-desk", "check-in desk", "quầy làm thủ tục", "체크인 카운터", "/ˈtʃek ɪn desk/", "CHECK-in desk", "neutral", ["go to the check-in desk", "a long queue at the check-in desk"]],
    ["gate", "departure gate", "cổng khởi hành", "탑승구", "/ɡeɪt/", "GATE", "neutral", ["the gate closes at", "go to gate twelve"]],
    ["carry-on", "carry-on bag", "túi xách tay", "기내 가방", "/ˈkæri ɒn bæɡ/", "CARRy-on bag", "neutral", ["one carry-on bag", "a heavy carry-on bag"]],
    ["luggage", "checked luggage", "hành lý ký gửi", "위탁 수하물", "/ˈlʌɡɪdʒ/", "LUGgage", "neutral", ["checked luggage", "collect your luggage"]],
    ["platform", "platform", "sân ga", "승강장", "/ˈplætfɔːm/", "PLATform", "neutral", ["platform six", "on platform two"]],
    ["delay", "a two-hour delay", "sự chậm hai giờ", "두 시간 지연", "/dɪˈleɪ/", "deLAY", "neutral", ["a long delay", "because of the delay"]],
    ["customs", "go through customs", "làm thủ tục hải quan", "세관을 통과하다", "/ˈkʌstəmz/", "CUS-toms", "neutral", ["go through customs", "customs control"]],
    ["security", "security check", "kiểm tra an ninh", "보안 검색", "/sɪˈkjʊərəti tʃek/", "seCURity check", "neutral", ["the security check", "at security"]],
    ["passport", "passport control", "kiểm soát hộ chiếu", "여권 심사", "/ˈpɑːspɔːt kənˈtrəʊl/", "PASSport conTROL", "formal", ["passport control", "show your passport"]],
  ],
  dialogue: [
    ["Agent", "Good morning. May I see your passport and booking reference?", "Chào buổi sáng. Cho tôi xem hộ chiếu và mã đặt chỗ của bạn được không?", "안녕하세요. 여권과 예약 번호를 보여 주시겠어요?", "formal"],
    ["Sora", "Here you are. I’m flying to Da Nang with one stop.", "Đây ạ. Tôi bay đến Đà Nẵng và quá cảnh một điểm.", "여기 있습니다. 다낭까지 한 번 환승해요.", "neutral"],
    ["Agent", "Thank you. Do you have any checked luggage?", "Cảm ơn. Bạn có hành lý ký gửi không?", "감사합니다. 위탁 수하물이 있나요?", "formal"],
    ["Sora", "Just one bag. Do I have to take my laptop out at security?", "Chỉ một túi thôi. Tôi có phải lấy máy tính ra ở chỗ kiểm tra an ninh không?", "가방 하나뿐이에요. 보안 검색에서 노트북을 꺼내야 하나요?", "neutral"],
    ["Agent", "Yes, you have to, but you don’t have to remove your shoes.", "Vâng, bạn phải lấy ra, nhưng không cần cởi giày.", "네, 꺼내야 하지만 신발은 벗지 않아도 돼요.", "formal"],
    ["Sora", "Could you tell me where gate twelve is?", "Bạn có thể cho tôi biết cổng mười hai ở đâu không?", "12번 탑승구가 어디인지 알려 주시겠어요?", "formal"],
    ["Agent", "It’s on the second floor, next to the coffee shop. Boarding starts at nine forty.", "Ở tầng hai, cạnh quán cà phê. Bắt đầu lên máy bay lúc chín giờ bốn mươi.", "2층 커피숍 옆에 있어요. 탑승은 9시 40분에 시작해요.", "formal"],
    ["Sora", "Thank you. Do you know if the flight is on time?", "Cảm ơn. Bạn có biết chuyến bay có đúng giờ không?", "감사합니다. 비행기가 정시에 출발하는지 아세요?", "neutral"],
    ["Agent", "There’s a short delay of twenty minutes, but the gate hasn’t changed.", "Có chậm khoảng hai mươi phút, nhưng cổng không thay đổi.", "20분 정도 지연되지만 탑승구는 바뀌지 않았어요.", "formal"],
    ["Sora", "That’s fine. Thanks for your help.", "Không sao. Cảm ơn bạn đã giúp.", "괜찮아요. 도와주셔서 감사합니다.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "have to, must và don’t have to",
      titleKo: "have to, must, don’t have to",
      explanationVi: "have to và must đều nói về việc bắt buộc: “You have to take your laptop out.” don’t have to nghĩa là không cần thiết, không phải là cấm: “You don’t have to remove your shoes.” Muốn nói bị cấm thì dùng mustn’t.",
      explanationKo: "have to와 must는 꼭 해야 하는 일을 말해요. don’t have to는 하지 않아도 된다는 뜻이고, 금지할 때는 mustn’t를 써요.",
      easierKorean: "꼭 해야 하면 have to, 안 해도 되면 don’t have to예요.",
    },
    {
      titleVi: "Câu hỏi gián tiếp cơ bản",
      titleKo: "기본 간접의문문",
      explanationVi: "Câu hỏi gián tiếp mở đầu bằng Could you tell me…? hoặc Do you know…? Sau đó dùng trật tự câu kể, không dùng trợ động từ: “Could you tell me where gate twelve is?” chứ không phải “where is gate twelve”.",
      explanationKo: "간접의문문은 Could you tell me…?나 Do you know…?로 시작해요. 그 뒤에는 평서문 어순을 쓰기 때문에 where is가 아니라 where gate twelve is라고 해요.",
      easierKorean: "정중하게 물을 때는 where it is처럼 어순을 바꿔요.",
    },
  ],
  examples: [
    ["You have to show your passport at the gate.", "Bạn phải trình hộ chiếu ở cổng lên máy bay.", "탑승구에서 여권을 보여 줘야 해요.", "Nhân viên nhắc hành khách trước khi lên máy bay."],
    ["I don’t have to check in online.", "Tôi không cần làm thủ tục trực tuyến.", "온라인 체크인을 하지 않아도 돼요.", "Sora hỏi ở quầy và được trả lời như vậy."],
    ["Passengers mustn’t use their phones during take-off.", "Hành khách không được dùng điện thoại khi máy bay cất cánh.", "이륙할 때 승객은 휴대폰을 사용하면 안 돼요.", "Câu thông báo trên máy bay."],
    ["Do I have to pay for extra luggage?", "Tôi có phải trả tiền cho hành lý thêm không?", "수하물 추가 요금을 내야 하나요?", "Sora hỏi ở quầy làm thủ tục vì túi của cô hơi nặng."],
    ["Could you tell me where the platform is?", "Bạn có thể cho tôi biết sân ga ở đâu không?", "승강장이 어디인지 알려 주시겠어요?", "Linh hỏi nhân viên nhà ga khi chuyển tàu."],
    ["Do you know if the train is delayed?", "Bạn có biết tàu có bị chậm không?", "기차가 지연되는지 아세요?", "Câu hỏi ở quầy thông tin nhà ga."],
    ["The security check took about fifteen minutes.", "Việc kiểm tra an ninh mất khoảng mười lăm phút.", "보안 검색은 15분 정도 걸렸어요.", "Sora kể lại với Linh sau khi vào phòng chờ."],
    ["My carry-on bag is small enough for the cabin.", "Túi xách tay của tôi đủ nhỏ để mang lên khoang.", "제 기내 가방은 캐빈에 들어갈 만큼 작아요.", "Sora kiểm tra kích thước túi trước khi xếp hàng."],
    ["We have to go through customs in Singapore.", "Chúng ta phải làm thủ tục hải quan ở Singapore.", "싱가포르에서 세관을 통과해야 해요.", "Thông tin Linh đọc trong email của hãng bay."],
    ["You don’t have to print the boarding pass at home.", "Bạn không cần in thẻ lên máy bay ở nhà.", "집에서 탑승권을 출력하지 않아도 돼요.", "Nhân viên trả lời khi Sora hỏi có cần in vé không."],
    ["Where do I collect my checked luggage?", "Tôi lấy hành lý ký gửi ở đâu?", "위탁 수하물은 어디에서 찾나요?", "Câu hỏi sau khi máy bay hạ cánh."],
    ["Could you tell me how long the delay is?", "Bạn có thể cho tôi biết chuyến bay chậm bao lâu không?", "지연이 얼마나 되는지 알려 주시겠어요?", "Sora hỏi ở cổng vì thấy bảng hiện “delayed”."],
    ["Boarding starts forty minutes before departure.", "Việc lên máy bay bắt đầu bốn mươi phút trước giờ khởi hành.", "탑승은 출발 40분 전에 시작해요.", "Thông tin trên bảng điện tử ở sân bay."],
    ["Is there a lift to platform six?", "Có thang máy đến sân ga số sáu không?", "6번 승강장으로 가는 엘리베이터가 있나요?", "Linh hỏi vì mang theo vali nặng."],
    ["You must keep your ticket until you leave the station.", "Bạn phải giữ vé cho đến khi rời nhà ga.", "역을 나갈 때까지 표를 보관해야 해요.", "Câu nhắc trên vé tàu điện."],
    ["I’ll meet you near the information desk.", "Tôi sẽ gặp bạn gần quầy thông tin.", "안내 데스크 근처에서 만날게요.", "Linh nhắn cho Sora khi cả hai ở hai nhà ga khác nhau."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-airport-station-listen-mc",
      "Nghe câu “There’s a short delay of twenty minutes.” và chọn thông tin đúng.",
      ["Chuyến bay chậm khoảng hai mươi phút.", "Chuyến bay bị hủy hoàn toàn.", "Cổng khởi hành đã thay đổi."],
      "Chuyến bay chậm khoảng hai mươi phút.",
      "listening",
      "a2-airport-station-communicate",
      "Từ khóa là “delay” và “twenty minutes”.",
    ),
    exercise.dictation(
      "a2-airport-station-listen-dictation",
      "Nghe và chép lại câu hỏi gián tiếp về cổng lên máy bay.",
      "Could you tell me where gate twelve is?",
      "a2-airport-station-ask",
    ),
  ],
  shadowing: {
    line: "Could you tell me where gate twelve is?",
    notesVi: ["Hạ giọng ở “tell me” rồi lên nhẹ ở “gate twelve”.", "Không ngắt giữa “gate” và “twelve”."],
    notesKo: ["“tell me”는 낮게, “gate twelve”는 살짝 올려 말해요.", "“gate”와 “twelve” 사이를 끊지 않아요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-airport-station-guided-mc",
      "Chọn câu đúng nghĩa “Bạn không cần cởi giày.”",
      ["You don’t have to remove your shoes.", "You mustn’t remove your shoes.", "You have to remove your shoes."],
      "You don’t have to remove your shoes.",
      "grammar",
      "a2-airport-station-form",
    ),
    exercise.arrange(
      "a2-airport-station-guided-arrange",
      "Sắp xếp thành câu hỏi gián tiếp lịch sự.",
      ["Could", "you", "tell", "me", "where", "the", "platform", "is", "?"],
      "Could you tell me where the platform is ?",
      "a2-airport-station-ask",
    ),
    exercise.fillBlank(
      "a2-airport-station-guided-blank",
      "Điền “have to” hoặc “don’t have to”: “You ______ print the boarding pass. A screenshot is fine.”",
      "don’t have to",
      "grammar",
      "a2-airport-station-form",
    ),
    exercise.translation(
      "a2-airport-station-guided-translate",
      "Dịch sang tiếng Anh: “Bạn có biết tàu có bị chậm không?”",
      "Do you know if the train is delayed?",
      "a2-airport-station-ask",
    ),
  ],
  production: [
    exercise.written(
      "a2-airport-station-production-write",
      "Viết 4–5 câu mô tả thủ tục ở sân bay của bạn: việc bắt buộc, việc không cần làm và hai câu hỏi bạn muốn hỏi nhân viên.",
      "a2-airport-station-communicate",
      "At the airport I have to show my passport and take my laptop out at security. I don’t have to print my boarding pass. Could you tell me where gate twelve is? Do you know if the flight is delayed?",
      ["Có ít nhất hai việc bắt buộc hoặc không bắt buộc", "Có hai câu hỏi gián tiếp", "Câu ngắn, rõ nghĩa"],
    ),
    exercise.speaking(
      "a2-airport-station-production-speak",
      "Đóng vai hành khách: làm thủ tục, hỏi vị trí cổng và hỏi xem chuyến bay có đúng giờ không. Nói 45–60 giây.",
      "a2-airport-station-communicate",
      "Good morning. Here’s my passport. I only have one carry-on bag. Could you tell me where gate twelve is? Do you know if the flight is on time?",
      ["Có lời chào và thông tin cá nhân", "Dùng have to hoặc don’t have to một lần", "Hỏi ít nhất hai câu"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-airport-station-mastery-mc",
      "Chọn câu nói đúng nghĩa “Bạn không được hút thuốc ở đây.”",
      ["You mustn’t smoke here.", "You don’t have to smoke here.", "You have to smoke here."],
      "You mustn’t smoke here.",
      "grammar",
      "a2-airport-station-form",
    ),
    exercise.fillBlank(
      "a2-airport-station-mastery-blank",
      "Viết lại thành câu hỏi gián tiếp: “Where is the check-in desk?” → “Could you tell me ______?”",
      "where the check-in desk is",
      "grammar",
      "a2-airport-station-ask",
    ),
    exercise.dictation(
      "a2-airport-station-mastery-dictation",
      "Nghe và chép lại câu thông báo về việc lên máy bay.",
      "Boarding starts at nine forty.",
      "a2-airport-station-communicate",
    ),
    exercise.translation(
      "a2-airport-station-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi có phải trả tiền cho hành lý thêm không?”",
      "Do I have to pay for extra luggage?",
      "a2-airport-station-form",
    ),
    exercise.speaking(
      "a2-airport-station-mastery-speak",
      "Nói lại toàn bộ tình huống ở quầy làm thủ tục: chào, trả lời câu hỏi của nhân viên và hỏi hai thông tin.",
      "a2-airport-station-communicate",
      "Good morning. Here’s my passport. I have one carry-on bag and no checked luggage. Could you tell me where gate twelve is? Do you know if the flight is delayed?",
      ["Có chào hỏi và trả lời", "Có hai câu hỏi", "Nói trôi chảy, tự sửa khi cần"],
    ),
  ],
  canDo: ["Có thể làm thủ tục và hỏi thông tin cần thiết ở sân bay hoặc nhà ga."],
  spiralReview: ["A1: hỏi giờ và hỏi vị trí", "A2 Unit 4 bài 1: kế hoạch chuyến đi"],
  errorCategories: ["grammar-form", "missing-word", "word-order", "preposition"],
};

/* ------------------------------------------------------------------ *
 * Bài 3 — Kể lại sự cố trong chuyến đi
 * ------------------------------------------------------------------ */
const travelProblems: LessonSeed = {
  id: "a2-travel-incidents",
  unitId,
  number: 3,
  prerequisites: ["a2-airport-station"],
  titleVi: "Kể lại sự cố trong chuyến đi",
  titleKo: "여행 중 생긴 문제 이야기하기",
  situationVi: "Chuyến bay của Sora bị hủy và hành lý bị thất lạc; cô kể lại diễn biến cho Linh nghe.",
  situationKo: "소라의 항공편이 취소되고 짐이 분실됐어요. 소라는 린에게 무슨 일이 있었는지 순서대로 이야기해요.",
  objectives: [
    { id: "a2-travel-incidents-communicate", en: "Describe a travel problem and its result.", vi: "Mô tả một sự cố du lịch và hậu quả của nó.", ko: "여행 중 문제와 그 결과를 설명할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-travel-incidents-form", en: "Combine the past simple and the past continuous.", vi: "Kết hợp quá khứ đơn và quá khứ tiếp diễn trong câu.", ko: "과거형과 과거진행형을 함께 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-travel-incidents-comprehension", en: "Follow the order of events in a travel story.", vi: "Nghe và theo dõi trình tự sự việc trong một câu chuyện du lịch.", ko: "여행 이야기에서 사건 순서를 따라갈 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["cancelled", "cancelled flight", "chuyến bay bị hủy", "결항된 항공편", "/ˈkænsld/", "CANcelled", "neutral", ["a cancelled flight", "get cancelled"]],
    ["connection", "missed connection", "bị trễ chuyến nối", "환승을 놓치다", "/ˈmɪst kəˈnekʃn/", "missed conNECtion", "neutral", ["miss a connection", "a tight connection"]],
    ["lost-luggage", "lost luggage", "hành lý thất lạc", "분실 수하물", "/lɒst ˈlʌɡɪdʒ/", "LOST LUGgage", "neutral", ["report lost luggage", "lost luggage claim"]],
    ["overbooked", "an overbooked flight", "chuyến bay bán quá số ghế", "초과 예약된 항공편", "/ˌəʊvəˈbʊkt/", "overBOOKED", "neutral", ["an overbooked flight", "the flight was overbooked"]],
    ["claim", "make a claim", "làm đơn yêu cầu bồi thường", "청구하다", "/kleɪm/", "CLAIM", "formal", ["make a claim", "an insurance claim"]],
    ["refund", "ask for a refund", "yêu cầu hoàn tiền", "환불을 요청하다", "/ˈriːfʌnd/", "REfund", "neutral", ["ask for a refund", "a full refund"]],
    ["insurance", "travel insurance", "bảo hiểm du lịch", "여행자 보험", "/ɪnˈʃʊərəns/", "inSUrance", "neutral", ["travel insurance", "claim on your insurance"]],
    ["queue", "stand in a queue", "xếp hàng", "줄을 서다", "/kjuː/", "QUEUE", "casual", ["stand in a queue", "a long queue"]],
    ["boarding-card", "boarding card", "thẻ lên máy bay", "탑승권", "/ˈbɔːdɪŋ kɑːd/", "BOARDing card", "neutral", ["a printed boarding card", "the boarding card number"]],
    ["announcement", "an announcement", "thông báo", "안내 방송", "/əˈnaʊnsmənt/", "anNOUNCEment", "formal", ["hear an announcement", "a last-minute announcement"]],
  ],
  dialogue: [
    ["Linh", "How was the trip? You look exhausted.", "Chuyến đi thế nào? Trông bạn mệt quá.", "여행은 어땠어요? 너무 피곤해 보여요.", "casual"],
    ["Sora", "It was a mess. My flight was cancelled at the last minute.", "Rất lộn xộn. Chuyến bay của tôi bị hủy vào phút cuối.", "엉망이었어요. 마지막 순간에 항공편이 취소됐어요.", "casual"],
    ["Linh", "Oh no. What were you doing when they announced it?", "Trời ơi. Lúc họ thông báo thì bạn đang làm gì?", "이런. 안내 방송이 나올 때 뭐 하고 있었어요?", "casual"],
    ["Sora", "I was waiting at the gate with my boarding card in my hand.", "Tôi đang đợi ở cổng với thẻ lên máy bay trên tay.", "탑승권을 손에 들고 탑승구에서 기다리고 있었어요.", "neutral"],
    ["Linh", "So what happened next?", "Vậy sau đó thế nào?", "그다음에는 어떻게 됐어요?", "casual"],
    ["Sora", "They rebooked me onto a flight the next morning, but my luggage didn’t arrive.", "Họ đổi cho tôi sang chuyến sáng hôm sau, nhưng hành lý của tôi không đến.", "다음 날 아침 비행기로 바꿔 줬는데, 짐이 도착하지 않았어요.", "neutral"],
    ["Linh", "Did you report it at the airport?", "Bạn có báo ở sân bay không?", "공항에서 신고했어요?", "neutral"],
    ["Sora", "Yes, I made a claim at the lost luggage desk and they gave me a reference number.", "Có, tôi làm đơn ở quầy hành lý thất lạc và họ cho tôi số hồ sơ.", "네, 분실 수하물 데스크에서 신청서를 냈고 접수 번호를 받았어요.", "neutral"],
    ["Linh", "And the hotel? Did you lose that night as well?", "Còn khách sạn? Bạn có mất luôn đêm đó không?", "호텔은요? 그날 밤도 못 잔 거예요?", "neutral"],
    ["Sora", "Fortunately, the airline paid for a room near the airport.", "May là hãng bay trả tiền phòng gần sân bay.", "다행히 항공사가 공항 근처 호텔 방을 제공했어요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "Quá khứ đơn và quá khứ tiếp diễn trong câu chuyện",
      titleKo: "이야기 속 과거형과 과거진행형",
      explanationVi: "Quá khứ tiếp diễn mô tả việc đang diễn ra: “I was waiting at the gate.” Quá khứ đơn mô tả việc xảy ra và cắt ngang: “They announced it.” Dùng when để nối hai loại này: “I was waiting when they announced it.”",
      explanationKo: "과거진행형은 그때 하고 있던 일, 과거형은 갑자기 일어난 일을 나타내요. when으로 두 문장을 연결하면 사건의 순서가 분명해져요.",
      easierKorean: "하고 있던 일은 was/were + -ing, 갑자기 생긴 일은 과거형으로 말해요.",
    },
    {
      titleVi: "while và at that moment để giữ mạch kể",
      titleKo: "이야기 흐름을 잇는 while, at that moment",
      explanationVi: "while đứng trước một việc kéo dài: “While I was queuing, I heard an announcement.” at that moment, suddenly, then giúp người nghe theo dõi trình tự sự việc.",
      explanationKo: "while 뒤에는 계속되던 일을 써요. at that moment, suddenly, then 같은 표현은 사건 순서를 알려 줘요.",
      easierKorean: "길게 이어진 일은 while, 갑작스러운 일은 suddenly로 이어 말해요.",
    },
  ],
  examples: [
    ["My flight was cancelled two hours before departure.", "Chuyến bay của tôi bị hủy hai giờ trước giờ khởi hành.", "출발 두 시간 전에 항공편이 취소됐어요.", "Sora kể lại sự việc đầu tiên trong chuyến đi."],
    ["I was checking the departure board when I heard the announcement.", "Tôi đang xem bảng khởi hành thì nghe thông báo.", "출발 안내판을 보고 있는데 안내 방송이 들렸어요.", "Diễn biến ngay lúc thông báo hủy chuyến."],
    ["We were standing in a long queue at the transfer desk.", "Chúng tôi đang xếp hàng dài ở quầy chuyển chuyến.", "환승 데스크에서 긴 줄을 서 있었어요.", "Cảnh tượng ở khu vực đổi chuyến bay."],
    ["While I was filling in the form, a staff member called my name.", "Trong khi tôi đang điền tờ khai, một nhân viên gọi tên tôi.", "제가 서류를 작성하고 있는 동안 직원이 제 이름을 불렀어요.", "Sora làm hồ sơ hành lý thất lạc."],
    ["The airline rebooked me onto the next morning flight.", "Hãng bay đổi cho tôi sang chuyến sáng hôm sau.", "항공사가 다음 날 아침 비행기로 바꿔 줬어요.", "Kết quả sau khi khiếu nại ở quầy."],
    ["My suitcase didn’t arrive with the plane.", "Vali của tôi không đến cùng chuyến bay.", "제 캐리어가 비행기와 함께 도착하지 않았어요.", "Sora phát hiện vấn đề ở băng chuyền hành lý."],
    ["I reported the missing luggage at the service desk.", "Tôi báo hành lý thất lạc ở quầy dịch vụ.", "서비스 데스크에 수하물 분실을 신고했어요.", "Bước tiếp theo sau khi nhận ra mất vali."],
    ["They gave me a reference number for the claim.", "Họ cho tôi số hồ sơ để theo dõi.", "청구를 위한 접수 번호를 받았어요.", "Thông tin cần thiết để kiểm tra sau này."],
    ["The hotel near the airport was full that night.", "Khách sạn gần sân bay đêm đó hết phòng.", "그날 밤 공항 근처 호텔은 방이 꽉 찼어요.", "Sora kể lại khó khăn trong đêm bị hoãn."],
    ["Fortunately, my travel insurance covered the extra night.", "May là bảo hiểm du lịch của tôi chi trả đêm phát sinh.", "다행히 여행자 보험이 추가 숙박비를 보상했어요.", "Chi tiết giúp câu chuyện kết thúc nhẹ nhàng hơn."],
    ["I had to buy a toothbrush while I was waiting for my bag.", "Tôi phải mua bàn chải trong lúc chờ hành lý.", "가방을 기다리는 동안 칫솔을 사야 했어요.", "Chi tiết nhỏ Sora kể khiến Linh bật cười."],
    ["The flight was overbooked, so the airline asked for volunteers.", "Chuyến bay bán quá số ghế nên hãng xin người nhường chỗ.", "항공편이 초과 예약되어 항공사가 자원자를 찾았어요.", "Tình huống khác mà Sora từng gặp ở sân bay."],
    ["My missed connection meant I arrived a day late.", "Việc trễ chuyến nối khiến tôi đến muộn một ngày.", "환승을 놓쳐서 하루 늦게 도착했어요.", "Ảnh hưởng của sự cố tới cả chuyến đi."],
    ["I asked for a refund at the ticket office.", "Tôi yêu cầu hoàn tiền ở quầy vé.", "매표소에서 환불을 요청했어요.", "Cách Sora xử lý ở nhà ga tàu."],
    ["In the end, the airline sent my suitcase to my hotel.", "Cuối cùng hãng bay gửi vali đến khách sạn của tôi.", "결국 항공사가 제 캐리어를 호텔로 보내 줬어요.", "Kết thúc câu chuyện về hành lý thất lạc."],
    ["Now I always keep medicine in my carry-on bag.", "Bây giờ tôi luôn để thuốc trong túi xách tay.", "이제는 항상 기내 가방에 약을 넣어요.", "Bài học Sora rút ra sau chuyến đi."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-travel-incidents-listen-mc",
      "Nghe câu “I was checking the departure board when I heard the announcement.” và chọn hành động Sora đang làm lúc nghe thông báo.",
      ["Cô ấy đang xem bảng khởi hành.", "Cô ấy đang lên máy bay.", "Cô ấy đang gọi điện cho khách sạn."],
      "Cô ấy đang xem bảng khởi hành.",
      "listening",
      "a2-travel-incidents-comprehension",
      "Hành động đang diễn ra đứng sau “was”.",
    ),
    exercise.dictation(
      "a2-travel-incidents-listen-dictation",
      "Nghe và chép lại câu kể về lúc điền hồ sơ.",
      "While I was filling in the form, a staff member called my name.",
      "a2-travel-incidents-form",
    ),
  ],
  shadowing: {
    line: "I was waiting at the gate when they announced the cancellation.",
    notesVi: ["Ngắt nhẹ sau “gate” để tách hai hành động.", "Đọc “announced the” thành một cụm liền."],
    notesKo: ["“gate” 뒤에서 잠깐 쉬면 두 행동이 잘 구분돼요.", "“announced the”는 붙여서 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-travel-incidents-guided-mc",
      "Chọn dạng đúng: “I ______ for my bag when the airline called.”",
      ["was waiting", "waited", "am waiting"],
      "was waiting",
      "grammar",
      "a2-travel-incidents-form",
    ),
    exercise.fillBlank(
      "a2-travel-incidents-guided-blank",
      "Điền dạng đúng của động từ trong ngoặc: “While we ______ (queue), the gate changed.”",
      "were queuing",
      "grammar",
      "a2-travel-incidents-form",
      "Chủ ngữ là “we”.",
    ),
    exercise.arrange(
      "a2-travel-incidents-guided-arrange",
      "Sắp xếp thành câu kể hoàn chỉnh.",
      ["I", "was", "checking", "the", "board", "when", "the", "flight", "was", "cancelled"],
      "I was checking the board when the flight was cancelled",
      "a2-travel-incidents-form",
    ),
    exercise.translation(
      "a2-travel-incidents-guided-translate",
      "Dịch sang tiếng Anh: “Tôi đang xếp hàng thì họ thông báo chuyến bay bị hủy.”",
      "I was standing in a queue when they announced the cancelled flight.",
      "a2-travel-incidents-communicate",
    ),
  ],
  production: [
    exercise.written(
      "a2-travel-incidents-production-write",
      "Viết 5–6 câu kể lại một sự cố khi đi lại (trễ tàu, mất đồ, hỏng xe). Dùng ít nhất hai câu quá khứ tiếp diễn với when hoặc while và nêu kết quả cuối cùng.",
      "a2-travel-incidents-communicate",
      "Last month I was travelling to Da Lat by bus when the engine made a strange noise. While the driver was calling for help, we were waiting beside the road. After an hour, another bus arrived, and in the end we arrived six hours late.",
      ["Có trình tự rõ ràng", "Dùng when hoặc while hai lần", "Có câu kết thúc"],
    ),
    exercise.speaking(
      "a2-travel-incidents-production-speak",
      "Kể lại sự cố trong chuyến đi của bạn trong 60 giây, bắt đầu bằng “It started when…” và kết thúc bằng kết quả.",
      "a2-travel-incidents-communicate",
      "It started when my flight was cancelled. I was waiting at the gate when they made the announcement. They rebooked me onto the next morning flight, and finally my bag arrived two days later.",
      ["Có mở đầu và kết thúc rõ", "Dùng thì quá khứ phù hợp", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-travel-incidents-mastery-mc",
      "Chọn câu đúng ngữ pháp.",
      ["We were queuing when the gate changed.", "We queued when the gate was changing.", "We were queue when the gate changed."],
      "We were queuing when the gate changed.",
      "grammar",
      "a2-travel-incidents-form",
    ),
    exercise.fillBlank(
      "a2-travel-incidents-mastery-blank",
      "Điền dạng đúng: “They ______ (announce) the delay while we were boarding.”",
      "announced",
      "grammar",
      "a2-travel-incidents-form",
    ),
    exercise.dictation(
      "a2-travel-incidents-mastery-dictation",
      "Nghe và chép lại câu về hậu quả của việc trễ chuyến nối.",
      "My missed connection meant I arrived a day late.",
      "a2-travel-incidents-comprehension",
    ),
    exercise.translation(
      "a2-travel-incidents-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi báo hành lý thất lạc ở quầy dịch vụ.”",
      "I reported the missing luggage at the service desk.",
      "a2-travel-incidents-communicate",
    ),
    exercise.speaking(
      "a2-travel-incidents-mastery-speak",
      "Kể lại sự cố ở sân bay trong 60 giây với đủ ba phần: điều đang diễn ra, điều bất ngờ, cách giải quyết.",
      "a2-travel-incidents-communicate",
      "I was waiting at the gate when the airline cancelled the flight. They rebooked me for the next morning, but my suitcase didn’t arrive. I made a claim at the lost luggage desk, and three days later the airline sent it to my hotel.",
      ["Đủ ba phần của câu chuyện", "Dùng quá khứ đơn và quá khứ tiếp diễn", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể kể lại một sự cố khi đi lại theo trình tự và mô tả cách giải quyết."],
  spiralReview: ["A2 Unit 3: kể sự việc và mô tả bối cảnh", "A2 Unit 4 bài 2: làm thủ tục và hỏi thông tin"],
  errorCategories: ["verb-tense", "word-order", "missing-word", "word-choice"],
};

/* ------------------------------------------------------------------ *
 * Bài 4 — Yêu cầu hỗ trợ và xác nhận giải pháp
 * ------------------------------------------------------------------ */
const askingForHelp: LessonSeed = {
  id: "a2-travel-support",
  unitId,
  number: 4,
  prerequisites: ["a2-travel-incidents"],
  titleVi: "Yêu cầu hỗ trợ và xác nhận giải pháp",
  titleKo: "도움을 요청하고 해결을 확인하기",
  situationVi: "Sora khiếu nại ở quầy dịch vụ, đề nghị phương án thay thế và xác nhận lại bằng email.",
  situationKo: "소라는 서비스 데스크에 문제를 말하고 대안을 요청한 뒤, 이메일로 다시 확인해요.",
  objectives: [
    { id: "a2-travel-support-communicate", en: "Ask for help with a problem and confirm the solution.", vi: "Yêu cầu hỗ trợ khi gặp vấn đề và xác nhận lại giải pháp.", ko: "문제를 말하고 도움을 요청한 뒤 해결 방법을 확인할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-travel-support-form", en: "Use will for instant decisions and the first conditional.", vi: "Dùng will cho quyết định tức thời và câu điều kiện loại 1.", ko: "will로 즉석 결정을 말하고 1형 조건문을 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-travel-support-register", en: "Stay calm and polite when complaining.", vi: "Giữ bình tĩnh và lịch sự khi phàn nàn.", ko: "불평할 때도 차분하고 정중하게 말할 수 있어요.", skills: ["speaking", "reading"] },
  ],
  vocab: [
    ["rebook", "rebook a flight", "đổi lại chuyến bay", "항공편을 다시 예약하다", "/ˌriːˈbʊk/", "reBOOK", "neutral", ["rebook a flight", "rebook for tomorrow"]],
    ["alternative", "an alternative flight", "chuyến bay thay thế", "대체 항공편", "/ɔːlˈtɜːnətɪv/", "alTERnative", "formal", ["an alternative flight", "look for alternatives"]],
    ["compensation", "claim compensation", "yêu cầu bồi thường", "보상금을 청구하다", "/ˌkɒmpenˈseɪʃn/", "compensAtion", "formal", ["claim compensation", "receive compensation"]],
    ["apologize", "apologize for the delay", "xin lỗi vì sự chậm trễ", "지연에 대해 사과하다", "/əˈpɒlədʒaɪz/", "aPOLogize", "formal", ["apologize for the delay", "apologize sincerely"]],
    ["solution", "find a solution", "tìm giải pháp", "해결책을 찾다", "/səˈluːʃn/", "soLUTion", "neutral", ["find a solution", "a quick solution"]],
    ["in-writing", "confirm in writing", "xác nhận bằng văn bản", "서면으로 확인하다", "/ɪn ˈraɪtɪŋ/", "in WRITing", "formal", ["confirm in writing", "put it in writing"]],
    ["reference-number", "reference number", "số hồ sơ", "접수 번호", "/ˈrefrəns ˈnʌmbə(r)/", "REFerence NUMber", "formal", ["keep the reference number", "quote the reference number"]],
    ["staff", "speak to the staff", "nói chuyện với nhân viên", "직원과 이야기하다", "/stɑːf/", "STAFF", "neutral", ["the ground staff", "a member of staff"]],
    ["receipt", "keep the receipt", "giữ hóa đơn", "영수증을 보관하다", "/rɪˈsiːt/", "reCEIPT", "neutral", ["keep the receipt", "ask for a receipt"]],
    ["request", "make a request", "đưa ra yêu cầu", "요청하다", "/rɪˈkwest/", "reQUEST", "formal", ["make a request", "a special request"]],
  ],
  dialogue: [
    ["Sora", "Excuse me, I’d like to talk to someone about my cancelled flight.", "Xin lỗi, tôi muốn nói chuyện với ai đó về chuyến bay bị hủy của tôi.", "실례합니다, 취소된 항공편에 대해 이야기하고 싶어요.", "neutral"],
    ["Staff", "Of course. Could you give me your booking reference?", "Tất nhiên. Bạn cho tôi mã đặt chỗ được không?", "물론이죠. 예약 번호를 알려 주시겠어요?", "formal"],
    ["Sora", "Here it is. My luggage is still missing, and I’ve already made a claim.", "Đây ạ. Hành lý của tôi vẫn chưa có, và tôi đã làm đơn rồi.", "여기 있습니다. 짐은 아직 못 받았고 신고도 했어요.", "neutral"],
    ["Staff", "I’m very sorry about that. Let me check the system right now.", "Tôi rất xin lỗi về việc này. Để tôi kiểm tra hệ thống ngay.", "정말 죄송합니다. 지금 바로 시스템을 확인해 볼게요.", "formal"],
    ["Sora", "Thank you. Could you offer an alternative flight instead?", "Cảm ơn. Bạn có thể cho tôi một chuyến bay thay thế không?", "감사합니다. 대신 다른 항공편을 제안해 주실 수 있나요?", "neutral"],
    ["Staff", "If you agree, I’ll move you to the eight o’clock flight tomorrow.", "Nếu bạn đồng ý, tôi sẽ chuyển bạn sang chuyến tám giờ sáng mai.", "괜찮으시다면 내일 8시 비행기로 바꿔 드릴게요.", "formal"],
    ["Sora", "That works. Will the airline pay for my hotel tonight?", "Được đấy. Hãng có trả tiền khách sạn đêm nay không?", "좋아요. 오늘 밤 호텔비도 항공사가 부담하나요?", "neutral"],
    ["Staff", "Yes, we will. I’ll send a confirmation email with the hotel details.", "Vâng, chúng tôi sẽ trả. Tôi sẽ gửi email xác nhận kèm thông tin khách sạn.", "네, 그렇게 해 드려요. 호텔 정보가 담긴 확인 이메일을 보내 드릴게요.", "formal"],
    ["Sora", "Could you put the reference number in the email as well?", "Bạn ghi luôn số hồ sơ vào email được không?", "이메일에 접수 번호도 넣어 주시겠어요?", "neutral"],
    ["Staff", "Certainly. If anything changes, we’ll call you immediately.", "Chắc chắn rồi. Nếu có gì thay đổi, chúng tôi sẽ gọi ngay cho bạn.", "물론입니다. 변경 사항이 있으면 바로 전화드릴게요.", "formal"],
    ["Sora", "Thank you for your help. I appreciate it.", "Cảm ơn bạn đã giúp. Tôi rất trân trọng điều đó.", "도와주셔서 감사합니다.", "formal"],
  ],
  grammar: [
    {
      titleVi: "will cho quyết định ngay lúc nói",
      titleKo: "말하는 순간 정한 결정의 will",
      explanationVi: "Khi quyết định được đưa ra ngay trong cuộc trò chuyện, dùng will + động từ nguyên mẫu: “I’ll send a confirmation email.” Không dùng be going to vì đó là việc quyết định ngay lúc nói, không phải kế hoạch chuẩn bị trước.",
      explanationKo: "대화 중에 바로 정한 일은 will + 동사원형으로 말해요. 미리 준비한 계획에는 be going to를 써요.",
      easierKorean: "지금 바로 하기로 했으면 will을 써요.",
    },
    {
      titleVi: "Câu điều kiện loại 1 trong xử lý vấn đề",
      titleKo: "문제 해결 상황의 1형 조건문",
      explanationVi: "Cấu trúc If + hiện tại đơn, will + động từ nguyên mẫu dùng để đề nghị giải pháp: “If you agree, I’ll move you to the eight o’clock flight.” Mệnh đề if không dùng will.",
      explanationKo: "해결 방법을 제안할 때는 If + 현재형, will + 동사원형을 써요. if 뒤에는 will을 쓰지 않아요.",
      easierKorean: "If 뒤에는 현재형, 뒤 문장에는 will을 써요.",
    },
  ],
  examples: [
    ["I’ll check the system right now.", "Tôi sẽ kiểm tra hệ thống ngay bây giờ.", "지금 바로 시스템을 확인할게요.", "Nhân viên trả lời khi Sora vừa trình bày vấn đề."],
    ["If you agree, I’ll move you to the morning flight.", "Nếu bạn đồng ý, tôi sẽ chuyển bạn sang chuyến sáng.", "괜찮으시면 오전 비행기로 바꿔 드릴게요.", "Lời đề nghị giải pháp ở quầy dịch vụ."],
    ["If anything changes, we’ll call you immediately.", "Nếu có gì thay đổi, chúng tôi sẽ gọi ngay cho bạn.", "변경 사항이 있으면 바로 전화드릴게요.", "Cam kết cuối buổi trao đổi với nhân viên."],
    ["I’ll put the reference number in the email.", "Tôi sẽ ghi số hồ sơ vào email.", "이메일에 접수 번호를 넣을게요.", "Chi tiết Sora yêu cầu để dễ theo dõi."],
    ["Would you mind confirming that in writing?", "Bạn có phiền xác nhận bằng văn bản không?", "서면으로 확인해 주시겠어요?", "Cách yêu cầu lịch sự khi cần bằng chứng."],
    ["I’d like to make a request about my luggage.", "Tôi muốn đưa ra một yêu cầu về hành lý của tôi.", "수하물에 대해 요청하고 싶어요.", "Mở đầu cuộc nói chuyện ở quầy."],
    ["Could you tell me who is responsible for this?", "Bạn cho tôi biết ai phụ trách việc này được không?", "이 일을 누가 담당하는지 알려 주시겠어요?", "Câu hỏi khi cần gặp đúng người phụ trách."],
    ["We can offer compensation if you keep the receipts.", "Chúng tôi có thể bồi thường nếu bạn giữ hóa đơn.", "영수증을 보관하시면 보상을 해 드릴 수 있어요.", "Nhân viên giải thích điều kiện bồi thường."],
    ["If the hotel is full, we’ll find another one.", "Nếu khách sạn hết phòng, chúng tôi sẽ tìm chỗ khác.", "호텔이 꽉 찼으면 다른 곳을 찾아 드릴게요.", "Phương án dự phòng cho đêm bị hoãn."],
    ["I’m sorry, but that solution doesn’t work for me.", "Tôi xin lỗi, nhưng giải pháp đó không phù hợp với tôi.", "죄송하지만 그 방법은 저에게 맞지 않아요.", "Cách từ chối phương án và đề nghị phương án khác."],
    ["Let me speak to a member of staff, please.", "Cho tôi nói chuyện với một nhân viên được không?", "직원과 이야기하게 해 주세요.", "Câu nói khi cần hỗ trợ trực tiếp."],
    ["I’ll send you the details this afternoon.", "Tôi sẽ gửi bạn thông tin chi tiết chiều nay.", "오늘 오후에 자세한 내용을 보내 드릴게요.", "Cam kết thời gian cụ thể của nhân viên."],
    ["If you send the form today, we’ll process it quickly.", "Nếu bạn gửi biểu mẫu hôm nay, chúng tôi sẽ xử lý nhanh.", "오늘 서류를 보내 주시면 빠르게 처리해 드릴게요.", "Hướng dẫn thủ tục tiếp theo."],
    ["Please keep this receipt for your claim.", "Hãy giữ hóa đơn này cho hồ sơ của bạn.", "청구를 위해 이 영수증을 보관해 주세요.", "Nhân viên nhắc khi trả lại tiền taxi."],
    ["Thanks for listening. I feel better now.", "Cảm ơn đã lắng nghe. Tôi thấy nhẹ nhõm hơn rồi.", "들어 주셔서 감사합니다. 이제 좀 편해졌어요.", "Câu kết thúc tự nhiên sau khi được hỗ trợ."],
    ["I’ll let you know if I need anything else.", "Tôi sẽ cho bạn biết nếu cần gì thêm.", "더 필요한 것이 있으면 알려 드릴게요.", "Câu kết thúc lịch sự ở quầy dịch vụ."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-travel-support-listen-mc",
      "Nghe câu “If you agree, I’ll move you to the eight o’clock flight tomorrow.” và chọn điều nhân viên đề nghị.",
      ["Đổi sang chuyến tám giờ sáng mai.", "Hủy toàn bộ chuyến đi.", "Trả lại hành lý ngay tại quầy."],
      "Đổi sang chuyến tám giờ sáng mai.",
      "listening",
      "a2-travel-support-register",
      "Số giờ quan trọng nằm sau “the”.",
    ),
    exercise.dictation(
      "a2-travel-support-listen-dictation",
      "Nghe và chép lại cam kết của nhân viên.",
      "If anything changes, we’ll call you immediately.",
      "a2-travel-support-form",
    ),
  ],
  shadowing: {
    line: "Would you mind confirming that in writing?",
    notesVi: ["Lên giọng nhẹ ở “mind” để thể hiện lời đề nghị lịch sự.", "Đọc “confirming that in” thành một cụm nhanh, nhẹ."],
    notesKo: ["“mind”를 살짝 올리면 정중한 부탁으로 들려요.", "“confirming that in”은 빠르고 가볍게 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-travel-support-guided-mc",
      "Chọn câu đúng ngữ pháp.",
      ["If the flight is late, I’ll take a taxi.", "If the flight will be late, I take a taxi.", "If the flight is late, I take a taxi tomorrow."],
      "If the flight is late, I’ll take a taxi.",
      "grammar",
      "a2-travel-support-form",
    ),
    exercise.arrange(
      "a2-travel-support-guided-arrange",
      "Sắp xếp thành câu đề nghị giải pháp.",
      ["If", "you", "agree", ",", "I’ll", "change", "your", "booking"],
      "If you agree , I’ll change your booking",
      "a2-travel-support-form",
    ),
    exercise.fillBlank(
      "a2-travel-support-guided-blank",
      "Điền dạng đúng: “If the hotel ______ (be) full, we’ll find another one.”",
      "is",
      "grammar",
      "a2-travel-support-form",
      "Mệnh đề if dùng hiện tại đơn.",
    ),
    exercise.translation(
      "a2-travel-support-guided-translate",
      "Dịch sang tiếng Anh: “Bạn có phiền xác nhận bằng văn bản không?”",
      "Would you mind confirming that in writing?",
      "a2-travel-support-register",
    ),
  ],
  production: [
    exercise.written(
      "a2-travel-support-production-write",
      "Viết email ngắn (5–6 câu) cho hãng bay: nêu vấn đề về hành lý, yêu cầu giải pháp, đề nghị xác nhận bằng văn bản và nêu điều kiện của bạn.",
      "a2-travel-support-communicate",
      "Dear Sir or Madam, my suitcase did not arrive with my flight on the twelfth. I reported it at the service desk and my reference number is AB1234. I’d like to request compensation for the things I had to buy. If you need the receipts, I’ll send them today. Could you confirm the next step in writing? Thank you for your help.",
      ["Nêu vấn đề và số hồ sơ", "Có yêu cầu cụ thể", "Dùng ít nhất một câu điều kiện loại 1"],
    ),
    exercise.speaking(
      "a2-travel-support-production-speak",
      "Đóng vai khiếu nại tại quầy: trình bày vấn đề, đề nghị phương án thay thế, hỏi về bồi thường và xác nhận lại kết quả.",
      "a2-travel-support-communicate",
      "Excuse me, I’d like to talk about my cancelled flight. My luggage is still missing and I’ve already made a claim. Could you offer an alternative flight? If the airline pays for the hotel, I’ll stay near the airport. Could you confirm that in writing?",
      ["Giữ giọng bình tĩnh, lịch sự", "Dùng will cho giải pháp tức thời", "Có câu xác nhận cuối cùng"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-travel-support-mastery-mc",
      "Chọn câu thể hiện quyết định ngay lúc nói.",
      ["I’ll send the confirmation email now.", "I’m going to have sent the email last week.", "I send the email yesterday."],
      "I’ll send the confirmation email now.",
      "grammar",
      "a2-travel-support-form",
    ),
    exercise.fillBlank(
      "a2-travel-support-mastery-blank",
      "Hoàn thành câu điều kiện: “If you ______ (keep) the receipts, we can pay the costs.”",
      "keep",
      "grammar",
      "a2-travel-support-form",
    ),
    exercise.dictation(
      "a2-travel-support-mastery-dictation",
      "Nghe và chép lại cam kết của nhân viên về việc gọi lại.",
      "If anything changes, we’ll call you immediately.",
      "a2-travel-support-communicate",
    ),
    exercise.translation(
      "a2-travel-support-mastery-translate",
      "Dịch sang tiếng Anh: “Nếu khách sạn hết phòng, chúng tôi sẽ tìm chỗ khác.”",
      "If the hotel is full, we’ll find another one.",
      "a2-travel-support-register",
    ),
    exercise.speaking(
      "a2-travel-support-mastery-speak",
      "Nói lại cuộc khiếu nại trong 60 giây: vấn đề, đề nghị, điều kiện và câu xác nhận.",
      "a2-travel-support-communicate",
      "My flight was cancelled and my luggage is still missing. If you can offer an alternative flight, I’ll take it. Could you confirm the hotel and the reference number in writing? I’ll send the receipts this afternoon if you need them.",
      ["Đủ bốn phần", "Ngôn ngữ lịch sự", "Tự nghe lại và nhận xét"],
    ),
  ],
  canDo: ["Có thể yêu cầu hỗ trợ lịch sự và xác nhận lại giải pháp bằng văn bản."],
  spiralReview: ["A2 Unit 2: nhờ giúp đỡ và đặt lịch", "A2 Unit 4 bài 3: kể lại sự cố"],
  errorCategories: ["grammar-form", "word-choice", "register", "missing-word"],
};

/* ------------------------------------------------------------------ *
 * Bài 5 — Ôn tập Unit 4 và nhiệm vụ du lịch
 * ------------------------------------------------------------------ */
const unitReview: LessonSeed = {
  id: "a2-unit-4-review",
  unitId,
  number: 5,
  prerequisites: ["a2-travel-support"],
  titleVi: "Ôn tập Unit 4 và nhiệm vụ du lịch",
  titleKo: "Unit 4 복습과 여행 미션",
  situationVi: "Linh và Sora xử lý trọn vẹn một chuyến đi có thay đổi: chốt kế hoạch, làm thủ tục, gặp sự cố, xin hỗ trợ và xác nhận kết quả.",
  situationKo: "린과 소라는 계획 세우기부터 수속, 문제 발생, 도움 요청, 확인까지 여행 전체를 처리해요.",
  objectives: [
    { id: "a2-unit-4-review-communicate", en: "Handle a complete travel situation from plan to solution.", vi: "Xử lý trọn vẹn một tình huống du lịch từ kế hoạch đến giải pháp.", ko: "계획부터 해결까지 여행 상황을 처리할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-unit-4-review-form", en: "Choose the right form for plans, rules, stories and solutions.", vi: "Chọn đúng cấu trúc cho kế hoạch, quy định, câu chuyện và giải pháp.", ko: "계획, 규칙, 이야기, 해결에 맞는 문법을 고를 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-unit-4-review-comprehension", en: "Understand key details in announcements and requests.", vi: "Nắm thông tin quan trọng trong thông báo và lời đề nghị.", ko: "안내 방송과 요청에서 중요한 정보를 이해할 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["itinerary", "final itinerary", "lịch trình cuối cùng", "최종 일정", "/aɪˈtɪnərəri/", "iTINerary", "neutral", ["the final itinerary", "send the itinerary"]],
    ["boarding-pass", "boarding pass", "thẻ lên máy bay", "탑승권", "/ˈbɔːdɪŋ pɑːs/", "BOARDing pass", "neutral", ["show the boarding pass", "a digital boarding pass"]],
    ["delay", "long delay", "chậm trễ lâu", "긴 지연", "/dɪˈleɪ/", "deLAY", "neutral", ["a long delay", "a three-hour delay"]],
    ["refund", "full refund", "hoàn tiền toàn bộ", "전액 환불", "/ˈriːfʌnd/", "REfund", "neutral", ["a full refund", "ask for a refund"]],
    ["alternative", "alternative plan", "phương án thay thế", "대안 계획", "/ɔːlˈtɜːnətɪv/", "alTERnative", "formal", ["an alternative plan", "an alternative route"]],
    ["confirm", "confirm the details", "xác nhận thông tin chi tiết", "세부 사항을 확인하다", "/kənˈfɜːm/", "conFIRM", "formal", ["confirm the details", "confirm by email"]],
    ["insurance", "travel insurance", "bảo hiểm du lịch", "여행자 보험", "/ɪnˈʃʊərəns/", "inSUrance", "neutral", ["travel insurance", "use your insurance"]],
    ["announcement", "hear an announcement", "nghe thông báo", "안내 방송을 듣다", "/əˈnaʊnsmənt/", "anNOUNCEment", "formal", ["hear an announcement", "a boarding announcement"]],
  ],
  dialogue: [
    ["Linh", "So, did everything work out in the end?", "Vậy cuối cùng mọi việc ổn cả chứ?", "결국 모든 게 잘 해결됐어요?", "casual"],
    ["Sora", "Almost. I was queuing at the transfer desk when they announced a second delay.", "Gần như vậy. Tôi đang xếp hàng ở quầy chuyển chuyến thì họ thông báo chậm thêm lần nữa.", "거의요. 환승 데스크에서 줄을 서 있는데 두 번째 지연 안내가 나왔어요.", "casual"],
    ["Linh", "What did you do?", "Bạn đã làm gì?", "어떻게 했어요?", "casual"],
    ["Sora", "I asked for an alternative flight and they rebooked me for the same evening.", "Tôi xin chuyến khác và họ đổi cho tôi chuyến tối cùng ngày.", "다른 항공편을 요청했더니 같은 날 저녁으로 바꿔 줬어요.", "neutral"],
    ["Linh", "That’s good news. Do you have it in writing?", "Tin tốt đấy. Bạn có giấy xác nhận chưa?", "다행이네요. 서면 확인은 받았어요?", "neutral"],
    ["Sora", "Yes, they sent an email with the reference number, and I printed it at the hotel.", "Rồi, họ gửi email kèm số hồ sơ, và tôi in ở khách sạn.", "네, 접수 번호가 있는 이메일을 받아서 호텔에서 출력했어요.", "neutral"],
    ["Linh", "And your suitcase?", "Còn vali của bạn?", "캐리어는요?", "casual"],
    ["Sora", "It arrived on the third day. The airline will pay for the clothes I bought.", "Nó đến vào ngày thứ ba. Hãng sẽ trả tiền quần áo tôi đã mua.", "3일째에 도착했어요. 항공사가 제가 산 옷값을 보상해 줄 거예요.", "neutral"],
    ["Linh", "Nice. If you send the receipts today, they’ll pay you quickly.", "Tốt đấy. Nếu bạn gửi hóa đơn hôm nay, họ sẽ trả nhanh.", "좋네요. 오늘 영수증을 보내면 빨리 지급해 줄 거예요.", "neutral"],
    ["Sora", "I’ll do it tonight. Next time I’ll take more in my carry-on bag.", "Tối nay tôi sẽ làm. Lần sau tôi sẽ mang nhiều hơn trong túi xách tay.", "오늘 밤에 할게요. 다음에는 기내 가방에 더 많이 넣을 거예요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "Chọn cấu trúc theo mục đích nói",
      titleKo: "말할 목적에 맞게 문법 고르기",
      explanationVi: "Kế hoạch đã định: be going to. Lịch đã chốt: hiện tại tiếp diễn. Quy định: have to, must, mustn’t. Việc không cần làm: don’t have to. Câu chuyện: quá khứ đơn và quá khứ tiếp diễn. Giải pháp tức thời: will. Điều kiện: If + hiện tại đơn, will.",
      explanationKo: "미리 정한 계획은 be going to, 확정된 일정은 현재진행형, 규칙은 have to와 must, 필요 없는 일은 don’t have to를 써요. 이야기는 과거형과 과거진행형, 즉석 결정은 will, 조건은 If + 현재형, will로 말해요.",
      easierKorean: "계획, 규칙, 이야기, 해결 중 어느 상황인지 먼저 생각하고 문법을 골라요.",
    },
  ],
  examples: [
    ["We’re flying on Friday and staying for four nights.", "Chúng ta bay thứ Sáu và ở lại bốn đêm.", "우리는 금요일에 가고 4박 동안 머물러요.", "Linh nhắc lại lịch chuyến đi đã chốt."],
    ["I’m going to download the tickets tonight.", "Tối nay tôi sẽ tải vé về máy.", "오늘 밤에 표를 다운로드할 거예요.", "Việc chuẩn bị trước ngày đi."],
    ["You have to be at the gate forty minutes before departure.", "Bạn phải có mặt ở cổng trước giờ khởi hành bốn mươi phút.", "출발 40분 전까지 탑승구에 있어야 해요.", "Quy định của sân bay trong email."],
    ["You don’t have to print the boarding pass.", "Bạn không cần in thẻ lên máy bay.", "탑승권을 출력하지 않아도 돼요.", "Thông tin nhân viên cho Sora ở quầy."],
    ["I was checking my bag when the announcement started.", "Tôi đang kiểm tra túi thì thông báo bắt đầu.", "가방을 확인하고 있는데 안내 방송이 시작됐어요.", "Diễn biến lúc sự cố xảy ra."],
    ["While we were waiting, the gate changed twice.", "Trong lúc chúng tôi chờ, cổng đổi hai lần.", "기다리는 동안 탑승구가 두 번 바뀌었어요.", "Sora kể lại sự lộn xộn ở sân bay."],
    ["If the flight is cancelled, I’ll ask for an alternative.", "Nếu chuyến bay bị hủy, tôi sẽ xin chuyến khác.", "항공편이 취소되면 다른 항공편을 요청할게요.", "Kế hoạch dự phòng Sora nói với Linh."],
    ["I’ll call the airline now.", "Tôi sẽ gọi hãng bay ngay bây giờ.", "지금 항공사에 전화할게요.", "Quyết định tức thời khi thấy email mới."],
    ["Could you tell me where the transfer desk is?", "Bạn cho tôi biết quầy chuyển chuyến ở đâu không?", "환승 데스크가 어디인지 알려 주시겠어요?", "Câu hỏi gián tiếp ở nhà ga."],
    ["Do you know if the train is delayed?", "Bạn có biết tàu có bị chậm không?", "기차가 지연되는지 아세요?", "Câu hỏi ở quầy thông tin."],
    ["They offered compensation for the lost day.", "Họ đề nghị bồi thường cho ngày bị mất.", "잃어버린 하루에 대해 보상을 제안했어요.", "Kết quả cuối của việc khiếu nại."],
    ["Please confirm the details in writing.", "Hãy xác nhận thông tin bằng văn bản.", "세부 사항을 서면으로 확인해 주세요.", "Câu Sora nói với nhân viên."],
    ["I’ve already sent the receipts by email.", "Tôi đã gửi hóa đơn qua email rồi.", "영수증은 이미 이메일로 보냈어요.", "Bước tiếp theo trong hồ sơ bồi thường."],
    ["In the end, the trip was still wonderful.", "Cuối cùng, chuyến đi vẫn rất tuyệt.", "결국 여행은 여전히 멋졌어요.", "Câu kết Sora nói khi kể lại chuyến đi."],
    ["Next time I’ll leave more time between flights.", "Lần sau tôi sẽ để nhiều thời gian hơn giữa các chuyến.", "다음에는 환승 사이에 시간을 더 넉넉히 둘 거예요.", "Bài học kinh nghiệm sau chuyến đi."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-unit-4-review-listen-mc",
      "Nghe câu “While we were waiting, the gate changed twice.” và chọn thông tin đúng.",
      ["Cổng thay đổi hai lần trong lúc chờ.", "Cổng không thay đổi.", "Hai người bỏ chuyến bay."],
      "Cổng thay đổi hai lần trong lúc chờ.",
      "listening",
      "a2-unit-4-review-comprehension",
      "Từ “twice” cho biết số lần.",
    ),
    exercise.dictation(
      "a2-unit-4-review-listen-dictation",
      "Nghe và chép lại câu về xác nhận bằng văn bản.",
      "Please confirm the details in writing.",
      "a2-unit-4-review-form",
    ),
  ],
  shadowing: {
    line: "If the flight is cancelled, I’ll ask for an alternative.",
    notesVi: ["Ngắt rõ sau “cancelled” để tách điều kiện và kết quả.", "Nối “ask_for_an” thành một cụm mượt."],
    notesKo: ["“cancelled” 뒤에서 또렷하게 쉬면 조건과 결과가 잘 들려요.", "“ask for an”은 부드럽게 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-unit-4-review-guided-mc",
      "Chọn câu đúng để nói về một lịch đã chốt.",
      ["We’re meeting the agent at ten tomorrow.", "We meet the agent at ten yesterday.", "We are going to met the agent at ten."],
      "We’re meeting the agent at ten tomorrow.",
      "grammar",
      "a2-unit-4-review-form",
    ),
    exercise.fillBlank(
      "a2-unit-4-review-guided-blank",
      "Điền dạng đúng: “You ______ (not have to) print the itinerary.”",
      "don’t have to",
      "grammar",
      "a2-unit-4-review-form",
    ),
    exercise.arrange(
      "a2-unit-4-review-guided-arrange",
      "Sắp xếp thành câu kể có quá khứ tiếp diễn.",
      ["I", "was", "queuing", "when", "they", "announced", "the", "delay"],
      "I was queuing when they announced the delay",
      "a2-unit-4-review-form",
    ),
    exercise.translation(
      "a2-unit-4-review-guided-translate",
      "Dịch sang tiếng Anh: “Nếu chuyến bay bị hủy, tôi sẽ xin chuyến khác.”",
      "If the flight is cancelled, I’ll ask for an alternative.",
      "a2-unit-4-review-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-unit-4-review-production-write",
      "Viết một báo cáo ngắn (6–8 câu) về chuyến đi có sự cố: kế hoạch ban đầu, sự việc xảy ra, cách bạn yêu cầu hỗ trợ và kết quả cuối cùng.",
      "a2-unit-4-review-communicate",
      "We were going to fly to Da Nang at seven in the evening. At the airport, the airline cancelled the flight because of bad weather. I was waiting at the gate when they made the announcement. I asked for an alternative flight, and they rebooked me for the next morning. If they pay for the hotel, I’ll stay near the airport. In the end, my luggage arrived three days later and the airline paid the extra costs.",
      ["Có kế hoạch, sự cố, yêu cầu hỗ trợ và kết quả", "Dùng ít nhất ba cấu trúc trọng tâm", "Câu nối mạch lạc"],
    ),
    exercise.speaking(
      "a2-unit-4-review-production-speak",
      "Nhiệm vụ du lịch: kể lại toàn bộ chuyến đi trong 90 giây, gồm kế hoạch, sự cố, yêu cầu hỗ trợ và xác nhận giải pháp.",
      "a2-unit-4-review-communicate",
      "We planned to fly to Da Nang on Friday evening. At the airport the flight was cancelled, and I was queuing at the transfer desk when they announced a delay. I asked for an alternative flight, so they rebooked me for the same evening. If they pay for the hotel, I’ll stay near the airport. They confirmed everything in writing, and my luggage arrived two days later.",
      ["Bốn phần đầy đủ", "Ngôn ngữ A2, không dùng cấu trúc B1", "Tự đánh giá và ghi lại một điểm cần sửa"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-unit-4-review-mastery-mc",
      "Chọn câu đúng nghĩa “Bạn không cần in lịch trình.”",
      ["You don’t have to print the itinerary.", "You mustn’t print the itinerary.", "You have to print the itinerary."],
      "You don’t have to print the itinerary.",
      "grammar",
      "a2-unit-4-review-form",
    ),
    exercise.fillBlank(
      "a2-unit-4-review-mastery-blank",
      "Điền dạng đúng: “While we ______ (wait), the airline announced a new gate.”",
      "were waiting",
      "grammar",
      "a2-unit-4-review-form",
    ),
    exercise.dictation(
      "a2-unit-4-review-mastery-dictation",
      "Nghe và chép lại câu hỏi gián tiếp ở nhà ga.",
      "Could you tell me where the transfer desk is?",
      "a2-unit-4-review-comprehension",
    ),
    exercise.translation(
      "a2-unit-4-review-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi sẽ gọi hãng bay ngay bây giờ.”",
      "I’ll call the airline now.",
      "a2-unit-4-review-form",
    ),
    exercise.speaking(
      "a2-unit-4-review-mastery-speak",
      "Trình bày lại chuyến đi có sự cố trong 90 giây, dùng ít nhất bốn cấu trúc khác nhau của Unit 4.",
      "a2-unit-4-review-communicate",
      "Our plan was to fly on Friday evening. I was queuing when the flight was cancelled, so I asked for an alternative. If they pay for the hotel, I’ll stay near the airport, and they’ll confirm it in writing. Everything worked out on the third day.",
      ["Dùng bốn cấu trúc trọng tâm", "Trình tự rõ ràng", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể xử lý một tình huống du lịch từ lúc lên kế hoạch đến khi nhận được giải pháp."],
  spiralReview: ["A1: hỏi giờ, hỏi đường, con số và ngày tháng", "A2 Unit 1 đến Unit 3: kế hoạch, nhờ giúp đỡ và kể sự việc"],
  errorCategories: ["grammar-form", "verb-tense", "word-choice", "register"],
};

export const a2Unit4 = bilingualUnitSchema.parse({
  id: unitId,
  level: "A2",
  titleVi: "Du lịch và những sự cố bất ngờ",
  titleKo: "여행과 예상치 못한 문제",
  lessons: [tripPlans, airportStation, travelProblems, askingForHelp, unitReview].map(buildLesson),
});
