import { bilingualUnitSchema } from "@/lib/curriculum/bilingual-schema";
import { buildLesson, exercise, type LessonSeed } from "./a2-lesson-factory";

const unitId = "a2-5-health-advice";

/* ------------------------------------------------------------------ *
 * Bài 1 — Mô tả triệu chứng đơn giản
 * ------------------------------------------------------------------ */
const symptoms: LessonSeed = {
  id: "a2-health-symptoms",
  unitId,
  number: 1,
  prerequisites: ["a2-unit-4-review"],
  titleVi: "Mô tả triệu chứng đơn giản",
  titleKo: "증상을 간단히 말하기",
  situationVi: "Sora thấy mệt sau nhiều ngày ngủ ít, cô mô tả triệu chứng cho Linh và chuẩn bị đi khám.",
  situationKo: "소라는 며칠 동안 잠을 적게 자서 몸이 안 좋아요. 린에게 증상을 설명하고 병원에 갈 준비를 해요.",
  objectives: [
    { id: "a2-health-symptoms-communicate", en: "Describe simple symptoms clearly.", vi: "Mô tả rõ những triệu chứng đơn giản.", ko: "간단한 증상을 분명하게 설명할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-health-symptoms-form", en: "Use have / have got and It hurts when…", vi: "Dùng have / have got và cấu trúc It hurts when…", ko: "have / have got과 It hurts when…을 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-health-symptoms-comprehension", en: "Understand how long and how often someone feels ill.", vi: "Nghe được ai đó khó chịu bao lâu và bao lâu một lần.", ko: "아픈 기간과 증상이 얼마나 자주 나타나는지 들을 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["symptom", "symptom", "triệu chứng", "증상", "/ˈsɪmptəm/", "SYMptom", "neutral", ["a common symptom", "describe the symptoms"]],
    ["sore-throat", "sore throat", "đau họng", "목이 아픔", "/sɔː θrəʊt/", "sore THROAT", "neutral", ["a bad sore throat", "have a sore throat"]],
    ["headache", "headache", "đau đầu", "두통", "/ˈhedeɪk/", "HEADache", "neutral", ["a terrible headache", "get a headache"]],
    ["fever", "a slight fever", "sốt nhẹ", "미열", "/ˈfiːvə(r)/", "FEver", "neutral", ["have a fever", "a high fever"]],
    ["cough", "a dry cough", "ho khan", "마른기침", "/kɒf/", "COUGH", "neutral", ["a dry cough", "a cough at night"]],
    ["runny-nose", "a runny nose", "chảy nước mũi", "콧물", "/ˈrʌni nəʊz/", "RUNny nose", "casual", ["a runny nose", "a blocked nose"]],
    ["stomachache", "stomachache", "đau bụng", "복통", "/ˈstʌməkeɪk/", "STOMachache", "casual", ["a bad stomachache", "have a stomachache"]],
    ["hurt", "it hurts when I swallow", "đau khi tôi nuốt", "삼킬 때 아프다", "/hɜːt/", "HURT", "neutral", ["it hurts when", "my back hurts"]],
    ["dizzy", "feel dizzy", "thấy chóng mặt", "어지럽다", "/ˈdɪzi/", "DIZzy", "neutral", ["feel dizzy", "a little dizzy"]],
    ["medicine", "take medicine", "uống thuốc", "약을 먹다", "/ˈmedsn/", "MEDicine", "neutral", ["take medicine", "medicine for a cough"]],
  ],
  dialogue: [
    ["Linh", "You look pale today. Are you okay?", "Hôm nay trông bạn nhợt nhạt. Bạn ổn không?", "오늘 안색이 안 좋아 보여요. 괜찮아요?", "casual"],
    ["Sora", "Not really. I’ve got a sore throat and a headache.", "Không hẳn. Tôi bị đau họng và đau đầu.", "별로요. 목이 아프고 머리도 아파요.", "casual"],
    ["Linh", "How long have you felt like this?", "Bạn thấy như vậy bao lâu rồi?", "이런 증상이 얼마나 됐어요?", "neutral"],
    ["Sora", "Since Monday. I also have a slight fever in the evening.", "Từ thứ Hai. Buổi tối tôi còn hơi sốt.", "월요일부터요. 저녁에는 미열도 있어요.", "neutral"],
    ["Linh", "Do you have a cough?", "Bạn có ho không?", "기침도 해요?", "neutral"],
    ["Sora", "A dry cough, mostly at night. It hurts when I swallow.", "Ho khan, chủ yếu ban đêm. Tôi đau khi nuốt.", "마른기침인데 주로 밤에 나요. 삼킬 때 아파요.", "neutral"],
    ["Linh", "Did you sleep well last week?", "Tuần trước bạn ngủ ngon không?", "지난주에 잠은 잘 잤어요?", "neutral"],
    ["Sora", "No. I drank too much coffee and stayed up late three nights.", "Không. Tôi uống quá nhiều cà phê và thức khuya ba đêm.", "아니요. 커피를 너무 많이 마시고 사흘 밤을 늦게 잤어요.", "casual"],
    ["Linh", "You don’t drink enough water either. You should see a doctor tomorrow.", "Bạn cũng không uống đủ nước. Mai bạn nên đi khám bác sĩ.", "물도 충분히 안 마시잖아요. 내일 병원에 가 보세요.", "casual"],
    ["Sora", "You’re right. I’ll book an appointment for tomorrow morning.", "Bạn nói đúng. Tôi sẽ đặt lịch hẹn sáng mai.", "맞아요. 내일 아침으로 예약할게요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "Mô tả triệu chứng với have và have got",
      titleKo: "have, have got으로 증상 말하기",
      explanationVi: "Dùng have + danh từ hoặc have got + danh từ để nói triệu chứng: “I have a sore throat.” / “I’ve got a headache.” Với cơn đau cụ thể, dùng It hurts when…: “It hurts when I swallow.”",
      explanationKo: "증상은 have 또는 have got 뒤에 명사를 붙여 말해요. 특정 동작에서 아플 때는 It hurts when…을 써요.",
      easierKorean: "아픈 곳은 have a + 증상, 아플 때는 It hurts when…으로 말해요.",
    },
    {
      titleVi: "too much, too many và enough",
      titleKo: "too much, too many, enough",
      explanationVi: "too much dùng trước danh từ không đếm được: “too much coffee”. too many dùng trước danh từ đếm được số nhiều: “too many late nights”. enough đứng sau tính từ hoặc trước danh từ: “I don’t drink enough water.”",
      explanationKo: "too much는 셀 수 없는 명사, too many는 셀 수 있는 복수 명사 앞에 써요. enough는 형용사 뒤나 명사 앞에 와요.",
      easierKorean: "커피는 too much, 밤은 too many, 물은 enough water예요.",
    },
  ],
  examples: [
    ["I’ve got a sore throat and a headache.", "Tôi bị đau họng và đau đầu.", "목이 아프고 머리도 아파요.", "Sora nói với Linh ở văn phòng buổi sáng."],
    ["She has a slight fever this evening.", "Tối nay cô ấy hơi sốt.", "그녀는 오늘 저녁에 미열이 있어요.", "Linh nhắn tin cho em gái của Sora."],
    ["It hurts when I swallow.", "Tôi đau khi nuốt.", "삼킬 때 아파요.", "Câu mô tả chính xác nhất cho bác sĩ."],
    ["I have a dry cough at night.", "Ban đêm tôi ho khan.", "밤에 마른기침을 해요.", "Sora kể thêm triệu chứng trong cuộc gọi."],
    ["My nose is runny and my eyes are tired.", "Mũi tôi chảy nước và mắt thì mỏi.", "콧물이 나고 눈이 피곤해요.", "Mô tả khi Sora bị cảm nhẹ."],
    ["I drank too much coffee last week.", "Tuần trước tôi uống quá nhiều cà phê.", "지난주에 커피를 너무 많이 마셨어요.", "Linh hỏi lý do Sora mất ngủ."],
    ["There were too many late nights before the deadline.", "Có quá nhiều đêm thức khuya trước hạn chót.", "마감 전에 늦게 잔 날이 너무 많았어요.", "Sora giải thích nguyên nhân mệt mỏi."],
    ["I don’t get enough sleep during the week.", "Trong tuần tôi không ngủ đủ.", "평일에는 잠이 충분하지 않아요.", "Sora thừa nhận thói quen của mình với bác sĩ."],
    ["You should drink more water.", "Bạn nên uống nhiều nước hơn.", "물을 더 마시는 게 좋아요.", "Linh đưa ra lời khuyên đơn giản."],
    ["Don’t take medicine on an empty stomach.", "Đừng uống thuốc lúc bụng đói.", "빈속에 약을 먹지 마세요.", "Dược sĩ nhắc khi bán thuốc giảm đau."],
    ["I felt dizzy when I stood up quickly.", "Tôi thấy chóng mặt khi đứng lên nhanh.", "급하게 일어났을 때 어지러웠어요.", "Triệu chứng Sora mô tả thêm ở phòng khám."],
    ["How long have you had this stomachache?", "Bạn bị đau bụng bao lâu rồi?", "이 복통은 얼마나 됐어요?", "Câu hỏi thường gặp của bác sĩ."],
    ["The pain is better in the morning.", "Cơn đau đỡ hơn vào buổi sáng.", "아침에는 통증이 나아져요.", "Thông tin hữu ích khi bác sĩ hỏi chi tiết."],
    ["I usually feel worse in the evening.", "Tôi thường thấy mệt hơn vào buổi tối.", "저녁에 보통 더 안 좋아져요.", "Sora trả lời bác sĩ về thời điểm nặng nhất."],
    ["Take a rest and call me if it gets worse.", "Nghỉ ngơi đi và gọi cho tôi nếu nặng hơn.", "쉬고 더 심해지면 전화하세요.", "Câu kết của bác sĩ trong buổi khám."],
    ["I’ve taken my temperature and it’s 37.8.", "Tôi đã đo nhiệt độ và là 37,8 độ.", "체온을 재 봤는데 37.8도예요.", "Sora báo thông tin khi gọi cho phòng khám."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-health-symptoms-listen-mc",
      "Nghe câu “It hurts when I swallow.” và chọn triệu chứng đúng.",
      ["Sora thấy đau khi nuốt.", "Sora đau bụng khi ăn.", "Sora đau chân khi đi bộ."],
      "Sora thấy đau khi nuốt.",
      "listening",
      "a2-health-symptoms-comprehension",
      "Chú ý từ “swallow”.",
    ),
    exercise.dictation(
      "a2-health-symptoms-listen-dictation",
      "Nghe và chép lại câu hỏi của bác sĩ.",
      "How long have you had this stomachache?",
      "a2-health-symptoms-comprehension",
    ),
  ],
  shadowing: {
    line: "I don’t get enough sleep during the week.",
    notesVi: ["Nhấn vào “enough” vì đó là điểm cần bác sĩ chú ý.", "Nối “get_enough” thành một cụm liền."],
    notesKo: ["“enough”를 살짝 세게 말하면 원인이 분명해져요.", "“get enough”는 붙여서 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-health-symptoms-guided-mc",
      "Chọn câu đúng.",
      ["I’ve got a headache.", "I’ve got headache.", "I have got a headaches."],
      "I’ve got a headache.",
      "grammar",
      "a2-health-symptoms-form",
    ),
    exercise.fillBlank(
      "a2-health-symptoms-guided-blank",
      "Điền “too much”, “too many” hoặc “enough”: “You drank ______ coffee last week.”",
      "too much",
      "grammar",
      "a2-health-symptoms-form",
      "Coffee là danh từ không đếm được.",
    ),
    exercise.arrange(
      "a2-health-symptoms-guided-arrange",
      "Sắp xếp thành câu mô tả triệu chứng.",
      ["It", "hurts", "when", "I", "swallow", "."],
      "It hurts when I swallow .",
      "a2-health-symptoms-form",
    ),
    exercise.translation(
      "a2-health-symptoms-guided-translate",
      "Dịch sang tiếng Anh: “Tôi không ngủ đủ trong tuần.”",
      "I don’t get enough sleep during the week.",
      "a2-health-symptoms-communicate",
    ),
  ],
  production: [
    exercise.written(
      "a2-health-symptoms-production-write",
      "Viết 5 câu mô tả tình trạng của bạn hoặc một người bạn: hai triệu chứng, thời gian kéo dài, một thói quen liên quan và một câu với too much, too many hoặc enough.",
      "a2-health-symptoms-communicate",
      "My sister has a sore throat and a dry cough. She has felt like this since Sunday. She has too many late nights because of her exams, and she doesn’t drink enough water. She is going to see a doctor tomorrow.",
      ["Có hai triệu chứng rõ ràng", "Có thời gian kéo dài", "Dùng đúng một trong ba cấu trúc lượng"],
    ),
    exercise.speaking(
      "a2-health-symptoms-production-speak",
      "Gọi điện cho phòng khám và mô tả triệu chứng: hai triệu chứng, thời gian, mức độ và một câu hỏi về việc có cần đến khám không.",
      "a2-health-symptoms-communicate",
      "Hello, I’d like to make an appointment. I’ve got a sore throat and a headache, and I’ve felt ill since Monday. It hurts when I swallow and I have a slight fever in the evening. Do I need to come in tomorrow?",
      ["Có hai triệu chứng và thời gian", "Có một câu hỏi cho nhân viên", "Giọng rõ ràng, tốc độ vừa phải"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-health-symptoms-mastery-mc",
      "Chọn câu nói đúng về số lần ngủ khuya quá nhiều.",
      ["I had too many late nights last week.", "I had too much late nights last week.", "I had enough late nights last week."],
      "I had too many late nights last week.",
      "grammar",
      "a2-health-symptoms-form",
    ),
    exercise.fillBlank(
      "a2-health-symptoms-mastery-blank",
      "Điền “enough” hoặc “too much”: “I don’t eat ______ vegetables.”",
      "enough",
      "grammar",
      "a2-health-symptoms-form",
    ),
    exercise.dictation(
      "a2-health-symptoms-mastery-dictation",
      "Nghe và chép lại câu mô tả thời điểm nặng nhất.",
      "I usually feel worse in the evening.",
      "a2-health-symptoms-comprehension",
    ),
    exercise.translation(
      "a2-health-symptoms-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi bị sốt nhẹ và ho khan.”",
      "I have a slight fever and a dry cough.",
      "a2-health-symptoms-communicate",
    ),
    exercise.speaking(
      "a2-health-symptoms-mastery-speak",
      "Mô tả tình trạng sức khỏe của bạn trong 60 giây: triệu chứng, thời gian, thói quen liên quan và lời nhờ giúp đỡ.",
      "a2-health-symptoms-communicate",
      "I’ve got a headache and a stomachache. I’ve felt ill since Friday because I’ve had too many late nights. I don’t drink enough water, and I feel dizzy in the morning. Could I see a doctor this week?",
      ["Đủ bốn phần", "Dùng have hoặc have got chính xác", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  canDo: ["Có thể mô tả triệu chứng và thời gian bị bệnh đủ rõ để người khác giúp."],
  spiralReview: ["A1: bộ phận cơ thể và con số", "A2 Unit 4: yêu cầu hỗ trợ khi gặp vấn đề"],
  errorCategories: ["word-choice", "grammar-form", "missing-word", "preposition"],
};

/* ------------------------------------------------------------------ *
 * Bài 2 — Trao đổi với bác sĩ hoặc dược sĩ
 * ------------------------------------------------------------------ */
const doctorPharmacy: LessonSeed = {
  id: "a2-doctor-pharmacy",
  unitId,
  number: 2,
  prerequisites: ["a2-health-symptoms"],
  titleVi: "Trao đổi với bác sĩ hoặc dược sĩ",
  titleKo: "의사와 약사와 이야기하기",
  situationVi: "Sora đi khám buổi sáng, nhận đơn thuốc và hỏi dược sĩ cách dùng thuốc đúng.",
  situationKo: "소라는 아침에 진료를 받고 처방전을 받아서, 약사에게 약을 어떻게 먹는지 물어봐요.",
  objectives: [
    { id: "a2-doctor-pharmacy-communicate", en: "Answer a doctor’s questions and understand instructions.", vi: "Trả lời câu hỏi của bác sĩ và hiểu hướng dẫn điều trị.", ko: "의사 선생님의 질문에 답하고 안내를 이해할 수 있어요.", skills: ["speaking", "listening"] },
    { id: "a2-doctor-pharmacy-form", en: "Use must, mustn’t and have to for medical instructions.", vi: "Dùng must, mustn’t và have to cho hướng dẫn y tế.", ko: "must, mustn’t, have to로 복약 지도를 말할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-doctor-pharmacy-sequence", en: "Give and follow instructions in order.", vi: "Đưa ra và làm theo hướng dẫn theo đúng thứ tự.", ko: "순서에 맞게 지시를 말하고 따라 할 수 있어요.", skills: ["reading", "writing"] },
  ],
  vocab: [
    ["prescription", "prescription", "đơn thuốc", "처방전", "/prɪˈskrɪpʃn/", "preSCRIPtion", "formal", ["write a prescription", "take the prescription to the pharmacy"]],
    ["pharmacist", "pharmacist", "dược sĩ", "약사", "/ˈfɑːməsɪst/", "PHARmacist", "formal", ["ask the pharmacist", "the pharmacist explained"]],
    ["dose", "dose", "liều lượng", "복용량", "/dəʊs/", "DOSE", "formal", ["the right dose", "a small dose"]],
    ["painkiller", "painkiller", "thuốc giảm đau", "진통제", "/ˈpeɪnkɪlə(r)/", "PAINkiller", "neutral", ["take a painkiller", "a strong painkiller"]],
    ["twice-a-day", "twice a day", "hai lần một ngày", "하루에 두 번", "/twaɪs ə deɪ/", "twice a DAY", "neutral", ["take it twice a day", "twice a day after meals"]],
    ["side-effect", "side effect", "tác dụng phụ", "부작용", "/ˈsaɪd ɪfekt/", "SIDE effect", "formal", ["a common side effect", "any side effects"]],
    ["allergy", "allergy", "dị ứng", "알레르기", "/ˈælədʒi/", "ALlergy", "formal", ["a medicine allergy", "ask about allergies"]],
    ["appointment", "make an appointment", "đặt lịch khám", "진료 예약을 하다", "/əˈpɔɪntmənt/", "apPOINTment", "neutral", ["make an appointment", "an appointment at nine"]],
    ["temperature", "take your temperature", "đo nhiệt độ", "체온을 재다", "/ˈtemprətʃə(r)/", "TEMperature", "neutral", ["take your temperature", "a high temperature"]],
    ["pharmacy", "pharmacy", "hiệu thuốc", "약국", "/ˈfɑːməsi/", "PHARmacy", "neutral", ["go to the pharmacy", "an open pharmacy"]],
  ],
  dialogue: [
    ["Doctor", "Good morning. What can I do for you?", "Chào buổi sáng. Tôi có thể giúp gì cho bạn?", "안녕하세요. 어떻게 도와드릴까요?", "formal"],
    ["Sora", "I’ve had a sore throat and a cough since Monday.", "Tôi bị đau họng và ho từ thứ Hai.", "월요일부터 목이 아프고 기침을 해요.", "neutral"],
    ["Doctor", "Do you have a temperature?", "Bạn có sốt không?", "열도 있나요?", "formal"],
    ["Sora", "Yes, 37.8 in the evening. I’m allergic to penicillin.", "Có, 37,8 độ vào buổi tối. Tôi dị ứng với penicillin.", "네, 저녁에 37.8도예요. 페니실린 알레르기가 있어요.", "neutral"],
    ["Doctor", "Thank you for telling me. You have a throat infection, but it’s not serious.", "Cảm ơn bạn đã cho biết. Bạn bị viêm họng nhưng không nghiêm trọng.", "알려 주셔서 감사합니다. 목 감염이지만 심하지 않아요.", "formal"],
    ["Sora", "Do I have to take antibiotics?", "Tôi có phải uống kháng sinh không?", "항생제를 먹어야 하나요?", "neutral"],
    ["Doctor", "Not this time. You must rest and you mustn’t drink coffee.", "Lần này thì không. Bạn phải nghỉ ngơi và không được uống cà phê.", "이번에는 필요 없어요. 쉬어야 하고 커피는 마시면 안 돼요.", "formal"],
    ["Sora", "Understood. Should I stay home tomorrow?", "Tôi hiểu rồi. Mai tôi có nên ở nhà không?", "알겠습니다. 내일 집에 있는 게 좋을까요?", "neutral"],
    ["Doctor", "Yes, stay home for two days and drink warm water. Here’s your prescription.", "Có, ở nhà hai ngày và uống nước ấm. Đây là đơn thuốc của bạn.", "네, 이틀 쉬고 따뜻한 물을 마시세요. 여기 처방전입니다.", "formal"],
    ["Sora", "Thank you. I’ll take it to the pharmacy now.", "Cảm ơn bác sĩ. Tôi sẽ mang ra hiệu thuốc ngay.", "감사합니다. 지금 약국에 가져갈게요.", "formal"],
    ["Pharmacist", "First, take one tablet after breakfast.", "Đầu tiên, uống một viên sau bữa sáng.", "먼저 아침 식사 후에 한 알 드세요.", "formal"],
    ["Sora", "And after dinner as well?", "Và sau bữa tối nữa phải không?", "저녁 식사 후에도요?", "neutral"],
    ["Pharmacist", "Yes, twice a day. Then use the spray at night. Don’t take two tablets at once.", "Vâng, hai lần một ngày. Sau đó dùng thuốc xịt vào buổi tối. Đừng uống hai viên cùng lúc.", "네, 하루 두 번이에요. 그리고 밤에 스프레이를 쓰세요. 두 알을 한꺼번에 먹으면 안 돼요.", "formal"],
  ],
  grammar: [
    {
      titleVi: "must, mustn’t và have to trong hướng dẫn y tế",
      titleKo: "복약 지도의 must, mustn’t, have to",
      explanationVi: "must nhấn mạnh việc bắt buộc do người nói quyết định: “You must rest.” mustn’t là cấm: “You mustn’t drink coffee.” have to dùng cho quy định bên ngoài: “Do I have to take antibiotics?”",
      explanationKo: "must는 꼭 해야 하는 일을 강하게 말해요. mustn’t는 하면 안 되는 일, have to는 규칙이나 지시에 따른 의무를 말해요.",
      easierKorean: "꼭 하라는 말은 must, 하면 안 된다는 말은 mustn’t예요.",
    },
    {
      titleVi: "Câu mệnh lệnh và hướng dẫn theo trình tự",
      titleKo: "순서대로 설명하는 지시문",
      explanationVi: "Dùng câu mệnh lệnh (động từ nguyên mẫu ở đầu câu) để ra chỉ dẫn: “Take one tablet after breakfast.” Nối các bước bằng first, then, after that, finally để người nghe làm đúng thứ tự.",
      explanationKo: "지시할 때는 동사원형으로 문장을 시작해요. first, then, after that, finally로 순서를 알려 줘요.",
      easierKorean: "먼저 First, 그다음 Then, 마지막은 Finally로 이어 말해요.",
    },
  ],
  examples: [
    ["You must rest for two days.", "Bạn phải nghỉ ngơi hai ngày.", "이틀 동안 쉬어야 해요.", "Bác sĩ kết luận sau khi khám họng."],
    ["You mustn’t drink coffee while you take this medicine.", "Bạn không được uống cà phê khi đang dùng thuốc này.", "이 약을 먹는 동안 커피를 마시면 안 돼요.", "Lời dặn của bác sĩ với Sora."],
    ["Do I have to take antibiotics?", "Tôi có phải uống kháng sinh không?", "항생제를 먹어야 하나요?", "Câu hỏi Sora hỏi bác sĩ ở phòng khám."],
    ["You don’t have to come back if the fever stops.", "Bạn không cần quay lại nếu hết sốt.", "열이 내리면 다시 오지 않아도 돼요.", "Bác sĩ trả lời về lần tái khám."],
    ["I’m allergic to penicillin.", "Tôi dị ứng với penicillin.", "페니실린 알레르기가 있어요.", "Thông tin Sora nói ngay khi bác sĩ kê thuốc."],
    ["First, take one tablet after breakfast.", "Đầu tiên, uống một viên sau bữa sáng.", "먼저 아침 식사 후에 한 알 드세요.", "Hướng dẫn đầu tiên của dược sĩ."],
    ["Then, use the spray before you go to bed.", "Sau đó, dùng thuốc xịt trước khi đi ngủ.", "그다음에는 자기 전에 스프레이를 쓰세요.", "Bước thứ hai trong hướng dẫn dùng thuốc."],
    ["After that, drink warm water.", "Sau đó, uống nước ấm.", "그 후에는 따뜻한 물을 마시세요.", "Thói quen hỗ trợ cổ họng trong hai ngày."],
    ["Finally, come back if the pain gets worse.", "Cuối cùng, hãy quay lại nếu cơn đau nặng hơn.", "마지막으로 통증이 심해지면 다시 오세요.", "Bước cuối cùng trong hướng dẫn của bác sĩ."],
    ["Are there any side effects?", "Thuốc có tác dụng phụ gì không?", "부작용이 있나요?", "Câu Sora hỏi dược sĩ khi nhận thuốc."],
    ["This painkiller can make you sleepy.", "Thuốc giảm đau này có thể làm bạn buồn ngủ.", "이 진통제는 졸릴 수 있어요.", "Cảnh báo của dược sĩ trước khi Sora lái xe."],
    ["Take it twice a day, morning and evening.", "Uống hai lần một ngày, sáng và tối.", "하루 두 번, 아침과 저녁에 드세요.", "Hướng dẫn liều lượng trên nhãn thuốc."],
    ["Don’t take two tablets at the same time.", "Đừng uống hai viên cùng một lúc.", "두 알을 동시에 먹지 마세요.", "Lời nhắc quan trọng khi dùng thuốc giảm đau."],
    ["The pharmacist explained the dose slowly.", "Dược sĩ giải thích liều lượng một cách chậm rãi.", "약사가 복용량을 천천히 설명해 주었어요.", "Sora kể lại với Linh sau khi mua thuốc."],
    ["I made an appointment for next Monday.", "Tôi đã đặt lịch hẹn cho thứ Hai tới.", "다음 주 월요일로 예약했어요.", "Sora chủ động đặt lịch tái khám."],
    ["You should drink tea instead of coffee.", "Bạn nên uống trà thay vì cà phê.", "커피 대신 차를 마시는 게 좋아요.", "Dược sĩ gợi ý thay đổi nhỏ trong hai ngày."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-doctor-pharmacy-listen-mc",
      "Nghe câu “First, take one tablet after breakfast.” và chọn hướng dẫn đúng.",
      ["Uống một viên sau bữa sáng.", "Uống một viên trước bữa sáng.", "Uống hai viên sau bữa tối."],
      "Uống một viên sau bữa sáng.",
      "listening",
      "a2-doctor-pharmacy-sequence",
      "“After breakfast” là mốc thời gian.",
    ),
    exercise.dictation(
      "a2-doctor-pharmacy-listen-dictation",
      "Nghe và chép lại lời dặn quan trọng của bác sĩ.",
      "You must rest for two days.",
      "a2-doctor-pharmacy-form",
    ),
  ],
  shadowing: {
    line: "Do I have to take antibiotics?",
    notesVi: ["Lên giọng ở “antibiotics” vì đây là câu hỏi.", "Nối “have_to_take” thành một cụm nhẹ, nhanh."],
    notesKo: ["질문이니까 “antibiotics”를 올려 말해요.", "“have to take”는 가볍게 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-doctor-pharmacy-guided-mc",
      "Chọn câu đúng: bác sĩ muốn nói “Bạn không được uống cà phê.”",
      ["You mustn’t drink coffee.", "You don’t have to drink coffee.", "You must drink coffee."],
      "You mustn’t drink coffee.",
      "grammar",
      "a2-doctor-pharmacy-form",
    ),
    exercise.arrange(
      "a2-doctor-pharmacy-guided-arrange",
      "Sắp xếp thành hướng dẫn theo trình tự.",
      ["First", ",", "take", "one", "tablet", "after", "breakfast", "."],
      "First , take one tablet after breakfast .",
      "a2-doctor-pharmacy-sequence",
    ),
    exercise.fillBlank(
      "a2-doctor-pharmacy-guided-blank",
      "Điền “mustn’t” hoặc “don’t have to”: “You ______ come back if you feel better.”",
      "don’t have to",
      "grammar",
      "a2-doctor-pharmacy-form",
      "Đây không phải điều bị cấm.",
    ),
    exercise.translation(
      "a2-doctor-pharmacy-guided-translate",
      "Dịch sang tiếng Anh: “Thuốc này có tác dụng phụ gì không?”",
      "Are there any side effects?",
      "a2-doctor-pharmacy-communicate",
    ),
  ],
  production: [
    exercise.written(
      "a2-doctor-pharmacy-production-write",
      "Viết hướng dẫn dùng thuốc trong 5–6 câu cho một người bạn: liều lượng, thời điểm, hai việc phải làm hoặc không được làm và một lời nhắc cuối.",
      "a2-doctor-pharmacy-sequence",
      "First, take one tablet after breakfast. Then take the second one after dinner. You must drink warm water, and you mustn’t drink coffee for three days. Finally, come back if the fever starts again. Don’t take two tablets at the same time.",
      ["Có ít nhất ba bước theo trình tự", "Dùng must, mustn’t hoặc don’t have to", "Câu ngắn, dễ làm theo"],
    ),
    exercise.speaking(
      "a2-doctor-pharmacy-production-speak",
      "Đóng vai buổi khám: trả lời hai câu hỏi của bác sĩ, nói một dị ứng và hỏi lại một hướng dẫn.",
      "a2-doctor-pharmacy-communicate",
      "I’ve had a sore throat and a cough since Monday, and I have a slight fever in the evening. I’m allergic to penicillin. Do I have to take antibiotics? Could you repeat how many tablets I should take?",
      ["Có câu trả lời và một dị ứng", "Có một câu hỏi làm rõ", "Giọng điệu lịch sự"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-doctor-pharmacy-mastery-mc",
      "Chọn câu phù hợp khi dược sĩ nói thuốc có thể gây buồn ngủ.",
      ["I won’t drive after taking this medicine.", "I will drive after taking this medicine.", "I must drive after taking this medicine."],
      "I won’t drive after taking this medicine.",
      "grammar",
      "a2-doctor-pharmacy-form",
    ),
    exercise.fillBlank(
      "a2-doctor-pharmacy-mastery-blank",
      "Điền “must” hoặc “mustn’t”: “You ______ take two tablets at the same time.”",
      "mustn’t",
      "grammar",
      "a2-doctor-pharmacy-form",
    ),
    exercise.dictation(
      "a2-doctor-pharmacy-mastery-dictation",
      "Nghe và chép lại hướng dẫn về liều lượng.",
      "Take it twice a day, morning and evening.",
      "a2-doctor-pharmacy-sequence",
    ),
    exercise.translation(
      "a2-doctor-pharmacy-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi dị ứng với kháng sinh này.”",
      "I’m allergic to this antibiotic.",
      "a2-doctor-pharmacy-communicate",
    ),
    exercise.speaking(
      "a2-doctor-pharmacy-mastery-speak",
      "Nói lại toàn bộ buổi khám và phần hỏi thuốc ở hiệu thuốc trong 75 giây.",
      "a2-doctor-pharmacy-communicate",
      "I’ve had a sore throat and a slight fever since Monday, and I’m allergic to penicillin. The doctor said I must rest and I mustn’t drink coffee. At the pharmacy they told me to take one tablet after breakfast and one after dinner, twice a day.",
      ["Có thông tin khám và hướng dẫn thuốc", "Dùng must hoặc mustn’t ít nhất một lần", "Trình bày rõ, tự sửa khi cần"],
    ),
  ],
  canDo: ["Có thể trao đổi với bác sĩ hoặc dược sĩ và làm theo hướng dẫn dùng thuốc."],
  spiralReview: ["A2 Unit 5 bài 1: mô tả triệu chứng", "A2 Unit 4: hỏi thông tin gián tiếp khi cần làm rõ"],
  errorCategories: ["grammar-form", "word-choice", "missing-word", "word-order"],
};

/* ------------------------------------------------------------------ *
 * Bài 3 — Thói quen và thay đổi lối sống
 * ------------------------------------------------------------------ */
const healthyHabits: LessonSeed = {
  id: "a2-healthy-habits",
  unitId,
  number: 3,
  prerequisites: ["a2-doctor-pharmacy"],
  titleVi: "Thói quen và thay đổi lối sống",
  titleKo: "습관과 생활 방식 바꾸기",
  situationVi: "Sora kể cho Linh nghe những thói quen cũ và kế hoạch thay đổi sau khi ốm.",
  situationKo: "소라는 린에게 예전 습관과 아픈 뒤 세운 생활 변화 계획을 이야기해요.",
  objectives: [
    { id: "a2-healthy-habits-communicate", en: "Talk about habits and lifestyle changes.", vi: "Nói về thói quen và những thay đổi trong lối sống.", ko: "습관과 생활 방식의 변화를 말할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-healthy-habits-frequency", en: "Use adverbs and phrases of frequency accurately.", vi: "Dùng đúng trạng từ và cụm từ chỉ tần suất.", ko: "빈도 부사와 빈도 표현을 정확하게 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-healthy-habits-gerund", en: "Use gerunds after common verbs.", vi: "Dùng động danh từ sau một số động từ thông dụng.", ko: "자주 쓰는 동사 뒤에 동명사를 쓸 수 있어요.", skills: ["grammar", "speaking"] },
  ],
  vocab: [
    ["habit", "habit", "thói quen", "습관", "/ˈhæbɪt/", "HABit", "neutral", ["a bad habit", "change a habit"]],
    ["routine", "daily routine", "nếp sinh hoạt hằng ngày", "일상 루틴", "/ruːˈtiːn/", "rouTINE", "neutral", ["a morning routine", "change your routine"]],
    ["stay-up", "stay up late", "thức khuya", "늦게까지 깨어 있다", "/steɪ ʌp leɪt/", "stay up LATE", "casual", ["stay up late", "stay up all night"]],
    ["cut-down", "cut down on sugar", "giảm bớt đường", "설탕을 줄이다", "/kʌt daʊn ɒn/", "cut DOWN on", "neutral", ["cut down on coffee", "cut down on screen time"]],
    ["take-up", "take up running", "bắt đầu chạy bộ", "달리기를 시작하다", "/teɪk ʌp/", "take UP", "neutral", ["take up a sport", "take up yoga"]],
    ["balanced-diet", "a balanced diet", "chế độ ăn cân bằng", "균형 잡힌 식사", "/ˈbælənst ˈdaɪət/", "BALanced DIet", "neutral", ["eat a balanced diet", "a healthy balanced diet"]],
    ["work-out", "work out", "tập thể dục", "운동하다", "/wɜːk aʊt/", "work OUT", "casual", ["work out twice a week", "work out at home"]],
    ["screen-time", "screen time", "thời gian dùng màn hình", "화면 보는 시간", "/ˈskriːn taɪm/", "SCREEN time", "neutral", ["too much screen time", "limit screen time"]],
    ["break", "take a break", "nghỉ giải lao", "휴식을 취하다", "/teɪk ə breɪk/", "take a BREAK", "neutral", ["take a short break", "a break from work"]],
    ["energy", "have more energy", "có nhiều năng lượng hơn", "기운이 더 나다", "/ˈenədʒi/", "ENergy", "neutral", ["have more energy", "low energy"]],
  ],
  dialogue: [
    ["Linh", "How do you feel after a week without coffee?", "Bạn thấy thế nào sau một tuần không uống cà phê?", "커피 없이 일주일 지내니까 어때요?", "casual"],
    ["Sora", "Much better. I usually slept badly, but now I sleep well.", "Khá hơn nhiều. Trước đây tôi thường ngủ kém, giờ thì ngủ ngon.", "훨씬 좋아요. 예전에는 잠을 잘 못 잤는데 지금은 잘 자요.", "casual"],
    ["Linh", "Do you still work late in the evening?", "Bạn vẫn làm việc muộn buổi tối chứ?", "저녁에도 계속 늦게까지 일해요?", "neutral"],
    ["Sora", "Rarely. I try to finish before seven, and I never stay up late on weekdays.", "Hiếm khi. Tôi cố gắng xong trước bảy giờ, và tôi không bao giờ thức khuya ngày thường.", "거의 안 해요. 7시 전에 끝내려고 하고, 평일에는 절대 늦게 자지 않아요.", "neutral"],
    ["Linh", "Have you changed your meals as well?", "Bạn có đổi bữa ăn không?", "식사도 바꿨어요?", "neutral"],
    ["Sora", "Yes, I’ve cut down on sugar and I’m eating more vegetables.", "Có, tôi đã giảm đường và ăn nhiều rau hơn.", "네, 설탕을 줄이고 채소를 더 먹고 있어요.", "neutral"],
    ["Linh", "That’s great. And exercise?", "Tuyệt đấy. Còn tập thể dục thì sao?", "좋네요. 운동은요?", "casual"],
    ["Sora", "I’ve taken up swimming. It’s easier for my back than running.", "Tôi đã bắt đầu bơi. Bơi dễ chịu cho lưng tôi hơn chạy bộ.", "수영을 시작했어요. 달리기보다 허리에 편해요.", "neutral"],
    ["Linh", "How often do you go?", "Bạn đi bao lâu một lần?", "얼마나 자주 가요?", "neutral"],
    ["Sora", "Twice a week, and I walk every morning before work.", "Hai lần một tuần, và tôi đi bộ mỗi sáng trước khi làm.", "일주일에 두 번, 그리고 평일 아침마다 걷어요.", "neutral"],
    ["Linh", "It sounds like you’ve changed a lot.", "Có vẻ như bạn đã thay đổi nhiều đấy.", "많이 바뀐 것 같네요.", "casual"],
    ["Sora", "I have, but I still enjoy a coffee on Sunday morning.", "Đúng vậy, nhưng tôi vẫn thích một ly cà phê sáng Chủ nhật.", "그래요. 그래도 일요일 아침에는 커피를 즐겨요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "Trạng từ và cụm từ chỉ tần suất",
      titleKo: "빈도 부사와 빈도 표현",
      explanationVi: "Trạng từ tần suất đứng trước động từ thường và sau động từ be: “I usually slept badly.” “I never stay up late.” Cụm từ dài hơn như twice a week, every morning, once a month thường đứng cuối câu.",
      explanationKo: "빈도 부사는 일반동사 앞, be동사 뒤에 와요. twice a week, every morning 같은 긴 표현은 보통 문장 끝에 써요.",
      easierKorean: "보통 usually는 동사 앞, twice a week는 문장 끝에 써요.",
    },
    {
      titleVi: "Động danh từ sau một số động từ",
      titleKo: "자주 쓰는 동사 뒤의 동명사",
      explanationVi: "Sau enjoy, avoid, keep, stop, finish, suggest, dùng động từ + -ing: “I still enjoy having a coffee.” “I’ve stopped drinking coffee at night.” Không dùng động từ nguyên mẫu sau những động từ này.",
      explanationKo: "enjoy, avoid, keep, stop, finish, suggest 뒤에는 동명사(-ing)를 써요. 이 동사들 뒤에 동사원형은 쓰지 않아요.",
      easierKorean: "enjoy, stop 뒤에는 -ing 형태를 써요.",
    },
  ],
  examples: [
    ["I usually sleep badly when I drink coffee late.", "Tôi thường ngủ kém khi uống cà phê muộn.", "늦게 커피를 마시면 보통 잠을 잘 못 자요.", "Sora giải thích thói quen cũ của mình."],
    ["She never stays up late on weekdays now.", "Bây giờ cô ấy không bao giờ thức khuya ngày thường.", "그녀는 이제 평일에는 절대 늦게 자지 않아요.", "Linh nhận xét về sự thay đổi của Sora."],
    ["I go swimming twice a week.", "Tôi đi bơi hai lần một tuần.", "일주일에 두 번 수영해요.", "Câu trả lời khi được hỏi về việc tập luyện."],
    ["He takes a short break every hour.", "Anh ấy nghỉ ngắn mỗi giờ một lần.", "그는 한 시간마다 짧게 쉬어요.", "Thói quen anh đồng nghiệp giữ khi làm việc máy tính."],
    ["We occasionally eat out on Friday evening.", "Thỉnh thoảng chúng tôi ăn ngoài vào tối thứ Sáu.", "금요일 저녁에는 가끔 외식을 해요.", "Linh kể về nếp sinh hoạt gia đình."],
    ["I’ve cut down on sugar since last month.", "Tôi giảm đường từ tháng trước.", "지난달부터 설탕을 줄였어요.", "Thay đổi Sora áp dụng sau khi ốm."],
    ["He has taken up yoga to help his back.", "Anh ấy bắt đầu tập yoga để giúp lưng đỡ đau.", "허리를 위해 요가를 시작했어요.", "Em trai Linh tìm môn tập phù hợp."],
    ["I enjoy walking to work in the morning.", "Tôi thích đi bộ đến chỗ làm vào buổi sáng.", "아침에 걸어서 출근하는 걸 좋아해요.", "Sora nói về thói quen mới cô thấy dễ chịu."],
    ["She avoids using her phone before bed.", "Cô ấy tránh dùng điện thoại trước khi ngủ.", "그녀는 자기 전에 휴대폰 사용을 피해요.", "Thay đổi giúp Sora ngủ tốt hơn."],
    ["I keep forgetting to drink water.", "Tôi cứ quên uống nước.", "자꾸 물 마시는 걸 잊어요.", "Vấn đề Sora thừa nhận với Linh."],
    ["He stopped eating fast food last year.", "Anh ấy ngừng ăn đồ ăn nhanh từ năm ngoái.", "그는 작년에 패스트푸드를 끊었어요.", "Thay đổi của anh đồng nghiệp sau khi khám sức khỏe."],
    ["Do you mind taking a break with me?", "Bạn có phiền nghỉ giải lao cùng tôi không?", "저와 같이 잠깐 쉬어 주시겠어요?", "Lời đề nghị lịch sự trong giờ làm việc."],
    ["Too much screen time makes my eyes tired.", "Dùng màn hình quá nhiều làm mắt tôi mỏi.", "화면을 너무 많이 보면 눈이 피곤해요.", "Lý do Sora giới hạn thời gian dùng điện thoại."],
    ["A balanced diet gives me more energy.", "Một chế độ ăn cân bằng giúp tôi nhiều năng lượng hơn.", "균형 잡힌 식사는 기운을 더 나게 해요.", "Điều Sora nhận ra sau ba tuần thay đổi."],
    ["I suggest starting with one small change.", "Tôi gợi ý bắt đầu bằng một thay đổi nhỏ.", "작은 변화 하나로 시작하는 걸 추천해요.", "Lời khuyên Sora dành cho Linh."],
    ["It’s hard at first, but it gets easier.", "Lúc đầu khó, nhưng rồi sẽ dễ hơn.", "처음에는 어렵지만 점점 쉬워져요.", "Câu kết Sora nói về việc thay đổi thói quen."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-healthy-habits-listen-mc",
      "Nghe câu “I go swimming twice a week.” và chọn tần suất đúng.",
      ["Hai lần một tuần.", "Hai lần một tháng.", "Mỗi ngày."],
      "Hai lần một tuần.",
      "listening",
      "a2-healthy-habits-frequency",
      "Chú ý “twice a week”.",
    ),
    exercise.dictation(
      "a2-healthy-habits-listen-dictation",
      "Nghe và chép lại câu về thói quen buổi sáng.",
      "I walk every morning before work.",
      "a2-healthy-habits-communicate",
    ),
  ],
  shadowing: {
    line: "I’ve cut down on sugar since last month.",
    notesVi: ["Nhấn vào “cut down” để thể hiện sự thay đổi.", "Đọc “since last month” liền mạch, không tách từng từ."],
    notesKo: ["“cut down”을 또렷하게 말하면 변화가 잘 드러나요.", "“since last month”는 끊지 말고 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-healthy-habits-guided-mc",
      "Chọn câu đúng.",
      ["I enjoy swimming in the morning.", "I enjoy to swim in the morning.", "I enjoy swim in the morning."],
      "I enjoy swimming in the morning.",
      "grammar",
      "a2-healthy-habits-gerund",
    ),
    exercise.fillBlank(
      "a2-healthy-habits-guided-blank",
      "Điền dạng đúng: “She has stopped ______ (drink) coffee at night.”",
      "drinking",
      "grammar",
      "a2-healthy-habits-gerund",
    ),
    exercise.arrange(
      "a2-healthy-habits-guided-arrange",
      "Sắp xếp thành câu có trạng từ tần suất.",
      ["I", "never", "stay", "up", "late", "on", "weekdays", "."],
      "I never stay up late on weekdays .",
      "a2-healthy-habits-frequency",
    ),
    exercise.translation(
      "a2-healthy-habits-guided-translate",
      "Dịch sang tiếng Anh: “Tôi đi bơi hai lần một tuần.”",
      "I go swimming twice a week.",
      "a2-healthy-habits-frequency",
    ),
  ],
  production: [
    exercise.written(
      "a2-healthy-habits-production-write",
      "Viết 6 câu về thói quen của bạn: hai thói quen cũ, hai thay đổi đã bắt đầu, một tần suất và một thói quen bạn vẫn giữ.",
      "a2-healthy-habits-communicate",
      "I used to drink two cups of coffee every morning, and I often stayed up late. Since January I’ve cut down on sugar and I’ve taken up walking. I walk every morning before work, and I go to the gym twice a week. I still enjoy eating out with friends at the weekend.",
      ["Có hai thói quen cũ và hai thay đổi", "Có tần suất chính xác", "Dùng ít nhất một động danh từ"],
    ),
    exercise.speaking(
      "a2-healthy-habits-production-speak",
      "Nói 60–75 giây về một thay đổi lối sống bạn đang thực hiện: lý do, tần suất và kết quả bước đầu.",
      "a2-healthy-habits-communicate",
      "I’ve changed two habits this year. I’ve cut down on coffee because I slept badly, and I’ve taken up swimming twice a week. I enjoy walking in the morning too. At first it was hard, but now I have more energy.",
      ["Có lý do và tần suất", "Có kết quả bước đầu", "Tự nghe lại và nhận xét"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-healthy-habits-mastery-mc",
      "Chọn câu đúng vị trí trạng từ tần suất.",
      ["I rarely eat fast food now.", "I eat rarely fast food now.", "Rarely I eat fast food now."],
      "I rarely eat fast food now.",
      "grammar",
      "a2-healthy-habits-frequency",
    ),
    exercise.fillBlank(
      "a2-healthy-habits-mastery-blank",
      "Điền dạng đúng: “He avoids ______ (use) his phone in bed.”",
      "using",
      "grammar",
      "a2-healthy-habits-gerund",
    ),
    exercise.dictation(
      "a2-healthy-habits-mastery-dictation",
      "Nghe và chép lại câu về thói quen mới.",
      "I’ve taken up swimming twice a week.",
      "a2-healthy-habits-communicate",
    ),
    exercise.translation(
      "a2-healthy-habits-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi đã giảm đường từ tháng trước.”",
      "I’ve cut down on sugar since last month.",
      "a2-healthy-habits-frequency",
    ),
    exercise.speaking(
      "a2-healthy-habits-mastery-speak",
      "Trình bày kế hoạch thay đổi lối sống trong 75 giây: hai thói quen, tần suất mới và một khó khăn.",
      "a2-healthy-habits-communicate",
      "I’ve decided to change two habits. I’ve cut down on sugar, and I go walking every morning before work. I’ve also taken up swimming twice a week. The difficult part is avoiding my phone at night, but I keep trying.",
      ["Có hai thói quen và tần suất", "Có một khó khăn cụ thể", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể nói về thói quen cũ, thay đổi mới và tần suất thực hiện."],
  spiralReview: ["A1: trạng từ tần suất cơ bản", "A2 Unit 5 bài 1 và 2: triệu chứng và lời dặn của bác sĩ"],
  errorCategories: ["word-order", "grammar-form", "word-choice", "missing-word"],
};

/* ------------------------------------------------------------------ *
 * Bài 4 — Đưa ra, tiếp nhận và làm rõ lời khuyên
 * ------------------------------------------------------------------ */
const givingAdvice: LessonSeed = {
  id: "a2-giving-advice",
  unitId,
  number: 4,
  prerequisites: ["a2-healthy-habits"],
  titleVi: "Đưa ra, tiếp nhận và làm rõ lời khuyên",
  titleKo: "조언을 주고받고 확인하기",
  situationVi: "Linh kể rằng em trai cô ấy thức khuya nhiều; Sora đưa lời khuyên, hỏi lại chi tiết và cả hai chọn một bước bắt đầu.",
  situationKo: "린의 남동생이 늦게까지 깨어 있다고 해요. 소라는 조언을 하고, 자세히 물어보고, 함께 첫 단계를 정해요.",
  objectives: [
    { id: "a2-giving-advice-communicate", en: "Give, accept and clarify advice.", vi: "Đưa ra, tiếp nhận và làm rõ lời khuyên.", ko: "조언을 하고 받아들이고 확인할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-giving-advice-form", en: "Use should, shouldn’t and could for advice.", vi: "Dùng should, shouldn’t và could để khuyên.", ko: "should, shouldn’t, could로 조언할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-giving-advice-comprehension", en: "Pick out the advice and the reason in a conversation.", vi: "Nghe ra lời khuyên và lý do trong một cuộc trò chuyện.", ko: "대화에서 조언과 이유를 찾아낼 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["advice", "give advice", "đưa ra lời khuyên", "조언을 하다", "/ədˈvaɪs/", "adVICE", "neutral", ["give advice", "ask for advice"]],
    ["suggest", "suggest a change", "gợi ý một thay đổi", "변화를 제안하다", "/səˈdʒest/", "sugGEST", "neutral", ["suggest a change", "suggest trying"]],
    ["try", "try something new", "thử điều gì mới", "새로운 것을 시도하다", "/traɪ/", "TRY", "casual", ["try again", "try something new"]],
    ["instead", "instead of", "thay vì", "대신에", "/ɪnˈsted əv/", "inSTEAD of", "neutral", ["instead of coffee", "drink tea instead"]],
    ["reason", "the reason is", "lý do là", "이유는", "/ˈriːzn/", "REAson", "neutral", ["the main reason", "for that reason"]],
    ["explain", "could you explain", "bạn có thể giải thích", "설명해 주시겠어요", "/ɪkˈspleɪn/", "exPLAIN", "neutral", ["explain again", "explain the steps"]],
    ["clarify", "clarify what you mean", "làm rõ ý bạn", "무슨 뜻인지 분명히 하다", "/ˈklærəfaɪ/", "CLARify", "formal", ["clarify the details", "clarify what you mean"]],
    ["reasonable", "that sounds reasonable", "nghe hợp lý đấy", "합리적으로 들리다", "/ˈriːznəbl/", "REAsonable", "neutral", ["a reasonable idea", "sound reasonable"]],
    ["agree", "I agree with you", "tôi đồng ý với bạn", "동의하다", "/əˈɡriː/", "aGREE", "neutral", ["agree with", "agree about the plan"]],
    ["step", "the first step", "bước đầu tiên", "첫 단계", "/step/", "STEP", "neutral", ["the first step", "one step at a time"]],
  ],
  dialogue: [
    ["Linh", "My brother stays up until two every night. What should he do?", "Em trai tôi thức đến hai giờ mỗi đêm. Nó nên làm gì?", "제 남동생은 매일 밤 2시까지 깨어 있어요. 어떻게 하면 좋을까요?", "neutral"],
    ["Sora", "He should try going to bed thirty minutes earlier.", "Cậu ấy nên thử đi ngủ sớm hơn ba mươi phút.", "30분 일찍 자 보는 게 좋겠어요.", "neutral"],
    ["Linh", "That sounds reasonable, but he says he isn’t sleepy.", "Nghe hợp lý đấy, nhưng nó bảo là không buồn ngủ.", "합리적으로 들리지만, 졸리지 않다고 해요.", "neutral"],
    ["Sora", "Then he could avoid screens after eleven.", "Vậy cậu ấy có thể tránh dùng màn hình sau mười một giờ.", "그러면 11시 이후에는 화면을 보지 않는 게 좋아요.", "neutral"],
    ["Linh", "Could you explain why that helps?", "Bạn giải thích được vì sao điều đó có ích không?", "그게 왜 도움이 되는지 설명해 줄 수 있어요?", "neutral"],
    ["Sora", "The bright light keeps your brain active, so you stay awake longer.", "Ánh sáng mạnh giữ não hoạt động, nên bạn thức lâu hơn.", "밝은 빛 때문에 뇌가 깨어 있어서 더 오래 깨어 있게 돼요.", "neutral"],
    ["Linh", "I see. Should he stop using his phone completely?", "Tôi hiểu rồi. Nó có nên bỏ hẳn điện thoại không?", "알겠어요. 휴대폰을 아예 쓰지 말아야 하나요?", "neutral"],
    ["Sora", "He doesn’t have to. He shouldn’t use it in bed, that’s all.", "Không cần bỏ hẳn. Cậu ấy không nên dùng trên giường, vậy thôi.", "완전히 끊을 필요는 없어요. 침대에서만 쓰지 않으면 돼요.", "neutral"],
    ["Linh", "What about coffee in the afternoon?", "Còn cà phê buổi chiều thì sao?", "오후에 마시는 커피는요?", "neutral"],
    ["Sora", "He’d better not drink coffee after three. Tea is a good alternative.", "Cậu ấy tốt nhất không uống cà phê sau ba giờ. Trà là lựa chọn thay thế tốt.", "3시 이후에는 커피를 마시지 않는 게 좋아요. 차가 좋은 대안이에요.", "neutral"],
    ["Linh", "So the first step is no coffee after three.", "Vậy bước đầu tiên là không uống cà phê sau ba giờ.", "그럼 첫 단계는 3시 이후 커피를 안 마시는 거네요.", "neutral"],
    ["Sora", "Exactly. He can start tonight and keep it for a week.", "Chính xác. Cậu ấy có thể bắt đầu tối nay và duy trì một tuần.", "맞아요. 오늘 밤부터 일주일만 지켜 보세요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "should, shouldn’t và could để khuyên",
      titleKo: "조언의 should, shouldn’t, could",
      explanationVi: "should và shouldn’t đưa ra lời khuyên trực tiếp nhưng vẫn lịch sự: “He should try going to bed earlier.” could nhẹ hơn, mang tính gợi ý: “He could avoid screens after eleven.” Cả ba đều theo sau là động từ nguyên mẫu không có to.",
      explanationKo: "should와 shouldn’t는 비교적 직접적인 조언이고, could는 더 부드러운 제안이에요. 세 가지 모두 뒤에 동사원형을 써요.",
      easierKorean: "조언할 때는 should, 부드럽게 제안할 때는 could를 써요.",
    },
    {
      titleVi: "Hỏi lại và xác nhận lời khuyên",
      titleKo: "조언을 되묻고 확인하기",
      explanationVi: "Khi cần hiểu rõ, dùng: Could you explain…? What do you mean by…? Do you mean I should…? Khi đồng ý, dùng: That sounds reasonable. I see. Exactly. Khi không cần làm gì, dùng: You don’t have to.",
      explanationKo: "설명을 요청할 때는 Could you explain…?, 뜻을 확인할 때는 Do you mean I should…?를 써요. 동의할 때는 That sounds reasonable.라고 말해요.",
      easierKorean: "다시 물을 때는 Could you explain…?, 동의할 때는 That sounds reasonable.이라고 해요.",
    },
  ],
  examples: [
    ["You should try going to bed thirty minutes earlier.", "Bạn nên thử đi ngủ sớm hơn ba mươi phút.", "30분 일찍 자 보는 게 좋아요.", "Lời khuyên đầu tiên Sora dành cho em Linh."],
    ["He shouldn’t use his phone in bed.", "Cậu ấy không nên dùng điện thoại trên giường.", "침대에서 휴대폰을 쓰지 않는 게 좋아요.", "Điều chỉnh lời khuyên sau khi Linh hỏi thêm."],
    ["He could drink tea instead of coffee in the afternoon.", "Cậu ấy có thể uống trà thay cà phê vào buổi chiều.", "오후에는 커피 대신 차를 마실 수 있어요.", "Gợi ý nhẹ hơn thay cho lời khuyên trực tiếp."],
    ["You don’t have to stop completely.", "Bạn không cần dừng hẳn.", "완전히 끊을 필요는 없어요.", "Sora trấn an khi Linh lo em mình bỏ hẳn điện thoại."],
    ["Could you explain why that helps?", "Bạn giải thích được vì sao việc đó có ích không?", "그게 왜 도움이 되는지 설명해 줄 수 있어요?", "Câu hỏi làm rõ trong cuộc trò chuyện."],
    ["What do you mean by “screens”?", "Bạn nói “màn hình” là ý gì?", "“화면”이 무슨 뜻이에요?", "Câu hỏi khi cần định nghĩa rõ ràng."],
    ["Do you mean I should start tonight?", "Ý bạn là tôi nên bắt đầu từ tối nay?", "오늘 밤부터 시작하라는 뜻이에요?", "Cách xác nhận lại lời khuyên."],
    ["That sounds reasonable.", "Nghe hợp lý đấy.", "합리적으로 들려요.", "Câu tiếp nhận lời khuyên một cách tự nhiên."],
    ["I agree with the first step.", "Tôi đồng ý với bước đầu tiên.", "첫 단계에 동의해요.", "Linh chọn cách bắt đầu nhỏ."],
    ["You should ask your doctor before you take anything.", "Bạn nên hỏi bác sĩ trước khi dùng bất cứ thứ gì.", "약을 먹기 전에 의사에게 물어보는 게 좋아요.", "Lời khuyên quan trọng trong tình huống sức khỏe."],
    ["Maybe you could write the plan on the fridge.", "Có lẽ bạn có thể viết kế hoạch lên tủ lạnh.", "냉장고에 계획을 붙여 두는 것도 좋아요.", "Gợi ý thực tế để duy trì thói quen."],
    ["Why don’t you try it for one week?", "Sao bạn không thử trong một tuần?", "일주일만 해 보는 건 어때요?", "Cách khuyên nhẹ nhàng bằng câu hỏi."],
    ["I’ll think about your advice.", "Tôi sẽ suy nghĩ về lời khuyên của bạn.", "조언을 생각해 볼게요.", "Câu trả lời khi chưa quyết định ngay."],
    ["Thanks, that’s a really useful idea.", "Cảm ơn, đó là ý thật hữu ích.", "고마워요, 정말 도움이 되는 생각이에요.", "Linh cảm ơn sau khi hiểu rõ hơn."],
    ["One step at a time is easier.", "Mỗi lần một bước sẽ dễ hơn.", "한 번에 한 단계씩 하면 더 쉬워요.", "Câu kết Sora nói khi kết thúc cuộc trò chuyện."],
    ["If he keeps going for a month, he’ll sleep better.", "Nếu cậu ấy duy trì một tháng, cậu ấy sẽ ngủ ngon hơn.", "한 달만 계속하면 잠을 더 잘 잘 거예요.", "Lời động viên kèm điều kiện ở cuối cuộc trò chuyện."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-giving-advice-listen-mc",
      "Nghe câu “He shouldn’t use his phone in bed.” và chọn lời khuyên đúng.",
      ["Không nên dùng điện thoại trên giường.", "Không nên dùng điện thoại vào buổi sáng.", "Nên dùng điện thoại ít hơn trong bữa ăn."],
      "Không nên dùng điện thoại trên giường.",
      "listening",
      "a2-giving-advice-form",
      "Chú ý “in bed”.",
    ),
    exercise.dictation(
      "a2-giving-advice-listen-dictation",
      "Nghe và chép lại câu hỏi làm rõ lời khuyên.",
      "Could you explain why that helps?",
      "a2-giving-advice-communicate",
    ),
  ],
  shadowing: {
    line: "He could avoid screens after eleven.",
    notesVi: ["Nhấn vào “eleven” vì đó là mốc thời gian quan trọng.", "Đọc “avoid screens” thành một cụm nhanh."],
    notesKo: ["“eleven”을 살짝 세게 말하면 시간 기준이 분명해져요.", "“avoid screens”는 빠르게 붙여 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-giving-advice-guided-mc",
      "Chọn lời khuyên phù hợp nhất khi bạn muốn nói nhẹ nhàng hơn.",
      ["You could drink tea instead.", "You must drink tea instead.", "You drank tea instead."],
      "You could drink tea instead.",
      "grammar",
      "a2-giving-advice-form",
    ),
    exercise.fillBlank(
      "a2-giving-advice-guided-blank",
      "Điền “should” hoặc “shouldn’t”: “You ______ drink coffee after three if you want to sleep well.”",
      "shouldn’t",
      "grammar",
      "a2-giving-advice-form",
    ),
    exercise.arrange(
      "a2-giving-advice-guided-arrange",
      "Sắp xếp thành câu hỏi làm rõ.",
      ["Could", "you", "explain", "why", "that", "helps", "?"],
      "Could you explain why that helps ?",
      "a2-giving-advice-communicate",
    ),
    exercise.translation(
      "a2-giving-advice-guided-translate",
      "Dịch sang tiếng Anh: “Bạn không cần dừng hẳn.”",
      "You don’t have to stop completely.",
      "a2-giving-advice-communicate",
    ),
  ],
  production: [
    exercise.written(
      "a2-giving-advice-production-write",
      "Viết 6 câu tư vấn cho một người bạn khó ngủ: hai lời khuyên với should, một gợi ý nhẹ với could, một điều không cần làm và một câu hỏi làm rõ.",
      "a2-giving-advice-communicate",
      "You should go to bed thirty minutes earlier, and you shouldn’t drink coffee after three. You could try drinking tea instead. You don’t have to stop using your phone completely, but you shouldn’t use it in bed. Could you explain which part is the most difficult? I’ll help you make a plan.",
      ["Có should, shouldn’t và could", "Có một câu hỏi làm rõ", "Lời khuyên thực tế, cụ thể"],
    ),
    exercise.speaking(
      "a2-giving-advice-production-speak",
      "Nói 75 giây: nêu vấn đề của một người bạn, đưa hai lời khuyên, tiếp nhận ý kiến ngược lại và chốt một bước bắt đầu.",
      "a2-giving-advice-communicate",
      "My friend sleeps badly. She should go to bed earlier and she shouldn’t drink coffee after three. She says she isn’t sleepy at eleven, so she could read instead of using her phone. That sounds reasonable. We agreed the first step is no coffee after three.",
      ["Có vấn đề, lời khuyên và bước bắt đầu", "Có phản hồi với ý kiến khác", "Dùng should, shouldn’t, could"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-giving-advice-mastery-mc",
      "Chọn câu khuyên đúng ngữ pháp.",
      ["You should drink more water.", "You should to drink more water.", "You should drinking more water."],
      "You should drink more water.",
      "grammar",
      "a2-giving-advice-form",
    ),
    exercise.fillBlank(
      "a2-giving-advice-mastery-blank",
      "Viết lại thành câu gợi ý nhẹ: “Try tea instead.” → “You ______ try tea instead.”",
      "could",
      "grammar",
      "a2-giving-advice-form",
    ),
    exercise.dictation(
      "a2-giving-advice-mastery-dictation",
      "Nghe và chép lại lời khuyên về bước bắt đầu.",
      "One step at a time is easier.",
      "a2-giving-advice-comprehension",
    ),
    exercise.translation(
      "a2-giving-advice-mastery-translate",
      "Dịch sang tiếng Anh: “Ý bạn là tôi nên bắt đầu từ tối nay?”",
      "Do you mean I should start tonight?",
      "a2-giving-advice-communicate",
    ),
    exercise.speaking(
      "a2-giving-advice-mastery-speak",
      "Nói 75 giây: cho lời khuyên về giấc ngủ, làm rõ một chi tiết và xác nhận kế hoạch.",
      "a2-giving-advice-communicate",
      "You should go to bed before midnight, and you shouldn’t use your phone in bed. You could read a book instead. Do you mean you should start tonight? Yes, and one step at a time is easier. You don’t have to change everything in one day.",
      ["Có ba lời khuyên với should, shouldn’t, could", "Có câu làm rõ và câu xác nhận", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể đưa ra, tiếp nhận và làm rõ lời khuyên một cách lịch sự."],
  spiralReview: ["A2 Unit 5 bài 3: thói quen và tần suất", "A2 Unit 4: xác nhận giải pháp bằng văn bản"],
  errorCategories: ["grammar-form", "word-choice", "missing-word", "register"],
};

/* ------------------------------------------------------------------ *
 * Bài 5 — Ôn tập Unit 5 và nhiệm vụ sức khỏe
 * ------------------------------------------------------------------ */
const unitReview: LessonSeed = {
  id: "a2-unit-5-review",
  unitId,
  number: 5,
  prerequisites: ["a2-giving-advice"],
  titleVi: "Ôn tập Unit 5 và nhiệm vụ sức khỏe",
  titleKo: "Unit 5 복습과 건강 미션",
  situationVi: "Sora kể lại toàn bộ tuần ốm và kế hoạch giữ sức khỏe, từ lúc mô tả triệu chứng đến khi thay đổi thói quen.",
  situationKo: "소라는 아팠던 한 주와 건강 계획을 처음부터 끝까지 이야기해요. 증상 설명부터 습관 변화까지 포함해요.",
  objectives: [
    { id: "a2-unit-5-review-communicate", en: "Explain a health problem and your plan in one conversation.", vi: "Trình bày vấn đề sức khỏe và kế hoạch của mình trong một cuộc trò chuyện.", ko: "건강 문제와 계획을 한 번에 설명할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-unit-5-review-form", en: "Choose the right structure for symptoms, instructions and advice.", vi: "Chọn đúng cấu trúc cho triệu chứng, hướng dẫn và lời khuyên.", ko: "증상, 지시, 조언에 맞는 문법을 고를 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-unit-5-review-comprehension", en: "Understand a health update with frequency and duration.", vi: "Nghe hiểu một cập nhật sức khỏe có tần suất và thời gian.", ko: "빈도와 기간이 들어간 건강 이야기를 이해할 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["symptom", "main symptom", "triệu chứng chính", "주요 증상", "/ˈsɪmptəm/", "SYMptom", "neutral", ["the main symptom", "describe a symptom"]],
    ["prescription", "repeat prescription", "đơn thuốc gia hạn", "재처방전", "/prɪˈskrɪpʃn/", "preSCRIPtion", "formal", ["a repeat prescription", "collect a prescription"]],
    ["dose", "the correct dose", "liều đúng", "정확한 복용량", "/dəʊs/", "DOSE", "formal", ["the correct dose", "a lower dose"]],
    ["habit", "daily habit", "thói quen hằng ngày", "매일 하는 습관", "/ˈhæbɪt/", "HABit", "neutral", ["a daily habit", "build a habit"]],
    ["work-out", "work out regularly", "tập thể dục đều đặn", "규칙적으로 운동하다", "/wɜːk aʊt/", "work OUT", "casual", ["work out regularly", "work out at home"]],
    ["advice", "useful advice", "lời khuyên hữu ích", "도움이 되는 조언", "/ədˈvaɪs/", "adVICE", "neutral", ["useful advice", "follow the advice"]],
    ["energy", "low energy", "ít năng lượng", "기운이 없음", "/ˈenədʒi/", "ENergy", "neutral", ["low energy", "more energy than before"]],
    ["pharmacy", "local pharmacy", "hiệu thuốc gần nhà", "동네 약국", "/ˈfɑːməsi/", "PHARmacy", "neutral", ["the local pharmacy", "an open pharmacy"]],
  ],
  dialogue: [
    ["Linh", "You look much better than last week.", "Trông bạn khá hơn tuần trước nhiều.", "지난주보다 훨씬 좋아 보여요.", "casual"],
    ["Sora", "Thanks. I had a sore throat and a slight fever for five days.", "Cảm ơn. Tôi bị đau họng và sốt nhẹ năm ngày.", "고마워요. 닷새 동안 목이 아프고 미열이 있었어요.", "neutral"],
    ["Linh", "Did the doctor give you antibiotics?", "Bác sĩ có cho bạn kháng sinh không?", "의사가 항생제를 주던가요?", "neutral"],
    ["Sora", "No. I had to rest, and I mustn’t drink coffee while I took the tablets.", "Không. Tôi phải nghỉ ngơi, và không được uống cà phê trong lúc uống thuốc.", "아니요. 쉬어야 했고, 약을 먹는 동안 커피를 마시면 안 됐어요.", "neutral"],
    ["Linh", "How often did you take them?", "Bạn uống thuốc bao lâu một lần?", "약은 얼마나 자주 먹었어요?", "neutral"],
    ["Sora", "Twice a day, after breakfast and after dinner, for five days.", "Hai lần một ngày, sau bữa sáng và sau bữa tối, trong năm ngày.", "하루 두 번, 아침과 저녁 식사 후에 닷새 동안 먹었어요.", "neutral"],
    ["Linh", "And now?", "Còn bây giờ thì sao?", "지금은요?", "casual"],
    ["Sora", "Now I sleep better because I’ve cut down on coffee.", "Bây giờ tôi ngủ ngon hơn vì đã giảm cà phê.", "이제는 커피를 줄여서 잠을 더 잘 자요.", "neutral"],
    ["Linh", "Do you still feel tired in the afternoon?", "Chiều bạn còn thấy mệt không?", "오후에도 아직 피곤해요?", "neutral"],
    ["Sora", "Sometimes, but I take a short break and walk for ten minutes.", "Thỉnh thoảng, nhưng tôi nghỉ ngắn và đi bộ mười phút.", "가끔요. 그래도 잠깐 쉬고 10분씩 걸어요.", "neutral"],
    ["Linh", "That’s a good habit. Should I try it too?", "Đó là thói quen tốt. Tôi có nên thử không?", "좋은 습관이네요. 저도 해 볼까요?", "casual"],
    ["Sora", "You could start with one walk a day. You don’t have to do more.", "Bạn có thể bắt đầu bằng một lần đi bộ mỗi ngày. Không cần làm nhiều hơn.", "하루 한 번 걷기부터 시작해 보세요. 더 많이 하지 않아도 돼요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "Chọn cấu trúc theo mục đích trong chủ đề sức khỏe",
      titleKo: "건강 주제에서 목적에 맞게 문법 고르기",
      explanationVi: "Triệu chứng: have / have got. Số lượng: too much, too many, enough. Hướng dẫn bắt buộc: must, mustn’t, have to. Tần suất: usually, twice a week. Thói quen và sở thích: động từ + -ing. Lời khuyên: should, shouldn’t, could.",
      explanationKo: "증상은 have / have got, 양은 too much, too many, enough, 의무는 must, mustn’t, have to를 써요. 빈도는 twice a week, 습관은 동명사, 조언은 should와 could로 말해요.",
      easierKorean: "증상, 의무, 빈도, 조언 중 무엇을 말하는지 먼저 정하고 문법을 골라요.",
    },
  ],
  examples: [
    ["I’ve had a sore throat since Monday.", "Tôi bị đau họng từ thứ Hai.", "월요일부터 목이 아팠어요.", "Câu mở đầu khi Sora kể lại tuần ốm."],
    ["I had too many late nights before I got ill.", "Tôi đã thức khuya quá nhiều trước khi bị ốm.", "아프기 전에 늦게 잔 날이 너무 많았어요.", "Nguyên nhân Sora nhận ra sau khi khám."],
    ["I didn’t drink enough water during the day.", "Tôi không uống đủ nước trong ngày.", "낮에 물을 충분히 마시지 않았어요.", "Thói quen cũ khiến Sora mệt hơn."],
    ["You must take the tablets after meals.", "Bạn phải uống thuốc sau bữa ăn.", "약은 식사 후에 먹어야 해요.", "Hướng dẫn dược sĩ ghi trên nhãn thuốc."],
    ["You mustn’t take two tablets at once.", "Bạn không được uống hai viên cùng lúc.", "두 알을 한꺼번에 먹으면 안 돼요.", "Cảnh báo quan trọng khi dùng thuốc."],
    ["I don’t have to go back if I feel well.", "Tôi không cần quay lại nếu thấy khỏe.", "몸이 괜찮으면 다시 가지 않아도 돼요.", "Bác sĩ nói ở cuối buổi khám."],
    ["I usually take a break at three o’clock.", "Tôi thường nghỉ giải lao lúc ba giờ.", "보통 3시에 잠깐 쉬어요.", "Thói quen mới giúp Sora đỡ mệt."],
    ["I go walking three times a week now.", "Bây giờ tôi đi bộ ba lần một tuần.", "이제 일주일에 세 번 걷어요.", "Kế hoạch vận động Sora duy trì sau khi khỏi."],
    ["I enjoy walking after work.", "Tôi thích đi bộ sau giờ làm.", "퇴근 후 걷는 걸 좋아해요.", "Lý do Sora giữ được thói quen này."],
    ["I’ve stopped drinking coffee in the evening.", "Tôi đã ngừng uống cà phê buổi tối.", "저녁에 커피 마시는 걸 끊었어요.", "Thay đổi giúp Sora ngủ tốt hơn."],
    ["You should rest if you still feel dizzy.", "Bạn nên nghỉ nếu vẫn thấy chóng mặt.", "아직 어지러우면 쉬는 게 좋아요.", "Lời khuyên Sora dành cho Linh."],
    ["You could try tea instead of coffee.", "Bạn có thể thử trà thay cà phê.", "커피 대신 차를 마셔 보세요.", "Gợi ý nhẹ nhàng trong cuộc trò chuyện."],
    ["Could you explain the dose again?", "Bạn nhắc lại liều lượng được không?", "복용량을 다시 설명해 주시겠어요?", "Câu hỏi Sora hỏi dược sĩ lần hai."],
    ["I feel much better than last week.", "Tôi thấy khá hơn tuần trước nhiều.", "지난주보다 훨씬 나아졌어요.", "Câu trả lời mở đầu cuộc trò chuyện với Linh."],
    ["If I sleep well, I have more energy.", "Nếu ngủ ngon, tôi có nhiều năng lượng hơn.", "잠을 잘 자면 기운이 더 나요.", "Điều Sora nhận ra sau hai tuần thay đổi."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-unit-5-review-listen-mc",
      "Nghe câu “Twice a day, after breakfast and after dinner, for five days.” và chọn hướng dẫn đúng.",
      ["Uống hai lần mỗi ngày, sau bữa sáng và bữa tối, trong năm ngày.", "Uống một lần mỗi ngày trong hai ngày.", "Uống hai viên mỗi bữa trong năm ngày."],
      "Uống hai lần mỗi ngày, sau bữa sáng và bữa tối, trong năm ngày.",
      "listening",
      "a2-unit-5-review-comprehension",
      "Nghe kỹ số lần và thời gian.",
    ),
    exercise.dictation(
      "a2-unit-5-review-listen-dictation",
      "Nghe và chép lại lời khuyên cuối cùng.",
      "You could start with one walk a day.",
      "a2-unit-5-review-form",
    ),
  ],
  shadowing: {
    line: "If I sleep well, I have more energy.",
    notesVi: ["Ngắt rõ sau “well” để tách điều kiện và kết quả.", "Đọc “more_energy” thành một cụm liền."],
    notesKo: ["“well” 뒤에서 잠깐 쉬면 조건과 결과가 분명해져요.", "“more energy”는 붙여서 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-unit-5-review-guided-mc",
      "Chọn câu đúng nghĩa “Bạn không được uống hai viên cùng lúc.”",
      ["You mustn’t take two tablets at once.", "You don’t have to take two tablets at once.", "You should take two tablets at once."],
      "You mustn’t take two tablets at once.",
      "grammar",
      "a2-unit-5-review-form",
    ),
    exercise.fillBlank(
      "a2-unit-5-review-guided-blank",
      "Điền dạng đúng: “I enjoy ______ (walk) after work.”",
      "walking",
      "grammar",
      "a2-unit-5-review-form",
    ),
    exercise.arrange(
      "a2-unit-5-review-guided-arrange",
      "Sắp xếp thành câu có tần suất.",
      ["I", "go", "walking", "three", "times", "a", "week", "now", "."],
      "I go walking three times a week now .",
      "a2-unit-5-review-form",
    ),
    exercise.translation(
      "a2-unit-5-review-guided-translate",
      "Dịch sang tiếng Anh: “Bạn nên nghỉ nếu vẫn thấy chóng mặt.”",
      "You should rest if you still feel dizzy.",
      "a2-unit-5-review-communicate",
    ),
  ],
  production: [
    exercise.written(
      "a2-unit-5-review-production-write",
      "Viết 8 câu kể lại một tuần bạn bị ốm và kế hoạch giữ sức khỏe: triệu chứng, thời gian, hướng dẫn của bác sĩ, hai lời khuyên và hai thay đổi bạn đã bắt đầu.",
      "a2-unit-5-review-communicate",
      "Last month I had a sore throat and a slight fever for five days. The doctor said I had to rest, and I mustn’t drink coffee with the tablets. I took them twice a day after meals. He advised me to sleep more and to drink warm water. Since then I’ve cut down on coffee and I’ve taken up walking three times a week. I enjoy walking after work, and I feel much better now.",
      ["Có triệu chứng, hướng dẫn và lời khuyên", "Có tần suất và động danh từ", "Câu nối theo thời gian"],
    ),
    exercise.speaking(
      "a2-unit-5-review-production-speak",
      "Nhiệm vụ sức khỏe: nói 90 giây kể lại tuần ốm và kế hoạch sức khỏe, dùng ít nhất bốn cấu trúc của Unit 5.",
      "a2-unit-5-review-communicate",
      "I had a sore throat and a slight fever for five days, and I felt dizzy in the evening. I had too many late nights and I didn’t drink enough water. The doctor said I had to rest, and I mustn’t drink coffee with the tablets. Now I take a break every afternoon, and I go walking three times a week. You should try it too.",
      ["Dùng bốn cấu trúc trọng tâm", "Có trình tự từ lúc ốm đến lúc khỏe hơn", "Tự đánh giá và ghi một điểm cần sửa"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-unit-5-review-mastery-mc",
      "Chọn câu khuyên đúng và lịch sự nhất.",
      ["You could try drinking tea instead.", "You could to try drinking tea instead.", "You could tried drinking tea instead."],
      "You could try drinking tea instead.",
      "grammar",
      "a2-unit-5-review-form",
    ),
    exercise.fillBlank(
      "a2-unit-5-review-mastery-blank",
      "Điền “too much” hoặc “too many”: “I had ______ late nights last week.”",
      "too many",
      "grammar",
      "a2-unit-5-review-form",
    ),
    exercise.dictation(
      "a2-unit-5-review-mastery-dictation",
      "Nghe và chép lại câu Sora nói về kết quả hiện tại.",
      "I feel much better than last week.",
      "a2-unit-5-review-comprehension",
    ),
    exercise.translation(
      "a2-unit-5-review-mastery-translate",
      "Dịch sang tiếng Anh: “Tôi đã ngừng uống cà phê buổi tối.”",
      "I’ve stopped drinking coffee in the evening.",
      "a2-unit-5-review-communicate",
    ),
    exercise.speaking(
      "a2-unit-5-review-mastery-speak",
      "Nói 90 giây về sức khỏe của bạn: triệu chứng cũ, hướng dẫn đã nhận, hai thay đổi và một lời khuyên cho người khác.",
      "a2-unit-5-review-communicate",
      "I had a bad cough and a slight fever for a week. I had to rest and I mustn’t drink coffee with the medicine. Twice a day I took one tablet after meals. Since then I’ve cut down on sugar and I’ve taken up swimming. You should start with one small change.",
      ["Đủ bốn phần", "Câu ngắn, rõ nghĩa", "Tự đánh giá trung thực"],
    ),
  ],
  canDo: ["Có thể trình bày một vấn đề sức khỏe, hướng dẫn đã nhận và kế hoạch thay đổi của mình."],
  spiralReview: ["A1: bộ phận cơ thể, ngày tháng và số đếm", "A2 Unit 1 đến Unit 4: kế hoạch, lịch hẹn, sự cố và xin hỗ trợ"],
  errorCategories: ["grammar-form", "word-choice", "word-order", "missing-word"],
};

export const a2Unit5 = bilingualUnitSchema.parse({
  id: unitId,
  level: "A2",
  titleVi: "Sức khỏe, thói quen và lời khuyên",
  titleKo: "건강, 습관, 조언",
  lessons: [symptoms, doctorPharmacy, healthyHabits, givingAdvice, unitReview].map(buildLesson),
});
