import { bilingualUnitSchema } from "@/lib/curriculum/bilingual-schema";
import { buildLesson, exercise, type LessonSeed } from "./a2-lesson-factory";

/**
 * A2 Unit 1 — Kết nối trong cuộc sống hằng ngày.
 *
 * ID bài, ID mục tiêu, ID từ vựng và ID bài tập được giữ nguyên như bản trước
 * để không làm mất liên kết tiến độ, thẻ ôn tập FSRS và dữ liệu cũ.
 */
const unitId = "a2-1-everyday-connections";

/* ------------------------------------------------------------------ *
 * Bài 1 — Kể về những thay đổi gần đây
 * ------------------------------------------------------------------ */
const recentChanges: LessonSeed = {
  id: "a2-recent-changes",
  unitId,
  number: 1,
  prerequisites: ["unit-review"],
  titleVi: "Kể về những thay đổi gần đây",
  titleKo: "최근 변화 말하기",
  situationVi: "Gặp lại đồng nghiệp cũ sau một năm: Linh kể về công việc mới, chỗ ở mới và nếp sinh hoạt đã đổi.",
  situationKo: "일 년 만에 옛 동료를 만나서 린은 새 직장, 새 집, 달라진 생활을 이야기해요.",
  objectives: [
    { id: "a2-recent-changes-communicate", en: "Talk about recent changes in your life.", vi: "Kể về những thay đổi gần đây trong cuộc sống.", ko: "최근에 생긴 변화를 이야기할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-recent-changes-form", en: "Use the present perfect for recent changes and the past simple for finished details.", vi: "Dùng hiện tại hoàn thành cho thay đổi gần đây và quá khứ đơn cho chi tiết đã kết thúc.", ko: "최근 변화는 현재완료, 끝난 세부 내용은 과거형으로 말할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-recent-changes-comprehension", en: "Catch when a change happened and how someone feels about it.", vi: "Nghe ra thay đổi xảy ra khi nào và người nói cảm thấy thế nào.", ko: "변화가 언제 생겼는지, 지금 어떤지 들을 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["recently", "recently", "gần đây", "최근에", "/ˈriːsntli/", "REcently", "neutral", ["recently started", "until recently"]],
    ["move", "move to", "chuyển đến", "…로 이사하다", "/muːv tuː/", "MOVE to", "neutral", ["move to a new flat", "move closer to work"]],
    ["start", "start a new job", "bắt đầu công việc mới", "새 일을 시작하다", "/stɑːt ə njuː dʒɒb/", "START a new job", "neutral", ["start a new job", "start work at eight"]],
    ["change", "change a lot", "thay đổi nhiều", "많이 변하다", "/tʃeɪndʒ ə lɒt/", "CHANGE a lot", "neutral", ["change a lot", "change your routine"]],
    ["lately", "lately", "dạo gần đây", "요즘", "/ˈleɪtli/", "LATEly", "neutral", ["busier lately", "lately I have"]],
    ["get-used", "get used to", "quen với", "…에 익숙해지다", "/ɡet juːst tuː/", "get USED to", "neutral", ["get used to the commute", "slowly get used to"]],
    ["still", "still", "vẫn còn", "여전히", "/stɪl/", "STILL", "neutral", ["still getting used to", "still busy"]],
    ["so-far", "so far", "cho đến hiện tại", "지금까지", "/səʊ fɑː/", "so FAR", "neutral", ["so far so good", "so far this year"]],
  ],
  dialogue: [
    ["Joon", "It’s been a while. How have you been?", "Lâu rồi không gặp. Dạo này bạn thế nào?", "오랜만이에요. 어떻게 지냈어요?", "casual"],
    ["Linh", "Pretty well. I’ve recently started a new job at a design studio.", "Khá tốt. Gần đây tôi bắt đầu làm ở một studio thiết kế.", "잘 지냈어요. 최근에 디자인 스튜디오에서 새 일을 시작했어요.", "casual"],
    ["Joon", "That’s great news. When did you start?", "Tin tốt đấy. Bạn bắt đầu khi nào?", "좋은 소식이네요. 언제 시작했어요?", "casual"],
    ["Linh", "In February. I moved to a flat near the office at the same time.", "Tháng Hai. Tôi cũng chuyển đến một căn hộ gần văn phòng.", "2월에요. 같은 시기에 사무실 근처로 이사했어요.", "neutral"],
    ["Joon", "So your whole routine has changed.", "Vậy là cả nếp sinh hoạt của bạn đã thay đổi.", "그럼 생활 패턴이 완전히 바뀌었네요.", "neutral"],
    ["Linh", "Yes. I used to leave home at seven, and now I walk for twenty minutes.", "Đúng vậy. Trước đây tôi rời nhà lúc bảy giờ, giờ tôi đi bộ hai mươi phút.", "네. 예전에는 7시에 집을 나섰는데 지금은 20분 걸어요.", "neutral"],
    ["Joon", "How is the new team?", "Nhóm mới thế nào?", "새 팀은 어때요?", "casual"],
    ["Linh", "Very helpful. So far they’ve explained everything patiently.", "Rất nhiệt tình. Cho đến giờ họ giải thích mọi thứ rất kiên nhẫn.", "아주 친절해요. 지금까지 모든 걸 잘 설명해 줬어요.", "neutral"],
    ["Joon", "Are you still working on weekends?", "Bạn vẫn làm cuối tuần chứ?", "주말에도 계속 일해요?", "casual"],
    ["Linh", "No, I haven’t worked on a weekend since March. I’m still getting used to the free time.", "Không, tôi không làm cuối tuần từ tháng Ba. Tôi vẫn đang quen với thời gian rảnh.", "아니요, 3월부터 주말에는 일하지 않았어요. 아직 자유 시간에 익숙해지는 중이에요.", "casual"],
    ["Joon", "That sounds like a good change. Let’s have lunch soon.", "Nghe như một thay đổi tốt. Sớm đi ăn trưa nhé.", "좋은 변화네요. 조만간 점심 먹어요.", "casual"],
    ["Linh", "Yes, let’s. I’ll message you next week.", "Vâng, đi nhé. Tuần sau tôi nhắn bạn.", "좋아요. 다음 주에 메시지할게요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "Hiện tại hoàn thành cho thay đổi gần đây",
      titleKo: "최근 변화의 현재완료",
      explanationVi: "Dùng have/has + quá khứ phân từ khi thay đổi xảy ra trong quá khứ nhưng kết quả còn ảnh hưởng tới hiện tại: “I’ve recently started a new job.” since + mốc thời gian và so far nhấn mạnh khoảng thời gian kéo dài đến bây giờ.",
      explanationKo: "과거에 생긴 변화가 지금까지 이어질 때는 have/has + 과거분사를 써요. since는 시작 시점, so far는 지금까지의 기간을 강조해요.",
      easierKorean: "최근에 시작했고 지금도 이어지면 have/has + 과거분사를 써요.",
    },
    {
      titleVi: "Quá khứ đơn cho chi tiết đã kết thúc",
      titleKo: "끝난 세부 내용의 과거형",
      explanationVi: "Khi nói rõ thời điểm đã qua, dùng quá khứ đơn: “I moved to a flat in February.” Câu hỏi When did you start? luôn đi với quá khứ đơn, không dùng hiện tại hoàn thành.",
      explanationKo: "지난 날짜나 시간을 말할 때는 과거형을 써요. When did you…?라고 물으면 과거형으로 대답해요.",
      easierKorean: "When did you…?로 물으면 과거형으로 대답해요.",
    },
  ],
  examples: [
    ["I’ve recently started a new job at a design studio.", "Gần đây tôi bắt đầu làm ở một studio thiết kế.", "최근에 디자인 스튜디오에서 새 일을 시작했어요.", "Câu mở đầu Linh nói khi gặp lại đồng nghiệp cũ."],
    ["She has moved closer to work.", "Cô ấy đã chuyển đến gần chỗ làm hơn.", "그녀는 직장 가까이로 이사했어요.", "Joon kể lại với một người bạn chung."],
    ["My schedule has changed a lot this year.", "Năm nay lịch của tôi thay đổi nhiều.", "올해 제 일정이 많이 바뀌었어요.", "Linh giải thích vì sao cô khó gặp bạn bè."],
    ["Have you tried the new café near the office yet?", "Bạn đã thử quán cà phê mới gần văn phòng chưa?", "사무실 근처 새 카페에 가 봤어요?", "Câu hỏi của Joon trong giờ nghỉ trưa."],
    ["I haven’t met the new manager yet.", "Tôi vẫn chưa gặp quản lý mới.", "아직 새 관리자를 만나지 못했어요.", "Câu trả lời của Linh trong tuần đầu đi làm."],
    ["We’ve been busier lately.", "Dạo gần đây chúng tôi bận hơn.", "요즘 더 바빠졌어요.", "Linh nói về nhóm thiết kế của mình."],
    ["I’m still getting used to the commute on foot.", "Tôi vẫn đang quen với việc đi bộ đi làm.", "아직 걸어서 출퇴근하는 것에 익숙해지는 중이에요.", "Câu trả lời khi Joon hỏi về chỗ ở mới."],
    ["So far, the team has been very helpful.", "Cho đến giờ, nhóm đã rất nhiệt tình.", "지금까지 팀이 많이 도와줬어요.", "Nhận xét Linh đưa ra sau hai tháng làm việc."],
    ["I changed apartments last month.", "Tháng trước tôi đã đổi căn hộ.", "지난달에 집을 옮겼어요.", "Chi tiết Linh kể kèm thời gian cụ thể."],
    ["My mornings are much quieter now.", "Buổi sáng của tôi giờ yên tĩnh hơn nhiều.", "이제 아침이 훨씬 조용해요.", "Cảm nhận của Linh sau khi chuyển nhà."],
    ["I’ve started cooking more often.", "Tôi đã bắt đầu nấu ăn thường xuyên hơn.", "요리를 더 자주 하기 시작했어요.", "Thay đổi Linh kể với Joon trong bữa trưa."],
    ["Nothing major has changed at home.", "Ở nhà chưa có thay đổi lớn nào.", "집에서는 큰 변화가 없었어요.", "Câu trả lời khi Joon hỏi về gia đình."],
    ["I recently joined a gym near my office.", "Gần đây tôi tham gia một phòng tập gần văn phòng.", "최근 사무실 근처 헬스장에 등록했어요.", "Thay đổi Linh thực hiện sau khi chuyển chỗ ở."],
    ["The neighborhood feels more familiar now.", "Khu phố giờ đã trở nên quen thuộc hơn.", "이제 동네가 더 익숙하게 느껴져요.", "Linh nói về nơi ở mới sau ba tháng."],
    ["I haven’t taken a long holiday since last summer.", "Tôi chưa có kỳ nghỉ dài nào từ hè năm ngoái.", "지난여름 이후로 긴 휴가를 가지 못했어요.", "Lý do Linh muốn đổi lịch hẹn sang tháng sau."],
    ["Let’s catch up over coffee soon.", "Sớm gặp nhau uống cà phê và trò chuyện nhé.", "곧 커피 마시며 이야기해요.", "Câu kết của Joon trước khi chia tay."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-recent-changes-listen",
      "Nghe câu “I’ve recently started a new job at a design studio.” và chọn thay đổi đúng.",
      ["Gần đây Linh bắt đầu công việc mới.", "Linh vừa nghỉ việc ở studio.", "Linh chuyển sang làm thiết kế từ năm ngoái."],
      "Gần đây Linh bắt đầu công việc mới.",
      "listening",
      "a2-recent-changes-communicate",
      "Chú ý “recently started”.",
    ),
    exercise.dictation(
      "a2-recent-changes-dictation",
      "Nghe và chép lại câu về thời gian Linh chuyển nhà.",
      "I moved to a flat near the office in February.",
      "a2-recent-changes-form",
    ),
  ],
  shadowing: {
    line: "I’ve recently started a new job at a design studio.",
    notesVi: ["Nhấn nhẹ vào “recently” để làm rõ thời gian.", "Đọc “started_a” nối liền, không ngắt giữa hai từ."],
    notesKo: ["“recently”를 살짝 세게 말하면 시점이 분명해져요.", "“started a”는 끊지 말고 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-recent-changes-g1",
      "Chọn câu đúng để nói về thay đổi còn liên quan đến hiện tại.",
      ["I’ve started a new job this year.", "I start a new job last year.", "I’ve start a new job this year."],
      "I’ve started a new job this year.",
      "grammar",
      "a2-recent-changes-form",
    ),
    exercise.translation(
      "a2-recent-changes-g2",
      "Dịch sang tiếng Anh: “Cô ấy đã chuyển đến gần chỗ làm hơn.”",
      "She has moved closer to work.",
      "a2-recent-changes-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-recent-changes-production",
      "Viết tin nhắn 4–5 câu kể cho một người bạn cũ về hai thay đổi gần đây của bạn: một thay đổi với hiện tại hoàn thành và một chi tiết đã kết thúc với quá khứ đơn.",
      "a2-recent-changes-communicate",
      "Hi Joon, I’ve recently changed jobs and I’ve moved closer to my office. I started the new job in February and I finished my old project in January. So far everything has been good, but I’m still getting used to the new routine.",
      ["Có hai thay đổi rõ ràng", "Dùng hiện tại hoàn thành và quá khứ đơn", "Có câu hỏi hoặc lời hẹn cuối tin nhắn"],
    ),
    exercise.speaking(
      "a2-recent-changes-speaking",
      "Nói 60 giây về hai thay đổi gần đây của bạn, kèm thời điểm cụ thể và cảm nhận hiện tại.",
      "a2-recent-changes-communicate",
      "I’ve recently started a new course and I’ve changed my daily routine. I began the course in March, and I moved to a quieter flat in April. So far I’ve felt much better, and I’m still getting used to waking up early.",
      ["Có hai thay đổi và thời điểm", "Dùng hiện tại hoàn thành ít nhất hai lần", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-recent-changes-m1",
      "Chọn câu phù hợp khi bạn nói về một thay đổi còn ảnh hưởng đến hiện tại.",
      ["I’ve recently moved to a new flat.", "I move to a new flat last year.", "I’ve move to a new flat."],
      "I’ve recently moved to a new flat.",
      "grammar",
      "a2-recent-changes-form",
    ),
    exercise.dictation(
      "a2-recent-changes-m2",
      "Nghe và chép lại câu về nhóm làm việc mới.",
      "So far, the team has been very helpful.",
      "a2-recent-changes-comprehension",
    ),
    exercise.translation(
      "a2-recent-changes-m3",
      "Dịch sang tiếng Anh: “Tôi vẫn chưa gặp quản lý mới.”",
      "I haven’t met the new manager yet.",
      "a2-recent-changes-form",
    ),
    exercise.speaking(
      "a2-recent-changes-m4",
      "Kể về một thay đổi gần đây trong 45 giây và thêm một chi tiết đã kết thúc.",
      "a2-recent-changes-communicate",
      "I’ve recently changed my working hours. I started at nine in January, and I’ve felt better since then. So far it has worked well for my family.",
      ["Có thay đổi và chi tiết quá khứ", "Dùng hiện tại hoàn thành chính xác", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-recent-changes-m5",
      "Điền “since” hoặc “for”: “I haven’t worked on weekends ______ March.”",
      "since",
      "grammar",
      "a2-recent-changes-comprehension",
      "March là mốc thời gian bắt đầu.",
    ),
  ],
  canDo: ["Có thể kể về những thay đổi gần đây và nói rõ thời điểm xảy ra."],
  spiralReview: ["A1: hiện tại đơn cho thói quen hằng ngày", "A1: quá khứ đơn với thời gian cụ thể"],
  errorCategories: ["verb-tense", "word-order", "missing-word", "word-choice"],
};

/* ------------------------------------------------------------------ *
 * Bài 2 — Chia sẻ trải nghiệm
 * ------------------------------------------------------------------ */
const sharingExperiences: LessonSeed = {
  id: "a2-sharing-experiences",
  unitId,
  number: 2,
  prerequisites: ["a2-recent-changes"],
  titleVi: "Chia sẻ trải nghiệm",
  titleKo: "경험 나누기",
  situationVi: "Joon và Linh kể cho nhau nghe về những chuyến đi và trải nghiệm đáng nhớ, kèm chi tiết cụ thể.",
  situationKo: "준과 린은 기억에 남는 여행과 경험을 구체적인 내용과 함께 나눠요.",
  objectives: [
    { id: "a2-sharing-experiences-communicate", en: "Share experiences and react to other people’s stories.", vi: "Chia sẻ trải nghiệm và phản hồi câu chuyện của người khác.", ko: "경험을 나누고 다른 사람의 이야기에 반응할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-sharing-experiences-form", en: "Ask about experiences with Have you ever…? and answer in detail.", vi: "Hỏi về trải nghiệm bằng Have you ever…? và trả lời chi tiết.", ko: "Have you ever…?로 경험을 묻고 자세히 대답할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-sharing-experiences-comprehension", en: "Understand the details of a short personal story.", vi: "Nghe hiểu chi tiết của một câu chuyện cá nhân ngắn.", ko: "짧은 개인 이야기의 세부 내용을 이해할 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["ever", "Have you ever…?", "Bạn đã từng… chưa?", "…해 본 적 있어요?", "/hæv juː ˈevə/", "Have you EV-er", "neutral", ["Have you ever been", "Have you ever tried"]],
    ["never", "never", "chưa bao giờ", "한 번도 …없다", "/ˈnevə(r)/", "NEVer", "neutral", ["I’ve never been", "never tried"]],
    ["before", "before", "trước đây", "전에", "/bɪˈfɔː(r)/", "beFORE", "neutral", ["been there before", "seen it before"]],
    ["once", "once", "một lần", "한 번", "/wʌns/", "ONCE", "neutral", ["once a year", "only once"]],
    ["experience", "a great experience", "trải nghiệm tuyệt vời", "좋은 경험", "/ɪkˈspɪəriəns/", "exPERience", "neutral", ["a memorable experience", "share an experience"]],
    ["recommend", "highly recommend", "rất khuyên thử", "강력히 추천하다", "/ˌhaɪli rekəˈmend/", "highly recomMEND", "neutral", ["highly recommend the food", "recommend a place"]],
    ["worth", "be worth visiting", "đáng ghé thăm", "가 볼 만하다", "/biː wɜːθ ˈvɪzɪtɪŋ/", "be WORTH VISiting", "neutral", ["be worth visiting", "worth the trip"]],
    ["memorable", "memorable", "đáng nhớ", "기억에 남는", "/ˈmemərəbl/", "MEMorable", "neutral", ["a memorable trip", "a memorable day"]],
  ],
  dialogue: [
    ["Joon", "Have you ever been to Jeju Island?", "Bạn đã từng đến đảo Jeju chưa?", "제주도에 가 본 적 있어요?", "casual"],
    ["Linh", "Yes, I’ve been there twice. Once in summer and once in winter.", "Rồi, tôi đến đó hai lần. Một lần mùa hè và một lần mùa đông.", "네, 두 번 가 봤어요. 여름에 한 번, 겨울에 한 번요.", "casual"],
    ["Joon", "What did you like most?", "Bạn thích điều gì nhất?", "무엇이 가장 좋았어요?", "casual"],
    ["Linh", "The coastal walk was beautiful. I highly recommend it.", "Đường đi bộ ven biển rất đẹp. Tôi rất khuyên bạn thử.", "해안 산책로가 아름다웠어요. 정말 추천해요.", "casual"],
    ["Joon", "I’ve never walked there. Was it difficult?", "Tôi chưa bao giờ đi bộ ở đó. Có khó không?", "거기서 걸어 본 적이 없어요. 힘들었어요?", "casual"],
    ["Linh", "No, it’s easy. It takes about an hour, and the view is worth the trip.", "Không, dễ thôi. Mất khoảng một giờ, và phong cảnh rất đáng đi.", "아니요, 쉬워요. 한 시간 정도 걸리고 경치가 갈 만한 가치가 있어요.", "neutral"],
    ["Joon", "Did you go there with your family?", "Bạn đi cùng gia đình à?", "가족과 함께 갔어요?", "casual"],
    ["Linh", "I went with my family the first time, and with two friends last winter.", "Lần đầu tôi đi cùng gia đình, còn mùa đông trước tôi đi với hai người bạn.", "처음에는 가족과 갔고, 지난겨울에는 친구 둘과 갔어요.", "neutral"],
    ["Joon", "That sounds like a lot of fun.", "Nghe có vẻ rất vui.", "정말 재미있었겠네요.", "casual"],
    ["Linh", "It was. Have you ever taken a night ferry?", "Đúng vậy. Bạn đã từng đi phà đêm chưa?", "그랬어요. 밤에 가는 페리를 타 본 적 있어요?", "casual"],
    ["Joon", "No, I’ve never taken one. Was it comfortable?", "Chưa, tôi chưa bao giờ đi. Có thoải mái không?", "아니요, 한 번도 타 본 적 없어요. 편했어요?", "casual"],
    ["Linh", "It was quiet, but I didn’t sleep much. Tell me more about your trips next time.", "Yên tĩnh, nhưng tôi không ngủ được nhiều. Lần sau kể tôi nghe về chuyến đi của bạn nhé.", "조용했지만 잠은 많이 못 잤어요. 다음에는 당신 여행 이야기도 들려주세요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "Have you ever…? để hỏi trải nghiệm",
      titleKo: "경험을 묻는 Have you ever…?",
      explanationVi: "Dùng hiện tại hoàn thành để hỏi một trải nghiệm vào bất kỳ thời điểm nào trước hiện tại: “Have you ever been to Jeju?” Trả lời ngắn: “Yes, I have.” hoặc “No, I’ve never been there.”",
      explanationKo: "지금까지의 경험을 물을 때는 현재완료를 써요. Have you ever…?에는 Yes, I have. 또는 I’ve never…로 대답해요.",
      easierKorean: "경험을 물으면 Have you ever, 대답은 I have hoặc I’ve never로 해요.",
    },
    {
      titleVi: "Quá khứ đơn cho chi tiết cụ thể",
      titleKo: "구체적인 세부 내용의 과거형",
      explanationVi: "Sau khi đã trả lời bằng hiện tại hoàn thành, chuyển sang quá khứ đơn khi kể chi tiết: “I went with my family the first time.” Câu hỏi chi tiết dùng What did you like? Did you go with your family?",
      explanationKo: "현재완료로 대답한 뒤 구체적인 내용은 과거형으로 말해요. 세부 질문도 과거형으로 물어요.",
      easierKorean: "경험은 현재완료, 자세한 이야기는 과거형으로 말해요.",
    },
  ],
  examples: [
    ["Have you ever tried Vietnamese coffee?", "Bạn đã từng thử cà phê Việt Nam chưa?", "베트남 커피를 마셔 본 적 있어요?", "Câu hỏi Joon hỏi khi cả hai đi ăn sáng."],
    ["I’ve never taken a night train.", "Tôi chưa bao giờ đi tàu đêm.", "야간 열차를 타 본 적이 없어요.", "Câu trả lời của Linh trong cuộc trò chuyện về di chuyển."],
    ["We’ve visited that museum once.", "Chúng tôi đã đến bảo tàng đó một lần.", "그 박물관에 한 번 가 봤어요.", "Chi tiết Linh kể trước khi giới thiệu bảo tàng."],
    ["It was a really memorable trip.", "Đó là một chuyến đi rất đáng nhớ.", "정말 기억에 남는 여행이었어요.", "Cảm nhận Joon nói sau chuyến đi Đà Lạt."],
    ["What did you do there?", "Bạn đã làm gì ở đó?", "거기서 뭐 했어요?", "Câu hỏi tiếp theo sau khi nghe trải nghiệm."],
    ["I tried surfing for the first time.", "Tôi đã thử lướt sóng lần đầu.", "처음으로 서핑을 해 봤어요.", "Trải nghiệm mới của Linh ở biển Mỹ Khê."],
    ["The market is worth visiting in the morning.", "Khu chợ đáng ghé thăm vào buổi sáng.", "시장은 아침에 가 볼 만해요.", "Lời khuyên Linh dành cho Joon."],
    ["I’d highly recommend the local food.", "Tôi rất khuyên bạn thử món ăn địa phương.", "현지 음식을 정말 추천해요.", "Lời giới thiệu trong tin nhắn sau chuyến đi."],
    ["Have you been there before?", "Bạn đã từng đến đó chưa?", "전에 거기 가 본 적 있어요?", "Câu hỏi làm rõ trước khi kể chi tiết."],
    ["I went there with my family last year.", "Năm ngoái tôi đến đó cùng gia đình.", "작년에 가족과 함께 갔어요.", "Chi tiết kèm thời gian cụ thể trong câu trả lời."],
    ["The view was better than I expected.", "Phong cảnh đẹp hơn tôi mong đợi.", "경치가 생각보다 더 좋았어요.", "Nhận xét Linh đưa ra khi xem lại ảnh."],
    ["We got lost, but a local helped us.", "Chúng tôi bị lạc nhưng một người địa phương đã giúp.", "길을 잃었지만 현지인이 도와줬어요.", "Câu chuyện nhỏ Joon kể trong bữa ăn."],
    ["I’ve had a similar experience.", "Tôi từng có trải nghiệm tương tự.", "저도 비슷한 경험이 있어요.", "Cách Linh nối câu chuyện của mình với Joon."],
    ["That sounds like a lot of fun.", "Nghe có vẻ rất vui.", "정말 재미있었겠네요.", "Phản hồi tự nhiên khi nghe kể chuyện."],
    ["I’d love to try that one day.", "Một ngày nào đó tôi rất muốn thử.", "언젠가 저도 해 보고 싶어요.", "Câu nói thể hiện mong muốn sau khi nghe trải nghiệm."],
    ["Tell me more when you have time.", "Khi nào có thời gian kể thêm cho tôi nhé.", "시간 있을 때 더 이야기해 주세요.", "Câu kết tự nhiên khi kết thúc cuộc trò chuyện."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-sharing-experiences-listen",
      "Nghe câu “I’ve been there twice. Once in summer and once in winter.” và chọn số lần Linh đến Jeju.",
      ["Hai lần.", "Một lần.", "Chưa bao giờ."],
      "Hai lần.",
      "listening",
      "a2-sharing-experiences-communicate",
      "Chú ý từ “twice”.",
    ),
    exercise.dictation(
      "a2-sharing-experiences-dictation",
      "Nghe và chép lại câu trả lời về trải nghiệm.",
      "Yes, I’ve been there twice.",
      "a2-sharing-experiences-form",
    ),
  ],
  shadowing: {
    line: "I highly recommend the coastal walk.",
    notesVi: ["Nhấn mạnh “highly” để thể hiện mức độ khuyến khích.", "Đọc “coastal_walk” thành một cụm liền."],
    notesKo: ["“highly”를 세게 말하면 추천의 강도가 잘 드러나요.", "“coastal walk”는 붙여서 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-sharing-experiences-g1",
      "Chọn câu hỏi đúng để hỏi về một trải nghiệm.",
      ["Have you ever been to Jeju?", "Did you ever go to Jeju?", "Have you ever go to Jeju?"],
      "Have you ever been to Jeju?",
      "grammar",
      "a2-sharing-experiences-form",
    ),
    exercise.translation(
      "a2-sharing-experiences-g2",
      "Dịch sang tiếng Anh: “Tôi chưa bao giờ đi tàu đêm.”",
      "I’ve never taken a night train.",
      "a2-sharing-experiences-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-sharing-experiences-production",
      "Viết 5 câu kể về một trải nghiệm đáng nhớ: hỏi hoặc trả lời bằng hiện tại hoàn thành, hai chi tiết với quá khứ đơn và một lời khuyên.",
      "a2-sharing-experiences-communicate",
      "Have you ever tried a night ferry? I’ve taken one once, from Jeju to Mokpo. It was quiet, and I watched the lights for two hours. The ferry was clean and comfortable. I highly recommend it if you have time.",
      ["Có câu hỏi hoặc trả lời với hiện tại hoàn thành", "Có hai chi tiết với quá khứ đơn", "Có một lời khuyên"],
    ),
    exercise.speaking(
      "a2-sharing-experiences-speaking",
      "Nói 60–75 giây kể lại một trải nghiệm du lịch: hỏi lại người nghe một câu, kể hai chi tiết và kết bằng một lời khuyên.",
      "a2-sharing-experiences-communicate",
      "Have you ever been to Da Nang? I’ve been there twice. The first time I went with my family, and we walked along the beach every morning. I tried surfing for the first time. It was a memorable trip, and I highly recommend the local food.",
      ["Có câu hỏi và câu trả lời", "Có hai chi tiết cụ thể", "Tự nghe lại và nhận xét"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-sharing-experiences-m1",
      "Chọn câu phù hợp khi bạn muốn nói mình chưa từng làm việc đó.",
      ["I’ve never tried surfing.", "I never tried surfing last year.", "I’ve never try surfing."],
      "I’ve never tried surfing.",
      "grammar",
      "a2-sharing-experiences-form",
    ),
    exercise.dictation(
      "a2-sharing-experiences-m2",
      "Nghe và chép lại lời khuyên về khu chợ.",
      "The market is worth visiting in the morning.",
      "a2-sharing-experiences-comprehension",
    ),
    exercise.translation(
      "a2-sharing-experiences-m3",
      "Dịch sang tiếng Anh: “Năm ngoái tôi đến đó cùng gia đình.”",
      "I went there with my family last year.",
      "a2-sharing-experiences-form",
    ),
    exercise.speaking(
      "a2-sharing-experiences-m4",
      "Kể một trải nghiệm trong 45 giây và kết bằng một lời khuyên.",
      "a2-sharing-experiences-communicate",
      "I’ve visited Jeju twice. The first time I went with my family and we walked along the coast. The second time was in winter, and it was very quiet. I highly recommend the coastal walk.",
      ["Có trải nghiệm và lời khuyên", "Dùng cả hiện tại hoàn thành và quá khứ đơn", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-sharing-experiences-m5",
      "Điền dạng đúng: “Have you ever ______ (be) to Jeju?”",
      "been",
      "grammar",
      "a2-sharing-experiences-comprehension",
    ),
  ],
  canDo: ["Có thể hỏi và kể về trải nghiệm với chi tiết cụ thể."],
  spiralReview: ["A2 Unit 1 bài 1: hiện tại hoàn thành và quá khứ đơn", "A1: kể sở thích và hoạt động trong kỳ nghỉ"],
  errorCategories: ["verb-tense", "word-choice", "missing-word", "word-order"],
};

/* ------------------------------------------------------------------ *
 * Bài 3 — Lên kế hoạch và sắp xếp thời gian
 * ------------------------------------------------------------------ */
const planningSchedules: LessonSeed = {
  id: "a2-planning-schedules",
  unitId,
  number: 3,
  prerequisites: ["a2-sharing-experiences"],
  titleVi: "Lên kế hoạch và sắp xếp thời gian",
  titleKo: "계획과 일정 조정하기",
  situationVi: "Linh và Joon tìm thời gian gặp nhau trong tuần bận rộn, đổi giờ hai lần và chốt lịch cuối cùng.",
  situationKo: "린과 준은 바쁜 한 주 안에서 만날 시간을 찾고, 시간을 두 번 바꾼 뒤 최종 일정을 정해요.",
  objectives: [
    { id: "a2-planning-schedules-communicate", en: "Arrange a meeting time and confirm the final plan.", vi: "Sắp xếp thời gian gặp và xác nhận kế hoạch cuối cùng.", ko: "만날 시간을 정하고 최종 계획을 확인할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-planning-schedules-form", en: "Use be going to for plans and will for instant decisions.", vi: "Dùng be going to cho kế hoạch và will cho quyết định tức thời.", ko: "계획은 be going to, 즉석 결정은 will로 말할 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-planning-schedules-comprehension", en: "Follow times and changes in a scheduling conversation.", vi: "Nghe theo dõi giờ và thay đổi trong một cuộc trao đổi lịch hẹn.", ko: "일정 대화에서 시간과 변경 사항을 따라갈 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["available", "be available", "có thời gian", "시간이 되다", "/biː əˈveɪləbl/", "be aVAILable", "neutral", ["be available on Friday", "not available before five"]],
    ["schedule", "check my schedule", "kiểm tra lịch", "일정을 확인하다", "/tʃek maɪ ˈʃedjuːl/", "check my SCHEDule", "neutral", ["a busy schedule", "check the schedule"]],
    ["going-to", "be going to", "dự định sẽ", "…할 예정이다", "/biː ˈɡəʊɪŋ tuː/", "be GOing to", "neutral", ["going to meet", "going to be out of town"]],
    ["move", "move the meeting", "dời cuộc họp", "회의를 옮기다", "/muːv ðə ˈmiːtɪŋ/", "MOVE the MEEting", "neutral", ["move the call", "move it to Friday"]],
    ["fit", "fit something in", "sắp xếp chen vào", "시간을 내다", "/fɪt ˈsʌmθɪŋ ɪn/", "FIT something IN", "casual", ["fit it in at four", "fit in a short call"]],
    ["by", "by Friday", "trước thứ Sáu", "금요일까지", "/baɪ ˈfraɪdeɪ/", "by FRIday", "neutral", ["by Friday", "by three o’clock"]],
    ["until", "not until", "mãi đến… mới", "…까지는 안 되다", "/nɒt ənˈtɪl/", "not unTIL", "neutral", ["not until five", "not free until"]],
    ["work-around", "work around", "sắp xếp phù hợp với", "…에 맞추다", "/wɜːk əˈraʊnd/", "work aROUND", "neutral", ["work around your schedule", "work around the meeting"]],
  ],
  dialogue: [
    ["Linh", "Are you available on Thursday afternoon?", "Chiều thứ Năm bạn có thời gian không?", "목요일 오후에 시간 있어요?", "neutral"],
    ["Joon", "I’m going to meet a client at two, but I’m free after four.", "Tôi sẽ gặp khách hàng lúc hai giờ, nhưng rảnh sau bốn giờ.", "2시에 고객을 만날 예정인데, 4시 이후에는 괜찮아요.", "neutral"],
    ["Linh", "Could we fit it in at four thirty?", "Chúng ta sắp xếp lúc bốn giờ ba mươi được không?", "4시 30분에 넣을 수 있을까요?", "neutral"],
    ["Joon", "Four thirty works, but only for thirty minutes.", "Bốn giờ ba mươi thì được, nhưng chỉ ba mươi phút thôi.", "4시 30분은 괜찮지만 30분만 가능해요.", "neutral"],
    ["Linh", "That’s fine. I’ll bring the short list so we can decide quickly.", "Được. Tôi sẽ mang danh sách ngắn để chúng ta quyết nhanh.", "괜찮아요. 빨리 정할 수 있게 짧은 목록을 가져갈게요.", "neutral"],
    ["Joon", "Actually, my client just moved the meeting to four o’clock.", "Thực ra khách vừa dời cuộc họp sang bốn giờ.", "아, 고객이 회의를 4시로 옮겼어요.", "neutral"],
    ["Linh", "No problem. I’ll move it to Thursday morning instead.", "Không sao. Tôi sẽ dời sang sáng thứ Năm.", "괜찮아요. 그럼 목요일 아침으로 옮길게요.", "neutral"],
    ["Joon", "I won’t be free until eleven, but I can work around that.", "Mãi đến mười một giờ tôi mới rảnh, nhưng tôi có thể sắp xếp theo giờ đó.", "11시까지는 시간이 안 되지만, 그 시간에 맞출 수 있어요.", "neutral"],
    ["Linh", "So eleven thirty on Thursday morning?", "Vậy mười một giờ ba mươi sáng thứ Năm nhé?", "그럼 목요일 오전 11시 30분이요?", "neutral"],
    ["Joon", "Yes, and let’s use the small meeting room.", "Vâng, và chúng ta dùng phòng họp nhỏ nhé.", "네, 작은 회의실을 쓰면 좋겠어요.", "neutral"],
    ["Linh", "I’ll book it now and send you a calendar invite.", "Tôi sẽ đặt ngay và gửi bạn lời mời lịch.", "지금 예약하고 캘린더 초대를 보낼게요.", "neutral"],
    ["Joon", "Perfect. See you on Thursday.", "Tuyệt. Hẹn gặp thứ Năm.", "좋아요. 목요일에 봐요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "be going to cho kế hoạch đã định",
      titleKo: "이미 정한 계획의 be going to",
      explanationVi: "Dùng be going to khi kế hoạch đã có trước lúc nói: “I’m going to meet a client at two.” Câu phủ định: “I’m not going to be in the office tomorrow.”",
      explanationKo: "말하기 전에 이미 정한 계획은 be going to로 말해요. 부정문은 am/is/are not going to를 써요.",
      easierKorean: "미리 정한 일정은 am/is/are going to를 써요.",
    },
    {
      titleVi: "will cho quyết định ngay lúc nói",
      titleKo: "말하는 순간의 결정 will",
      explanationVi: "Khi quyết định ngay trong cuộc trò chuyện, dùng will: “I’ll move it to Thursday morning.” “I’ll book it now.” Câu phủ định “I won’t be free until eleven” cũng là một quyết định hoặc thông tin vừa xác nhận.",
      explanationKo: "대화 중 바로 정한 일은 will로 말해요. I’ll move it, I’ll book it now처럼 즉석 결정에 써요.",
      easierKorean: "지금 바로 정했으면 will을 써요.",
    },
  ],
  examples: [
    ["I’m going to meet a client at two.", "Tôi sẽ gặp khách hàng lúc hai giờ.", "2시에 고객을 만날 예정이에요.", "Joon nói về kế hoạch đã có trong lịch."],
    ["I’ll check my calendar now.", "Tôi sẽ kiểm tra lịch ngay.", "지금 일정을 확인할게요.", "Quyết định tức thời khi Linh hỏi giờ."],
    ["Are you available after lunch?", "Sau bữa trưa bạn có thời gian không?", "점심 이후에 시간 있어요?", "Câu hỏi mở đầu khi sắp xếp gặp mặt."],
    ["Thursday morning works better for me.", "Sáng thứ Năm phù hợp hơn với tôi.", "저는 목요일 아침이 더 좋아요.", "Câu trả lời khi có hai phương án."],
    ["Could we move the call to Friday?", "Chúng ta dời cuộc gọi sang thứ Sáu được không?", "통화를 금요일로 옮길 수 있을까요?", "Lời đề nghị khi lịch cũ bị trùng."],
    ["I can fit it in before three.", "Tôi có thể sắp xếp trước ba giờ.", "3시 전에는 시간을 낼 수 있어요.", "Câu trả lời xác nhận khoảng thời gian trống."],
    ["I won’t be free until five.", "Mãi đến năm giờ tôi mới rảnh.", "5시까지는 시간이 안 돼요.", "Thông tin Joon báo khi khách đổi giờ."],
    ["Let’s work around your schedule.", "Hãy sắp xếp theo lịch của bạn.", "당신 일정에 맞춰요.", "Câu thể hiện sự linh hoạt khi hẹn."],
    ["We need to finish this by Friday.", "Chúng ta cần hoàn thành việc này trước thứ Sáu.", "금요일까지는 끝내야 해요.", "Hạn chót Linh nhắc trong cuộc họp."],
    ["I’m going to be out of town next week.", "Tuần tới tôi sẽ đi vắng.", "다음 주에는 다른 지역에 있을 예정이에요.", "Lý do Joon muốn gặp sớm hơn."],
    ["I’ll send you a calendar invite.", "Tôi sẽ gửi bạn lời mời lịch.", "캘린더 초대를 보낼게요.", "Bước xác nhận cuối của Linh."],
    ["Does ten thirty still work?", "Mười giờ rưỡi vẫn phù hợp chứ?", "10시 30분도 괜찮아요?", "Câu hỏi kiểm tra lại khi lịch có thể đổi."],
    ["I have a gap between meetings.", "Tôi có một khoảng trống giữa các cuộc họp.", "회의 사이에 시간이 비어 있어요.", "Thông tin giúp chọn được giờ gặp."],
    ["Could you give me a little notice?", "Bạn báo trước cho tôi một chút được không?", "조금 미리 알려 줄 수 있어요?", "Lời đề nghị khi cần sắp xếp công việc."],
    ["That gives us enough time.", "Như vậy chúng ta có đủ thời gian.", "그러면 시간이 충분해요.", "Câu kết khi đã chọn được khung giờ."],
    ["Let’s confirm the room tomorrow.", "Ngày mai chúng ta xác nhận phòng nhé.", "내일 회의실을 확인해요.", "Việc còn lại trước cuộc họp."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-planning-schedules-listen",
      "Nghe câu “I won’t be free until five.” và chọn thời gian rảnh.",
      ["Từ năm giờ.", "Trước năm giờ.", "Cả buổi chiều."],
      "Từ năm giờ.",
      "listening",
      "a2-planning-schedules-comprehension",
      "Chú ý cấu trúc “not until”.",
    ),
    exercise.dictation(
      "a2-planning-schedules-dictation",
      "Nghe và chép lại giờ hẹn cuối cùng.",
      "I’ll move it to Thursday morning instead.",
      "a2-planning-schedules-form",
    ),
  ],
  shadowing: {
    line: "Could we fit it in at four thirty?",
    notesVi: ["Lên giọng ở “thirty” vì đây là câu hỏi.", "Nối “fit_it_in” thành một cụm nhanh."],
    notesKo: ["질문이므로 “thirty”를 올려 말해요.", "“fit it in”은 빠르게 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-planning-schedules-g1",
      "Chọn câu thể hiện quyết định ngay lúc nói.",
      ["I’ll check my calendar now.", "I’m going to have checked my calendar.", "I check my calendar yesterday."],
      "I’ll check my calendar now.",
      "grammar",
      "a2-planning-schedules-form",
    ),
    exercise.translation(
      "a2-planning-schedules-g2",
      "Dịch sang tiếng Anh: “Sáng thứ Năm phù hợp hơn với tôi.”",
      "Thursday morning works better for me.",
      "a2-planning-schedules-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-planning-schedules-production",
      "Viết một tin nhắn 5–6 câu để sắp xếp cuộc hẹn: đề xuất hai khung giờ, nêu một kế hoạch đã có, một thay đổi và xác nhận cuối cùng.",
      "a2-planning-schedules-communicate",
      "Hi Joon, are you available on Thursday? I’m going to be in meetings all morning, but I’m free after two. Could we meet at four thirty? If that doesn’t work, I’ll move my afternoon slot. Let’s confirm the small meeting room tomorrow.",
      ["Có hai khung giờ đề xuất", "Có be going to và will", "Có câu xác nhận cuối cùng"],
    ),
    exercise.speaking(
      "a2-planning-schedules-speaking",
      "Nói 60 giây để sắp xếp một cuộc hẹn: nêu kế hoạch đã có, đề xuất giờ, xử lý một thay đổi và xác nhận.",
      "a2-planning-schedules-communicate",
      "I’m going to visit a client on Thursday morning, so I’m free after one. Could we meet at two thirty? If that doesn’t work, I’ll move my afternoon call. Let’s confirm the room tomorrow and I’ll send a calendar invite.",
      ["Có kế hoạch, đề xuất giờ và xác nhận", "Dùng be going to và will", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-planning-schedules-m1",
      "Chọn câu phù hợp khi bạn quyết định ngay trong cuộc trò chuyện.",
      ["I’ll send the invite now.", "I’m going to send the invite yesterday.", "I send the invite now tomorrow."],
      "I’ll send the invite now.",
      "grammar",
      "a2-planning-schedules-form",
    ),
    exercise.dictation(
      "a2-planning-schedules-m2",
      "Nghe và chép lại câu về khoảng trống giữa các cuộc họp.",
      "I have a gap between meetings at three.",
      "a2-planning-schedules-comprehension",
    ),
    exercise.translation(
      "a2-planning-schedules-m3",
      "Dịch sang tiếng Anh: “Mãi đến năm giờ tôi mới rảnh.”",
      "I won’t be free until five.",
      "a2-planning-schedules-form",
    ),
    exercise.speaking(
      "a2-planning-schedules-m4",
      "Sắp xếp một cuộc hẹn trong 45 giây, có một thay đổi về giờ.",
      "a2-planning-schedules-communicate",
      "I’m going to meet a client at two, so I’m not free until four. Could we fit it in at four thirty? Actually, I’ll move my call to Friday instead. Let’s meet on Thursday morning.",
      ["Có kế hoạch, thay đổi và giờ cuối", "Dùng be going to và will", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-planning-schedules-m5",
      "Điền “by” hoặc “until”: “I won’t be free ______ eleven.”",
      "until",
      "grammar",
      "a2-planning-schedules-comprehension",
    ),
  ],
  canDo: ["Có thể sắp xếp thời gian, xử lý thay đổi và xác nhận kế hoạch cuối cùng."],
  spiralReview: ["A1: hỏi giờ và ngày", "A2 Unit 1 bài 1: trao đổi về thay đổi lịch"],
  errorCategories: ["grammar-form", "word-choice", "missing-word", "preposition"],
};

/* ------------------------------------------------------------------ *
 * Bài 4 — Đưa ra lời mời, chấp nhận và từ chối
 * ------------------------------------------------------------------ */
const invitations: LessonSeed = {
  id: "a2-invitations",
  unitId,
  number: 4,
  prerequisites: ["a2-planning-schedules"],
  titleVi: "Đưa ra lời mời, chấp nhận và từ chối",
  titleKo: "초대하고 수락·거절하기",
  situationVi: "Joon mời Linh ăn tối cùng nhóm; Linh từ chối lịch sự vì đã có kế hoạch và cả hai thống nhất dịp khác.",
  situationKo: "준이 린을 팀 저녁 식사에 초대해요. 린은 이미 약속이 있어서 정중히 거절하고, 두 사람은 다른 날짜를 정해요.",
  objectives: [
    { id: "a2-invitations-communicate", en: "Invite someone, accept and decline politely.", vi: "Mời ai đó, chấp nhận và từ chối một cách lịch sự.", ko: "누군가를 초대하고 정중하게 수락하거나 거절할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-invitations-form", en: "Use Would you like to…? and polite refusals.", vi: "Dùng Would you like to…? và cách từ chối lịch sự.", ko: "Would you like to…?와 정중한 거절 표현을 쓸 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-invitations-comprehension", en: "Understand the reason behind a refusal.", vi: "Nghe hiểu lý do phía sau một lời từ chối.", ko: "거절의 이유를 들을 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["would-like", "Would you like to…?", "Bạn có muốn…?", "…할래요?", "/wʊd juː laɪk tuː/", "Would you LIKE to", "neutral", ["Would you like to join us", "Would you like to come"]],
    ["love-to", "I’d love to", "Tôi rất muốn", "정말 좋아요", "/aɪd lʌv tuː/", "I’d LOVE to", "casual", ["I’d love to come", "I’d love to join"]],
    ["sounds", "That sounds great", "Nghe tuyệt đấy", "좋네요", "/ðæt saʊndz ɡreɪt/", "That SOUNDS GREAT", "casual", ["that sounds great", "that sounds good"]],
    ["afraid", "I’m afraid I can’t", "Tiếc là tôi không thể", "아쉽지만 안 돼요", "/aɪm əˈfreɪd aɪ kɑːnt/", "I’m aFRAID I CAN’T", "formal", ["I’m afraid I can’t make it", "I’m afraid I’m busy"]],
    ["maybe", "Maybe another time", "Có lẽ để dịp khác", "다음 기회에요", "/ˈmeɪbi əˈnʌðə taɪm/", "MAYbe aNOther time", "casual", ["maybe next week", "maybe another time"]],
    ["join", "join us", "tham gia cùng chúng tôi", "우리와 함께하다", "/dʒɔɪn ʌs/", "JOIN us", "neutral", ["join us for dinner", "join the group"]],
    ["thanks", "Thanks for inviting me", "Cảm ơn đã mời tôi", "초대해 줘서 고마워요", "/θæŋks fər ɪnˈvaɪtɪŋ miː/", "THANKS for inVITing me", "neutral", ["thanks for inviting me", "thanks for thinking of me"]],
    ["make-it", "I can’t make it", "Tôi không thể đến", "참석하기 어렵다", "/aɪ kɑːnt meɪk ɪt/", "I can’t MAKE it", "casual", ["I can’t make it on Friday", "sorry, I can’t make it"]],
  ],
  dialogue: [
    ["Joon", "We’re having dinner on Friday. Would you like to join us?", "Chúng tôi ăn tối vào thứ Sáu. Bạn có muốn tham gia không?", "금요일에 저녁을 먹어요. 같이 할래요?", "neutral"],
    ["Linh", "I’d love to. What time are you meeting?", "Tôi rất muốn. Mọi người gặp lúc mấy giờ?", "정말 좋아요. 몇 시에 만나요?", "casual"],
    ["Joon", "Around seven at the Thai restaurant near work.", "Khoảng bảy giờ ở nhà hàng Thái gần chỗ làm.", "직장 근처 태국 식당에서 7시쯤이요.", "neutral"],
    ["Linh", "Let me check my schedule. I think I have something on Friday.", "Để tôi kiểm tra lịch. Hình như thứ Sáu tôi có việc.", "일정을 확인해 볼게요. 금요일에 약속이 있는 것 같아요.", "neutral"],
    ["Joon", "No pressure. Let me know tonight if you can come.", "Không sao đâu. Tối nay cho tôi biết nếu bạn đến được.", "부담 갖지 마세요. 올 수 있으면 오늘 밤에 알려 주세요.", "casual"],
    ["Linh", "Thanks. I’m afraid I can’t make it on Friday — I have a family dinner.", "Cảm ơn. Tiếc là thứ Sáu tôi không đến được — tôi có bữa tối gia đình.", "고마워요. 아쉽지만 금요일에는 못 가요. 가족 저녁 식사가 있어요.", "formal"],
    ["Joon", "That’s okay. Maybe another time.", "Không sao. Có lẽ để dịp khác.", "괜찮아요. 다음 기회에 해요.", "casual"],
    ["Linh", "Could we do Saturday lunch instead?", "Chúng ta ăn trưa thứ Bảy thay vào đó được không?", "대신 토요일 점심은 어때요?", "neutral"],
    ["Joon", "Saturday lunch works for me. I’ll ask the others.", "Trưa thứ Bảy thì được với tôi. Tôi sẽ hỏi mọi người.", "토요일 점심은 괜찮아요. 다른 사람들에게 물어볼게요.", "neutral"],
    ["Linh", "Thanks for inviting me. I appreciate it.", "Cảm ơn đã mời tôi. Tôi rất trân trọng.", "초대해 줘서 고마워요.", "formal"],
    ["Joon", "No problem. I’ll confirm the place tomorrow.", "Không có gì. Mai tôi xác nhận địa điểm.", "괜찮아요. 내일 장소를 알려 줄게요.", "neutral"],
    ["Linh", "Perfect. See you on Saturday.", "Tuyệt. Hẹn gặp thứ Bảy.", "좋아요. 토요일에 봐요.", "casual"],
  ],
  grammar: [
    {
      titleVi: "Would you like to…? để mời",
      titleKo: "초대할 때 쓰는 Would you like to…?",
      explanationVi: "Would you like to + động từ nguyên mẫu là lời mời lịch sự ở mọi tình huống: “Would you like to join us?” Khi muốn rủ nhẹ hơn, dùng “Do you want to…?” hoặc “How about…?”",
      explanationKo: "Would you like to + 동사원형은 어디서나 쓸 수 있는 정중한 초대예요. 더 가볍게 초대할 때는 Do you want to…?나 How about…?을 써요.",
      easierKorean: "정중한 초대는 Would you like to로 시작해요.",
    },
    {
      titleVi: "Chấp nhận và từ chối lịch sự",
      titleKo: "정중하게 수락하고 거절하기",
      explanationVi: "Chấp nhận: “I’d love to.” / “That sounds great.” Từ chối: cảm ơn trước, nói I’m afraid I can’t, rồi nêu lý do ngắn: “Thanks, but I’m afraid I can’t make it — I have a family dinner.” Nên kết bằng phương án khác: “Maybe another time.”",
      explanationKo: "수락할 때는 I’d love to. 또는 That sounds great.라고 해요. 거절할 때는 먼저 고맙다고 말하고, I’m afraid I can’t로 부드럽게 거절한 뒤 짧게 이유를 말해요.",
      easierKorean: "거절할 때는 고맙다 → 아쉽다 → 이유 → 다른 제안 순서로 말해요.",
    },
  ],
  examples: [
    ["Would you like to join us for lunch?", "Bạn có muốn ăn trưa cùng chúng tôi không?", "우리와 점심 먹을래요?", "Joon mời Linh trong giờ nghỉ trưa."],
    ["I’d love to.", "Tôi rất muốn.", "정말 좋아요.", "Câu chấp nhận ngắn và tự nhiên."],
    ["That sounds great.", "Nghe tuyệt đấy.", "좋네요.", "Phản hồi khi được mời dự một buổi ăn tối."],
    ["Thanks, but I already have plans.", "Cảm ơn, nhưng tôi đã có kế hoạch rồi.", "고맙지만 이미 약속이 있어요.", "Cách từ chối kèm lý do ngắn."],
    ["I’m afraid I can’t make it on Friday.", "Tiếc là thứ Sáu tôi không đến được.", "아쉽지만 금요일에는 못 가요.", "Câu từ chối lịch sự trong tin nhắn."],
    ["Maybe another time?", "Có lẽ để dịp khác nhé?", "다음 기회에 할까요?", "Câu giữ quan hệ tốt sau khi từ chối."],
    ["Thanks for inviting me.", "Cảm ơn đã mời tôi.", "초대해 줘서 고마워요.", "Câu cảm ơn trong thư trả lời."],
    ["Are you doing anything this weekend?", "Cuối tuần này bạn có kế hoạch gì không?", "이번 주말에 뭐 해요?", "Câu mở đầu trước khi mời."],
    ["We’re getting together after work.", "Chúng tôi sẽ gặp nhau sau giờ làm.", "퇴근 후에 모여요.", "Thông tin Joon nói kèm lời mời."],
    ["Feel free to bring a friend.", "Bạn cứ tự nhiên rủ thêm một người bạn.", "친구를 데려와도 괜찮아요.", "Câu mời thân thiện trong nhóm chat."],
    ["I might be a little late.", "Có thể tôi sẽ đến hơi muộn.", "조금 늦을 수도 있어요.", "Linh báo trước khi nhận lời."],
    ["Can I let you know tomorrow?", "Ngày mai tôi trả lời được không?", "내일 알려 줘도 될까요?", "Cách trả lời khi chưa chắc lịch."],
    ["No pressure if you’re busy.", "Nếu bạn bận thì không sao đâu.", "바쁘면 부담 갖지 않아도 돼요.", "Câu nói giảm áp lực cho người được mời."],
    ["I appreciate the invitation.", "Tôi rất cảm kích lời mời.", "초대해 주셔서 감사합니다.", "Câu cảm ơn trang trọng trong email."],
    ["Could we do Saturday lunch instead?", "Chúng ta ăn trưa thứ Bảy thay vào đó được không?", "대신 토요일 점심으로 할까요?", "Cách đề xuất phương án khác sau khi từ chối."],
    ["See you there around seven.", "Hẹn gặp bạn ở đó khoảng bảy giờ.", "7시쯤 거기서 봐요.", "Câu xác nhận trước khi gặp."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-invitations-listen",
      "Nghe câu “I’m afraid I can’t make it on Friday — I have a family dinner.” và chọn lý do Linh từ chối.",
      ["Linh có bữa tối gia đình.", "Linh phải đi công tác.", "Linh không thích nhà hàng Thái."],
      "Linh có bữa tối gia đình.",
      "listening",
      "a2-invitations-comprehension",
      "Lý do nằm sau dấu gạch ngang.",
    ),
    exercise.dictation(
      "a2-invitations-dictation",
      "Nghe và chép lại lời mời lịch sự.",
      "Would you like to join us for dinner on Friday?",
      "a2-invitations-form",
    ),
  ],
  shadowing: {
    line: "I’m afraid I can’t make it on Friday.",
    notesVi: ["Hạ giọng ở “afraid” để thể hiện sự tiếc nuối.", "Đọc “can’t_make_it” thành một cụm liền."],
    notesKo: ["“afraid”를 낮게 말하면 아쉬운 마음이 잘 전해져요.", "“can’t make it”은 붙여서 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-invitations-g1",
      "Chọn câu mời lịch sự nhất.",
      ["Would you like to join us?", "You join us.", "Join us now."],
      "Would you like to join us?",
      "grammar",
      "a2-invitations-form",
    ),
    exercise.translation(
      "a2-invitations-g2",
      "Dịch sang tiếng Anh: “Cảm ơn, nhưng tôi đã có kế hoạch rồi.”",
      "Thanks, but I already have plans.",
      "a2-invitations-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-invitations-production",
      "Viết một lời mời (2 câu), một câu chấp nhận và một câu từ chối lịch sự có lý do và đề xuất dịp khác.",
      "a2-invitations-communicate",
      "Would you like to join us for dinner on Friday? I’d love to come. Thanks for inviting me, but I’m afraid I can’t make it on Friday because I have a family dinner. Could we do Saturday lunch instead?",
      ["Có lời mời, chấp nhận và từ chối", "Có lý do ngắn và đề xuất khác", "Giọng lịch sự"],
    ),
    exercise.speaking(
      "a2-invitations-speaking",
      "Nói 60 giây: mời một người bạn đi ăn, nhận lời, sau đó từ chối một lời mời khác và đề xuất dịp khác.",
      "a2-invitations-communicate",
      "Would you like to join us for lunch on Saturday? I’d love to come. That sounds great. Thanks for inviting me, but I’m afraid I can’t make it on Friday because I’m working late. Maybe another time?",
      ["Có đủ ba phần", "Có lý do trong lời từ chối", "Tự nghe lại và sửa một lỗi"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-invitations-m1",
      "Chọn câu từ chối lịch sự nhất.",
      ["Thanks, but I’m afraid I can’t make it.", "No, I don’t come.", "I can’t, bye."],
      "Thanks, but I’m afraid I can’t make it.",
      "grammar",
      "a2-invitations-form",
    ),
    exercise.dictation(
      "a2-invitations-m2",
      "Nghe và chép lại lời mời ăn trưa.",
      "Would you like to join us for lunch?",
      "a2-invitations-comprehension",
    ),
    exercise.translation(
      "a2-invitations-m3",
      "Dịch sang tiếng Anh: “Tiếc là tôi không thể đến vào thứ Sáu.”",
      "I’m afraid I can’t make it on Friday.",
      "a2-invitations-form",
    ),
    exercise.speaking(
      "a2-invitations-m4",
      "Trả lời một lời mời trong 45 giây: chấp nhận hoặc từ chối, nêu lý do và kết thúc tự nhiên.",
      "a2-invitations-communicate",
      "Thanks for inviting me. I’m afraid I can’t make it on Saturday because I have a family dinner, but I’d love to come next week. Could we do Friday lunch instead?",
      ["Có lời từ chối và lý do", "Có đề xuất khác hoặc lời hẹn mới", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-invitations-m5",
      "Điền trợ động từ: “Thanks, but I ______ afraid I can’t make it.”",
      "am",
      "grammar",
      "a2-invitations-comprehension",
    ),
  ],
  canDo: ["Có thể mời, chấp nhận và từ chối một cách lịch sự."],
  spiralReview: ["A1: Would you like…? ở mức cơ bản", "A2 Unit 1 bài 3: sắp xếp thời gian"],
  errorCategories: ["register", "word-choice", "grammar-form", "missing-word"],
};

/* ------------------------------------------------------------------ *
 * Bài 5 — Ôn tập Unit 1 và nhiệm vụ thực tế
 * ------------------------------------------------------------------ */
const unitReview: LessonSeed = {
  id: "a2-unit-1-review",
  unitId,
  number: 5,
  prerequisites: ["a2-invitations"],
  titleVi: "Ôn tập Unit 1 và nhiệm vụ thực tế",
  titleKo: "Unit 1 복습과 실전 미션",
  situationVi: "Gặp lại người quen, kể thay đổi và trải nghiệm, sắp xếp một cuộc hẹn và phản hồi lời mời trong cùng một cuộc trò chuyện.",
  situationKo: "지인을 다시 만나 변화와 경험을 이야기하고, 약속을 정하고, 초대에 답하는 대화를 해요.",
  objectives: [
    { id: "a2-unit-1-review-communicate", en: "Share news, arrange a meeting and respond to an invitation.", vi: "Chia sẻ tin mới, sắp xếp cuộc hẹn và phản hồi lời mời.", ko: "근황을 나누고, 약속을 정하고, 초대에 답할 수 있어요.", skills: ["speaking", "vocabulary"] },
    { id: "a2-unit-1-review-form", en: "Choose between the present perfect, the past simple, going to and will.", vi: "Chọn giữa hiện tại hoàn thành, quá khứ đơn, going to và will.", ko: "현재완료, 과거형, going to, will 중 알맞은 것을 고를 수 있어요.", skills: ["grammar", "writing"] },
    { id: "a2-unit-1-review-comprehension", en: "Follow a long conversation about news and plans.", vi: "Nghe hiểu một cuộc trò chuyện dài về tin mới và kế hoạch.", ko: "근황과 계획에 대한 긴 대화를 이해할 수 있어요.", skills: ["listening", "reading"] },
  ],
  vocab: [
    ["catch-up", "catch up", "trò chuyện về tình hình gần đây", "근황을 나누다", "/kætʃ ʌp/", "catch UP", "casual", ["catch up properly", "let’s catch up"]],
    ["recently", "recently", "gần đây", "최근에", "/ˈriːsntli/", "REcently", "neutral", ["recently moved", "until recently"]],
    ["experience", "share an experience", "chia sẻ trải nghiệm", "경험을 나누다", "/ʃeə ən ɪkˈspɪəriəns/", "SHARE an exPERience", "neutral", ["share an experience", "a new experience"]],
    ["available", "be available", "có thời gian", "시간이 되다", "/biː əˈveɪləbl/", "be aVAILable", "neutral", ["be available on Saturday", "available in the morning"]],
    ["invite", "invite someone", "mời ai đó", "누군가를 초대하다", "/ɪnˈvaɪt/", "inVITE", "neutral", ["invite a friend", "invite the team"]],
    ["accept", "accept an invitation", "nhận lời mời", "초대를 수락하다", "/əkˈsept ən ɪnvɪˈteɪʃn/", "acCEPT an inviTAtion", "formal", ["accept the invitation", "accept politely"]],
    ["decline", "decline politely", "từ chối lịch sự", "정중히 거절하다", "/dɪˈklaɪn pəˈlaɪtli/", "deCLINE poLITEly", "formal", ["decline an offer", "decline politely"]],
    ["confirm", "confirm the plan", "xác nhận kế hoạch", "계획을 확인하다", "/kənˈfɜːm ðə plæn/", "conFIRM the PLAN", "neutral", ["confirm the plan", "confirm by message"]],
  ],
  dialogue: [
    ["Joon", "It’s good to see you again. What’s new?", "Rất vui được gặp lại bạn. Có gì mới không?", "다시 만나서 반가워요. 새로운 소식 있어요?", "casual"],
    ["Linh", "I’ve recently moved, and I’ve started a new job.", "Gần đây tôi đã chuyển nhà và bắt đầu công việc mới.", "최근에 이사했고 새 일을 시작했어요.", "casual"],
    ["Joon", "Where did you move to?", "Bạn chuyển đến đâu?", "어디로 이사했어요?", "casual"],
    ["Linh", "To a small flat near the river. I moved in February.", "Đến một căn hộ nhỏ gần sông. Tôi chuyển vào tháng Hai.", "강 근처 작은 집으로요. 2월에 이사했어요.", "neutral"],
    ["Joon", "We should catch up properly. Are you free on Saturday?", "Chúng ta nên trò chuyện kỹ hơn. Thứ Bảy bạn rảnh không?", "제대로 이야기해요. 토요일에 시간 있어요?", "casual"],
    ["Linh", "I’m available after two. Would you like to meet for coffee at three?", "Tôi rảnh sau hai giờ. Bạn muốn gặp uống cà phê lúc ba giờ không?", "2시 이후에는 괜찮아요. 3시에 커피 마실래요?", "casual"],
    ["Joon", "That sounds great. I’ll book a table near the park.", "Nghe tuyệt đấy. Tôi sẽ đặt bàn gần công viên.", "좋아요. 공원 근처로 자리를 예약할게요.", "casual"],
    ["Linh", "Thanks. Have you been to that café before?", "Cảm ơn. Bạn đã đến quán đó chưa?", "고마워요. 그 카페에 가 본 적 있어요?", "casual"],
    ["Joon", "Yes, I’ve been there twice. The cakes are worth trying.", "Rồi, tôi đến đó hai lần. Bánh ở đó đáng thử.", "네, 두 번 가 봤어요. 케이크가 먹어 볼 만해요.", "casual"],
    ["Linh", "Good to know. I’m afraid I can’t stay long because I have a class at six.", "Biết vậy thì tốt. Tiếc là tôi không ở lâu được vì sáu giờ có lớp.", "알아 두면 좋겠네요. 6시에 수업이 있어서 오래 못 있어요.", "casual"],
    ["Joon", "That’s fine. Two hours is enough for a proper catch-up.", "Không sao. Hai tiếng là đủ để trò chuyện kỹ rồi.", "괜찮아요. 두 시간이면 충분히 이야기할 수 있어요.", "casual"],
    ["Linh", "Let’s confirm on Friday evening.", "Tối thứ Sáu chúng ta xác nhận nhé.", "금요일 저녁에 확인해요.", "neutral"],
  ],
  grammar: [
    {
      titleVi: "Đối chiếu cấu trúc của Unit 1",
      titleKo: "Unit 1 문법 정리",
      explanationVi: "Trải nghiệm: Have you ever…? — Yes, I’ve been there twice. Thay đổi còn liên quan tới hiện tại: I’ve recently moved. Chi tiết đã kết thúc: I moved in February. Kế hoạch đã định: I’m going to meet a client. Quyết định tức thời: I’ll book a table. Lời mời: Would you like to…?",
      explanationKo: "경험은 Have you ever…?, 최근 변화는 현재완료, 끝난 일은 과거형, 계획은 be going to, 즉석 결정은 will, 초대는 Would you like to…?를 써요.",
      easierKorean: "경험, 변화, 지난 일, 계획, 즉석 결정, 초대를 상황에 맞게 구분해요.",
    },
  ],
  examples: [
    ["I’ve recently changed jobs.", "Gần đây tôi đã đổi công việc.", "최근에 직장을 옮겼어요.", "Câu mở đầu khi kể tin mới."],
    ["Have you ever worked abroad?", "Bạn đã từng làm việc ở nước ngoài chưa?", "해외에서 일해 본 적 있어요?", "Câu hỏi về trải nghiệm trong cuộc trò chuyện."],
    ["I worked in Singapore in 2023.", "Tôi đã làm việc ở Singapore năm 2023.", "2023년에 싱가포르에서 일했어요.", "Chi tiết có thời gian xác định."],
    ["I’m going to visit my family next month.", "Tháng tới tôi sẽ thăm gia đình.", "다음 달에 가족을 방문할 예정이에요.", "Kế hoạch Linh kể với Joon."],
    ["Would you like to come with me?", "Bạn có muốn đi cùng tôi không?", "저와 함께 갈래요?", "Lời mời trong cuộc trò chuyện."],
    ["I’d love to, but I need to check my schedule.", "Tôi rất muốn, nhưng cần kiểm tra lịch.", "좋지만 일정을 확인해야 해요.", "Câu trả lời vừa chấp nhận vừa trì hoãn."],
    ["I’ll let you know this evening.", "Tối nay tôi sẽ báo cho bạn.", "오늘 저녁에 알려 줄게요.", "Cam kết thời gian ngắn gọn."],
    ["The new office is closer to home.", "Văn phòng mới gần nhà hơn.", "새 사무실은 집에서 더 가까워요.", "Lý do Linh hài lòng với thay đổi."],
    ["I’ve already met most of the team.", "Tôi đã gặp hầu hết thành viên trong nhóm.", "이미 팀원 대부분을 만났어요.", "Cập nhật trong tuần đầu làm việc."],
    ["We had lunch together yesterday.", "Hôm qua chúng tôi đã ăn trưa cùng nhau.", "어제 함께 점심을 먹었어요.", "Chi tiết đã kết thúc rõ thời gian."],
    ["Are you available this weekend?", "Cuối tuần này bạn có rảnh không?", "이번 주말에 시간 있어요?", "Câu hỏi trước khi hẹn gặp."],
    ["Sunday afternoon works best for me.", "Chiều Chủ nhật phù hợp nhất với tôi.", "저는 일요일 오후가 가장 좋아요.", "Câu trả lời khi có nhiều lựa chọn."],
    ["Thanks for thinking of me.", "Cảm ơn vì đã nghĩ đến tôi.", "저를 생각해 줘서 고마워요.", "Câu cảm ơn khi được mời."],
    ["I’m afraid I can’t make it this time.", "Tiếc là lần này tôi không tham gia được.", "아쉽지만 이번에는 참석하기 어려워요.", "Cách từ chối lịch sự."],
    ["Let’s confirm the place tomorrow.", "Ngày mai chúng ta xác nhận địa điểm nhé.", "내일 장소를 확인해요.", "Bước cuối trước khi gặp."],
    ["It was nice to catch up with you.", "Rất vui được trò chuyện với bạn.", "이야기 나눠서 좋았어요.", "Câu kết khi chia tay."],
  ],
  listening: [
    exercise.multipleChoice(
      "a2-unit-1-review-listen",
      "Nghe câu “I’m available after two. Would you like to meet for coffee at three?” và chọn giờ hẹn.",
      ["Ba giờ chiều.", "Hai giờ chiều.", "Sáu giờ tối."],
      "Ba giờ chiều.",
      "listening",
      "a2-unit-1-review-comprehension",
      "Chú ý số giờ sau “coffee at”.",
    ),
    exercise.dictation(
      "a2-unit-1-review-dictation",
      "Nghe và chép lại câu xác nhận cuối cùng.",
      "Let’s confirm the place tomorrow.",
      "a2-unit-1-review-form",
    ),
  ],
  shadowing: {
    line: "I’d love to, but I need to check my schedule.",
    notesVi: ["Ngắt nhẹ sau “to” để tách ý đồng ý và lý do trì hoãn.", "Đọc “check my schedule” liền mạch."],
    notesKo: ["“to” 뒤에서 잠깐 쉬면 수락과 이유가 구분돼요.", "“check my schedule”은 이어 말해요."],
  },
  guided: [
    exercise.multipleChoice(
      "a2-unit-1-review-g1",
      "Chọn câu đúng cho một kế hoạch đã định.",
      ["I’m going to visit my family next month.", "I visit my family next month.", "I’ve visit my family next month."],
      "I’m going to visit my family next month.",
      "grammar",
      "a2-unit-1-review-form",
    ),
    exercise.translation(
      "a2-unit-1-review-g2",
      "Dịch sang tiếng Anh: “Tối nay tôi sẽ báo cho bạn.”",
      "I’ll let you know this evening.",
      "a2-unit-1-review-form",
    ),
  ],
  production: [
    exercise.written(
      "a2-unit-1-review-production",
      "Viết một tin nhắn 6–7 câu: kể một thay đổi, hỏi một trải nghiệm, đề xuất kế hoạch gặp, phản hồi một lời mời và xác nhận.",
      "a2-unit-1-review-communicate",
      "Hi Joon, I’ve recently moved to a new flat and I’ve started a course. Have you ever studied online? I’m going to be free on Saturday afternoon, so would you like to meet for coffee at three? I’d love to stay longer, but I’m afraid I can’t because I have a class at six. Let’s confirm the place tomorrow.",
      ["Có thay đổi, trải nghiệm, kế hoạch và lời mời", "Dùng ít nhất ba cấu trúc của Unit 1", "Có câu xác nhận"],
    ),
    exercise.speaking(
      "a2-unit-1-review-speaking",
      "Nói 90 giây: kể hai tin mới, hỏi một trải nghiệm, sắp xếp một cuộc hẹn và phản hồi một lời mời.",
      "a2-unit-1-review-communicate",
      "I’ve recently moved closer to work, and I’ve started learning Korean again. Have you ever studied with a tutor online? I’m going to be free on Saturday, so would you like to meet for coffee? I’d love to come to dinner on Friday, but I’m afraid I can’t make it. Let’s confirm the time tomorrow.",
      ["Đủ bốn phần", "Dùng hiện tại hoàn thành, quá khứ đơn và going to", "Tự đánh giá và ghi một điểm cần sửa"],
    ),
  ],
  mastery: [
    exercise.multipleChoice(
      "a2-unit-1-review-m1",
      "Chọn câu đúng.",
      ["Have you ever been to Jeju?", "Have you ever go to Jeju?", "Did you ever been to Jeju?"],
      "Have you ever been to Jeju?",
      "grammar",
      "a2-unit-1-review-form",
    ),
    exercise.dictation(
      "a2-unit-1-review-m2",
      "Nghe và chép lại câu kể về thay đổi gần đây.",
      "I’ve recently changed jobs and moved closer to work.",
      "a2-unit-1-review-comprehension",
    ),
    exercise.translation(
      "a2-unit-1-review-m3",
      "Dịch sang tiếng Anh: “Tiếc là lần này tôi không tham gia được.”",
      "I’m afraid I can’t make it this time.",
      "a2-unit-1-review-form",
    ),
    exercise.speaking(
      "a2-unit-1-review-m4",
      "Nói 90 giây: hai tin mới, một câu hỏi trải nghiệm, một kế hoạch và một lời mời.",
      "a2-unit-1-review-communicate",
      "I’ve recently started a new job and I’ve moved to a smaller flat. Have you ever worked from home? I’m going to visit my family next month, and I’ll book the tickets this week. Would you like to join us for dinner before I go?",
      ["Đủ bốn phần", "Dùng đúng bốn cấu trúc", "Tự đánh giá trung thực"],
    ),
    exercise.fillBlank(
      "a2-unit-1-review-m5",
      "Điền “been” hoặc “gone”: “Have you ever ______ to Jeju?”",
      "been",
      "grammar",
      "a2-unit-1-review-comprehension",
    ),
  ],
  canDo: ["Có thể chia sẻ tin mới, sắp xếp cuộc hẹn và phản hồi lời mời trong một cuộc trò chuyện."],
  spiralReview: ["A1: giới thiệu bản thân, sở thích và thời gian", "A2 Unit 1 bài 1 đến bài 4"],
  errorCategories: ["verb-tense", "word-choice", "register", "word-order"],
};

export const a2Unit1 = bilingualUnitSchema.parse({
  id: unitId,
  level: "A2",
  titleVi: "Kết nối trong cuộc sống hằng ngày",
  titleKo: "일상 속 관계",
  lessons: [recentChanges, sharingExperiences, planningSchedules, invitations, unitReview].map(buildLesson),
});
