import type{BranchingScenario}from"@/lib/branching";const goodVi="Cách nói này phù hợp và tự nhiên.";const weakVi="Ý đã rõ, nhưng hãy chọn cách diễn đạt mềm mại hơn.";const goodKo="상황에 맞고 자연스러운 표현이에요.";const weakKo="뜻은 통하지만 더 부드러운 표현을 골라 보세요.";
const choice=(id:string,text:string,natural:boolean,outcome:string)=>({id,text,natural,feedbackVi:natural?goodVi:weakVi,feedbackKo:natural?goodKo:weakKo,outcome});
export const scenarios:BranchingScenario[]=[
{id:"introduce",title:"처음 만난 동료에게 소개하기",titleVi:"Giới thiệu với đồng nghiệp mới",startId:"a",nodes:[{id:"a",speaker:"Alex",line:"Hi, I’m Alex. Nice to meet you.",promptVi:"Hãy trả lời một cách tự nhiên.",promptKo:"자연스럽게 답하세요.",requireAttempt:"written",choices:[choice("a1","Nice to meet you, too. I’m Mina.",true,"connected"),choice("a2","My name Mina.",false,"retry")]}]},
{id:"food",title:"식당에서 주문하기",titleVi:"Gọi món tại nhà hàng",startId:"a",nodes:[{id:"a",speaker:"Server",line:"Are you ready to order?",promptVi:"Hãy bắt đầu gọi món.",choices:[{id:"a1",text:"Yes, I’d like the chicken salad, please.",natural:true,feedbackVi:goodVi,feedbackKo:goodKo,nextId:"b"},choice("a2","Give chicken.",false,"retry")]},{id:"b",speaker:"Server",line:"Anything to drink?",promptVi:"Hãy chọn đồ uống.",choices:[choice("b1","Water, please.",true,"ordered"),choice("b2","No drink give.",false,"retry")]}]},
{id:"appointment",title:"약속 시간 바꾸기",titleVi:"Đổi giờ hẹn",startId:"a",nodes:[{id:"a",speaker:"Jin",line:"See you at three.",promptVi:"Hãy đề nghị đổi sang 4 giờ.",requireAttempt:"written",choices:[choice("a1","Could we make it four?",true,"changed"),choice("a2","Change four.",false,"retry")]}]},
{id:"help",title:"길을 물어 도움 요청하기",titleVi:"Hỏi đường",startId:"a",nodes:[{id:"a",speaker:"Passerby",line:"Can I help you?",promptVi:"Hãy hỏi vị trí nhà ga.",choices:[choice("a1","Yes, could you tell me where the station is?",true,"helped"),choice("a2","Station where?",false,"retry")]}]},
{id:"late",title:"늦는다고 알리기",titleVi:"Báo rằng bạn sẽ đến muộn",startId:"a",nodes:[{id:"a",speaker:"Mina",line:"Are you almost here?",promptVi:"Hãy báo rằng bạn sẽ muộn 10 phút.",choices:[choice("a1","Sorry, I’m running about ten minutes late.",true,"notified"),choice("a2","I late ten.",false,"retry")]}]}
];
