export const viUi={
 nav:{today:"Hôm nay",curriculum:"Lộ trình",review:"Ôn tập",practice:"Luyện nghe nói",notebook:"Sổ từ vựng",errors:"Sổ lỗi",settings:"Cài đặt"},
 common:{loading:"Đang tải…",empty:"Chưa có nội dung",save:"Lưu",saved:"Đã lưu",cancel:"Hủy",delete:"Xóa",confirm:"Xác nhận",retry:"Thử lại",previous:"Quay lại",next:"Tiếp theo",complete:"Hoàn thành",unavailable:"Không khả dụng",error:"Đã xảy ra lỗi"},
 dashboard:{greeting:"Xin chào.",prompt:"Hôm nay mình tiếp tục thêm một bước nhé?",subtitle:"Học ngắn, học thường xuyên và dùng tiếng Anh trong tình huống thật.",continue:"Tiếp tục học",todayReview:"Ôn tập hôm nay",weekly:"Học tập tuần này",current:"Khóa học hiện tại",skills:"Tiến bộ theo kỹ năng",mistakes:"Lỗi gần đây"},
 curriculum:{title:"Lộ trình học",subtitle:"Tiến từng bước theo kiến thức tiên quyết.",available:"Có thể học",prerequisite:"Cần hoàn thành bài trước",unitReview:"Ôn tập cuối bài"},
 lesson:{goals:"Mục tiêu bài học",situation:"Tình huống hôm nay",dialogue:"Hội thoại",vocabulary:"Từ vựng",grammar:"Ngữ pháp",examples:"Ví dụ",practice:"Luyện tập",production:"Vận dụng",mastery:"Kiểm tra cuối bài",back:"Về lộ trình",easyKorean:"Giải thích tiếng Hàn dễ hơn"},
 practice:{title:"Phòng luyện nghe và nói",shadowing:"Luyện nói theo",listening:"Luyện nghe",audio:"Phát âm thanh",recording:"Ghi âm tự do",dialogue:"Hội thoại tình huống"},
 review:{title:"Trung tâm ôn tập",due:"Nội dung đến hạn",again:"Học lại",hard:"Khó",good:"Tốt",easy:"Dễ"},
 settings:{title:"Cài đặt học tập",englishLevel:"Trình độ tiếng Anh",explanationMode:"Ngôn ngữ giải thích",both:"Tiếng Việt + tiếng Hàn",viOnly:"Chỉ tiếng Việt",koOnly:"Chỉ tiếng Hàn",duration:"Thời gian học mỗi ngày",accent:"Giọng phát âm",data:"Dữ liệu của tôi",storage:"Bộ nhớ ghi âm cục bộ"},
 media:{play:"Phát",pause:"Tạm dừng",replay:"Nghe lại",speed:"Tốc độ",repeat:"Số lần lặp",showTranscript:"Hiện bản chép lời",hideTranscript:"Ẩn bản chép lời",record:"Bắt đầu ghi âm",stop:"Dừng ghi âm",resume:"Tiếp tục ghi",delete:"Xóa bản ghi",privacy:"Bản ghi chỉ được lưu trong trình duyệt này."},
 audio:{player:"Trình phát âm thanh",browserVoice:"Giọng đọc tổng hợp của trình duyệt",synthetic:"Âm thanh tổng hợp",localRecording:"Bản ghi cục bộ",voice:"Giọng đọc",unavailable:"Không có giọng đọc phù hợp với vùng đã chọn.",playError:"Không thể phát âm thanh.",times:"lần"},
 recorder:{privacyDetail:"Bản ghi không được tải ra ngoài. Nếu xóa dữ liệu trình duyệt, bản ghi cũng có thể mất; đây không phải bản sao lưu lâu dài.",seconds:"giây",keep:"Giữ làm bản ghi yêu thích",saved:"Bản ghi đã giữ",temporary:"Bản ghi tạm",myWaveform:"Dạng sóng bản ghi của tôi",myAudio:"Phát bản ghi của tôi",waiting:"Đang chờ quyền dùng micrô…",unsupported:"Trình duyệt này không hỗ trợ ghi âm.",permissionDenied:"Quyền dùng micrô đã bị từ chối.",formatUnsupported:"Không tìm thấy định dạng ghi âm được hỗ trợ.",failed:"Không thể bắt đầu hoặc lưu bản ghi.",confirmDelete:"Xóa vĩnh viễn bản ghi này? Không thể khôi phục sau khi xóa."},
 shadowing:{title:"Luyện nói theo",stages:["Nghe trước","Nghe chậm","Đọc lời thoại","Nhận biết nối âm","Ẩn lời thoại","Thu âm","So sánh A/B","Tự đánh giá"],hidden:"Lời thoại đã được ẩn. Hãy nhớ lại nhịp điệu và cách nối âm rồi nói.",reference:"A · Giọng mẫu",learner:"B · Giọng của tôi",waveHelp:"Dạng sóng chỉ giúp tìm vị trí cần nghe, không phải điểm phát âm.",reflect:"Tự xem lại khả năng truyền đạt ý, trọng âm và nhịp điệu.",keep:"Giữ lần thử này làm bản ghi yêu thích",ratingSaved:"Đã lưu tự đánh giá. ‘Học lại’ và ‘Khó’ sẽ đưa câu này vào ôn tập.",restart:"Bắt đầu lại"},
 listening:{title:"Luyện nghe và chép chính tả",answer:"Câu trả lời nghe",notes:"Ghi chú so sánh",answerPlaceholder:"Nhập nội dung bạn nghe được",notesPlaceholder:"Ghi lại điểm khác biệt hoặc phần khó nghe",check:"Kiểm tra",correct:"Chính xác.",tryAgain:"Hãy nghe lại từ làm thay đổi nghĩa hoặc dạng ngữ pháp.",selfDone:"Đã hoàn tất phần tự so sánh; hoạt động này không chấm điểm tự động."},
 dialogue:{eyebrow:"HỘI THOẠI PHÂN NHÁNH",missing:"Không tìm thấy bước hội thoại.",ownAnswer:"Câu trả lời của tôi trước khi xem lựa chọn",ownPlaceholder:"Tự trả lời bằng tiếng Anh",natural:"Lựa chọn tự nhiên.",improve:"Có một cách diễn đạt tự nhiên hơn.",restart:"Chơi lại từ đầu",retryWeak:"Thử lại nhánh cần luyện"},
 waveform:{unavailable:"chưa có dạng sóng âm thanh"},
 exercise:{arrangeHint:"Chạm vào từ để tạo câu.",answer:"Câu trả lời",spokenNote:"Bạn có thể ghi chú ngắn nội dung vừa nói.",writtenPlaceholder:"Viết câu trả lời tại đây. Nội dung sẽ được tự động lưu tạm.",answerPlaceholder:"Nhập câu trả lời",reset:"Sắp xếp lại",model:"Xem câu trả lời mẫu",check:"Kiểm tra đáp án",modelTitle:"Câu trả lời mẫu",selfRating:"Tự đánh giá",again:"Làm lại",help:"Cần hỗ trợ",done:"Làm tốt",correct:"Tốt lắm. Đáp án chính xác.",incorrect:"Hãy xem lại một lần nữa."},
 storage:{unknown:"Không xác định",checkFailed:"Không thể kiểm tra bộ nhớ.",confirmClear:"Xóa vĩnh viễn tất cả bản ghi cục bộ? Bản ghi đã giữ cũng sẽ bị xóa và không thể khôi phục.",clearFailed:"Không thể xóa bản ghi.",title:"Bộ nhớ bản ghi cục bộ",items:"bản ghi",kept:"Đã giữ",temporary:"Tạm thời",usage:"Dung lượng trình duyệt",quota:"hạn mức ước tính",loading:"Đang kiểm tra bộ nhớ…",notice:"Bản ghi chỉ được lưu trong IndexedDB. Dữ liệu có thể mất khi xóa dữ liệu trình duyệt, kết thúc chế độ riêng tư hoặc theo chính sách lưu trữ; đây không phải bản sao lưu lâu dài.",clear:"Xóa tất cả bản ghi"},
 validation:{required:"Vui lòng nhập nội dung.",invalid:"Nội dung chưa hợp lệ.",network:"Không thể lưu dữ liệu cục bộ lúc này."}
}as const;
export type ViUi=typeof viUi;
